import { MakeLogicType, actions, kea, reducers, path, key, props, connect, listeners, selectors } from 'kea'
import { forms } from 'kea-forms'

import { FrameScene, RepositoryType, TemplateForm, TemplateType, FrameId } from '../../../../types'
import { frameLogic } from '../../frameLogic'
import { templatesModel } from '../../../../models/templatesModel'
import { repositoriesModel } from '../../../../models/repositoriesModel'
import { appsModel } from '../../../../models/appsModel'
import { searchInText } from '../../../../utils/searchInText'
import { apiFetch } from '../../../../utils/apiFetch'
import { assignCloudFrameStoreScene } from '../../../../utils/cloudFrameApi'
import { isCloudMode } from '../../../../utils/cloudMode'
import { longRunningTasksModel } from '../../../../models/longRunningTasksModel'
import { framesModel } from '../../../../models/framesModel'
import { settingsLogic } from '../../../settings/settingsLogic'
import { templateCompatibilityForFrame } from '../../../../utils/embeddedCompatibility'
import { templateWithSceneOrigins } from '../../../../utils/sceneOrigin'
import { templateFavouriteId, type TemplateWithFavouriteId } from './templateFavourites'
import { cloudDriveLogic } from './cloudDriveLogic'
import type { DeepPartial, DeepPartialMap, FieldName, ValidationErrorType } from 'kea-forms'
import type { AppConfig, FrameOSSettings, FrameType } from '../../../../types'

export interface TemplateLogicProps {
  frameId: FrameId
}

/** Repository listings only carry template metadata; fetch the scenes separately when needed. */
export async function fetchTemplateScenes(template: TemplateType): Promise<FrameScene[]> {
  if (template.scenes?.length) {
    return template.scenes
  }
  if (!template.scenesUrl) {
    throw new Error('Template has no scenes to load')
  }
  const response = await apiFetch(template.scenesUrl)
  if (!response.ok) {
    throw new Error('Failed to load template scenes')
  }
  return await response.json()
}

/** Resolve a repository template's scenes from inline data, its scenes URL, or its zip archive. */
export async function loadRepositoryTemplateScenes(
  repository: RepositoryType,
  template: TemplateType
): Promise<FrameScene[]> {
  if (template.scenes?.length || template.scenesUrl) {
    return fetchTemplateScenes(template)
  }

  const templateWithZip = template as TemplateType & { zip?: string }
  let zipPath = templateWithZip.zip
  if (!zipPath) {
    throw new Error('Failed to load template')
  }
  if (zipPath.startsWith('./')) {
    const repositoryPath = repository.url.replace(/\/[^/]+$/, '')
    zipPath = `${repositoryPath}/${zipPath.slice(2)}`
  }

  const response = await apiFetch(`/api/templates`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ format: 'scenes', url: zipPath }),
  })
  if (!response.ok) {
    throw new Error('Failed to load template scenes')
  }
  return await response.json()
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface templatesLogicValues {
  apps: Record<string, AppConfig> // appsModel
  frame: FrameType // frameLogic
  frameForm: Partial<FrameType> // frameLogic
  allRepositories: RepositoryType[] // repositoriesModel
  settings: FrameOSSettings // settingsLogic
  allTemplates: TemplateType[] // templatesModel
  addRepositoryForm: {
    name: string
    url: string
  }
  addRepositoryFormAllErrors: Record<string, any>
  addRepositoryFormChanged: boolean
  addRepositoryFormErrors: DeepPartialMap<
    {
      name: string
      url: string
    },
    ValidationErrorType
  >
  addRepositoryFormHasErrors: boolean
  addRepositoryFormManualErrors: Record<string, any>
  addRepositoryFormTouched: boolean
  addRepositoryFormTouches: Record<string, boolean>
  addRepositoryFormValidationErrors: DeepPartialMap<
    {
      name: string
      url: string
    },
    ValidationErrorType
  >
  addTemplateUrlForm: {
    url: string
  }
  addTemplateUrlFormAllErrors: Record<string, any>
  addTemplateUrlFormChanged: boolean
  addTemplateUrlFormErrors: DeepPartialMap<
    {
      url: string
    },
    ValidationErrorType
  >
  addTemplateUrlFormHasErrors: boolean
  addTemplateUrlFormManualErrors: Record<string, any>
  addTemplateUrlFormTouched: boolean
  addTemplateUrlFormTouches: Record<string, boolean>
  addTemplateUrlFormValidationErrors: DeepPartialMap<
    {
      url: string
    },
    ValidationErrorType
  >
  addingUrlToFrame: boolean
  expanded: Record<string, boolean>
  favouriteTemplateIds: Set<string>
  favouriteTemplates: TemplateWithFavouriteId[]
  hiddenRepositories: number
  installableFavouriteTemplates: TemplateWithFavouriteId[]
  installedTemplatesByName: {
    [k: string]: true
  }
  isAddRepositoryFormSubmitting: boolean
  isAddRepositoryFormValid: boolean
  isAddTemplateUrlFormSubmitting: boolean
  isAddTemplateUrlFormValid: boolean
  isExpanded: (url: string) => boolean
  isTemplateFormSubmitting: boolean
  isTemplateFormValid: boolean
  isUploadTemplateFormSubmitting: boolean
  isUploadTemplateFormValid: boolean
  modalTarget: 'cloud' | 'localTemplate' | 'zip'
  repositories: RepositoryType[]
  search: string
  showAddRepositoryFormErrors: boolean
  showAddTemplateUrlFormErrors: boolean
  showTemplateFormErrors: boolean
  showUploadTemplateFormErrors: boolean
  showingAddRepository: boolean
  showingModal: boolean
  showingRemoteTemplate: boolean
  showingUploadTemplate: boolean
  templateForm: TemplateForm
  templateFormAllErrors: Record<string, any>
  templateFormChanged: boolean
  templateFormErrors: DeepPartialMap<TemplateForm, ValidationErrorType>
  templateFormHasErrors: boolean
  templateFormManualErrors: Record<string, any>
  templateFormTouched: boolean
  templateFormTouches: Record<string, boolean>
  templateFormValidationErrors: DeepPartialMap<TemplateForm, ValidationErrorType>
  templates: TemplateType[]
  uploadTemplateForm: {
    file: any
  }
  uploadTemplateFormAllErrors: Record<string, any>
  uploadTemplateFormChanged: boolean
  uploadTemplateFormErrors: DeepPartialMap<
    {
      file: any
    },
    ValidationErrorType
  >
  uploadTemplateFormHasErrors: boolean
  uploadTemplateFormManualErrors: Record<string, any>
  uploadTemplateFormTouched: boolean
  uploadTemplateFormTouches: Record<string, boolean>
  uploadTemplateFormValidationErrors: DeepPartialMap<
    {
      file: any
    },
    ValidationErrorType
  >
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface templatesLogicActions {
  applyTemplate: (
    template: Partial<TemplateType>,
    openDrawer?: boolean | undefined,
    preserveSceneIds?: boolean | undefined
  ) => {
    openDrawer: boolean
    preserveSceneIds: boolean
    template: Partial<TemplateType>
  } // frameLogic
  updateRepository: (repository: RepositoryType) => {
    repository: RepositoryType
  } // repositoriesModel
  updateTemplate: (template: TemplateType) => {
    template: TemplateType
  } // templatesModel
  addUrlToFrame: (
    url: string,
    openDrawer?: boolean
  ) => {
    openDrawer: boolean
    url: string
  }
  applyFavouriteTemplatesToFrame: (openDrawer?: boolean) => {
    openDrawer: boolean
  }
  applyRemoteToFrame: (
    repository: RepositoryType,
    template: TemplateType,
    openDrawer?: boolean
  ) => {
    openDrawer: boolean
    repository: RepositoryType
    template: TemplateType
  }
  editLocalTemplate: (template: TemplateType) => {
    template: TemplateType
  }
  hideAddRepository: () => {
    value: true
  }
  hideModal: () => {
    value: true
  }
  hideRemoteTemplate: () => {
    value: true
  }
  hideUploadTemplate: () => {
    value: true
  }
  resetAddRepositoryForm: (values?: { name: string; url: string }) => {
    values?: {
      name: string
      url: string
    }
  }
  resetAddTemplateUrlForm: (values?: { url: string }) => {
    values?: {
      url: string
    }
  }
  resetTemplateForm: (values?: TemplateForm) => {
    values?: TemplateForm
  }
  resetUploadTemplateForm: (values?: { file: any }) => {
    values?: {
      file: any
    }
  }
  saveAsCloudTemplate: (template?: Partial<TemplateForm>) => {
    template: Partial<TemplateForm>
  }
  saveAsTemplate: (template?: Partial<TemplateForm>) => {
    template: Partial<TemplateForm>
  }
  saveAsZip: (template?: Partial<TemplateForm>) => {
    template: Partial<TemplateForm>
  }
  saveRemoteAsLocal: (
    repository: RepositoryType,
    template: TemplateType
  ) => {
    repository: RepositoryType
    template: TemplateType
  }
  setAddRepositoryFormManualErrors: (errors: Record<string, any>) => {
    errors: Record<string, any>
  }
  setAddRepositoryFormValue: (
    key: FieldName,
    value: any
  ) => {
    name: FieldName
    value: any
  }
  setAddRepositoryFormValues: (
    values: DeepPartial<{
      name: string
      url: string
    }>
  ) => {
    values: DeepPartial<{
      name: string
      url: string
    }>
  }
  setAddTemplateUrlFormManualErrors: (errors: Record<string, any>) => {
    errors: Record<string, any>
  }
  setAddTemplateUrlFormValue: (
    key: FieldName,
    value: any
  ) => {
    name: FieldName
    value: any
  }
  setAddTemplateUrlFormValues: (
    values: DeepPartial<{
      url: string
    }>
  ) => {
    values: DeepPartial<{
      url: string
    }>
  }
  setAddingUrlToFrame: (adding: boolean) => {
    adding: boolean
  }
  setSearch: (search: string) => {
    search: string
  }
  setTemplateFormManualErrors: (errors: Record<string, any>) => {
    errors: Record<string, any>
  }
  setTemplateFormValue: (
    key: FieldName,
    value: any
  ) => {
    name: FieldName
    value: any
  }
  setTemplateFormValues: (values: DeepPartial<TemplateForm>) => {
    values: DeepPartial<TemplateForm>
  }
  setUploadTemplateFormManualErrors: (errors: Record<string, any>) => {
    errors: Record<string, any>
  }
  setUploadTemplateFormValue: (
    key: FieldName,
    value: any
  ) => {
    name: FieldName
    value: any
  }
  setUploadTemplateFormValues: (
    values: DeepPartial<{
      file: any
    }>
  ) => {
    values: DeepPartial<{
      file: any
    }>
  }
  showAddRepository: () => {
    value: true
  }
  showRemoteTemplate: () => {
    value: true
  }
  showUploadTemplate: () => {
    value: true
  }
  submitAddRepositoryForm: () => {
    value: boolean
  }
  submitAddRepositoryFormFailure: (
    error: Error,
    errors: Record<string, any>
  ) => {
    error: Error
    errors: Record<string, any>
  }
  submitAddRepositoryFormRequest: (addRepositoryForm: { name: string; url: string }) => {
    addRepositoryForm: {
      name: string
      url: string
    }
  }
  submitAddRepositoryFormSuccess: (addRepositoryForm: { name: string; url: string }) => {
    addRepositoryForm: {
      name: string
      url: string
    }
  }
  submitAddTemplateUrlForm: () => {
    value: boolean
  }
  submitAddTemplateUrlFormFailure: (
    error: Error,
    errors: Record<string, any>
  ) => {
    error: Error
    errors: Record<string, any>
  }
  submitAddTemplateUrlFormRequest: (addTemplateUrlForm: { url: string }) => {
    addTemplateUrlForm: {
      url: string
    }
  }
  submitAddTemplateUrlFormSuccess: (addTemplateUrlForm: { url: string }) => {
    addTemplateUrlForm: {
      url: string
    }
  }
  submitTemplateForm: () => {
    value: boolean
  }
  submitTemplateFormFailure: (
    error: Error,
    errors: Record<string, any>
  ) => {
    error: Error
    errors: Record<string, any>
  }
  submitTemplateFormRequest: (templateForm: TemplateForm) => {
    templateForm: TemplateForm
  }
  submitTemplateFormSuccess: (templateForm: TemplateForm) => {
    templateForm: TemplateForm
  }
  submitUploadTemplateForm: () => {
    value: boolean
  }
  submitUploadTemplateFormFailure: (
    error: Error,
    errors: Record<string, any>
  ) => {
    error: Error
    errors: Record<string, any>
  }
  submitUploadTemplateFormRequest: (uploadTemplateForm: { file: any }) => {
    uploadTemplateForm: {
      file: any
    }
  }
  submitUploadTemplateFormSuccess: (uploadTemplateForm: { file: any }) => {
    uploadTemplateForm: {
      file: any
    }
  }
  toggleExpanded: (url: string) => {
    url: string
  }
  touchAddRepositoryFormField: (key: string) => {
    key: string
  }
  touchAddTemplateUrlFormField: (key: string) => {
    key: string
  }
  touchTemplateFormField: (key: string) => {
    key: string
  }
  touchUploadTemplateFormField: (key: string) => {
    key: string
  }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface templatesLogicMeta {
  key: FrameId
  __keaTypeGenInternalSelectorTypes: {
    templates: (allTemplates: TemplateType[], search: string) => TemplateType[]
    repositories: (allRepositories: RepositoryType[], search: string) => RepositoryType[]
    hiddenRepositories: (allRepositories: RepositoryType[], repositories: RepositoryType[]) => number
    isExpanded: (expanded: Record<string, boolean>) => (url: string) => boolean
    installedTemplatesByName: (frameForm: Partial<FrameType>) => {
      [k: string]: true
    }
    favouriteTemplateIds: (settings: FrameOSSettings) => Set<string>
    favouriteTemplates: (
      allTemplates: TemplateType[],
      allRepositories: RepositoryType[],
      favouriteTemplateIds: Set<string>,
      frame: FrameType,
      frameForm: Partial<FrameType>,
      apps: Record<string, AppConfig>
    ) => TemplateWithFavouriteId[]
    installableFavouriteTemplates: (favouriteTemplates: TemplateWithFavouriteId[]) => TemplateWithFavouriteId[]
  }
}

export type templatesLogicType = MakeLogicType<templatesLogicValues, templatesLogicActions, TemplateLogicProps> &
  templatesLogicMeta

export const templatesLogic = kea<templatesLogicType>([
  path(['src', 'scenes', 'frame', 'panels', 'Templates', 'templatesLogic']),
  props({} as TemplateLogicProps),
  key((props) => props.frameId),
  connect((props: TemplateLogicProps) => ({
    values: [
      frameLogic(props),
      ['frame', 'frameForm'],
      templatesModel,
      ['templates as allTemplates'],
      repositoriesModel,
      ['repositories as allRepositories'],
      appsModel,
      ['apps'],
      settingsLogic,
      ['settings'],
    ],
    actions: [
      templatesModel,
      ['updateTemplate'],
      repositoriesModel,
      ['updateRepository'],
      frameLogic(props),
      ['applyTemplate'],
    ],
  })),
  actions({
    saveAsTemplate: (template?: Partial<TemplateForm>) => ({ template: template ?? {} }),
    saveAsZip: (template?: Partial<TemplateForm>) => ({ template: template ?? {} }),
    saveAsCloudTemplate: (template?: Partial<TemplateForm>) => ({ template: template ?? {} }),
    editLocalTemplate: (template: TemplateType) => ({ template }),
    hideModal: true,
    saveRemoteAsLocal: (repository: RepositoryType, template: TemplateType) => ({ repository, template }),
    applyRemoteToFrame: (repository: RepositoryType, template: TemplateType, openDrawer?: boolean) => ({
      openDrawer: openDrawer ?? false,
      repository,
      template,
    }),
    showRemoteTemplate: true,
    hideRemoteTemplate: true,
    showUploadTemplate: true,
    hideUploadTemplate: true,
    showAddRepository: true,
    hideAddRepository: true,
    setSearch: (search: string) => ({ search }),
    addUrlToFrame: (url: string, openDrawer?: boolean) => ({ url, openDrawer: openDrawer ?? false }),
    setAddingUrlToFrame: (adding: boolean) => ({ adding }),
    toggleExpanded: (url: string) => ({ url }),
    applyFavouriteTemplatesToFrame: (openDrawer?: boolean) => ({
      openDrawer: openDrawer ?? false,
    }),
  }),
  forms(({ actions, values, props }) => ({
    templateForm: {
      defaults: {} as TemplateForm,
      errors: (templateForm) => ({
        name: !templateForm.name ? 'Name is required' : null,
      }),
      submit: async (formValues) => {
        if (formValues.id) {
          // update
          const request = {
            name: formValues.name,
            description: formValues.description,
          }
          const response = await apiFetch(`/api/templates/${formValues.id}`, {
            method: 'PATCH',
            body: JSON.stringify(request),
            headers: {
              'Content-Type': 'application/json',
            },
          })
          if (!response.ok) {
            throw new Error('Failed to update template')
          }
          actions.updateTemplate(await response.json())
        } else {
          // create
          const target = values.modalTarget
          const exportScenes = formValues.exportScenes ?? []
          // The preview image should show one of the scenes being saved: use
          // the frame's snapshot only when the active scene is included,
          // otherwise the first selected scene's cached snapshot.
          const activeSceneId = values.frame?.active_scene_id
          const imageSceneId = activeSceneId && exportScenes.includes(activeSceneId) ? undefined : exportScenes[0]

          if (target === 'cloud') {
            const response = await apiFetch('/api/cloud/store/publish', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({
                name: formValues.name,
                description: formValues.description,
                scenes: (values.frameForm.scenes || []).filter((scene) => exportScenes.includes(scene.id)),
                from_frame_id: props.frameId,
                ...(imageSceneId ? { image_scene_id: imageSceneId } : {}),
                ...(formValues.visibility === 'private' || formValues.visibility === 'public'
                  ? { visibility: formValues.visibility }
                  : {}),
              }),
            })
            if (!response.ok) {
              let detail = `unexpected status ${response.status}`
              try {
                detail = (await response.json())?.detail ?? detail
              } catch {
                // keep fallback detail
              }
              window.alert(`Could not save to your private cloud: ${detail}`)
              throw new Error('Failed to save to private cloud scenes')
            }
            const payload = await response.json()
            const scene = payload?.scene
            cloudDriveLogic.findMounted()?.actions.loadDrive()
            actions.hideModal()
            actions.resetTemplateForm()
            if (
              scene?.url &&
              window.confirm(
                `Saved "${formValues.name}" to your private cloud scenes (v${scene?.version ?? '?'}). Open it?`
              )
            ) {
              window.open(scene.url, '_blank', 'noopener')
            }
            return
          }

          const request: TemplateType & Record<string, any> = {
            name: formValues.name,
            description: formValues.description,
            scenes: (values.frameForm.scenes || []).filter((scene) => exportScenes.includes(scene.id)),
            from_frame_id: props.frameId,
            ...(imageSceneId ? { image_scene_id: imageSceneId } : {}),
            format: target === 'zip' ? 'zip' : 'json',
          }
          const response = await apiFetch('/api/templates', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(request),
          })
          if (!response.ok) {
            throw new Error('Failed to create template')
          }
          if (target === 'zip') {
            const blob = await response.blob()
            const url = window.URL.createObjectURL(blob)
            const a = document.createElement('a')
            a.href = url
            a.download = `${formValues.name}.zip`
            document.body.appendChild(a)
            a.click()
            window.URL.revokeObjectURL(url)
            document.body.removeChild(a)
          } else {
            actions.updateTemplate(await response.json())
          }
        }
        actions.hideModal()
        actions.resetTemplateForm()
      },
      options: {
        showErrorsOnTouch: true,
      },
    },
    addTemplateUrlForm: {
      defaults: {
        url: '',
      } as { url: string },
      errors: (addTemplateUrlForm) => ({
        url: !addTemplateUrlForm.url ? 'URL is required' : null,
      }),
      submit: async (formValues) => {
        const request = {
          url: formValues.url,
        }
        const response = await apiFetch(`/api/templates`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(request),
        })
        if (!response.ok) {
          let detail = `unexpected status ${response.status}`
          try {
            detail = (await response.json())?.detail ?? detail
          } catch {
            // keep fallback detail
          }
          window.alert(`Could not add the scene: ${detail}`)
          throw new Error('Failed to add template from URL')
        }
        actions.updateTemplate(await response.json())
        actions.resetAddTemplateUrlForm()
        // A pasted URL doubles as the search value ("Add scene from URL"
        // quick action); clear it so the freshly added scene is visible.
        if (values.search === formValues.url) {
          actions.setSearch('')
        }
      },
    },
    uploadTemplateForm: {
      defaults: {
        file: null,
      } as { file: any },
      errors: (addTemplateUrlForm) => ({
        file: !addTemplateUrlForm.file ? 'File is required' : null,
      }),
      submit: async (formValues) => {
        const formData = new FormData()
        formData.append('file', formValues.file)
        const response = await apiFetch(`/api/templates`, {
          method: 'POST',
          body: formData,
        })
        if (!response.ok) {
          throw new Error('Failed to update frame')
        }
        actions.updateTemplate(await response.json())
        actions.resetUploadTemplateForm()
      },
    },
    addRepositoryForm: {
      defaults: {
        url: '',
      } as { name: string; url: string },
      errors: (formValues) => ({
        url: !formValues.url ? 'URL is required' : null,
      }),
      submit: async (formValues) => {
        const request = {
          url: formValues.url,
        }
        const response = await apiFetch(`/api/repositories`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(request),
        })
        if (!response.ok) {
          throw new Error('Failed to update frame')
        }
        actions.updateRepository(await response.json())
        actions.resetAddRepositoryForm()
      },
    },
  })),
  reducers({
    search: ['', { setSearch: (_, { search }) => search }],
    addingUrlToFrame: [false, { setAddingUrlToFrame: (_, { adding }) => adding }],
    showingModal: [
      false,
      {
        saveAsZip: () => true,
        saveAsTemplate: () => true,
        saveAsCloudTemplate: () => true,
        editLocalTemplate: () => true,
        hideModal: () => false,
      },
    ],
    modalTarget: [
      'localTemplate' as 'localTemplate' | 'zip' | 'cloud',
      {
        saveAsZip: () => 'zip',
        saveAsTemplate: () => 'localTemplate',
        saveAsCloudTemplate: () => 'cloud',
        editLocalTemplate: () => 'localTemplate',
      },
    ],
    templateForm: {
      saveAsTemplate: (_, { template }) => ({
        id: '',
        name: '',
        description: '',
        exportScenes: undefined,
        ...template,
      }),
      saveAsZip: (_, { template }) => ({ id: '', name: '', description: '', exportScenes: undefined, ...template }),
      saveAsCloudTemplate: (_, { template }) => ({
        id: '',
        name: '',
        description: '',
        exportScenes: undefined,
        // '' = keep current visibility (new scenes start private)
        visibility: '',
        ...template,
      }),
      editLocalTemplate: (_, { template }) => ({
        id: template.id,
        name: template.name,
        description: template.description,
      }),
    },
    showingUploadTemplate: [
      false,
      {
        showUploadTemplate: () => true,
        hideUploadTemplate: () => false,
        submitAddTemplateUrlFormSuccess: () => false,
      },
    ],
    showingRemoteTemplate: [
      false,
      {
        showRemoteTemplate: () => true,
        hideRemoteTemplate: () => false,
        submitUploadTemplateFormSuccess: () => false,
      },
    ],
    showingAddRepository: [
      false,
      {
        showAddRepository: () => true,
        hideAddRepository: () => false,
        submitAddRepositoryFormSuccess: () => false,
      },
    ],
    expanded: [
      {} as Record<string, boolean>,
      { persist: true, storageKey: 'templatesLogic.expanded' },
      {
        toggleExpanded: (state, { url }) => ({ ...state, [url]: !(state[url] ?? true) }),
      },
    ],
  }),
  selectors({
    templates: [
      (s) => [s.allTemplates, s.search],
      (allTemplates: templatesLogicValues['allTemplates'], search: templatesLogicValues['search']) => {
        if (search !== '') {
          return allTemplates
            .filter((template) => searchInText(search, template.name))
            .sort((a, b) => a.name.localeCompare(b.name))
        }
        return allTemplates
      },
    ],
    repositories: [
      (s) => [s.allRepositories, s.search],
      (
        allRepositories: templatesLogicValues['allRepositories'],
        search: templatesLogicValues['search']
      ): RepositoryType[] => {
        if (search === '') {
          return allRepositories.map((repository) => ({
            ...repository,
            templates: repository.templates?.sort((a, b) => a.name.localeCompare(b.name)),
          }))
        }
        return allRepositories
          .filter(
            (repository) =>
              searchInText(search, repository.name) ||
              repository.templates?.some((t) => searchInText(search, t.name) || searchInText(search, t.description))
          )
          .map((repository) => ({
            ...repository,
            templates: repository.templates
              ?.filter((t) => searchInText(search, t.name) || searchInText(search, t.description))
              .sort((a, b) => a.name.localeCompare(b.name)),
          }))
      },
    ],
    hiddenRepositories: [
      (s) => [s.allRepositories, s.repositories],
      (allRepositories: templatesLogicValues['allRepositories'], repositories: templatesLogicValues['repositories']) =>
        allRepositories.length - repositories.length,
    ],
    isExpanded: [
      (s) => [s.expanded],
      (expanded: templatesLogicValues['expanded']) => (url: string) => expanded[url] ?? true,
    ],
    installedTemplatesByName: [
      (s) => [s.frameForm],
      (frameForm: templatesLogicValues['frameForm']) =>
        Object.fromEntries(frameForm?.scenes?.map((s) => [s.name, true]) || []),
    ],
    favouriteTemplateIds: [
      (s) => [s.settings],
      (settings: templatesLogicValues['settings']): Set<string> =>
        new Set(settings.personal?.favouriteTemplateIds ?? []),
    ],
    favouriteTemplates: [
      (s) => [s.allTemplates, s.allRepositories, s.favouriteTemplateIds, s.frame, s.frameForm, s.apps],
      (
        allTemplates: templatesLogicValues['allTemplates'],
        allRepositories: templatesLogicValues['allRepositories'],
        favouriteTemplateIds: templatesLogicValues['favouriteTemplateIds'],
        frame: templatesLogicValues['frame'],
        frameForm: templatesLogicValues['frameForm'],
        apps: templatesLogicValues['apps']
      ): TemplateWithFavouriteId[] => {
        const mode = frameForm?.mode ?? frame?.mode
        const rows: TemplateWithFavouriteId[] = []
        for (const template of allTemplates) {
          const favouriteId = templateFavouriteId(template)
          if (favouriteTemplateIds.has(favouriteId)) {
            rows.push({
              compatibility: templateCompatibilityForFrame(mode, template, apps, frameForm),
              favouriteId,
              template,
            })
          }
        }
        for (const repository of allRepositories) {
          for (const template of repository.templates ?? []) {
            const favouriteId = templateFavouriteId(template, repository)
            if (favouriteTemplateIds.has(favouriteId)) {
              rows.push({
                compatibility: templateCompatibilityForFrame(mode, template, apps, frameForm),
                favouriteId,
                repository,
                template,
              })
            }
          }
        }
        return rows.toSorted((a, b) => a.template.name.localeCompare(b.template.name))
      },
    ],
    installableFavouriteTemplates: [
      (s) => [s.favouriteTemplates],
      (favouriteTemplates: templatesLogicValues['favouriteTemplates']): TemplateWithFavouriteId[] =>
        favouriteTemplates.filter((template) => template.compatibility.supported),
    ],
  }),
  listeners(({ actions, props, values }) => ({
    // Install the scene(s) behind a pasted URL (template zip, or a scene page
    // with a frameos:zip meta tag) straight onto this frame — the flow behind
    // "copy this link into the Templates search box" on FrameOS Cloud.
    addUrlToFrame: async ({ url, openDrawer }) => {
      actions.setAddingUrlToFrame(true)
      try {
        const response = await apiFetch(`/api/templates`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ url, format: 'scenes' }),
        })
        if (!response.ok) {
          let detail = `unexpected status ${response.status}`
          try {
            detail = (await response.json())?.detail ?? detail
          } catch {
            // keep fallback detail
          }
          window.alert(`Could not add the scene: ${detail}`)
          return
        }
        const scenes = await response.json()
        if (!Array.isArray(scenes) || scenes.length === 0) {
          window.alert('No scenes found at this URL.')
          return
        }
        actions.applyTemplate({ scenes }, openDrawer)
        if (values.search === url) {
          actions.setSearch('')
        }
      } finally {
        actions.setAddingUrlToFrame(false)
      }
    },
    saveRemoteAsLocal: async ({ template, repository }) => {
      if ('zip' in template) {
        let zipPath = (template as any).zip
        if (zipPath.startsWith('./')) {
          const repositoryPath = repository.url.replace(/\/[^/]+$/, '')
          zipPath = `${repositoryPath}/${zipPath.slice(2)}`
        }
        actions.setAddTemplateUrlFormValues({ url: zipPath })
        actions.submitAddTemplateUrlForm()
        return
      }

      if (template.scenesUrl || template.scenes?.length) {
        const scenes = await fetchTemplateScenes(template)
        const response = await apiFetch(`/api/templates`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            name: template.name,
            description: template.description,
            scenes,
          }),
        })
        if (!response.ok) {
          throw new Error('Failed to save template')
        }
        actions.updateTemplate(await response.json())
      }
    },
    applyRemoteToFrame: async ({ template, repository, openDrawer }) => {
      // Cloud store scenes carry risk flags; installing one that can run shell
      // commands on the frame deserves an explicit confirmation. This listener
      // is the funnel for every remote install — buttons, menus and
      // drag-and-drop alike.
      if (
        template.flags?.includes('shell') &&
        !window.confirm(
          `"${template.name}" configures apps or custom code that run shell commands on the frame. ` +
            'Only install it if you trust the publisher. Install anyway?'
        )
      ) {
        return
      }
      const scenes = await loadRepositoryTemplateScenes(repository, template)
      const storeSceneId = (template as TemplateType & { sceneId?: string }).sceneId
      // A cloud store install keeps the published scene ids. They are not a
      // local detail there: the assignment below is what actually reaches the
      // device, and the server resolves both the tile's cover image and (on
      // the next save) the form scene's owning assignment BY those ids. A
      // re-ided local copy therefore showed a permanently blank tile and got
      // saved a second time as a private scene of its own.
      const preserveSceneIds = isCloudMode() && Boolean(storeSceneId)
      // The origin stamp is the backend's "update from repository" bookkeeping.
      // A cloud store install has no use for it — the assignment tracks the
      // store scene (and its version) server-side — and persisting it made
      // every install a perpetual edit: the stamp's version lagged the
      // published version by one forever, so each save published (or forked)
      // again. See cloudFrameScenesSave.ts.
      actions.applyTemplate(
        preserveSceneIds ? { ...template, scenes } : templateWithSceneOrigins({ ...template, scenes }, repository),
        openDrawer,
        preserveSceneIds
      )

      // On the cloud control plane the scene list that actually reaches the
      // device is the server-side store-scene assignment (set_scenes over the
      // hub WS) — the client-side applyTemplate above only shapes the
      // workspace view. Both cloud catalogs (the public store and "my cloud
      // scenes") carry the store scene uuid, so assign it here too.
      if (isCloudMode() && storeSceneId) {
        longRunningTasksModel.actions.startTask({
          frameId: props.frameId,
          kind: 'save',
          title: `Adding "${template.name}"`,
          detail: 'Assigning the scene to this frame',
        })
        try {
          const assigned = await assignCloudFrameStoreScene(props.frameId, storeSceneId)
          longRunningTasksModel.actions.finishTask({
            frameId: props.frameId,
            kind: 'save',
            status: 'success',
            // Say what is left to do: the assignment is stored, but the frame
            // only picks it up once the workspace pushes — and "queued" on its
            // own read as "nothing more to do here".
            detail: assigned
              ? 'Added to this frame — press Save, then Deploy, to send it to the device'
              : 'Scene was already on the frame',
          })
          if (assigned) {
            // The server now owns this scene; rehydrate frame.scenes from the
            // assignment list (force skips the poll throttle) so the tiles
            // show server truth immediately — not just until the next reload.
            framesModel.actions.hydrateCloudFrameScenes(props.frameId, true)
            framesModel.actions.loadFrame(props.frameId)
          }
        } catch (error) {
          const message = error instanceof Error ? error.message : String(error)
          longRunningTasksModel.actions.taskFailed({
            frameId: props.frameId,
            kind: 'save',
            detail: message.includes('frame_not_active')
              ? 'This frame is still pending — confirm it on its dashboard, then add the scene again.'
              : message,
          })
        }
      }
    },
    applyFavouriteTemplatesToFrame: async ({ openDrawer }) => {
      const templates: Partial<TemplateType>[] = []
      for (const row of values.installableFavouriteTemplates) {
        if (!row.repository) {
          templates.push(row.template)
          continue
        }

        const templateWithZip = row.template as TemplateType & { zip?: string }
        if (!row.template.scenes?.length && !row.template.scenesUrl && !templateWithZip.zip) {
          continue
        }

        const scenes = await loadRepositoryTemplateScenes(row.repository, row.template)
        templates.push(templateWithSceneOrigins({ ...row.template, scenes }, row.repository))
      }

      if (templates.length) {
        actions.applyTemplate({ __templateBatch: templates } as Partial<TemplateType>, openDrawer)
      }
    },
    saveAsTemplate: () => {
      if ((values.templateForm.exportScenes?.length ?? 0) === 0) {
        actions.setTemplateFormValues({ exportScenes: values.frameForm?.scenes?.map((s) => s.id) || [] })
      }
    },
    saveAsZip: () => {
      if ((values.templateForm.exportScenes?.length ?? 0) === 0) {
        actions.setTemplateFormValues({ exportScenes: values.frameForm?.scenes?.map((s) => s.id) || [] })
      }
    },
    saveAsCloudTemplate: () => {
      if ((values.templateForm.exportScenes?.length ?? 0) === 0) {
        actions.setTemplateFormValues({ exportScenes: values.frameForm?.scenes?.map((s) => s.id) || [] })
      }
    },
    showAddRepository: () => {
      actions.setAddRepositoryFormValues({ name: '', url: '' })
    },
    showRemoteTemplate: () => {
      actions.setUploadTemplateFormValues({ file: null })
    },
    showUploadTemplate: () => {
      actions.setAddTemplateUrlFormValues({ url: '' })
    },
  })),
])
