import { MakeLogicType, afterMount, kea, path } from 'kea'

import { forms } from 'kea-forms'

import { urls } from '../../urls'
import { clearCachedProjectId } from '../../utils/projectApi'
import { getBasePath } from '../../utils/getBasePath'
import type { DeepPartial, DeepPartialMap, FieldName, ValidationErrorType } from 'kea-forms'

export interface LoginLogicForm {
  email: string
  password: string
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface loginLogicValues {
  isLoginFormSubmitting: boolean
  isLoginFormValid: boolean
  loginForm: LoginLogicForm
  loginFormAllErrors: Record<string, any>
  loginFormChanged: boolean
  loginFormErrors: DeepPartialMap<LoginLogicForm, ValidationErrorType>
  loginFormHasErrors: boolean
  loginFormManualErrors: Record<string, any>
  loginFormTouched: boolean
  loginFormTouches: Record<string, boolean>
  loginFormValidationErrors: DeepPartialMap<LoginLogicForm, ValidationErrorType>
  showLoginFormErrors: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface loginLogicActions {
  resetLoginForm: (values?: LoginLogicForm) => {
    values?: LoginLogicForm
  }
  setLoginFormManualErrors: (errors: Record<string, any>) => {
    errors: Record<string, any>
  }
  setLoginFormValue: (
    key: FieldName,
    value: any
  ) => {
    name: FieldName
    value: any
  }
  setLoginFormValues: (values: DeepPartial<LoginLogicForm>) => {
    values: DeepPartial<LoginLogicForm>
  }
  submitLoginForm: () => {
    value: boolean
  }
  submitLoginFormFailure: (
    error: Error,
    errors: Record<string, any>
  ) => {
    error: Error
    errors: Record<string, any>
  }
  submitLoginFormRequest: (loginForm: LoginLogicForm) => {
    loginForm: LoginLogicForm
  }
  submitLoginFormSuccess: (loginForm: LoginLogicForm) => {
    loginForm: LoginLogicForm
  }
  touchLoginFormField: (key: string) => {
    key: string
  }
}

export type loginLogicType = MakeLogicType<loginLogicValues, loginLogicActions>

export const loginLogic = kea<loginLogicType>([
  path(['src', 'scenes', 'login', 'loginForm']),
  forms(({ actions }) => ({
    loginForm: {
      defaults: {
        email: '',
        password: '',
      } as LoginLogicForm,
      options: {
        showErrorsOnTouch: true,
        canSubmitWithErrors: true,
      },
      errors: (frame: Partial<LoginLogicForm>) => ({
        email: !frame.email ? 'Please enter an e-mail address' : null,
        password: !frame.password ? 'Please enter a password' : null,
      }),
      submit: async (frame) => {
        try {
          const { email, password } = frame
          const formData = new URLSearchParams()
          formData.append('grant_type', 'password')
          formData.append('username', email)
          formData.append('password', password)
          formData.append('scope', 'password')
          const response = await fetch(`/api/login`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
            body: formData.toString(),
          })
          if (response.ok) {
            clearCachedProjectId()
            window.location.href = urls.frames()
          } else {
            let error
            try {
              const json = await response.json()
              error = json.detail || json.error
            } catch (e) {
              error = response.statusText
            }
            actions.setLoginFormManualErrors({ password: error })
          }
        } catch (error) {
          console.error(error)
        }
      },
    },
  })),
  afterMount(async () => {
    try {
      const response = await fetch(`${getBasePath()}/api/user`, {
        method: 'GET',
        headers: { Accept: 'application/json' },
        credentials: 'include',
      })
      if (response.ok) {
        window.location.href = urls.frames()
      }
    } catch (error) {
      console.error('Error checking current user:', error)
    }
  }),
])
