import { MakeLogicType, actions, connect, kea, key, listeners, path, props, reducers, selectors } from 'kea'

import { appsModel, categoryLabels } from '../../../../models/appsModel'
import { searchInText } from '../../../../utils/searchInText'
import { AppConfig, AppNodeData, SceneApp, FrameId } from '../../../../types'
import { frameLogic } from '../../frameLogic'
import { frameEditorsLogic } from '../../frameEditorsLogic'
import { isJavaScriptCatalogApp, normalizeSceneApps, sceneAppsToAppConfigs } from '../../../../utils/sceneApps'
import type { FrameType } from '../../../../types'
import type { FrameScene } from '../../../../types'

export const INLINE_CODE_NODE_KEYWORD = '__frameos_inline_code_node__'

export const INLINE_CODE_NODE_APP: AppConfig = {
  name: 'Inline code node',
  category: 'code',
  description: 'Run inline code directly in the diagram.',
}

export interface AppsLogicProps {
  frameId: FrameId
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface appsLogicValues {
  allApps: Record<string, AppConfig> // appsModel
  selectedSceneId: string | null // frameEditorsLogic
  frameForm: Partial<FrameType> // frameLogic
  apps: Record<string, AppConfig>
  appsByCategory: Record<string, Record<string, AppConfig>>
  appsWithSaveAssets: Record<string, string>
  rawSceneApps: Record<string, SceneApp>
  sceneAppUsageCounts: Record<string, number>
  sceneApps: Record<string, AppConfig>
  search: string
  selectedScene: FrameScene | null
  visibleSceneApps: Record<string, AppConfig>
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface appsLogicActions {
  updateScene: (
    sceneId: string,
    scene: Partial<FrameScene>
  ) => {
    scene: Partial<FrameScene>
    sceneId: string
  } // frameLogic
  deleteUnusedSceneApp: (keyword: string) => {
    keyword: string
  }
  setSearch: (search: string) => {
    search: string
  }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface appsLogicMeta {
  key: FrameId
  __keaTypeGenInternalSelectorTypes: {
    apps: (search: string, allApps: Record<string, AppConfig>) => Record<string, AppConfig>
    selectedScene: (frameForm: Partial<FrameType>, selectedSceneId: string | null) => FrameScene | null
    appsByCategory: (apps: Record<string, AppConfig>, search: string) => Record<string, Record<string, AppConfig>>
    sceneApps: (selectedScene: FrameScene | null) => Record<string, AppConfig>
    rawSceneApps: (selectedScene: FrameScene | null) => Record<string, SceneApp>
    sceneAppUsageCounts: (selectedScene: FrameScene | null) => Record<string, number>
    visibleSceneApps: (search: string, sceneApps: Record<string, AppConfig>) => Record<string, AppConfig>
    appsWithSaveAssets: (apps: Record<string, AppConfig>) => Record<string, string>
  }
}

export type appsLogicType = MakeLogicType<appsLogicValues, appsLogicActions, AppsLogicProps> & appsLogicMeta

export const appsLogic = kea<appsLogicType>([
  path(['src', 'scenes', 'frame', 'panels', 'Apps', 'appsLogic']),
  props({} as AppsLogicProps),
  key((props) => props.frameId),
  connect(({ frameId }: AppsLogicProps) => ({
    actions: [frameLogic({ frameId }), ['updateScene']],
    values: [
      appsModel,
      ['apps as allApps'],
      frameLogic({ frameId }),
      ['frameForm'],
      frameEditorsLogic({ frameId }),
      ['selectedSceneId'],
    ],
  })),
  actions({
    setSearch: (search: string) => ({ search }),
    deleteUnusedSceneApp: (keyword: string) => ({ keyword }),
  }),
  reducers({
    search: ['', { setSearch: (_, { search }) => search }],
  }),
  selectors({
    apps: [
      (s) => [s.search, s.allApps],
      (search: appsLogicValues['search'], allApps: appsLogicValues['allApps']): Record<string, AppConfig> => {
        return Object.fromEntries(
          Object.entries(allApps).filter(
            ([_, app]) => searchInText(search, app.name) || searchInText(search, app.description)
          )
        )
      },
    ],
    selectedScene: [
      (s) => [s.frameForm, s.selectedSceneId],
      (frameForm: appsLogicValues['frameForm'], selectedSceneId: appsLogicValues['selectedSceneId']) =>
        frameForm?.scenes?.find((scene) => scene.id === selectedSceneId) ?? null,
    ],
    appsByCategory: [
      (s) => [s.apps, s.search],
      (
        apps: Record<string, AppConfig>,
        search: appsLogicValues['search']
      ): Record<string, Record<string, AppConfig>> => {
        const defaultEntries: Record<string, Record<string, AppConfig>> = Object.fromEntries(
          Object.keys(categoryLabels).map((c) => [c, {}])
        )
        if (searchInText(search, INLINE_CODE_NODE_APP.name) || searchInText(search, INLINE_CODE_NODE_APP.description)) {
          defaultEntries.code[INLINE_CODE_NODE_KEYWORD] = INLINE_CODE_NODE_APP
        }
        return Object.fromEntries(
          Object.entries(
            Object.entries(apps).reduce((acc, [keyword, app]) => {
              const category = isJavaScriptCatalogApp(keyword) ? 'code' : (app.category || 'other').toLowerCase()
              if (!acc[category]) {
                acc[category] = {}
              }
              acc[category][keyword] = app
              return acc
            }, defaultEntries)
          ).filter(([_, apps]) => Object.keys(apps).length > 0)
        )
      },
    ],
    sceneApps: [
      (s) => [s.selectedScene],
      (selectedScene: appsLogicValues['selectedScene']): Record<string, AppConfig> =>
        sceneAppsToAppConfigs(selectedScene),
    ],
    rawSceneApps: [
      (s) => [s.selectedScene],
      (selectedScene: appsLogicValues['selectedScene']): Record<string, SceneApp> =>
        normalizeSceneApps(selectedScene?.apps),
    ],
    sceneAppUsageCounts: [
      (s) => [s.selectedScene],
      (selectedScene: appsLogicValues['selectedScene']): Record<string, number> => {
        const sceneAppKeys = Object.keys(selectedScene?.apps ?? {})
        const counts = Object.fromEntries(sceneAppKeys.map((keyword) => [keyword, 0]))
        for (const node of selectedScene?.nodes ?? []) {
          if (node.type === 'app') {
            const keyword = (node.data as AppNodeData | undefined)?.keyword
            if (keyword && keyword in counts) {
              counts[keyword] += 1
            }
          }
        }
        return counts
      },
    ],
    visibleSceneApps: [
      (s) => [s.search, s.sceneApps],
      (search: appsLogicValues['search'], sceneApps: appsLogicValues['sceneApps']): Record<string, AppConfig> => {
        return Object.fromEntries(
          Object.entries(sceneApps).filter(
            ([_, app]) => !search || searchInText(search, app.name) || searchInText(search, app.description)
          )
        )
      },
    ],
    appsWithSaveAssets: [
      (s) => [s.apps],
      (apps: Record<string, AppConfig>): Record<string, string> => {
        return Object.fromEntries(
          Object.entries(apps)
            .filter(([_, app]) => app.fields?.some((f) => !('markdown' in f) && f.name === 'saveAssets'))
            .map(([k, v]) => [k, v.name])
        )
      },
    ],
  }),
  listeners(({ actions, values }) => ({
    deleteUnusedSceneApp: ({ keyword }) => {
      if (!values.selectedSceneId || values.sceneAppUsageCounts[keyword] !== 0) {
        return
      }
      const { [keyword]: _deleted, ...apps } = values.rawSceneApps
      actions.updateScene(values.selectedSceneId, { apps })
    },
  })),
])
