import { MakeLogicType, afterMount, kea, path } from 'kea'
import { forms } from 'kea-forms'
import { urls } from '../../urls'
import { firstUserStatus } from '../../utils/apiFetch'
import { clearCachedProjectId } from '../../utils/projectApi'
import type { DeepPartial, DeepPartialMap, FieldName, ValidationErrorType } from 'kea-forms'

export interface SignupForm {
  email: string
  password: string
  password2: string
  newsletter: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface signupLogicValues {
  isSignupFormSubmitting: boolean
  isSignupFormValid: boolean
  showSignupFormErrors: boolean
  signupForm: SignupForm
  signupFormAllErrors: Record<string, any>
  signupFormChanged: boolean
  signupFormErrors: DeepPartialMap<SignupForm, ValidationErrorType>
  signupFormHasErrors: boolean
  signupFormManualErrors: Record<string, any>
  signupFormTouched: boolean
  signupFormTouches: Record<string, boolean>
  signupFormValidationErrors: DeepPartialMap<SignupForm, ValidationErrorType>
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface signupLogicActions {
  resetSignupForm: (values?: SignupForm) => {
    values?: SignupForm
  }
  setSignupFormManualErrors: (errors: Record<string, any>) => {
    errors: Record<string, any>
  }
  setSignupFormValue: (
    key: FieldName,
    value: any
  ) => {
    name: FieldName
    value: any
  }
  setSignupFormValues: (values: DeepPartial<SignupForm>) => {
    values: DeepPartial<SignupForm>
  }
  submitSignupForm: () => {
    value: boolean
  }
  submitSignupFormFailure: (
    error: Error,
    errors: Record<string, any>
  ) => {
    error: Error
    errors: Record<string, any>
  }
  submitSignupFormRequest: (signupForm: SignupForm) => {
    signupForm: SignupForm
  }
  submitSignupFormSuccess: (signupForm: SignupForm) => {
    signupForm: SignupForm
  }
  touchSignupFormField: (key: string) => {
    key: string
  }
}

export type signupLogicType = MakeLogicType<signupLogicValues, signupLogicActions>

export const signupLogic = kea<signupLogicType>([
  path(['src', 'scenes', 'signup', 'signupLogic']),
  forms(({ actions }) => ({
    signupForm: {
      defaults: {
        email: '',
        password: '',
        password2: '',
        newsletter: false,
      } as SignupForm,
      options: {
        showErrorsOnTouch: true,
        canSubmitWithErrors: true,
      },
      errors: (formData: Partial<SignupForm>) => ({
        email: !formData.email ? 'Please enter an email address' : null,
        password: !formData.password ? 'Please enter a password' : null,
        password2: formData.password !== formData.password2 ? 'Passwords do not match' : null,
      }),
      submit: async (formData) => {
        try {
          const { email, password, password2, newsletter } = formData
          const response = await fetch(`/api/signup`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ email, password, password2, newsletter }),
          })
          if (response.ok) {
            clearCachedProjectId()
            window.location.href = urls.frames()
          } else {
            let errors = {}
            try {
              const json = await response.json()
              if (json.errors) {
                errors = json.errors
              } else if (json.error) {
                errors = { password2: json.error }
              } else if (Array.isArray(json.detail)) {
                const message = json.detail
                  .map((detail: { msg?: string }) => detail?.msg)
                  .filter(Boolean)
                  .join(' ')
                errors = { password2: message || response.statusText }
              } else if (json.detail) {
                errors = { password2: json.detail }
              }
            } catch (e) {
              errors = { password2: response.statusText }
            }
            actions.setSignupFormManualErrors(errors)
          }
        } catch (error) {
          console.error(error)
          actions.setSignupFormManualErrors({ password2: 'An unexpected error occurred.' })
        }
      },
    },
  })),
  afterMount(async () => {
    const status = await firstUserStatus()
    if (status === 'exists') {
      window.location.href = urls.login()
    } else if (status === 'unknown') {
      window.location.href = urls.setupUnavailable()
    }
  }),
])
