repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: trailing-whitespace
      files: ^(backend/|frameos/vendor/).*$

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.14
  hooks:
    # Run the linter.
    - id: ruff
      files: ^(backend/|frameos/vendor/).*$
      args: ['--ignore', 'E402,F403,E722']
      # E402 Module level import not at top of file
      # F403 `from foo import *` used; unable to detect undefined names
      # E722 Do not use bare `except`
