from sqlalchemy import Column, Integer, String, Boolean, DateTime, Float
from sqlalchemy.dialects.sqlite import JSON as SQLiteJSON
from app.core.database import Base

class Frame(Base):
    __tablename__ = "frames"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(256), nullable=False)
    frame_host = Column(String(256), nullable=False)
    frame_port = Column(Integer, default=8787)
    frame_access_key = Column(String(256), nullable=True)
    frame_access = Column(String(50), nullable=True)
    ssh_user = Column(String(50), nullable=True)
    ssh_pass = Column(String(50), nullable=True)
    ssh_port = Column(Integer, default=22)
    server_host = Column(String(256), nullable=True)
    server_port = Column(Integer, default=8989)
    server_api_key = Column(String(64), nullable=True)
    status = Column(String(15), nullable=False)
    version = Column(String(50), nullable=True)
    width = Column(Integer, nullable=True)
    height = Column(Integer, nullable=True)
    device = Column(String(256), nullable=True)
    color = Column(String(256), nullable=True)
    interval = Column(Float, default=300)
    metrics_interval = Column(Float, default=60)
    scaling_mode = Column(String(64), nullable=True)
    rotate = Column(Integer, nullable=True)
    log_to_file = Column(String(256), nullable=True)
    assets_path = Column(String(256), nullable=True)
    save_assets = Column(SQLiteJSON, nullable=True)
    debug = Column(Boolean, nullable=True)
    last_log_at = Column(DateTime, nullable=True)
    reboot = Column(SQLiteJSON, nullable=True)
    control_code = Column(SQLiteJSON, nullable=True)
    apps = Column(SQLiteJSON, nullable=True)
    scenes = Column(SQLiteJSON, nullable=True)
    image_url = Column(String(256), nullable=True)
    background_color = Column(String(64), nullable=True)
