# This file is autogenerated.
# To add a new driver, make an entry in backend/app/models/drivers.py

import pixie
# import inkyPython/inkyPython as inkyDriver
# import frameBuffer/frameBuffer as frameBufferDriver

from frameos/types import Logger

# var inkyDriverInstance: inkyDriver.Driver
# var frameBufferDriverInstance: frameBufferDriver.Driver

proc init*(logger: Logger) =
  # inkyDriverInstance = inkyDriver.init(logger)
  # frameBufferDriverInstance = frameBufferDriver.init(logger)
  discard

proc render*(image: Image) =
  # inkyDriverInstance.render(image)
  # frameBufferDriverInstance.render(image)
  discard
