import { MakeLogicType, actions, connect, events, kea, key, listeners, path, props, reducers, selectors } from 'kea'

import { frameLogic } from '../../frameLogic'
import { FrameScene, FrameId } from '../../../../types'
import type { FrameType } from '../../../../types'

export interface SceneJSONLogicProps {
  frameId: FrameId
  sceneId: string | null
}

function printScene(scene: FrameScene | null): string {
  const { id, default: def, name, settings, fields, nodes, edges, ...rest } = scene ?? {}
  return JSON.stringify(
    {
      id,
      name,
      ...(def ? { default: true } : {}),
      settings,
      fields,
      nodes,
      edges,
      ...rest,
    },
    null,
    2
  )
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface sceneJSONLogicValues {
  frame: FrameType // frameLogic
  frameForm: Partial<FrameType> // frameLogic
  editedSceneJSON: string | null
  hasChanges: boolean
  hasError: boolean
  scene: FrameScene | null
  sceneJSON: string
  sceneName: string
  scenes: FrameScene[]
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface sceneJSONLogicActions {
  updateScene: (
    sceneId: string,
    scene: Partial<FrameScene>
  ) => {
    scene: Partial<FrameScene>
    sceneId: string
  } // frameLogic
  saveChanges: () => {
    value: true
  }
  setEditedSceneJSON: (sceneJSON: string | null) => {
    sceneJSON: string | null
  }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface sceneJSONLogicMeta {
  key: string
  __keaTypeGenInternalSelectorTypes: {
    scenes: (frame: FrameType, frameForm: Partial<FrameType>) => FrameScene[]
    scene: (scenes: FrameScene[], sceneId: string | null) => FrameScene | null
    sceneJSON: (scene: FrameScene | null, editedSceneJSON: string | null) => string
    hasChanges: (sceneJSON: string, scene: FrameScene | null) => boolean
    hasError: (sceneJSON: string) => boolean
    sceneName: (scene: FrameScene | null) => string
  }
}

export type sceneJSONLogicType = MakeLogicType<sceneJSONLogicValues, sceneJSONLogicActions, SceneJSONLogicProps> &
  sceneJSONLogicMeta

export const sceneJSONLogic = kea<sceneJSONLogicType>([
  path(['src', 'scenes', 'frame', 'panels', 'SceneJSON', 'sceneJSONLogic']),
  props({} as SceneJSONLogicProps),
  key((props) => `${props.frameId}/${props.sceneId}`),
  connect(({ frameId }: SceneJSONLogicProps) => ({
    values: [frameLogic({ frameId }), ['frame', 'frameForm']],
    actions: [frameLogic({ frameId }), ['updateScene']],
  })),
  actions({
    setEditedSceneJSON: (sceneJSON: string | null) => ({ sceneJSON }),
    saveChanges: true,
  }),
  reducers({
    editedSceneJSON: [
      null as string | null,
      {
        setEditedSceneJSON: (_, { sceneJSON }) => sceneJSON,
      },
    ],
  }),
  selectors({
    scenes: [
      (s) => [s.frame, s.frameForm],
      (frame: sceneJSONLogicValues['frame'], frameForm: sceneJSONLogicValues['frameForm']) =>
        frameForm.scenes ?? frame.scenes ?? [],
    ],
    scene: [
      (s, p) => [s.scenes, p.sceneId],
      (scenes: sceneJSONLogicValues['scenes'], sceneId: string | null): FrameScene | null =>
        scenes?.find((scene) => scene.id === sceneId) ?? null,
    ],
    sceneJSON: [
      (s) => [s.scene, s.editedSceneJSON],
      (scene: sceneJSONLogicValues['scene'], editedSceneJSON: sceneJSONLogicValues['editedSceneJSON']): string => {
        if (editedSceneJSON !== null) {
          return editedSceneJSON
        }
        return printScene(scene)
      },
    ],
    hasChanges: [
      (s) => [s.sceneJSON, s.scene],
      (sceneJSON: sceneJSONLogicValues['sceneJSON'], scene: sceneJSONLogicValues['scene']) =>
        sceneJSON !== printScene(scene),
    ],
    hasError: [
      (s) => [s.sceneJSON],
      (sceneJSON: sceneJSONLogicValues['sceneJSON']) => {
        if (sceneJSON === null) {
          return false
        }
        try {
          JSON.parse(sceneJSON)
          return false
        } catch {
          return true
        }
      },
    ],
    sceneName: [(s) => [s.scene], (scene: sceneJSONLogicValues['scene']) => scene?.name ?? 'Scene'],
  }),
  events(({ actions }) => ({
    afterMount: () => {
      actions.setEditedSceneJSON(null)
    },
  })),
  listeners(({ values, props, actions }) => ({
    saveChanges: async () => {
      try {
        if (!props.sceneId) {
          return
        }
        const { id: _, default: __, name, ...scene } = JSON.parse(values.sceneJSON)
        actions.updateScene(props.sceneId, {
          id: props.sceneId,
          name,
          ...(values.scene?.default ? { default: true } : {}),
          ...scene,
        })
        actions.setEditedSceneJSON(null)
      } catch {
        console.error('Cannot save invalid JSON')
      }
    },
  })),
])
