#!/usr/bin/env bash
set -euo pipefail

# Make nginx believe Cloudflare — and only Cloudflare — about who the client
# is. Run as root ON the production host; idempotent; --dry-run shows the
# changes and touches nothing.
#
# Why: every public hostname is proxied by Cloudflare, but the origin still
# answers 80/443 from anywhere, and the app keyed rate limits and audit IPs
# on "the Nth-from-the-right X-Forwarded-For entry" with N=2. Anyone who
# reaches the origin directly could send a two-entry chain of their choosing
# and be rate-limited (and logged) as whoever they named. After this script:
#
#   1. /etc/nginx/conf.d/cloudflare-real-ip.conf lists Cloudflare's published
#      ranges as `set_real_ip_from` and takes the client from
#      CF-Connecting-IP — a header Cloudflare always sets to the true client
#      and that a direct request from a non-Cloudflare address cannot use
#      (the realip module only honours it from the listed ranges).
#   2. The proxy snippets send `X-Forwarded-For $remote_addr` — the address
#      nginx now trusts, ONE entry, overwriting whatever the request carried
#      — instead of appending to a client-controlled chain.
#   3. RATE_LIMIT_TRUSTED_PROXY_COUNT=1 in auth-web.env and frame-hub.env,
#      since nginx is now the only hop the app sees.
#
# A request that comes around Cloudflare keys on its own source address.
#
# Cloudflare's ranges change rarely; rerun this when they do (the file
# records the date it was generated). Both apps read the count at start, so
# the script finishes by flipping auth-web to the other instance (zero
# downtime) and restarting the frame hub (frames reconnect within seconds);
# the window between the nginx reload and the restarts is the only moment
# the two disagree, and it is seconds.

conf="/etc/nginx/conf.d/cloudflare-real-ip.conf"
snippets=(/etc/nginx/snippets/frameos-cloud-proxy.conf /etc/nginx/snippets/frameos-frame-hub.conf)
env_files=(/etc/frameos-cloud/auth-web.env /etc/frameos-cloud/frame-hub.env)
sources=(https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6)

dry_run=false
[ "${1:-}" = "--dry-run" ] && dry_run=true
log() { echo "[cloudflare-real-ip] $*"; }
die() { log "$*" >&2; exit 1; }
run() {
  if [ "$dry_run" = true ]; then echo "[cloudflare-real-ip] would run: $*"; else "$@"; fi
}

[ "$(id -u)" -eq 0 ] || die "must run as root on the production host"
nginx -V 2>&1 | grep -q -- '--with-http_realip_module' || die "this nginx has no realip module"

# --- 1. the trusted ranges ---------------------------------------------------

ranges=()
for url in "${sources[@]}"; do
  body="$(curl -fsS --max-time 20 "$url")" || die "could not fetch $url"
  while IFS= read -r cidr; do
    cidr="${cidr//[[:space:]]/}"
    [ -n "$cidr" ] || continue
    [[ "$cidr" =~ ^[0-9a-fA-F:.]+/[0-9]{1,3}$ ]] || die "unexpected line from $url: '$cidr'"
    ranges+=("$cidr")
  done <<<"$body"
done
# Cloudflare publishes ~15 v4 + ~7 v6 ranges; a short list means a truncated
# or wrong answer, and a wrong list would make every visitor "direct".
[ "${#ranges[@]}" -ge 15 ] || die "only ${#ranges[@]} ranges fetched; refusing to write a partial list"

tmp="$(mktemp)"
{
  echo "# Generated by cloud/ops/deploy/cloudflare-real-ip.sh on $(date -u +%F)."
  echo "# Do not edit: rerun the script. Requests from these ranges (Cloudflare's"
  echo "# published edge addresses) get \$remote_addr replaced by CF-Connecting-IP;"
  echo "# from anywhere else the socket peer stays the client."
  for cidr in "${ranges[@]}"; do echo "set_real_ip_from $cidr;"; done
  echo "real_ip_header CF-Connecting-IP;"
} >"$tmp"

if [ -f "$conf" ] && diff -q <(grep -v '^#' "$conf") <(grep -v '^#' "$tmp") >/dev/null; then
  log "$conf already lists these ${#ranges[@]} ranges"
  rm -f "$tmp"
else
  log "writing $conf (${#ranges[@]} ranges)"
  run install -m 0644 "$tmp" "$conf"
  rm -f "$tmp"
fi

# --- 2. one honest X-Forwarded-For entry ------------------------------------

for snippet in "${snippets[@]}"; do
  [ -f "$snippet" ] || { log "no $snippet on this host; skipping"; continue; }
  if grep -q 'proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;' "$snippet"; then
    log "patching $snippet: X-Forwarded-For \$proxy_add_x_forwarded_for -> \$remote_addr"
    if [ "$dry_run" = false ]; then
      [ -e "$snippet.pre-real-ip" ] || cp -p "$snippet" "$snippet.pre-real-ip"
      sed -i 's/proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;/proxy_set_header X-Forwarded-For $remote_addr;/g' "$snippet"
    fi
  elif grep -q 'proxy_set_header X-Forwarded-For \$remote_addr;' "$snippet"; then
    log "$snippet already sends X-Forwarded-For \$remote_addr"
  else
    die "$snippet sets X-Forwarded-For in a way this script does not recognise; edit it by hand"
  fi
done

if [ "$dry_run" = false ]; then
  nginx -t || die "nginx rejected the config; nothing reloaded (restore the .pre-real-ip copies if needed)"
fi

# --- 3. the app counts one proxy hop ----------------------------------------

changed_env=false
for env_file in "${env_files[@]}"; do
  [ -f "$env_file" ] || { log "no $env_file on this host; skipping"; continue; }
  if grep -q '^RATE_LIMIT_TRUSTED_PROXY_COUNT=1$' "$env_file"; then
    log "$env_file already has RATE_LIMIT_TRUSTED_PROXY_COUNT=1"
  elif grep -q '^RATE_LIMIT_TRUSTED_PROXY_COUNT=' "$env_file"; then
    log "setting RATE_LIMIT_TRUSTED_PROXY_COUNT=1 in $env_file"
    run sed -i 's/^RATE_LIMIT_TRUSTED_PROXY_COUNT=.*/RATE_LIMIT_TRUSTED_PROXY_COUNT=1/' "$env_file"
    changed_env=true
  else
    log "appending RATE_LIMIT_TRUSTED_PROXY_COUNT=1 to $env_file"
    [ "$dry_run" = true ] || echo "RATE_LIMIT_TRUSTED_PROXY_COUNT=1" >>"$env_file"
    changed_env=true
  fi
done

# --- 4. apply -----------------------------------------------------------------

log "reloading nginx"
run systemctl reload nginx
if [ "$changed_env" = true ]; then
  log "restarting the frame hub (frames reconnect on their own)"
  run systemctl restart frameos-cloud-frame-hub.service
  log "flipping auth-web to the other instance so it reads the new count"
  run /usr/local/bin/frameos-cloud-update --activate /opt/frameos-cloud
else
  log "apps already on count 1; no restart needed"
fi
log "done. Check: a request through Cloudflare must key on your own IP —"
log "  journalctl -u frameos-cloud-frame-hub -n 20 | grep -i 'client'"
