import {
  MakeLogicType,
  actions,
  afterMount,
  connect,
  kea,
  key,
  listeners,
  path,
  props,
  propsChanged,
  reducers,
  selectors,
} from 'kea'

import { loaders } from 'kea-loaders'
import { Node } from 'reactflow'
import { frameLogic } from '../../frameLogic'
import { editor, MarkerSeverity } from 'monaco-editor'
import { AppNodeData, FrameId } from '../../../../types'
import { appsLogic } from '../Apps/appsLogic'
import { apiFetch } from '../../../../utils/apiFetch'
import { diagramLogic } from '../Diagram/diagramLogic'
import { buildAppTypeDeclarations } from '../../../../utils/appTypeDeclarations'
import {
  appOrigin,
  buildSceneApp,
  hasCompiledAppSource,
  javascriptAppSourceFiles,
  loadAppSources,
  nextSceneAppKey,
  normalizeSceneApps,
  sceneAppToAppConfig,
} from '../../../../utils/sceneApps'
import { sceneExecutionForFrame } from '../../../../utils/sceneExecution'
import type { FrameScene } from '../../../../types'
import type { AppConfig, FrameType } from '../../../../types'
import type { SceneApp } from '../../../../types'

export interface ModelMarker extends editor.IMarkerData {}

export interface EditAppLogicProps {
  frameId: FrameId
  sceneId: string
  nodeId: string
}

export interface SourceError {
  line: number
  column: number
  error: string
}

const sourceLoadOrder = ['README.md', ...javascriptAppSourceFiles, 'app.nim', 'config.nim']
const primaryFiles = ['config.json', ...javascriptAppSourceFiles, 'app.nim']

function firstSourceFile(sources: Record<string, string>): string {
  for (const file of sourceLoadOrder) {
    if (file in sources) {
      return file
    }
  }
  return Object.keys(sources)[0] ?? ''
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface editAppLogicValues {
  apps: Record<string, AppConfig> // appsLogic
  scene: FrameScene | null // diagramLogic
  frameForm: Partial<FrameType> // frameLogic
  activeFile: string
  app: Node<AppNodeData, 'app'> | null
  appData: AppNodeData | null
  appTypeDeclarations: string
  appUsageCount: number
  changedFiles: Record<string, boolean>
  configJson: Record<string, any> | null
  filenames: string[]
  hasChanges: boolean
  hasMultipleAppUsages: boolean
  initialSources: Record<string, string>
  isInterpreted: boolean
  modelMarkers: Record<string, ModelMarker[]>
  requiresCompiledOnSave: boolean
  savedKeyword: string | null
  savedSources: Record<string, string> | null
  sceneApp: SceneApp | null
  sceneAppKey: string | null
  sourceErrors: Record<string, SourceError[]>
  sources: Record<string, string>
  sourcesLoading: boolean
  title: string
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface editAppLogicActions {
  updateNodeData: (
    sceneId: string,
    nodeId: string,
    nodeData: Record<string, any>
  ) => {
    nodeData: Record<string, any>
    nodeId: string
    sceneId: string
  } // frameLogic
  updateScene: (
    sceneId: string,
    scene: Partial<FrameScene>
  ) => {
    scene: Partial<FrameScene>
    sceneId: string
  } // frameLogic
  addFile: () => {
    value: true
  }
  deleteFile: (file: string) => {
    file: string
  }
  discardChanges: () => {
    value: true
  }
  forkAndSaveChanges: () => {
    value: true
  }
  loadSources: () => any
  loadSourcesFailure: (
    error: string,
    errorObject?: any
  ) => {
    error: string
    errorObject?: any
  }
  loadSourcesSuccess: (
    sources: Record<string, string>,
    payload?: any
  ) => {
    sources: Record<string, string>
    payload?: any
  }
  replaceSources: (sources: Record<string, string>) => {
    sources: Record<string, string>
  }
  resetEnhanceSuggestion: () => {
    value: true
  }
  saveChanges: () => {
    value: true
  }
  setActiveFile: (file: string) => {
    file: string
  }
  setInitialSources: (sources: Record<string, string>) => {
    sources: Record<string, string>
  }
  setSourceErrors: (
    file: string,
    errors: SourceError[]
  ) => {
    errors: SourceError[]
    file: string
  }
  updateFile: (
    file: string,
    source: string
  ) => {
    file: string
    source: string
  }
  validateSource: (
    file: string,
    source: string,
    initial?: boolean
  ) => {
    file: string
    initial: boolean
    source: string
  }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface editAppLogicMeta {
  key: string
  __keaTypeGenInternalSelectorTypes: {
    app: (frameForm: Partial<FrameType>, sceneId: string, nodeId: string) => Node<AppNodeData, 'app'> | null
    appData: (app: Node<AppNodeData, 'app'> | null) => AppNodeData | null
    savedKeyword: (appData: AppNodeData | null) => string | null
    sceneAppKey: (scene: FrameScene | null, savedKeyword: string | null) => string | null
    sceneApp: (scene: FrameScene | null, sceneAppKey: string | null) => SceneApp | null
    savedSources: (appData: AppNodeData | null, sceneApp: SceneApp | null) => Record<string, string> | null
    isInterpreted: (scene: FrameScene | null, frameForm: Partial<FrameType>) => boolean
    appUsageCount: (scene: FrameScene | null, sceneAppKey: string | null) => number
    hasMultipleAppUsages: (appUsageCount: number) => boolean
    requiresCompiledOnSave: (isInterpreted: boolean, sources: Record<string, string>) => boolean
    hasChanges: (
      sources: Record<string, string>,
      sourcesLoading: boolean,
      initialSources: Record<string, string>
    ) => boolean
    changedFiles: (sources: Record<string, string>, initialSources: Record<string, string>) => Record<string, boolean>
    configJson: (sources: Record<string, string>) => Record<string, any> | null
    appTypeDeclarations: (configJson: Record<string, any> | null) => string
    title: (
      savedKeyword: string | null,
      nodeId: string,
      apps: Record<string, AppConfig>,
      sceneApp: SceneApp | null,
      configJson: Record<string, any> | null
    ) => string
    modelMarkers: (sourceErrors: Record<string, SourceError[]>) => Record<string, ModelMarker[]>
    filenames: (sources: Record<string, string>) => string[]
  }
}

export type editAppLogicType = MakeLogicType<editAppLogicValues, editAppLogicActions, EditAppLogicProps> &
  editAppLogicMeta

export const editAppLogic = kea<editAppLogicType>([
  path(['src', 'scenes', 'frame', 'panels', 'EditApp', 'editAppLogic']),
  props({} as EditAppLogicProps),
  key((props) => `${props.frameId}:${props.sceneId}.${props.nodeId}`),
  connect(({ frameId, sceneId }: EditAppLogicProps) => ({
    actions: [frameLogic({ frameId }), ['updateNodeData', 'updateScene']],
    values: [
      frameLogic({ frameId }),
      ['frameForm'],
      appsLogic({ frameId }),
      ['apps'],
      diagramLogic({ frameId, sceneId }),
      ['scene'],
    ],
  })),
  actions({
    setActiveFile: (file: string) => ({ file }),
    updateFile: (file: string, source: string) => ({ file, source }),
    saveChanges: true,
    forkAndSaveChanges: true,
    discardChanges: true,
    replaceSources: (sources: Record<string, string>) => ({ sources }),
    setInitialSources: (sources: Record<string, string>) => ({ sources }),
    validateSource: (file: string, source: string, initial: boolean = false) => ({ file, source, initial }),
    setSourceErrors: (file: string, errors: SourceError[]) => ({ file, errors }),
    resetEnhanceSuggestion: true,
    addFile: true,
    deleteFile: (file: string) => ({ file }),
  }),
  selectors({
    app: [
      (s, p) => [s.frameForm, p.sceneId, p.nodeId],
      (
        frameForm: editAppLogicValues['frameForm'],
        sceneId: string,
        nodeId: string
      ): Node<AppNodeData, 'app'> | null => {
        const scene = frameForm?.scenes?.find((scene) => scene.id === sceneId)
        const node = scene?.nodes?.find((node) => node.id === nodeId) as Node<AppNodeData, 'app'> | undefined
        return node ?? null
      },
    ],
    appData: [(s) => [s.app], (app: editAppLogicValues['app']): AppNodeData | null => app?.data || null],
    savedKeyword: [
      (s) => [s.appData],
      (appData: editAppLogicValues['appData']): string | null => appData?.keyword || null,
    ],
    sceneAppKey: [
      (s) => [s.scene, s.savedKeyword],
      (scene: editAppLogicValues['scene'], savedKeyword: editAppLogicValues['savedKeyword']): string | null =>
        savedKeyword && scene?.apps?.[savedKeyword] ? savedKeyword : null,
    ],
    sceneApp: [
      (s) => [s.scene, s.sceneAppKey],
      (scene: editAppLogicValues['scene'], sceneAppKey: editAppLogicValues['sceneAppKey']) =>
        sceneAppKey ? scene?.apps?.[sceneAppKey] ?? null : null,
    ],
    savedSources: [
      (s) => [s.appData, s.sceneApp],
      (
        appData: editAppLogicValues['appData'],
        sceneApp: editAppLogicValues['sceneApp']
      ): Record<string, string> | null => appData?.sources || sceneApp?.sources || null,
    ],
    isInterpreted: [
      (s) => [s.scene, s.frameForm],
      (scene: editAppLogicValues['scene'], frameForm: editAppLogicValues['frameForm']): boolean =>
        sceneExecutionForFrame(scene, frameForm?.mode) === 'interpreted',
    ],
    appUsageCount: [
      (s) => [s.scene, s.sceneAppKey],
      (scene: editAppLogicValues['scene'], sceneAppKey: editAppLogicValues['sceneAppKey']): number =>
        sceneAppKey
          ? (scene?.nodes ?? []).filter(
              (node) => node.type === 'app' && (node.data as AppNodeData | undefined)?.keyword === sceneAppKey
            ).length
          : 1,
    ],
    hasMultipleAppUsages: [
      (s) => [s.appUsageCount],
      (appUsageCount: editAppLogicValues['appUsageCount']): boolean => appUsageCount > 1,
    ],
  }),
  loaders(({ actions, values }) => ({
    sources: [
      {} as Record<string, string>,
      {
        loadSources: async () => {
          let sources: Record<string, string> = {}
          if (values.savedSources) {
            sources = values.savedSources
          } else if (values.savedKeyword) {
            sources = await loadAppSources(values.savedKeyword)
          }
          if (sources['app_loader.nim'] !== undefined) {
            const { ['app_loader.nim']: _ignored, ...filteredSources } = sources
            sources = filteredSources
          }
          actions.setActiveFile(firstSourceFile(sources))
          return sources
        },
      },
    ],
  })),
  reducers(({ props }) => ({
    activeFile: [
      '' as string,
      {
        setActiveFile: (_, { file }) => file,
        resetEnhanceSuggestion: (state) => (state === 'app.nim/suggestion' ? 'app.nim' : state),
        deleteFile: (state, { file }) => (state === file ? 'config.json' : state),
      },
    ],
    sources: {
      updateFile: (state, { file, source }) => ({ ...state, [file]: source }),
      replaceSources: (_, { sources }) => sources,
      deleteFile: (state, { file }) => {
        const newState = { ...state }
        delete newState[file]
        return newState
      },
    },
    initialSources: [
      {} as Record<string, string>,
      {
        loadSourcesSuccess: (_, { sources }) => sources,
        setInitialSources: (_, { sources }) => sources,
      },
    ],
    sourceErrors: [
      {} as Record<string, SourceError[]>,
      {
        setSourceErrors: (state, { file, errors }) => ({ ...state, [file]: errors }),
      },
    ],
  })),
  selectors({
    requiresCompiledOnSave: [
      (s) => [s.isInterpreted, s.sources],
      (isInterpreted: editAppLogicValues['isInterpreted'], sources: editAppLogicValues['sources']): boolean =>
        isInterpreted && hasCompiledAppSource(sources),
    ],
    hasChanges: [
      (s) => [s.sources, s.sourcesLoading, s.initialSources],
      (
        sources: editAppLogicValues['sources'],
        sourcesLoading: editAppLogicValues['sourcesLoading'],
        initialSources: editAppLogicValues['initialSources']
      ) => {
        if (sourcesLoading) {
          return false
        }
        return Object.entries(sources).some(([file, source]) => source !== initialSources[file])
      },
    ],
    changedFiles: [
      (s) => [s.sources, s.initialSources],
      (
        sources: editAppLogicValues['sources'],
        initialSources: editAppLogicValues['initialSources']
      ): Record<string, boolean> => {
        return Object.fromEntries(
          Object.entries(sources).map(([file, source]) => [file, source !== initialSources[file]])
        )
      },
    ],
    configJson: [
      (s) => [s.sources],
      (sources: editAppLogicValues['sources']): Record<string, any> | null => {
        try {
          return JSON.parse(sources['config.json'])
        } catch (e) {
          return null
        }
      },
    ],
    appTypeDeclarations: [
      (s) => [s.configJson],
      (configJson: editAppLogicValues['configJson']): string => buildAppTypeDeclarations(configJson),
    ],
    title: [
      (s, p) => [s.savedKeyword, p.nodeId, s.apps, s.sceneApp, s.configJson],
      (
        keyword: editAppLogicValues['savedKeyword'],
        nodeId: string,
        apps: editAppLogicValues['apps'],
        sceneApp: editAppLogicValues['sceneApp'],
        configJson: editAppLogicValues['configJson']
      ): string => configJson?.name || sceneApp?.name || (keyword ? apps[keyword]?.name || keyword : nodeId),
    ],
    modelMarkers: [
      (s) => [s.sourceErrors],
      (sourceErrors: editAppLogicValues['sourceErrors']): Record<string, ModelMarker[]> =>
        Object.fromEntries(
          Object.entries(sourceErrors).map(([file, errors]) => [
            file,
            errors.map((error) => ({
              startLineNumber: error.line,
              startColumn: error.column,
              endLineNumber: error.line,
              endColumn: error.column,
              message: error.error,
              severity: MarkerSeverity.Error,
            })),
          ])
        ),
    ],
    filenames: [
      (s) => [s.sources],
      (sources: editAppLogicValues['sources']): string[] => {
        const filenames = Object.keys(sources)
        const first = primaryFiles.filter((file) => filenames.includes(file))
        const rest = filenames.filter((f) => !primaryFiles.includes(f)).sort()
        return [...first, ...rest]
      },
    ],
  }),
  listeners(({ actions, props, values }) => ({
    saveChanges: () => {
      const settings = values.requiresCompiledOnSave
        ? { ...values.scene?.settings, execution: 'compiled' as const }
        : values.scene?.settings
      if (values.sceneAppKey) {
        const sceneApps = normalizeSceneApps(values.scene?.apps)
        actions.updateScene(props.sceneId, {
          apps: {
            ...sceneApps,
            [values.sceneAppKey]: buildSceneApp(
              values.sceneAppKey,
              values.apps[values.sceneAppKey],
              values.sources,
              values.sceneApp ?? undefined
            ),
          },
          settings,
        })
      } else {
        if (values.isInterpreted) {
          actions.updateScene(props.sceneId, { settings })
        }
        actions.updateNodeData(props.sceneId, props.nodeId, { sources: values.sources })
      }
      actions.setInitialSources(values.sources)
    },
    discardChanges: () => {
      const nextSources = values.initialSources
      const discardedFiles = Object.keys(values.sources).filter((file) => !(file in nextSources))
      actions.replaceSources(nextSources)
      if (!(values.activeFile in nextSources)) {
        actions.setActiveFile(firstSourceFile(nextSources))
      }
      for (const [file, source] of Object.entries(nextSources)) {
        actions.validateSource(file, source, true)
      }
      for (const file of discardedFiles) {
        actions.setSourceErrors(file, [])
      }
    },
    forkAndSaveChanges: () => {
      const keyword = values.sceneAppKey
      const scene = values.scene
      if (!keyword || !scene) {
        actions.saveChanges()
        return
      }

      const sceneApps = normalizeSceneApps(scene.apps)
      const app = values.apps[keyword] ?? (values.sceneApp ? sceneAppToAppConfig(values.sceneApp) : undefined)
      const newKeyword = nextSceneAppKey(sceneApps, keyword, app)
      const previous = values.sceneApp
        ? { ...values.sceneApp, origin: appOrigin(values.sceneApp) || keyword }
        : { origin: keyword }
      const nodes = scene.nodes?.map((node) => {
        if (node.id !== props.nodeId || node.type !== 'app') {
          return node
        }
        const { sources: _sources, ...data } = (node.data ?? {}) as AppNodeData
        return { ...node, data: { ...data, keyword: newKeyword } }
      })

      actions.updateScene(props.sceneId, {
        apps: {
          ...sceneApps,
          [newKeyword]: buildSceneApp(newKeyword, app, values.sources, previous),
        },
        ...(nodes ? { nodes } : {}),
      })
      actions.setInitialSources(values.sources)
    },
    setInitialSources: ({ sources }) => {
      for (const [file, source] of Object.entries(sources)) {
        actions.validateSource(file, source)
      }
    },
    updateFile: ({ file, source }) => {
      actions.validateSource(file, source)
    },
    validateSource: async ({ initial, file, source }, breakpoint) => {
      if (!initial) {
        await breakpoint(300)
      }
      const response = await apiFetch(`/api/apps/validate_source`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ file, source }),
      })
      const { errors } = await response.json()
      if (!initial) {
        breakpoint()
      }
      actions.setSourceErrors(file, errors || [])
    },
    addFile: () => {
      const fileName = window.prompt('Enter file name')
      if (fileName) {
        actions.updateFile(fileName, '')
        actions.setActiveFile(fileName)
      }
    },
  })),
  afterMount(({ actions, values }) => {
    actions.loadSources()
  }),
])
