## Rasterizes the FrameOS mark (src/frameos/utils/status_screen/frameos_mark.svg)
## into the 1-bit C bitmap the ESP32 thin-client status screen draws
## (embedded/esp32/main/fos_logo_bitmap.h). Thin clients have no pixie, so the
## mark ships as rows of bits: bit (W-1-x) of row y is set where the mark is
## opaque. Re-run after changing the SVG:
##
##   cd frameos && nim r tools/gen_logo_bitmap.nim
##
import std/[os, strutils, strformat]
import pixie
import frameos/utils/status_screen

const
  markHeight = 28
  header = "../embedded/esp32/main/fos_logo_bitmap.h"

let mark = frameosMark(markHeight, color(0, 0, 0, 1))
doAssert mark.width <= 32, "rows are uint32; the mark must be at most 32 px wide"
var lines: seq[string] = @[]
lines.add("/* Generated by frameos/tools/gen_logo_bitmap.nim from")
lines.add(" * frameos/src/frameos/utils/status_screen/frameos_mark.svg — do not edit. */")
lines.add("#pragma once")
lines.add("#include <stdint.h>")
lines.add("")
lines.add(&"#define FOS_LOGO_W {mark.width}")
lines.add(&"#define FOS_LOGO_H {mark.height}")
lines.add("")
lines.add("/* Bit (FOS_LOGO_W - 1 - x) of row y is set where the mark is opaque. */")
lines.add(&"static const uint32_t FOS_LOGO_ROWS[FOS_LOGO_H] = {{")
for y in 0 ..< mark.height:
  var row: uint32 = 0
  var preview = ""
  for x in 0 ..< mark.width:
    let opaque = mark[x, y].a >= 128
    if opaque:
      row = row or (1'u32 shl (mark.width - 1 - x))
    preview.add(if opaque: "#" else: ".")
  lines.add(&"    0x{row:08X}u, /* {preview} */")
lines.add("};")
lines.add("")
let path = currentSourcePath().parentDir() / ".." / header
writeFile(path, lines.join("\n"))
echo "wrote ", path.normalizedPath(), " (", mark.width, "x", mark.height, ")"
