from __future__ import annotations

import argparse
import base64
import gzip
from pathlib import Path


def iter_asset_files(root: Path) -> list[Path]:
    return sorted(path for path in root.rglob("*") if path.is_file())


def asset_key(source_dir: Path, path: Path, asset_root: Path | None = None, key_prefix: str | None = None) -> str:
    if key_prefix is not None:
        if asset_root is None:
            raise ValueError("asset_root is required with key_prefix")
        relative = path.relative_to(asset_root).as_posix()
        return f"{key_prefix.rstrip('/')}/{relative}" if relative else key_prefix.rstrip("/")
    return path.relative_to(source_dir).as_posix()


def compressed_base64(path: Path) -> str:
    return base64.b64encode(gzip.compress(path.read_bytes(), mtime=0)).decode("ascii")


def render_asset_module(
    source_dir: Path,
    asset_paths: list[Path],
    asset_root: Path | None = None,
    key_prefix: str | None = None,
) -> str:
    lines = [
        "# Auto-generated by tools/generate_compressed_asset_nim.py",
        "",
        "import tables, base64, zippy",
        "",
        "var assets: Table[string, string]",
        "",
        "proc getCompressedAsset*(path: string): string =",
        "  assets[path].decode()",
        "",
        "proc getAsset*(path: string): string =",
        "  uncompress(getCompressedAsset(path), dataFormat = dfGzip)",
        "",
        "func toByteSeq(str: string): seq[byte] {.inline.} =",
        "  ## Copy ``string`` memory into an immutable ``seq[byte]``.",
        "  let length = str.len",
        "  if length > 0:",
        "    result = newSeq[byte](length)",
        "    copyMem(result[0].unsafeAddr, str[0].unsafeAddr, length)",
        "",
        "proc getAssetToByteSeq*(path: string): seq[byte] =",
        "  toByteSeq(getAsset(path))",
        "",
        "proc listAssetPaths*(): seq[string] =",
        "  for path in assets.keys:",
        "    result.add(path)",
        "",
    ]

    for path in asset_paths:
        key = asset_key(source_dir, path, asset_root, key_prefix)
        lines.append(f'assets["{key}"] = """{compressed_base64(path)}"""')

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate gzip-compressed asset Nim modules")
    parser.add_argument("--source-dir", default=".", help="FrameOS project root")
    parser.add_argument("--output", required=True, help="Output path for generated Nim module")
    parser.add_argument("--key-prefix", help="Asset key prefix for directories outside the source dir")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--dir", dest="asset_dir", help="Directory to include recursively")
    group.add_argument("--file", dest="asset_file", help="Single file to include")
    args = parser.parse_args()

    source_dir = Path(args.source_dir).resolve()
    output_path = Path(args.output)
    if not output_path.is_absolute():
        output_path = source_dir / output_path

    if args.asset_dir:
        root = (source_dir / args.asset_dir).resolve()
        asset_paths = iter_asset_files(root)
    else:
        asset_paths = [(source_dir / args.asset_file).resolve()]

    output_path.parent.mkdir(parents=True, exist_ok=True)
    asset_root = root if args.asset_dir else None
    output_path.write_text(render_asset_module(source_dir, asset_paths, asset_root, args.key_prefix))


if __name__ == "__main__":
    main()
