#!/usr/bin/env python3
"""Generate the per-language tables of the scene event contract.

Source of truth: docs/events-contract.json (prose: docs/events.md, conformance
corpus: docs/event-fixtures.json). Outputs (all committed):

  frameos/src/frameos/events_gen.nim                    every Nim host (Linux, ESP32, wasm)
  frameos/src/frameos/keyboard_gen.nim                  the keyboard tables (Linux and wasm: the hosts with a keyboard)
  embedded/esp32/main/fos_events_gen.h                  the ESP32's C paths
  frontend/src/utils/eventsContract.gen.ts              the shared SPA (editor, Monaco typings)
  frontend/schema/events.json                           the editor catalog (also read by the legacy
                                                        compiled-scene codegen and the AI context)
  frameos/wasm/src/events.gen.ts                        the frameos-wasm npm package
  cloud/apps/auth-web/src/lib/events-contract.gen.ts    the cloud's event route and schedule validator
  backend/app/utils/events_contract_gen.py              the self-hosted backend

    python3 frameos/tools/generate_events_contract.py          # write
    python3 frameos/tools/generate_events_contract.py --check  # CI: fail if stale

Same arrangement as generate_cloud_contract.py: this script only turns one
JSON document into data files; the few procs that walk them are hand-written,
one small module per language (frameos/src/frameos/events.nim,
frontend/src/utils/eventsContract.ts, …).
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SOURCE = REPO / "docs" / "events-contract.json"
CLOUD_CONTRACT = REPO / "docs" / "cloud-frames-contract.json"
OUTPUTS = {
    "nim": REPO / "frameos" / "src" / "frameos" / "events_gen.nim",
    "nim_keyboard": REPO / "frameos" / "src" / "frameos" / "keyboard_gen.nim",
    "c": REPO / "embedded" / "esp32" / "main" / "fos_events_gen.h",
    "ts_frontend": REPO / "frontend" / "src" / "utils" / "eventsContract.gen.ts",
    "catalog": REPO / "frontend" / "schema" / "events.json",
    "ts_wasm": REPO / "frameos" / "wasm" / "src" / "events.gen.ts",
    "ts_cloud": REPO / "cloud" / "apps" / "auth-web" / "src" / "lib" / "events-contract.gen.ts",
    "py": REPO / "backend" / "app" / "utils" / "events_contract_gen.py",
}
BANNER = "Generated by frameos/tools/generate_events_contract.py from docs/events-contract.json — do not edit."

CLASSES = ["lifecycle", "input", "scene-command", "device-command"]
DEVICES = ["keyboard", "pointer", "button"]
RENDER_AFTER = ["never", "always", "if-state-changed"]
COALESCE = ["none", "latest"]
LOG = ["full", "name-only", "none"]
SCENE_STATE = ["read", "payload"]
CODE_RE = re.compile(r"[A-Z][A-Za-z0-9]*")
FIELD_TYPES = {
    # contract type -> TypeScript
    "string": "string",
    "integer": "number",
    "float": "number",
    "boolean": "boolean",
    "scene": "string",
    "json": "any",
}
CONTEXT_TYPES = {**FIELD_TYPES, "event": "keyof FrameOSEventPayloads | (string & {})", "payload": "any", "image": "FrameOSImageRef"}
SANDBOXES = ["code", "app"]
VERSION_RE = re.compile(r"\d{4}\.\d{1,2}\.\d+")
NAME_RE = re.compile(r"[a-z][A-Za-z0-9]*")


def fail(message):
    raise SystemExit(f"events-contract: {message}")


def load():
    doc = json.loads(SOURCE.read_text())
    origins = list(doc["origins"])
    hosts = doc["hosts"]
    if set(doc["classes"]) != set(CLASSES):
        fail(f"classes must be exactly {CLASSES}")
    verbs = {verb["type"]: verb for verb in json.loads(CLOUD_CONTRACT.read_text())["verbs"]}

    def check_policy(where, spec):
        if spec.get("renderAfter") not in RENDER_AFTER:
            fail(f"{where}: renderAfter must be one of {RENDER_AFTER}")
        if spec.get("coalesce") not in COALESCE:
            fail(f"{where}: coalesce must be one of {COALESCE}")
        if spec.get("log") not in LOG:
            fail(f"{where}: log must be one of {LOG}")
        if not spec.get("origins") or any(o not in origins for o in spec["origins"]):
            fail(f"{where}: origins must be a non-empty subset of {origins}")

    def check_cloud(where, cloud):
        for mapping in [cloud, cloud.get("before")]:
            if mapping is None:
                continue
            verb = verbs.get(mapping.get("verb"))
            if verb is None:
                fail(f"{where}: cloud.verb {mapping.get('verb')!r} is not in docs/cloud-frames-contract.json")
            for profile in mapping.get("profiles", verb["profiles"]):
                if profile not in verb["profiles"]:
                    fail(f"{where}: verb {verb['type']} has no {profile!r} profile")
        if "since" in cloud and not VERSION_RE.fullmatch(cloud["since"]):
            fail(f"{where}: cloud.since must be a FrameOS version")
        if "before" in cloud and "since" not in cloud:
            fail(f"{where}: cloud.before is what a frame older than cloud.since gets — it needs a since")

    custom = doc["customEvents"]
    check_policy("customEvents", custom)
    if not isinstance(custom.get("maxNameLength"), int):
        fail("customEvents.maxNameLength must be an integer")
    declarable = custom.get("declarableOrigins", [])
    if any(o not in origins or o in custom["origins"] for o in declarable):
        fail("customEvents.declarableOrigins: origins a scene opts into, none of them in customEvents.origins")
    if ("cloud" in declarable) != ("cloud" in custom):
        fail("customEvents: the declarable `cloud` origin and the `cloud` verb mapping come together")
    if "cloud" in custom:
        check_cloud("customEvents", custom["cloud"])

    seen = set()
    by_name = {event.get("name"): event for event in doc["events"]}
    for event in doc["events"]:
        name = event.get("name")
        where = f"events.{name}"
        if not isinstance(name, str) or not NAME_RE.fullmatch(name):
            fail(f"{where}: event names are camelCase identifiers")
        if len(name) > custom["maxNameLength"]:
            fail(f"{where}: longer than customEvents.maxNameLength")
        if name in seen:
            fail(f"{where}: listed twice")
        seen.add(name)
        if event.get("class") not in CLASSES:
            fail(f"{where}: class must be one of {CLASSES}")
        if (event["class"] == "input") != ("device" in event):
            fail(f"{where}: `device` is for input events, and every input event has one")
        if "device" in event and event["device"] not in DEVICES:
            fail(f"{where}: device must be one of {DEVICES}")
        if not isinstance(event.get("description"), str) or not event["description"].strip():
            fail(f"{where}: needs a description")
        for flag in ("listen", "dispatch"):
            if not isinstance(event.get(flag), bool):
                fail(f"{where}: `{flag}` must be true or false")
        if event["class"] == "device-command" and (event["listen"] or event["dispatch"]):
            fail(f"{where}: a device command is never delivered to a scene nor offered to one")
        if event["class"] != "device-command" and not (event["listen"] or event["dispatch"]):
            fail(f"{where}: neither listenable nor dispatchable — what is it for?")
        check_policy(where, event)
        if event.get("sceneState") is not None and event["sceneState"] not in SCENE_STATE:
            fail(f"{where}: sceneState must be one of {SCENE_STATE}")
        if set(event.get("hosts", {})) != set(hosts) or any(not isinstance(v, bool) for v in event["hosts"].values()):
            fail(f"{where}: hosts must say true/false for each of {hosts}")
        if "since" in event and not VERSION_RE.fullmatch(event["since"]):
            fail(f"{where}: since must be a FrameOS version")
        field_names = set()
        for field in event.get("payload", []):
            fname = field.get("name")
            if not isinstance(fname, str) or not NAME_RE.fullmatch(fname) or fname in field_names:
                fail(f"{where}: bad or repeated payload field {fname!r}")
            field_names.add(fname)
            if field.get("type") not in FIELD_TYPES:
                fail(f"{where}.{fname}: type must be one of {sorted(FIELD_TYPES)}")
            if not isinstance(field.get("label"), str) or not isinstance(field.get("required"), bool):
                fail(f"{where}.{fname}: needs a label and a required flag")
            if field.get("wire") not in (None, "pointer"):
                fail(f"{where}.{fname}: the only wire form is \"pointer\"")
            if "listenDefault" in field and (not isinstance(field["listenDefault"], str) or not event["listen"]):
                fail(f"{where}.{fname}: listenDefault is the value a listener without a filter on this field hears")
        if sum(1 for f in event.get("payload", []) if "listenDefault" in f) > 1:
            fail(f"{where}: one listenDefault field per event (the generated lookup returns one)")
        if "synthesized" in event and (not isinstance(event["synthesized"], bool) or "driver" not in event["origins"]):
            fail(f"{where}: `synthesized` marks an event the dispatcher makes out of others; it keeps the driver origin")
        alias_of = event.get("aliasOf")
        if alias_of is not None:
            target = by_name.get(alias_of)
            if target is None or target.get("aliasOf") is not None:
                fail(f"{where}: aliasOf must name a contract event that is not itself an alias")
            if target.get("class") != event["class"] or target.get("device") != event.get("device"):
                fail(f"{where}: an alias has its target's class and device")
            target_fields = {f["name"] for f in target.get("payload", [])}
            if not field_names <= target_fields:
                fail(f"{where}: an alias payload is a subset of {alias_of}'s ({sorted(field_names - target_fields)} is not)")
            if event["dispatch"] or not event["listen"]:
                fail(f"{where}: an alias is an old name a listener keeps hearing, nothing more")
        cloud = event.get("cloud")
        if ("cloud" in event["origins"]) != (cloud is not None):
            fail(f"{where}: the `cloud` origin and the `cloud` verb mapping come together")
        if cloud is not None:
            check_cloud(where, cloud)
        schedule = event.get("schedule")
        if schedule is not None:
            if "schedule" not in event["origins"]:
                fail(f"{where}: offered by the schedule editor but `schedule` is not an origin")
            if not isinstance(schedule.get("label"), str):
                fail(f"{where}: schedule.label is what the Schedule panel shows")
            if "since" in schedule and not VERSION_RE.fullmatch(schedule["since"]):
                fail(f"{where}: schedule.since must be a FrameOS version")

    for section, keys in (("gestures", ("tapSlopPx", "tapMs", "doubleTapMs", "longPressMs", "swipeMinPx")),
                          ("buttons", ("longPressMs", "repeatMs"))):
        for key in keys:
            if not isinstance(doc[section].get(key), int) or doc[section][key] <= 0:
                fail(f"{section}.{key}: a positive integer")
    if doc["gestures"].get("directions") != ["left", "right", "up", "down"]:
        fail("gestures.directions: left, right, up, down")
    buttons = doc["buttons"]
    if not buttons.get("roles") or any(not NAME_RE.fullmatch(r) for r in buttons["roles"]):
        fail("buttons.roles: camelCase identifiers")
    if buttons.get("actions") != ["press", "longPress", "repeat", "release"]:
        fail("buttons.actions: press, longPress, repeat, release")
    for label, role in buttons["roleByLabel"].items():
        if label != label.upper() or role not in buttons["roles"]:
            fail(f"buttons.roleByLabel.{label}: an upper-case label and one of buttons.roles")
    if not doc["pointer"].get("types") or any(not NAME_RE.fullmatch(t) for t in doc["pointer"]["types"]):
        fail("pointer.types: camelCase identifiers")
    keyboard = doc["keyboard"]
    codes = set()
    for linux, code in keyboard["codes"].items():
        if not linux.isdigit() or not CODE_RE.fullmatch(code) or code in codes:
            fail(f"keyboard.codes.{linux}: a Linux KEY_* number to one W3C code, once")
        codes.add(code)
    for code, key in keyboard["named"].items():
        if code not in codes or not isinstance(key, str) or not key:
            fail(f"keyboard.named.{code}: a code from keyboard.codes and its `key`")
    if "us" not in keyboard["layouts"]:
        fail("keyboard.layouts: `us` is the default layout")
    for layout_id, layout in keyboard["layouts"].items():
        if not re.fullmatch(r"[a-z]{2}(-[a-z]{2})?", layout_id) or not isinstance(layout.get("label"), str):
            fail(f"keyboard.layouts.{layout_id}: a short id and a label")
        if "inherits" in layout and layout["inherits"] not in keyboard["layouts"]:
            fail(f"keyboard.layouts.{layout_id}: inherits an unknown layout")
        for code, values in layout["keys"].items():
            if code not in codes or code in keyboard["named"]:
                fail(f"keyboard.layouts.{layout_id}.{code}: a printable code from keyboard.codes")
            if not isinstance(values, list) or len(values) not in (2, 3) or any(not isinstance(v, str) for v in values):
                fail(f"keyboard.layouts.{layout_id}.{code}: [unshifted, shifted, altGr?]")
    for key in doc["context"]["keys"]:
        if key.get("type") not in CONTEXT_TYPES:
            fail(f"context.{key.get('name')}: type must be one of {sorted(CONTEXT_TYPES)}")
        if not key.get("sandboxes") or any(s not in SANDBOXES for s in key["sandboxes"]):
            fail(f"context.{key.get('name')}: sandboxes must be a non-empty subset of {SANDBOXES}")
    for name, lines in doc["logEvents"].items():
        if name.startswith("$"):
            continue
        if not isinstance(lines, list) or not all(isinstance(line, str) for line in lines):
            fail(f"logEvents.{name}: a list of log event names")
    return doc


# ------------------------------------------------------------- shared views

def origin_names(doc):
    return list(doc["origins"])


def refused_by_origin(doc):
    """origin -> the contract events it may NOT emit (the old deny-lists, derived)."""
    return {
        origin: [event["name"] for event in doc["events"] if origin not in event["origins"]]
        for origin in origin_names(doc)
    }


def log_events(doc):
    return {name: lines for name, lines in doc["logEvents"].items() if not name.startswith("$")}


def catalog(doc):
    """The editor's view: what a scene can listen for or dispatch, in contract order."""
    out = []
    for event in doc["events"]:
        if not (event["listen"] or event["dispatch"]):
            continue
        entry = {"name": event["name"], "description": event["description"]}
        if event["listen"]:
            entry["canListen"] = True
        if event["dispatch"]:
            entry["canDispatch"] = True
        if event.get("aliasOf"):
            entry["aliasOf"] = event["aliasOf"]
        entry["fields"] = [
            {"name": f["name"], "label": f["label"], "type": f["type"], "required": f["required"],
             **({"listenDefault": f["listenDefault"]} if "listenDefault" in f else {})}
            for f in event.get("payload", [])
            if f.get("catalog", True)
        ]
        out.append(entry)
    return out


def camel(text, first_upper=True):
    parts = re.split(r"[^A-Za-z0-9]+", text)
    joined = "".join(p[:1].upper() + p[1:] for p in parts if p)
    return joined if first_upper else joined[:1].lower() + joined[1:]


def upper_snake(text):
    return re.sub(r"[^A-Za-z0-9]+", "_", re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", text)).upper()


# ----------------------------------------------------------------- Nim

def nim_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def nim_origin(origin):
    return "eo" + camel(origin)


def nim_policy(spec, indent="    "):
    origins = ", ".join(nim_origin(o) for o in spec["origins"])
    return (
        f"{indent}origins: {{{origins}}},\n"
        f"{indent}renderAfter: ra{camel(spec['renderAfter'])}, coalesceLatest: {str(spec['coalesce'] == 'latest').lower()}, "
        f"log: el{camel(spec['log'])}"
    )


def gen_nim(doc):
    events = doc["events"]
    out = [f"# {BANNER}", "#", "# The walkers are in events.nim; this file is data only.", ""]
    out.append("type")
    out.append("  EventOrigin* = enum")
    for origin in origin_names(doc):
        out.append(f"    {nim_origin(origin)} = {nim_str(origin)}")
    out.append("  EventClass* = enum")
    for cls in CLASSES:
        out.append(f"    ec{camel(cls)} = {nim_str(cls)}")
    out.append('    ecCustom = "custom"')
    out.append("  EventDevice* = enum")
    out.append('    edNone = ""')
    for device in DEVICES:
        out.append(f"    ed{camel(device)} = {nim_str(device)}")
    out.append("  EventRenderAfter* = enum")
    for value in RENDER_AFTER:
        out.append(f"    ra{camel(value)} = {nim_str(value)}")
    out.append("  EventLogPolicy* = enum")
    for value in LOG:
        out.append(f"    el{camel(value)} = {nim_str(value)}")
    out.append("  RuntimeCommand* = enum")
    out.append("    ## The device commands: handled by the host before scene dispatch, never")
    out.append("    ## delivered to a scene (event_loop.nim).")
    for event in events:
        if event["class"] == "device-command":
            out.append(f"    rc{camel(event['name'])} = {nim_str(event['name'])}")
    out += [
        "  EventPolicy* = object",
        "    ## No strings and no refs: a policy is read on every thread that sends or",
        "    ## drains events, once per event.",
        "    class*: EventClass",
        "    device*: EventDevice",
        "    listen*, dispatch*: bool",
        "    origins*: set[EventOrigin]",
        "    renderAfter*: EventRenderAfter",
        "    coalesceLatest*: bool",
        "    log*: EventLogPolicy",
        "    endsRuntime*: bool ## the runtime does not survive it (a schedule must remember it fired)",
        "    synthesized*: bool ## made by the dispatcher out of other events (a tap, a textInput)",
        "    aliasOfIndex*: int ## the contract index of the event this one is an old name for, -1 for none",
        "    linux*, esp32*, wasm*: bool",
        "",
        "const",
        f"  EventsContractVersion* = {int(doc['version'])}",
        f"  PointerWireMax* = {int(doc['pointer']['wireMax'])}",
        f"  CustomEventMaxNameLength* = {int(doc['customEvents']['maxNameLength'])}",
        "  ## How the dispatcher makes gestures out of pointerDown / pointerUp (docs/events.md).",
        f"  GestureTapSlopPx* = {int(doc['gestures']['tapSlopPx'])}",
        f"  GestureTapMs* = {int(doc['gestures']['tapMs'])}",
        f"  GestureDoubleTapMs* = {int(doc['gestures']['doubleTapMs'])}",
        f"  GestureLongPressMs* = {int(doc['gestures']['longPressMs'])}",
        f"  GestureSwipeMinPx* = {int(doc['gestures']['swipeMinPx'])}",
        "  ## A GPIO button held: `longPress` once, then `repeat` every so often.",
        f"  ButtonLongPressMs* = {int(doc['buttons']['longPressMs'])}",
        f"  ButtonRepeatMs* = {int(doc['buttons']['repeatMs'])}",
        f"  ButtonRoles*: array[{len(doc['buttons']['roles'])}, string] = [{', '.join(nim_str(r) for r in doc['buttons']['roles'])}]",
        f"  PointerTypes*: array[{len(doc['pointer']['types'])}, string] = [{', '.join(nim_str(t) for t in doc['pointer']['types'])}]",
        "  ## Origins a scene opts into per custom event (`origins` on its declaration).",
        f"  CustomEventDeclarableOrigins*: set[EventOrigin] = {{{', '.join(nim_origin(o) for o in doc['customEvents'].get('declarableOrigins', []))}}}",
        "",
    ]
    for event in events:
        out.append(f"  ev{camel(event['name'])}* = {nim_str(event['name'])}")
    out.append("")
    out.append(f"  ContractEventNames*: array[{len(events)}, string] = [")
    out += [f"    ev{camel(e['name'])}," for e in events]
    out.append("  ]")
    out.append("")
    out.append(f"  ContractEventPolicies*: array[{len(events)}, EventPolicy] = [")
    for event in events:
        device = "ed" + camel(event["device"]) if "device" in event else "edNone"
        hosts = ", ".join(f"{host}: {str(event['hosts'][host]).lower()}" for host in doc["hosts"])
        out.append(f"    EventPolicy( # {event['name']}")
        out.append(f"      class: ec{camel(event['class'])}, device: {device}, "
                   f"listen: {str(event['listen']).lower()}, dispatch: {str(event['dispatch']).lower()},")
        out.append(nim_policy(event, "      ") + ",")
        if event.get("schedule", {}).get("endsRuntime"):
            out.append("      endsRuntime: true,")
        if event.get("synthesized"):
            out.append("      synthesized: true,")
        alias_index = index_of(events, event["aliasOf"]) if event.get("aliasOf") else -1
        out.append(f"      aliasOfIndex: {alias_index},")
        out.append(f"      {hosts}),")
    out.append("  ]")
    out.append("")
    out.append("  CustomEventPolicy* = EventPolicy(")
    out.append("    class: ecCustom, device: edNone, listen: true, dispatch: true,")
    out.append(nim_policy(doc["customEvents"]) + ",")
    out.append("    aliasOfIndex: -1,")
    out.append("    " + ", ".join(f"{host}: true" for host in doc["hosts"]) + ")")
    out.append("")
    for name, lines in log_events(doc).items():
        out.append(f"  {camel(name)}LogEvents*: array[{len(lines)}, string] = [{', '.join(nim_str(l) for l in lines)}]")
    out.append("")
    out.append("proc contractEventIndex*(name: string): int =")
    out.append("  ## Index into the tables above, -1 for a custom event. A `case` over string")
    out.append("  ## literals: no allocation, no table to share between threads.")
    out.append("  case name")
    for index, event in enumerate(events):
        out.append(f"  of ev{camel(event['name'])}: {index}")
    out.append("  else: -1")
    out.append("")
    # Procs, not iterators: an inline iterator copies its loop body into every
    # call site once per `yield`, and with ~80 payload keys that was 20 KB of
    # flash in the interpreter alone on the ESP32.
    aliases_of = {event["name"]: [a["name"] for a in events if a.get("aliasOf") == event["name"]] for event in events}
    out.append("proc eventAliasCount*(name: string): int =")
    out.append("  ## How many old names a listener may know `name` by (eventAlias).")
    out.append("  case name")
    for event in events:
        if aliases_of[event["name"]]:
            out.append(f"  of ev{camel(event['name'])}: {len(aliases_of[event['name']])}")
    out.append("  else: 0")
    out.append("")
    out.append("proc eventAlias*(name: string, index: int): string =")
    out.append("  ## The old names of `name`, in order; the dispatcher delivers each one too,")
    out.append("  ## with that alias's own (smaller) payload. Empty past eventAliasCount.")
    out.append("  case name")
    for event in events:
        if aliases_of[event["name"]]:
            out.append(f"  of ev{camel(event['name'])}:")
            out.append("    case index")
            for i, alias in enumerate(aliases_of[event["name"]]):
                out.append(f"    of {i}: ev{camel(alias)}")
            out.append('    else: ""')
    out.append('  else: ""')
    out.append("")
    out.append("proc eventPayloadKeyCount*(name: string): int =")
    out.append("  ## How many payload fields the contract lists for `name` (0 for a custom event).")
    out.append("  case name")
    for event in events:
        if event.get("payload"):
            out.append(f"  of ev{camel(event['name'])}: {len(event['payload'])}")
    out.append("  else: 0")
    out.append("")
    out.append("proc eventPayloadKey*(name: string, index: int): string =")
    out.append("  ## The contract's payload fields of `name`, in order. Empty past the count.")
    out.append("  case name")
    for event in events:
        if event.get("payload"):
            out.append(f"  of ev{camel(event['name'])}:")
            out.append("    case index")
            for i, field in enumerate(event["payload"]):
                out.append(f"    of {i}: {nim_str(field['name'])}")
            out.append('    else: ""')
    out.append('  else: ""')
    out.append("")
    out.append("proc eventListenDefault*(name: string): (string, string) =")
    out.append("  ## The one payload field of `name` with a `listenDefault`, and the value: a")
    out.append("  ## listener with no filter on that field hears only events where it equals")
    out.append("  ## this (`button` without an `action` filter hears presses). (\"\", \"\"): none.")
    out.append("  case name")
    for event in events:
        defaults = [f for f in event.get("payload", []) if "listenDefault" in f]
        if defaults:
            out.append(f"  of ev{camel(event['name'])}: ({nim_str(defaults[0]['name'])}, {nim_str(defaults[0]['listenDefault'])})")
    out.append('  else: ("", "")')
    out.append("")
    out.append("proc buttonRoleForLabel*(upperLabel: string): string =")
    out.append("  ## The default role of a GPIO button that has none configured, by its label")
    out.append("  ## (upper-cased by the caller); empty when the label says nothing.")
    out.append("  case upperLabel")
    for label, role in doc["buttons"]["roleByLabel"].items():
        out.append(f"  of {nim_str(label)}: {nim_str(role)}")
    out.append('  else: ""')
    return "\n".join(out) + "\n"


def index_of(events, name):
    for index, event in enumerate(events):
        if event["name"] == name:
            return index
    fail(f"no event {name}")


def resolved_layout(keyboard, layout_id):
    """A layout's full table: what it inherits, then what it lists."""
    layout = keyboard["layouts"][layout_id]
    table = dict(resolved_layout(keyboard, layout["inherits"])) if "inherits" in layout else {}
    if "inherits" not in layout:
        for code in keyboard["codes"].values():
            if code.startswith("Key") and len(code) == 4:
                table[code] = [code[3].lower(), code[3], ""]
    for code, values in layout["keys"].items():
        table[code] = list(values) + [""] * (3 - len(values))
    return table


def gen_nim_keyboard(doc):
    keyboard = doc["keyboard"]
    layouts = list(keyboard["layouts"])
    out = [f"# {BANNER}", "#",
           "# The keyboard tables: a Linux key number to its W3C `code`, a code to the `key`",
           "# it means when it is not printable, and per layout what a printable code",
           "# means as (unshifted, shifted, altGr). Only the hosts with a keyboard compile",
           "# this (frameos/input_state.nim); the ESP32 does not.", ""]
    out.append("const")
    out.append(f"  DefaultKeyboardLayout* = \"us\"")
    out.append(f"  KeyboardLayoutIds*: array[{len(layouts)}, string] = [{', '.join(nim_str(l) for l in layouts)}]")
    out.append("")
    out.append("proc linuxKeyCode*(linuxCode: int): string =")
    out.append("  ## The W3C KeyboardEvent.code of a Linux KEY_* number; empty when unknown.")
    out.append("  case linuxCode")
    for linux, code in keyboard["codes"].items():
        out.append(f"  of {int(linux)}: {nim_str(code)}")
    out.append('  else: ""')
    out.append("")
    out.append("proc keyNamedValue*(code: string): string =")
    out.append("  ## The `key` of a code that is not printable (\"Enter\", \"ArrowLeft\"); empty for")
    out.append("  ## a printable one, whose key is the layout's.")
    out.append("  case code")
    for code, key in keyboard["named"].items():
        out.append(f"  of {nim_str(code)}: {nim_str(key)}")
    out.append('  else: ""')
    out.append("")
    out.append("proc isKeyboardLayout*(layout: string): bool =")
    out.append("  layout in KeyboardLayoutIds")
    out.append("")
    for layout_id in layouts:
        out.append(f"proc layoutKey{camel(layout_id)}(code: string): (string, string, string) =")
        out.append("  case code")
        for code, values in sorted(resolved_layout(keyboard, layout_id).items()):
            out.append(f"  of {nim_str(code)}: ({nim_str(values[0])}, {nim_str(values[1])}, {nim_str(values[2])})")
        out.append('  else: ("", "", "")')
        out.append("")
    out.append("proc keyboardLayoutKey*(layout, code: string): (string, string, string) =")
    out.append("  ## What a printable `code` means under `layout`: (unshifted, shifted, altGr);")
    out.append("  ## empty strings for a code the layout has no character for. An unknown")
    out.append("  ## layout is the default.")
    out.append("  case layout")
    for layout_id in layouts:
        if layout_id == "us":
            continue
        out.append(f"  of {nim_str(layout_id)}: layoutKey{camel(layout_id)}(code)")
    out.append("  else: layoutKeyUs(code)")
    return "\n".join(out) + "\n"


# ------------------------------------------------------------------- C

def c_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def gen_c(doc):
    origins = origin_names(doc)
    out = [
        f"/* {BANNER}",
        " *",
        " * Header-only and IDF-free: names, classes and the origin allow-lists — what",
        " * is left of an event's policy (log, render-after, coalescing) is the Nim",
        " * dispatcher's — for the one C path that looks at an event before the Nim runtime",
        " * does (fos_events.c, which every producer calls) and the cloud verb that",
        " * vets a name first (fos_cloud.c). Host-tested by main/tests/test_fos_events.c. */",
        "#pragma once",
        "",
        "#include <stdbool.h>",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "#include <string.h>",
        "",
        f"#define FOS_EVENTS_CONTRACT_VERSION {int(doc['version'])}",
        f"#define FOS_POINTER_WIRE_MAX {int(doc['pointer']['wireMax'])}",
        f"#define FOS_CUSTOM_EVENT_MAX_NAME_LENGTH {int(doc['customEvents']['maxNameLength'])}",
        "",
        "/* `button {action}`: the firmware reports the edges; longPress and repeat are the",
        " * Nim dispatcher's (frameos/input_state.nim), like on every host. */",
    ]
    for action in doc["buttons"]["actions"]:
        out.append(f"#define FOS_BUTTON_ACTION_{upper_snake(action)} {c_str(action)}")
    out.append("")
    for event in doc["events"]:
        out.append(f"#define FOS_EVENT_{upper_snake(event['name'])} {c_str(event['name'])}")
    out += ["", "typedef enum {"]
    for index, origin in enumerate(origins):
        out.append(f"    FOS_ORIGIN_{upper_snake(origin)} = 1u << {index},")
    out += ["} fos_event_origin_t;", "", "typedef enum {"]
    for cls in CLASSES:
        out.append(f"    FOS_EVENT_CLASS_{upper_snake(cls)},")
    out += [
        "    FOS_EVENT_CLASS_CUSTOM,",
        "} fos_event_class_t;",
        "",
        "typedef struct {",
        "    const char *name;",
        "    uint8_t event_class;   /* fos_event_class_t */",
        "    uint16_t origins;      /* mask of fos_event_origin_t that may emit it */",
        "    uint8_t ends_runtime;  /* the firmware does not survive it: a schedule must remember it fired */",
        "} fos_event_spec_t;",
        "",
    ]

    def mask(spec):
        return " | ".join(f"FOS_ORIGIN_{upper_snake(o)}" for o in spec["origins"])

    out.append("static const fos_event_spec_t FOS_EVENT_SPECS[] = {")
    for event in doc["events"]:
        out.append(
            f"    {{FOS_EVENT_{upper_snake(event['name'])}, FOS_EVENT_CLASS_{upper_snake(event['class'])},\n"
            f"     {mask(event)}, {1 if event.get('schedule', {}).get('endsRuntime') else 0}}},"
        )
    out.append("};")
    out.append(f"#define FOS_EVENT_SPEC_COUNT {len(doc['events'])}")
    out.append("")
    custom = doc["customEvents"]
    out.append("static const fos_event_spec_t FOS_CUSTOM_EVENT_SPEC = {")
    out.append(f"    NULL, FOS_EVENT_CLASS_CUSTOM,\n     {mask(custom)}, 0}};")
    declarable = " | ".join(f"FOS_ORIGIN_{upper_snake(o)}" for o in custom.get("declarableOrigins", [])) or "0"
    out.append("/* Origins a scene opts into per custom event; the Nim dispatcher knows the scene's answer. */")
    out.append(f"#define FOS_CUSTOM_EVENT_DECLARABLE_ORIGINS ({declarable})")
    out += [
        "",
        "/* The contract row of `name`; the custom-event row for any other name. Never NULL. */",
        "static inline const fos_event_spec_t *fos_event_spec(const char *name)",
        "{",
        "    if (name != NULL) {",
        "        for (size_t i = 0; i < FOS_EVENT_SPEC_COUNT; i++) {",
        "            if (strcmp(FOS_EVENT_SPECS[i].name, name) == 0) {",
        "                return &FOS_EVENT_SPECS[i];",
        "            }",
        "        }",
        "    }",
        "    return &FOS_CUSTOM_EVENT_SPEC;",
        "}",
        "",
        "/* What the firmware's C edges ask (fos_events.c). For a custom event an origin",
        " * a scene can opt into passes here: whether the scene showing declared it is",
        " * the Nim dispatcher's to say (frameos/event_loop.nim). */",
        "static inline bool fos_event_origin_may_emit(fos_event_origin_t origin, const char *name)",
        "{",
        "    const fos_event_spec_t *spec = fos_event_spec(name);",
        "    if ((spec->origins & (uint16_t)origin) != 0) {",
        "        return true;",
        "    }",
        "    return spec->event_class == FOS_EVENT_CLASS_CUSTOM &&",
        "           (FOS_CUSTOM_EVENT_DECLARABLE_ORIGINS & (uint16_t)origin) != 0;",
        "}",
        "",
        "static inline bool fos_event_is_device_command(const char *name)",
        "{",
        "    return fos_event_spec(name)->event_class == FOS_EVENT_CLASS_DEVICE_COMMAND;",
        "}",
        "",
        "/* The contract's name for one origin bit, for log lines. Never NULL. */",
        "static inline const char *fos_event_origin_name(fos_event_origin_t origin)",
        "{",
        "    switch (origin) {",
    ]
    for origin in origins:
        out.append(f"        case FOS_ORIGIN_{upper_snake(origin)}: return {c_str(origin)};")
    out += [
        "    }",
        '    return "unknown";',
        "}",
    ]
    return "\n".join(out) + "\n"


# ---------------------------------------------------------- TypeScript

def ts_json(value, indent=2):
    return json.dumps(value, indent=indent, ensure_ascii=False)


def ts_payload_type(event):
    if event.get("sceneState") == "read":
        return "Record<string, any>"
    fields = event.get("payload", [])
    if not fields:
        return "Record<string, never>"
    parts = [f"{f['name']}{'' if f['required'] else '?'}: {FIELD_TYPES[f['type']]}" for f in fields]
    return "{ " + "; ".join(parts) + " }"


def ts_context_block(doc, sandbox):
    lines = []
    for key in doc["context"]["keys"]:
        if sandbox not in key["sandboxes"]:
            continue
        optional = "?" if key.get("optional") else ""
        lines.append(f"  /** {key['description']} */")
        lines.append(f"  {key['name']}{optional}: {CONTEXT_TYPES[key['type']]};")
    return "\n".join(lines)


def ts_event_declarations(doc):
    """Ambient declarations for Monaco: event names and what each one carries."""
    lines = ["/** What each built-in scene event carries in `context.payload` (docs/events.md). */",
             "interface FrameOSEventPayloads {"]
    for event in doc["events"]:
        if not (event["listen"] or event["dispatch"]):
            continue
        lines.append(f"  /** {event['description']} */")
        lines.append(f"  {event['name']}: {ts_payload_type(event)};")
    # Interfaces only: both editors add their declarations to one Monaco
    # TypeScript program, where a second `type` alias of the same name is a
    # duplicate identifier and a second identical interface simply merges.
    lines += ["}", ""]
    return "\n".join(lines)


def spec_view(doc, event):
    view = {
        "class": event["class"],
        **({"device": event["device"]} if "device" in event else {}),
        **({"aliasOf": event["aliasOf"]} if "aliasOf" in event else {}),
        **({"synthesized": True} if event.get("synthesized") else {}),
        "listen": event["listen"],
        "dispatch": event["dispatch"],
        **({"sceneState": event["sceneState"]} if "sceneState" in event else {}),
        "origins": event["origins"],
        "renderAfter": event["renderAfter"],
        "coalesce": event["coalesce"],
        "log": event["log"],
        "hosts": event["hosts"],
        **({"since": event["since"]} if "since" in event else {}),
        **({"schedule": event["schedule"]} if "schedule" in event else {}),
        **({"cloud": event["cloud"]} if "cloud" in event else {}),
    }
    return view


def gen_ts_frontend(doc):
    origins = origin_names(doc)
    out = [f"// {BANNER}", "//", "// The helpers that read these tables are in eventsContract.ts.", ""]
    out.append(f"export const EVENTS_CONTRACT_VERSION = {int(doc['version'])}")
    out.append(f"export const POINTER_WIRE_MAX = {int(doc['pointer']['wireMax'])}")
    out.append(f"export const CUSTOM_EVENT_MAX_NAME_LENGTH = {int(doc['customEvents']['maxNameLength'])}")
    out.append("")
    out.append("export type EventOrigin = " + " | ".join(f"'{o}'" for o in origins))
    out.append("export type EventClass = " + " | ".join(f"'{c}'" for c in CLASSES))
    out.append("export type EventDevice = " + " | ".join(f"'{d}'" for d in DEVICES))
    out.append("export type EventRenderAfter = " + " | ".join(f"'{v}'" for v in RENDER_AFTER))
    out.append("export type EventCoalesce = " + " | ".join(f"'{v}'" for v in COALESCE))
    out.append("export type EventLogPolicy = " + " | ".join(f"'{v}'" for v in LOG))
    out.append("export type ContractEventName =\n  | " + "\n  | ".join(f"'{e['name']}'" for e in doc["events"]))
    out.append("")
    out += [
        "export interface ContractEventSpec {",
        "  class: EventClass",
        "  device?: EventDevice",
        "  /** An old name of `aliasOf`: a listener keeps hearing it, the editor does not offer it. */",
        "  aliasOf?: ContractEventName",
        "  /** Made by the dispatcher out of other events (a tap, a textInput). */",
        "  synthesized?: boolean",
        "  listen: boolean",
        "  dispatch: boolean",
        "  /** 'read': an event node offers the scene's state; 'payload': the payload IS the scene's state fields. */",
        "  sceneState?: 'read' | 'payload'",
        "  origins: EventOrigin[]",
        "  renderAfter: EventRenderAfter",
        "  coalesce: EventCoalesce",
        "  log: EventLogPolicy",
        "  hosts: { " + "; ".join(f"{h}: boolean" for h in doc["hosts"]) + " }",
        "  since?: string",
        "  /** Offered by the Schedule panel. `endsRuntime`: the runtime does not survive it. */",
        "  schedule?: { label: string; description?: string; since?: string; endsRuntime?: boolean }",
        "  cloud?: {",
        "    verb: string",
        "    profiles?: string[]",
        "    eventRoute?: boolean",
        "    since?: string",
        "    before?: { verb: string; profiles?: string[] }",
        "  }",
        "}",
        "",
    ]
    specs = {event["name"]: spec_view(doc, event) for event in doc["events"]}
    out.append(f"export const contractEventSpecs: Record<ContractEventName, ContractEventSpec> = {ts_json(specs)}")
    out.append("")
    custom = doc["customEvents"]
    custom_view = {k: custom[k] for k in ("origins", "renderAfter", "coalesce", "log")}
    out.append(
        "export const customEventPolicy: Pick<ContractEventSpec, 'origins' | 'renderAfter' | 'coalesce' | 'log'> = "
        + ts_json(custom_view)
    )
    out.append("")
    out.append("/** Origins a scene opts into per custom event: `origins` on its declaration. */")
    out.append(f"export const customEventDeclarableOrigins: readonly EventOrigin[] = {ts_json(custom.get('declarableOrigins', []), None)}")
    out.append("")
    for name, lines in log_events(doc).items():
        out.append(f"/** Log lines, not scene events (docs/events-contract.json `logEvents`). */")
        out.append(f"export const {name}LogEvents: readonly string[] = {ts_json(lines, None)}")
    out.append("")
    out.append("/** GPIO button roles (`gpioButtons[].role`), and the default by label for a button without one. */")
    out.append(f"export const buttonRoles: readonly string[] = {ts_json(doc['buttons']['roles'], None)}")
    out.append(f"export const buttonRoleByLabel: Record<string, string> = {ts_json(doc['buttons']['roleByLabel'])}")
    out.append(f"export const buttonActions: readonly string[] = {ts_json(doc['buttons']['actions'], None)}")
    out.append("")
    out.append("/** Keyboard layouts a frame's `keyboardLayout` setting can name. */")
    out.append("export const keyboardLayouts: readonly { id: string; label: string }[] = "
               + ts_json([{"id": k, "label": v["label"]} for k, v in doc["keyboard"]["layouts"].items()]))
    out.append("export const defaultKeyboardLayout = 'us'")
    out.append("")
    out.append("/** `context` keys per JavaScript sandbox. */")
    for sandbox in SANDBOXES:
        keys = [k["name"] for k in doc["context"]["keys"] if sandbox in k["sandboxes"]]
        out.append(f"export const {sandbox}ContextKeys: readonly string[] = {ts_json(keys, None)}")
    out.append("")
    out.append("/** Ambient declarations for the Monaco editors: event names and payloads. */")
    out.append("export const eventTypeDeclarations = `" + ts_event_declarations(doc).replace("`", "\\`") + "`")
    out.append("")
    out.append("/** The members of a code node's `context`. */")
    out.append("export const codeContextMembers = `" + ts_context_block(doc, "code") + "\n`")
    out.append("")
    out.append("/** The members of a JavaScript app's `FrameOSContext`. */")
    out.append("export const appContextMembers = `" + ts_context_block(doc, "app") + "\n`")
    return "\n".join(out) + "\n"


def gen_catalog(doc):
    return json.dumps(catalog(doc), indent=2, ensure_ascii=False) + "\n"


def names_where(doc, predicate):
    return [event["name"] for event in doc["events"] if predicate(event)]


def gen_ts_wasm(doc):
    hosted = names_where(doc, lambda e: e["class"] in ("lifecycle", "scene-command"))
    pointer = names_where(doc, lambda e: e.get("device") == "pointer")
    keyboard = names_where(doc, lambda e: e.get("device") == "keyboard")
    out = [
        f"// {BANNER}",
        "",
        "/** Both pointer axes on the wire: 0..POINTER_WIRE_MAX across the picture. */",
        f"export const POINTER_WIRE_MAX = {int(doc['pointer']['wireMax'])}",
        "",
        "/** Lifecycle events and scene commands: the host sends these, a button would not. */",
        f"export const HOST_EVENT_NAMES: readonly string[] = {ts_json(hosted, None)}",
        "",
        "/** Pointer input: sent by the canvas with a position, never by a button. */",
        f"export const POINTER_EVENT_NAMES: readonly string[] = {ts_json(pointer, None)}",
        "",
        "/** Keyboard input: sent by the focused canvas, never by a button. */",
        f"export const KEYBOARD_EVENT_NAMES: readonly string[] = {ts_json(keyboard, None)}",
    ]
    return "\n".join(out) + "\n"


def gen_ts_cloud(doc):
    def route(cloud):
        return {key: cloud[key] for key in ("verb", "profiles", "since", "before") if key in cloud}

    routed = {
        event["name"]: route(event["cloud"])
        for event in doc["events"]
        if event.get("cloud") and event["cloud"].get("eventRoute", True)
    }
    out = [
        f"// {BANNER}",
        "",
        f"export const customEventMaxNameLength = {int(doc['customEvents']['maxNameLength'])};",
        "",
        "/** Every built-in event name. Any other name is a custom scene event. */",
        f"export const contractEventNames: readonly string[] = {ts_json([e['name'] for e in doc['events']], None)};",
        "",
        "export type CloudEventRoute = {",
        "  verb: string;",
        "  profiles?: readonly string[];",
        "  /** The FrameOS version whose frames know `verb`; older ones get `before`, or a refusal. */",
        "  since?: string;",
        "  before?: { verb: string; profiles?: readonly string[] };",
        "};",
        "",
        "/** Events the frame event route accepts, and the hub verb each becomes.",
        " * `profiles`: the device planes whose verb can carry it (absent = all). */",
        f"export const cloudEventRouteVerbs: Record<string, CloudEventRoute> = {ts_json(routed)};",
        "",
        "/** A custom scene event: sent when the scene declares it with the `cloud` origin. */",
        f"export const cloudCustomEventRoute: CloudEventRoute = {ts_json(route(doc['customEvents']['cloud']))};",
        "",
        "/** Origins a scene opts into per custom event: `origins` on its declaration. */",
        f"export const customEventDeclarableOrigins: readonly string[] = {ts_json(doc['customEvents'].get('declarableOrigins', []), None)};",
        "",
        "/** Contract events a schedule entry may not fire: the device refuses them. */",
        f"export const scheduleRefusedEvents: readonly string[] = {ts_json(refused_by_origin(doc)['schedule'], None)};",
    ]
    return "\n".join(out) + "\n"


# -------------------------------------------------------------- Python

def gen_py(doc):
    refused = refused_by_origin(doc)
    out = [f'"""{BANNER}"""', "", f"EVENTS_CONTRACT_VERSION = {int(doc['version'])}", ""]
    out.append("# origin -> contract events it may not emit. `http:write` is the frame access")
    out.append("# key: what it is refused needs an admin session or the serverApiKey instead.")
    out.append("REFUSED_BY_ORIGIN: dict[str, frozenset[str]] = {")
    for origin in origin_names(doc):
        names = ", ".join(json.dumps(name) for name in refused[origin])
        out.append(f"    {json.dumps(origin)}: frozenset({{{names}}}),")
    out.append("}")
    out.append("")
    out.append("# Origins a scene opts into per custom event: `origins` on its declaration.")
    declarable = ", ".join(json.dumps(o) for o in doc["customEvents"].get("declarableOrigins", []))
    out.append(f"CUSTOM_EVENT_DECLARABLE_ORIGINS: frozenset[str] = frozenset({{{declarable}}})")
    out.append("")
    device = names_where(doc, lambda e: e["class"] == "device-command")
    out.append("DEVICE_COMMAND_EVENTS: frozenset[str] = frozenset({" + ", ".join(json.dumps(n) for n in device) + "})")
    out.append("")
    out.append("# The frame's input settings (frame.json `inputSettings`): the keyboard layout")
    out.append("# ids of `keyboard.layouts`, `us` being the default, and the button roles a")
    out.append("# `gpioButtons[].role` may carry (`buttons.roles`).")
    out.append('DEFAULT_KEYBOARD_LAYOUT = "us"')
    layouts = ", ".join(json.dumps(layout_id) for layout_id in doc["keyboard"]["layouts"])
    out.append(f"KEYBOARD_LAYOUTS: tuple[str, ...] = ({layouts})")
    roles = ", ".join(json.dumps(role) for role in doc["buttons"]["roles"])
    out.append(f"BUTTON_ROLES: tuple[str, ...] = ({roles})")
    out.append("")
    for name, lines in log_events(doc).items():
        out.append("# Log lines, not scene events (docs/events-contract.json `logEvents`).")
        items = ", ".join(json.dumps(line) for line in lines) + ("," if len(lines) == 1 else "")
        out.append(f"{upper_snake(name)}_LOG_EVENTS: tuple[str, ...] = ({items})")
    return "\n".join(out) + "\n"


GENERATORS = {
    "nim": gen_nim,
    "nim_keyboard": gen_nim_keyboard,
    "c": gen_c,
    "ts_frontend": gen_ts_frontend,
    "catalog": gen_catalog,
    "ts_wasm": gen_ts_wasm,
    "ts_cloud": gen_ts_cloud,
    "py": gen_py,
}


def main():
    check = "--check" in sys.argv
    doc = load()
    stale = []
    for key, path in OUTPUTS.items():
        text = GENERATORS[key](doc)
        if check:
            if not path.is_file() or path.read_text() != text:
                stale.append(path.relative_to(REPO))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    if stale:
        for path in stale:
            print(f"stale: {path}", file=sys.stderr)
        print("run: python3 frameos/tools/generate_events_contract.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
