#!/usr/bin/env python3
"""Generate the per-language tables of the cloud verb contract.

Source of truth: docs/cloud-frames-contract.json. Outputs (all committed):

  frameos/src/frameos/cloud/contract_gen.nim           Linux runtime
  embedded/esp32/main/fos_cloud_contract_gen.h          ESP32 firmware (esp32 profile only)
  cloud/apps/auth-web/src/lib/cloud-frames-contract.gen.ts   cloud (rules + profiles)
  frontend/src/utils/cloudFramesContract.gen.ts         SPA (keys, floors, restart flags)

    python3 frameos/tools/generate_cloud_contract.py          # write
    python3 frameos/tools/generate_cloud_contract.py --check  # CI: fail if stale

The validators that walk these tables are hand-written and small, one per
language; this script only turns one JSON document into four data files, so
"which keys, which ranges, which profile, from which version" can never be
declared three times again.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SOURCE = REPO / "docs" / "cloud-frames-contract.json"
OUTPUTS = {
    "nim": REPO / "frameos" / "src" / "frameos" / "cloud" / "contract_gen.nim",
    "c": REPO / "embedded" / "esp32" / "main" / "fos_cloud_contract_gen.h",
    "ts_cloud": REPO / "cloud" / "apps" / "auth-web" / "src" / "lib" / "cloud-frames-contract.gen.ts",
    "ts_frontend": REPO / "frontend" / "src" / "utils" / "cloudFramesContract.gen.ts",
}
BANNER = "Generated by frameos/tools/generate_cloud_contract.py from docs/cloud-frames-contract.json — do not edit."

FORMATS = {"iana_zone": 1, "html_hex_color": 2, "gpio_label": 3}
KINDS = ["bool", "int", "number", "string", "object", "array", "map", "null", "anyOf"]


def load():
    doc = json.loads(SOURCE.read_text())
    for name, spec in doc["settings"].items():
        if not re.fullmatch(r"[a-z][a-z0-9_]*", name):
            raise SystemExit(f"setting {name!r}: wire keys are snake_case")
        for profile in spec["profiles"]:
            if profile not in doc["profiles"]:
                raise SystemExit(f"setting {name!r}: unknown profile {profile!r}")
        validate_rule(spec["rule"], f"settings.{name}")
        for profile, pspec in spec["profiles"].items():
            if "rule" in pspec:
                validate_rule(pspec["rule"], f"settings.{name}.profiles.{profile}")
    return doc


def validate_rule(rule, where):
    if "anyOf" in rule:
        for i, alt in enumerate(rule["anyOf"]):
            validate_rule(alt, f"{where}.anyOf[{i}]")
        return
    kind = rule.get("type")
    if kind not in KINDS or kind == "anyOf":
        raise SystemExit(f"{where}: unknown rule type {kind!r}")
    if rule.get("format") and rule["format"] not in FORMATS:
        raise SystemExit(f"{where}: unknown format {rule['format']!r}")
    if kind == "object":
        for key, sub in rule.get("keys", {}).items():
            validate_rule(sub, f"{where}.keys.{key}")
        for key in rule.get("required", []):
            if key not in rule.get("keys", {}):
                raise SystemExit(f"{where}: required key {key!r} has no rule")
    if kind == "array":
        validate_rule(rule["items"], f"{where}.items")
    if kind == "map":
        validate_rule(rule["values"], f"{where}.values")


def profile_rule(spec, profile):
    return spec["profiles"][profile].get("rule", spec["rule"])


# ----------------------------------------------------------------- Nim

def nim_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def nim_rule(rule, indent):
    pad = " " * indent
    if "anyOf" in rule:
        alts = ",\n".join(nim_rule(a, indent + 2) for a in rule["anyOf"])
        return f"{pad}Rule(kind: rkAnyOf, children: @[\n{alts}])"
    kind = rule["type"]
    fields = [f"kind: rk{kind[0].upper()}{kind[1:]}"]
    if "min" in rule:
        fields.append(f"hasMin: true, min: {float(rule['min'])!r}")
    if "max" in rule:
        fields.append(f"hasMax: true, max: {float(rule['max'])!r}")
    if "enum" in rule:
        if kind == "int":
            fields.append("intEnum: @[" + ", ".join(str(int(v)) for v in rule["enum"]) + "]")
        else:
            fields.append("strEnum: @[" + ", ".join(nim_str(v) for v in rule["enum"]) + "]")
    for name in ("minLen", "maxLen", "maxItems", "minKeys", "keyMinLen", "keyMaxLen"):
        if name in rule:
            fields.append(f"{name}: {int(rule[name])}")
    if rule.get("format"):
        fmt = {"iana_zone": "sfIanaZone", "html_hex_color": "sfHtmlHexColor", "gpio_label": "sfGpioLabel"}[rule["format"]]
        fields.append(f"format: {fmt}")
    if rule.get("open"):
        fields.append("open: true")
    if rule.get("required"):
        fields.append("required: @[" + ", ".join(nim_str(k) for k in rule["required"]) + "]")
    head = f"{pad}Rule({', '.join(fields)}"
    if kind == "object" and rule.get("keys"):
        keys = ",\n".join(
            f"{pad}  KeyRule(name: {nim_str(k)}, rule:\n{nim_rule(v, indent + 4)})"
            for k, v in rule["keys"].items())
        return f"{head}, keys: @[\n{keys}])"
    if kind == "array":
        return f"{head}, children: @[\n{nim_rule(rule['items'], indent + 2)}])"
    if kind == "map":
        return f"{head}, children: @[\n{nim_rule(rule['values'], indent + 2)}])"
    return head + ")"


def gen_nim(doc):
    out = [f"# {BANNER}", "", "import ./contract_types", "", "const CloudContractSettings* = @["]
    for name, spec in doc["settings"].items():
        profiles = []
        for profile, pspec in spec["profiles"].items():
            fields = [f"profile: {nim_str(profile)}"]
            if pspec.get("since"):
                fields.append(f"since: {nim_str(pspec['since'])}")
            if pspec.get("restart"):
                fields.append("restart: true")
            if "rule" in pspec:
                profiles.append(f"    ProfileSpec({', '.join(fields)}, hasRule: true, rule:\n{nim_rule(pspec['rule'], 6)})")
            else:
                profiles.append(f"    ProfileSpec({', '.join(fields)})")
        companion = f", companion: {nim_str(spec['companion'])}" if spec.get("companion") else ""
        extra = ""
        if spec.get("extraChecks"):
            extra = ", extraChecks: @[" + ", ".join(nim_str(c) for c in spec["extraChecks"]) + "]"
        out.append(f"  SettingSpec(key: {nim_str(name)}{companion}{extra}, rule:\n{nim_rule(spec['rule'], 4)},")
        out.append("  profiles: @[\n" + ",\n".join(profiles) + "]),")
    out.append("]")
    out.append("")
    out.append("const CloudContractVerbs* = @[")
    for verb in doc["verbs"]:
        scope = nim_str(verb["scope"] or "")
        out.append(f"  VerbSpec(verb: {nim_str(verb['type'])}, scope: {scope}, content: {'true' if verb.get('content') else 'false'}),")
    out.append("]")
    out.append("")
    out.append("const CloudContractLimits* = @[")
    for name, per in doc["limits"].items():
        if name.startswith("$"):
            continue
        for profile, value in per.items():
            out.append(f"  LimitSpec(name: {nim_str(name)}, profile: {nim_str(profile)}, value: {int(value)}),")
    out.append("]")
    out.append("")
    return "\n".join(out)


# ------------------------------------------------------------------- C

class CTables:
    """Flat arrays: rules reference sub-rules, keys and enums by index."""

    def __init__(self):
        self.rules = []      # dicts of fields
        self.keys = []       # (name, rule_index, required)
        self.children = []   # rule indices
        self.int_enums = []
        self.str_enums = []

    def add(self, rule):
        entry = {"kind": "ANY_OF" if "anyOf" in rule else rule["type"].upper().replace("NUMBER", "NUMBER"),
                 "format": FORMATS.get(rule.get("format"), 0), "has_min": 0, "has_max": 0,
                 "min": 0.0, "max": 0.0, "min_len": -1, "max_len": -1, "max_items": -1,
                 "key_min_len": -1, "key_max_len": -1, "open": 0, "min_keys": 0,
                 "enum_start": 0, "enum_count": 0, "keys_start": 0, "keys_count": 0,
                 "children_start": 0, "children_count": 0}
        index = len(self.rules)
        self.rules.append(entry)  # reserve the slot so parents precede children
        if "anyOf" in rule:
            idx = [self.add(a) for a in rule["anyOf"]]
            entry["children_start"], entry["children_count"] = len(self.children), len(idx)
            self.children.extend(idx)
            return index
        kind = rule["type"]
        if "min" in rule:
            entry["has_min"], entry["min"] = 1, float(rule["min"])
        if "max" in rule:
            entry["has_max"], entry["max"] = 1, float(rule["max"])
        if "enum" in rule:
            if kind == "int":
                entry["enum_start"], entry["enum_count"] = len(self.int_enums), len(rule["enum"])
                self.int_enums.extend(int(v) for v in rule["enum"])
            else:
                entry["enum_start"], entry["enum_count"] = len(self.str_enums), len(rule["enum"])
                self.str_enums.extend(rule["enum"])
        for src, dst in (("minLen", "min_len"), ("maxLen", "max_len"), ("maxItems", "max_items"),
                         ("minKeys", "min_keys"), ("keyMinLen", "key_min_len"), ("keyMaxLen", "key_max_len")):
            if src in rule:
                entry[dst] = int(rule[src])
        if kind == "map" and "maxEntries" in rule:
            entry["max_items"] = int(rule["maxEntries"])
        entry["open"] = 1 if rule.get("open") else 0
        if kind == "object" and rule.get("keys"):
            required = set(rule.get("required", []))
            sub = [(k, self.add(v), 1 if k in required else 0) for k, v in rule["keys"].items()]
            entry["keys_start"], entry["keys_count"] = len(self.keys), len(sub)
            self.keys.extend(sub)
        if kind == "array":
            child = self.add(rule["items"])
            entry["children_start"], entry["children_count"] = len(self.children), 1
            self.children.append(child)
        if kind == "map":
            child = self.add(rule["values"])
            entry["children_start"], entry["children_count"] = len(self.children), 1
            self.children.append(child)
        return index


def c_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def gen_c(doc):
    tables = CTables()
    settings = []
    for name, spec in doc["settings"].items():
        if "esp32" not in spec["profiles"]:
            continue  # the firmware carries only its own profile's rules
        pspec = spec["profiles"]["esp32"]
        idx = tables.add(profile_rule(spec, "esp32"))
        settings.append((name, idx, 1 if pspec.get("restart") else 0, spec.get("companion")))
    out = [f"/* {BANNER}",
           " *",
           " * The ESP32 profile of the cloud verb contract as flat tables: the",
           " * set_settings keys the firmware accepts with their value rules, the verb",
           " * table and the wire limits. Walked by fos_cloud_contract.c. */",
           "#pragma once", "", "#include <stdbool.h>", "#include <stdint.h>", "",
           "typedef enum {",
           "    FOS_RULE_BOOL = 0, FOS_RULE_INT, FOS_RULE_NUMBER, FOS_RULE_STRING, FOS_RULE_OBJECT,",
           "    FOS_RULE_ARRAY, FOS_RULE_MAP, FOS_RULE_NULL, FOS_RULE_ANY_OF,",
           "} fos_rule_kind_t;", "",
           "typedef enum { FOS_FMT_NONE = 0, FOS_FMT_IANA_ZONE, FOS_FMT_HTML_HEX_COLOR, FOS_FMT_GPIO_LABEL } fos_rule_format_t;", "",
           "typedef struct {",
           "    uint8_t kind, format, has_min, has_max, open, min_keys;",
           "    int16_t min_len, max_len, max_items, key_min_len, key_max_len;",
           "    int16_t enum_start, enum_count, keys_start, keys_count, children_start, children_count;",
           "    float min, max; /* every bound in the contract is exact in a float */",
           "} fos_rule_t;", "",
           "typedef struct { const char *name; int16_t rule; uint8_t required; } fos_rule_key_t;", "",
           "typedef struct {",
           "    const char *key;",
           "    int16_t rule;",
           "    uint8_t restart;      /* applying it reboots the chip */",
           "    const char *companion; /* only valid next to this key, or NULL */",
           "} fos_contract_setting_t;", "",
           "static const fos_rule_t k_fos_rules[] = {"]
    for r in tables.rules:
        out.append(f"    {{FOS_RULE_{r['kind']}, {r['format']}, {r['has_min']}, {r['has_max']}, {r['open']}, {r['min_keys']}, "
                   f"{r['min_len']}, {r['max_len']}, {r['max_items']}, {r['key_min_len']}, {r['key_max_len']}, "
                   f"{r['enum_start']}, {r['enum_count']}, {r['keys_start']}, {r['keys_count']}, {r['children_start']}, {r['children_count']}, "
                   f"{r['min']!r}f, {r['max']!r}f}},")
    out.append("};")
    out.append("static const fos_rule_key_t k_fos_rule_keys[] = {")
    for name, idx, req in tables.keys:
        out.append(f"    {{{c_str(name)}, {idx}, {req}}},")
    if not tables.keys:
        out.append("    {NULL, -1, 0},")
    out.append("};")
    out.append("static const int16_t k_fos_rule_children[] = {" + ", ".join(str(i) for i in tables.children) + (", " if tables.children else "-1") + "};")
    out.append("static const int32_t k_fos_rule_int_enums[] = {" + ", ".join(str(v) for v in tables.int_enums) + (", " if tables.int_enums else "0") + "};")
    out.append("static const char *const k_fos_rule_str_enums[] = {" + ", ".join(c_str(v) for v in tables.str_enums) + (", " if tables.str_enums else "NULL") + "};")
    out.append("")
    out.append("static const fos_contract_setting_t k_fos_contract_settings[] = {")
    for name, idx, restart, companion in settings:
        out.append(f"    {{{c_str(name)}, {idx}, {restart}, {c_str(companion) if companion else 'NULL'}}},")
    out.append("};")
    out.append(f"#define FOS_CONTRACT_SETTINGS_COUNT {len(settings)}")
    out.append("")
    out.append("/* Every verb in the contract, with the scope it requires (NULL = none) and")
    out.append(" * whether it is a content verb (refused `backend_managed` when a backend owns the frame). */")
    out.append("typedef struct { const char *verb; const char *scope; uint8_t content; } fos_contract_verb_t;")
    out.append("static const fos_contract_verb_t k_fos_contract_verbs[] = {")
    for verb in doc["verbs"]:
        out.append(f"    {{{c_str(verb['type'])}, {c_str(verb['scope']) if verb['scope'] else 'NULL'}, {1 if verb.get('content') else 0}}},")
    out.append("};")
    out.append(f"#define FOS_CONTRACT_VERBS_COUNT {len(doc['verbs'])}")
    out.append("")
    for name, per in doc["limits"].items():
        if name.startswith("$"):
            continue
        macro = "FOS_CONTRACT_" + re.sub(r"([A-Z])", r"_\1", name).upper()
        out.append(f"#define {macro} {int(per['esp32'])}")
    out.append("")
    return "\n".join(out)


# ------------------------------------------------------------------ TS

def ts_json(value, indent=0):
    return json.dumps(value, indent=2)


def gen_ts_cloud(doc):
    settings = {}
    for name, spec in doc["settings"].items():
        entry = {"rule": spec["rule"], "profiles": {}}
        if spec.get("companion"):
            entry["companion"] = spec["companion"]
        if spec.get("extraChecks"):
            entry["extraChecks"] = spec["extraChecks"]
        for profile, pspec in spec["profiles"].items():
            p = {"since": pspec.get("since")}
            if pspec.get("restart"):
                p["restart"] = True
            if "rule" in pspec:
                p["rule"] = pspec["rule"]
            entry["profiles"][profile] = p
        settings[name] = entry
    verbs = [{"type": v["type"], "scope": v["scope"], "content": bool(v.get("content"))} for v in doc["verbs"]]
    limits = {k: v for k, v in doc["limits"].items() if not k.startswith("$")}
    errors = {k: v for k, v in doc["errors"].items() if not k.startswith("$")}
    body = {"version": doc["version"], "profiles": doc["profiles"], "settings": settings,
            "formats": doc["formats"], "verbs": verbs, "errors": errors, "limits": limits}
    return (f"// {BANNER}\n"
            "// The cloud's copy of the verb contract: set_settings rules per profile,\n"
            "// verb table, wire limits. Walked by cloud-frames-contract.ts.\n\n"
            f"export const cloudFramesContract = {ts_json(body)} as const;\n")


def gen_ts_frontend(doc):
    """The SPA needs only: which keys each profile takes, from which version,
    and which of them restart the runtime. Import-free on purpose (the shared
    tests run it in node)."""
    per_profile = {}
    for profile in doc["profiles"]:
        keys = {}
        for name, spec in doc["settings"].items():
            if profile in spec["profiles"]:
                pspec = spec["profiles"][profile]
                entry = {"since": pspec.get("since")}
                if pspec.get("restart"):
                    entry["restart"] = True
                if spec.get("companion"):
                    entry["companion"] = spec["companion"]
                keys[name] = entry
        per_profile[profile] = keys
    return (f"// {BANNER}\n"
            "// The keys a cloud-managed frame accepts over set_settings, per profile:\n"
            "// `since` is the first firmware version that knows the key (null = every\n"
            "// version), `restart` means applying it restarts the runtime / reboots the\n"
            "// chip, `companion` keys ride only next to another key. Rules live on the\n"
            "// cloud (cloud-frames-contract.gen.ts) and the devices; the SPA only\n"
            "// decides what to offer and send.\n\n"
            f"export const cloudFramesContractSettings = {ts_json(per_profile)} as const\n\n"
            "export type CloudFramesContractProfile = keyof typeof cloudFramesContractSettings\n")


def main():
    check = "--check" in sys.argv
    doc = load()
    outputs = {"nim": gen_nim(doc), "c": gen_c(doc), "ts_cloud": gen_ts_cloud(doc), "ts_frontend": gen_ts_frontend(doc)}
    stale = []
    for name, text in outputs.items():
        path = OUTPUTS[name]
        if check:
            if not path.exists() or path.read_text() != text:
                stale.append(path)
        else:
            path.write_text(text)
            print(f"wrote {path.relative_to(REPO)}")
    if stale:
        for path in stale:
            print(f"stale: {path.relative_to(REPO)}", file=sys.stderr)
        print("run: python3 frameos/tools/generate_cloud_contract.py", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
