import argparse
import base64
import gzip
import json
from pathlib import Path

JS_APP_SOURCE_FILES = ("app.ts", "app.js", "app.tsx", "app.jsx")


def get_app_configs(source_dir: Path) -> dict[str, dict]:
    configs: dict[str, dict] = {}

    apps_root = source_dir / "src" / "apps"
    if apps_root.exists():
        for category_dir in sorted(apps_root.iterdir()):
            if not category_dir.is_dir():
                continue
            for app_dir in sorted(category_dir.iterdir()):
                if not app_dir.is_dir():
                    continue
                config_path = app_dir / "config.json"
                if not config_path.exists():
                    continue
                try:
                    config = json.loads(config_path.read_text())
                    if isinstance(config, dict) and "name" in config:
                        configs[f"{category_dir.name}/{app_dir.name}"] = config
                except Exception:
                    # Keep behavior resilient: skip malformed config files.
                    continue

    return configs


def get_app_sources(source_dir: Path) -> dict[str, dict[str, str]]:
    """Mirrors the backend's get_one_app_sources: every text file in the app
    directory, minus the generated loader and (for JS apps) the app.nim shim.
    Embedded in the binary so the on-device admin can show app source code."""
    sources: dict[str, dict[str, str]] = {}

    apps_root = source_dir / "src" / "apps"
    if not apps_root.exists():
        return sources

    for category_dir in sorted(apps_root.iterdir()):
        if not category_dir.is_dir():
            continue
        for app_dir in sorted(category_dir.iterdir()):
            if not app_dir.is_dir() or not (app_dir / "config.json").exists():
                continue
            has_js_source = any((app_dir / name).exists() for name in JS_APP_SOURCE_FILES)
            app_sources: dict[str, str] = {}
            for path in sorted(app_dir.iterdir()):
                if not path.is_file() or path.name == "app_loader.nim":
                    continue
                if has_js_source and path.name == "app.nim":
                    continue
                try:
                    app_sources[path.name] = path.read_text()
                except (UnicodeDecodeError, OSError):
                    continue
            if app_sources:
                sources[f"{category_dir.name}/{app_dir.name}"] = app_sources

    return sources


def render_apps_asset_nim(source_dir: Path) -> str:
    payload = {"apps": get_app_configs(source_dir)}
    payload_json = json.dumps(payload, separators=(",", ":"), sort_keys=True)
    sources_json = json.dumps(get_app_sources(source_dir), separators=(",", ":"), sort_keys=True)
    sources_blob = base64.b64encode(gzip.compress(sources_json.encode(), mtime=0)).decode("ascii")
    return "\n".join([
        "# Auto-generated by tools/generate_apps_asset_nim.py",
        "",
        "import base64, zippy",
        "",
        "const appsJson* = \"\"\"" + payload_json + "\"\"\"",
        "",
        "proc getAppsJson*(): string =",
        "  appsJson",
        "",
        "# keyword -> {filename: contents}, gzip+base64 to keep the binary small.",
        "const appSourcesJsonCompressed = \"\"\"" + sources_blob + "\"\"\"",
        "",
        "proc getAppSourcesJson*(): string =",
        "  uncompress(appSourcesJsonCompressed.decode(), dataFormat = dfGzip)",
        "",
    ])


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate src/assets/apps.nim from app config.json files")
    parser.add_argument("--source-dir", default=".", help="FrameOS project root containing src/apps")
    parser.add_argument("--output", default="src/assets/apps.nim", help="Output path for apps.nim")
    args = parser.parse_args()

    source_dir = Path(args.source_dir).resolve()
    output_path = Path(args.output)
    if not output_path.is_absolute():
        output_path = source_dir / output_path

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_apps_asset_nim(source_dir))


if __name__ == "__main__":
    main()
