#!/usr/bin/env node
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const frontendRoot = path.resolve(__dirname, '..')
const repoRoot = path.resolve(frontendRoot, '..')
const sourceRoot = path.join(repoRoot, 'repo', 'apps', 'code')
const outputPath = path.join(frontendRoot, 'src', 'generated', 'repoApps.ts')
const sourceFiles = ['app.ts', 'app.tsx', 'app.js', 'app.jsx']

async function pathExists(filePath) {
  try {
    await fs.access(filePath)
    return true
  } catch {
    return false
  }
}

async function getAppDirs() {
  if (!(await pathExists(sourceRoot))) {
    return []
  }
  const entries = await fs.readdir(sourceRoot, { withFileTypes: true })
  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()
}

async function buildEmbeddedRepoApps() {
  const configs = {}
  const sources = {}

  for (const appName of await getAppDirs()) {
    const appDir = path.join(sourceRoot, appName)
    const configPath = path.join(appDir, 'config.json')
    if (!(await pathExists(configPath))) {
      continue
    }

    const config = JSON.parse(await fs.readFile(configPath, 'utf8'))
    if (!config || typeof config !== 'object' || !config.name) {
      continue
    }

    const files = (await fs.readdir(appDir, { withFileTypes: true }))
      .filter((entry) => entry.isFile())
      .map((entry) => entry.name)
      .sort()
    const hasJavaScriptSource = files.some((file) => sourceFiles.includes(file))
    const keyword = `repo/apps/code/${appName}`

    configs[keyword] = { ...config, origin: keyword }
    sources[keyword] = {}

    for (const file of files) {
      if (file === 'app_loader.nim') {
        continue
      }
      if (hasJavaScriptSource && file === 'app.nim') {
        continue
      }
      sources[keyword][file] = await fs.readFile(path.join(appDir, file), 'utf8')
    }
  }

  return { configs, sources }
}

function renderModule({ configs, sources }) {
  return `${[
    '// Auto-generated by scripts/generateRepoApps.mjs.',
    "import type { AppConfig } from '../types'",
    '',
    `export const embeddedRepoAppConfigs: Record<string, AppConfig> = ${JSON.stringify(configs, null, 2)}`,
    '',
    `export const embeddedRepoAppSources: Record<string, Record<string, string>> = ${JSON.stringify(sources, null, 2)}`,
    '',
  ].join('\n')}`
}

await fs.mkdir(path.dirname(outputPath), { recursive: true })
await fs.writeFile(outputPath, renderModule(await buildEmbeddedRepoApps()))
