#!/usr/bin/env node
// Embed the built-in (Nim) app catalog into the bundle, mirroring
// generateRepoApps.mjs. The backend serves the same configs via GET
// /api/apps; the embedded copy makes the app catalog available without a
// backend (standalone/embedded editor, offline fallback) and ships the app
// sources so "view app source" works there too.
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const frontendRoot = path.resolve(__dirname, '..')
const repoRoot = path.resolve(frontendRoot, '..')
const sourceRoot = path.join(repoRoot, 'frameos', 'src', 'apps')
const outputPath = path.join(frontendRoot, 'src', 'generated', 'builtinApps.ts')

async function pathExists(filePath) {
  try {
    await fs.access(filePath)
    return true
  } catch {
    return false
  }
}

async function subdirs(dir) {
  if (!(await pathExists(dir))) {
    return []
  }
  const entries = await fs.readdir(dir, { withFileTypes: true })
  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()
}

async function buildEmbeddedBuiltinApps() {
  const configs = {}
  const sources = {}

  for (const category of await subdirs(sourceRoot)) {
    for (const appName of await subdirs(path.join(sourceRoot, category))) {
      const appDir = path.join(sourceRoot, category, appName)
      const configPath = path.join(appDir, 'config.json')
      if (!(await pathExists(configPath))) {
        continue
      }
      const config = JSON.parse(await fs.readFile(configPath, 'utf8'))
      if (!config || typeof config !== 'object' || !config.name) {
        continue
      }

      const keyword = `${category}/${appName}`
      configs[keyword] = { ...config, category }

      const files = (await fs.readdir(appDir, { withFileTypes: true }))
        .filter((entry) => entry.isFile())
        .map((entry) => entry.name)
        .sort()
      sources[keyword] = {}
      for (const file of files) {
        sources[keyword][file] = await fs.readFile(path.join(appDir, file), 'utf8')
      }
    }
  }

  return { configs, sources }
}

function renderModule({ configs, sources }) {
  return `${[
    '// Auto-generated by scripts/generateBuiltinApps.mjs.',
    "import type { AppConfig } from '../types'",
    '',
    // Cast: real config.json files use a few field properties the strict
    // frontend types don't model (min/max, bare showIf operators).
    `export const embeddedBuiltinAppConfigs = ${JSON.stringify(configs, null, 2)} as unknown as Record<string, AppConfig>`,
    '',
    `export const embeddedBuiltinAppSources: Record<string, Record<string, string>> = ${JSON.stringify(sources, null, 2)}`,
    '',
  ].join('\n')}`
}

// Several builds run this generator at the same time (turbo runs the frontend,
// cloud-frontend and frame-frontend builds in parallel) while esbuild is
// reading the output, and a plain writeFile truncates first: a reader can see
// an empty file. Skip the write when nothing changed, rename into place
// otherwise. Same helper as generateRepoApps.mjs, which deploys copy on its own.
async function writeFileAtomic(filePath, contents) {
  const existing = await fs.readFile(filePath, 'utf8').catch(() => null)
  if (existing === contents) {
    return
  }
  const tempPath = `${filePath}.${process.pid}.tmp`
  await fs.writeFile(tempPath, contents)
  await fs.rename(tempPath, filePath)
}

await fs.mkdir(path.dirname(outputPath), { recursive: true })
await writeFileAtomic(outputPath, renderModule(await buildEmbeddedBuiltinApps()))
