import { MakeLogicType, actions, afterMount, beforeUnmount, kea, listeners, path, reducers } from 'kea'

import { loaders } from 'kea-loaders'
import { RepositoryType } from '../types'
import { apiFetch, logApiError } from '../utils/apiFetch'
import { isCloudMode } from '../utils/cloudMode'
import { cloudStoreRepository } from '../utils/cloudStoreRepository'
import { isFrameControlMode } from '../utils/frameControlMode'
import { isInFrameAdminMode } from '../utils/frameAdmin'

// The public store catalog this very deployment serves (the scene picker's
// built-in repository in cloud mode). The "system-" prefix is what marks a
// repository non-removable in the picker (isSystemRepository in
// Templates.tsx) — there is no /api/repositories to remove it from.
const cloudStoreRepositoryUrl = '/api/store/repository.json'

/** A repository listing is an array; anything else (an older frame, a stub) counts as none. */
function asRepositoryList(value: unknown): RepositoryType[] {
  return Array.isArray(value) ? (value as RepositoryType[]) : []
}
const cloudStoreRepositoryId = 'system-cloud-store'

// The backend refreshes a repository's cached catalog once a day, while
// answering the listing that noticed. It waits a few seconds for that refresh
// (backend/app/api/repositories.py, STALE_REFRESH_WAIT_SECONDS); when the
// provider is slower the answer still carries the old copy, so the SPA asks
// again a few times — and gives up, so a dead provider is not polled for ever.
const REPOSITORY_STALE_AFTER_MS = 24 * 60 * 60 * 1000
const PENDING_REFRESH_POLLS = 3
const PENDING_REFRESH_POLL_MS = 4000

/** The backend stamps `last_updated_at` as naive UTC (`datetime.utcnow().isoformat()`). */
export function repositoryUpdatedAt(repository: RepositoryType): number | null {
  const raw = repository.last_updated_at
  if (!raw) {
    return null
  }
  const withZone = /(?:Z|[+-]\d\d:?\d\d)$/.test(raw) ? raw : `${raw}Z`
  const time = new Date(withZone).getTime()
  return Number.isNaN(time) ? null : time
}

/** A refresh is pending for this repository on the backend: never fetched, or
 * fetched more than a day ago. Built-in ("system-") repositories are read off
 * disk and never refresh. */
export function repositoryRefreshPending(repository: RepositoryType, now = Date.now()): boolean {
  if (repository.id?.startsWith('system-')) {
    return false
  }
  const updatedAt = repositoryUpdatedAt(repository)
  return updatedAt === null || now - updatedAt > REPOSITORY_STALE_AFTER_MS
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface repositoriesModelValues {
  repositories: RepositoryType[]
  repositoriesLoadedAt: number | null
  repositoriesLoading: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface repositoriesModelActions {
  loadRepositories: () => any
  loadRepositoriesFailure: (
    error: string,
    errorObject?: any
  ) => {
    error: string
    errorObject?: any
  }
  loadRepositoriesIfStale: (maxAgeMs: number) => {
    maxAgeMs: number
  }
  loadRepositoriesSuccess: (
    repositories: RepositoryType[],
    payload?: any
  ) => {
    repositories: RepositoryType[]
    payload?: any
  }
  refreshRepository: (id: string) => {
    id: string
  }
  refreshRepositoryFailure: (
    error: string,
    errorObject?: any
  ) => {
    error: string
    errorObject?: any
  }
  refreshRepositorySuccess: (
    repositories: any[],
    payload?: {
      id: string
    }
  ) => {
    repositories: any[]
    payload?: {
      id: string
    }
  }
  removeRepository: (id: string) => {
    id: string
  }
  removeRepositoryFailure: (
    error: string,
    errorObject?: any
  ) => {
    error: string
    errorObject?: any
  }
  removeRepositorySuccess: (
    repositories: RepositoryType[],
    payload?: {
      id: string
    }
  ) => {
    repositories: RepositoryType[]
    payload?: {
      id: string
    }
  }
  updateRepository: (repository: RepositoryType) => {
    repository: RepositoryType
  }
}

export type repositoriesModelType = MakeLogicType<repositoriesModelValues, repositoriesModelActions>

export const repositoriesModel = kea<repositoriesModelType>([
  path(['src', 'models', 'repositoriesModel']),
  actions({
    updateRepository: (repository: RepositoryType) => ({ repository }),
    removeRepository: (id: string) => ({ id }),
    refreshRepository: (id: string) => ({ id }),
    /** Reload unless the list was fetched within `maxAgeMs`. The scene picker
     * calls this every time it opens: a tab left open for days (Home
     * Assistant's ingress panel) otherwise keeps the catalog it loaded at
     * mount for ever. */
    loadRepositoriesIfStale: (maxAgeMs: number) => ({ maxAgeMs }),
  }),
  loaders(({ values }) => ({
    repositories: [
      [] as RepositoryType[],
      {
        loadRepositories: async () => {
          try {
            if (isCloudMode()) {
              // The cloud has no /api/repositories — the store catalog IS the
              // repository. The SPA fetches the repository JSON itself (no
              // backend to cache it) and the picker shows it like any other
              // repo: searchable, installable, not removable.
              const response = await apiFetch(cloudStoreRepositoryUrl)
              if (!response.ok) {
                throw new Error('Failed to fetch the scene store catalog')
              }
              return [cloudStoreRepository(cloudStoreRepositoryId, cloudStoreRepositoryUrl, await response.json())]
            }
            // On a backend this is the tracked repositories (the seeded cloud
            // store among them); on the frame it is the cloud store the frame
            // fetches from its provider. The bundled samples and galleries
            // (/api/repositories/system) are a subset of the store and are no
            // longer listed anywhere in the UI (2026-09-17).
            const response = await apiFetch('/api/repositories')
            if (!response.ok) {
              throw new Error('Failed to fetch repositories')
            }
            return asRepositoryList(await response.json())
          } catch (error) {
            logApiError(error)
            return values.repositories
          }
        },
        removeRepository: async ({ id }) => {
          try {
            const response = await apiFetch(`/api/repositories/${id}`, { method: 'DELETE' })
            if (!response.ok) {
              throw new Error('Failed to remove repository')
            }
            return values.repositories.filter((t) => t.id !== id)
          } catch (error) {
            console.error(error)
            return values.repositories
          }
        },
        refreshRepository: async ({ id }) => {
          try {
            const response = await apiFetch(`/api/repositories/${id}`, {
              method: 'PATCH',
              body: '{}',
              headers: {
                'Content-Type': 'application/json',
              },
            })
            if (!response.ok) {
              throw new Error('Failed to refresh repository')
            }
            const data = await response.json()
            return values.repositories.map((r) => (r.id === id ? data : r))
          } catch (error) {
            console.error(error)
            return values.repositories
          }
        },
      },
    ],
  })),
  reducers({
    repositories: {
      updateRepository: (state, { repository }) => {
        const index = state.findIndex((t) => t.id === repository.id)
        if (index === -1) {
          return [...state, repository]
        }
        return [...state.slice(0, index), repository, ...state.slice(index + 1)]
      },
    },
    repositoriesLoadedAt: [
      null as number | null,
      {
        loadRepositoriesSuccess: () => Date.now(),
      },
    ],
  }),
  listeners(({ actions, cache, values }) => ({
    loadRepositoriesIfStale: ({ maxAgeMs }) => {
      if (isFrameControlMode() && !isInFrameAdminMode()) {
        return
      }
      if (values.repositoriesLoading) {
        return
      }
      const loadedAt = values.repositoriesLoadedAt
      if (loadedAt !== null && Date.now() - loadedAt < maxAgeMs) {
        return
      }
      cache.pendingRefreshPolls = 0
      actions.loadRepositories()
    },
    loadRepositoriesSuccess: ({ repositories }) => {
      window.clearTimeout(cache.pendingRefreshTimer)
      if (isCloudMode() || isInFrameAdminMode()) {
        // Neither has a backend cache to wait for: the cloud SPA fetched the
        // live index itself, and the frame keeps its own short-lived one.
        return
      }
      if (!repositories.some((repository) => repositoryRefreshPending(repository))) {
        cache.pendingRefreshPolls = 0
        return
      }
      const polls: number = cache.pendingRefreshPolls ?? 0
      if (polls >= PENDING_REFRESH_POLLS) {
        return
      }
      cache.pendingRefreshPolls = polls + 1
      cache.pendingRefreshTimer = window.setTimeout(() => {
        if (!values.repositoriesLoading) {
          actions.loadRepositories()
        }
      }, PENDING_REFRESH_POLL_MS * (polls + 1))
    },
  })),
  afterMount(({ actions }) => {
    if (isFrameControlMode() && !isInFrameAdminMode()) {
      return
    }
    actions.loadRepositories()
  }),
  beforeUnmount(({ cache }) => {
    window.clearTimeout(cache.pendingRefreshTimer)
  }),
])
