type ColorOption* = enum
  Black = "Black"
  BlackWhiteRed = "BlackWhiteRed"
  BlackWhiteYellow = "BlackWhiteYellow"
  BlackWhiteYellowRed = "BlackWhiteYellowRed"
  FourGray = "FourGray"
  SixteenGray = "SixteenGray"
  SevenColor = "SevenColor"
  SpectraSixColor = "SpectraSixColor"
