# This file is autogenerated for your frame on deploy

import frameos/driver_setup
import frameos/types
import drivers/waveshare/types

when not defined(testing):
  import ePaper/DEV_Config as waveshareConfig
  import ePaper/EPD_2in13_V3 as waveshareDisplay

# This file is autogenerated for your frame on deploy
let width* = 122
let height* = 250

let colorOption* = ColorOption.Black

proc setup*(_: FrameConfig): DriverSetupSpec =
  driverSetupSpec:
    enableSpi()

when defined(testing):
  proc init*() =
    discard

  proc start*(self: Driver) =
    discard

  proc clear*() =
    discard

  proc sleep*() =
    discard

  proc renderImage*(image: seq[uint8]) =
    discard

  proc renderImageBlackWhiteRed*(image1: seq[uint8], image2: seq[uint8]) =
    discard
else:
  proc init*() =
    let resp = waveshareConfig.DEV_Module_Init()
    if resp != 0: raise newException(Exception, "Failed to initialize waveshare display")

  proc start*(self: Driver) =
    # This file is autogenerated for your frame on deploy
    waveshareDisplay.EPD_2in13_V3_Init()

  proc clear*() =
    # This file is autogenerated for your frame on deploy
    waveshareDisplay.EPD_2in13_V3_Clear()

  proc sleep*() =
    # This file is autogenerated for your frame on deploy
    waveshareDisplay.EPD_2in13_V3_Sleep()

  proc renderImage*(image: seq[uint8]) =
    # This file is autogenerated for your frame on deploy
    waveshareDisplay.EPD_2in13_V3_Display_Base(addr image[0])

  proc renderImageBlackWhiteRed*(image1: seq[uint8], image2: seq[uint8]) =
    discard
