# This file is autogenerated for your frame on deploy

import ePaper/DEV_Config as waveshareConfig
import ePaper/EPD_2in13_V3 as waveshareDisplay
from ./types import ColorOption

# This file is autogenerated for your frame on deploy
let width* = waveshareDisplay.EPD_2in13_V3_WIDTH
let height* = waveshareDisplay.EPD_2in13_V3_HEIGHT

let colorOption* = ColorOption.Black

proc init*() =
  let resp = waveshareConfig.DEV_Module_Init()
  if resp != 0: raise newException(Exception, "Failed to initialize waveshare display")

proc start*() =
  # This file is autogenerated for your frame on deploy
  waveshareDisplay.EPD_2in13_V3_Init()

proc clear*() =
  # This file is autogenerated for your frame on deploy
  waveshareDisplay.EPD_2in13_V3_Clear()

proc sleep*() =
  # This file is autogenerated for your frame on deploy
  waveshareDisplay.EPD_2in13_V3_Sleep()

proc renderImage*(image: seq[uint8]) =
  # This file is autogenerated for your frame on deploy
  waveshareDisplay.EPD_2in13_V3_Display_Base(addr image[0])

proc renderImageBlackWhiteRed*(image1: seq[uint8], image2: seq[uint8]) =
  discard
