import os
import sys
import json
from pathlib import Path

from app.codegen.scene_nim import scene_module_filename, write_scene_library_nim, write_scene_nim, write_scenes_nim
from app.models import Frame

def scene_references(scene):
    references = []
    for node in scene.get('nodes', []):
        if node.get('type') == 'scene':
            keyword = node.get('data', {}).get('keyword')
            if keyword:
                references.append(keyword)
    return references

def include_scene_dependencies(files, all_files_by_stem):
    selected_files = list(files)
    selected_stems = {file_path.stem for file_path in selected_files}
    pending_files = list(files)
    scene_cache = {}

    while pending_files:
        file_path = pending_files.pop(0)
        if file_path not in scene_cache:
            with open(file_path, 'r') as file:
                scene_cache[file_path] = json.load(file)

        for reference in scene_references(scene_cache[file_path]):
            dependency_path = all_files_by_stem.get(reference)
            if dependency_path is None or dependency_path.stem in selected_stems:
                continue
            selected_files.append(dependency_path)
            selected_stems.add(dependency_path.stem)
            pending_files.append(dependency_path)

    if len(selected_files) != len(files):
        added_count = len(selected_files) - len(files)
        print(f"Including {added_count} scene dependenc{'y' if added_count == 1 else 'ies'} for generated scene imports")

    return sorted(selected_files)

def apply_shard(files):
    shard = os.environ.get("FRAMEOS_E2E_SHARD")
    shard_count = os.environ.get("FRAMEOS_E2E_SHARDS")

    if not shard and not shard_count:
        return files

    if not shard or not shard_count:
        raise ValueError("FRAMEOS_E2E_SHARD and FRAMEOS_E2E_SHARDS must be set together")

    shard = int(shard)
    shard_count = int(shard_count)
    if shard_count < 1:
        raise ValueError("FRAMEOS_E2E_SHARDS must be at least 1")
    if shard < 1 or shard > shard_count:
        raise ValueError("FRAMEOS_E2E_SHARD must be between 1 and FRAMEOS_E2E_SHARDS")

    selected = [
        file_path
        for index, file_path in enumerate(files)
        if index % shard_count == shard - 1
    ]
    print(f"Generating e2e scene shard {shard}/{shard_count}: {len(selected)} of {len(files)} scenes")
    return selected

if __name__ == '__main__':
    scenes_dir = Path('./scenes')
    generated_dir = Path('./generated')
    scenes = {}

    # read filter from env or argv
    filter_str = os.environ.get("SCENE_FILTER") or (sys.argv[1] if len(sys.argv) > 1 else "")
    filter_str = filter_str.strip().lower()

    generated_dir.mkdir(exist_ok=True)
    shared_generated_dir = generated_dir / 'shared'
    if shared_generated_dir.exists():
        for file_path in shared_generated_dir.glob('*.nim'):
            file_path.unlink()
    shared_generated_dir.mkdir(exist_ok=True)

    all_files = sorted(scenes_dir.glob('*.json'))
    all_files_by_stem = {file_path.stem: file_path for file_path in all_files}
    files = list(all_files)
    black_scene = all_files_by_stem.get("black")
    if filter_str:
        files = [p for p in files if filter_str in p.stem.lower()]
    files = apply_shard(files)

    if not files:
        print(f"No scenes matched filter: '{filter_str}'" if filter_str else "No scenes found.")
        sys.exit(0)

    if black_scene is not None and black_scene not in files:
        files = [black_scene, *files]
        files.sort()
    files = include_scene_dependencies(files, all_files_by_stem)

    for file_path in files:
        with open(file_path, 'r') as file:
            scene = json.load(file)
            scene['id'] = file_path.stem
            scene['default'] = False
            scenes[file_path.stem] = scene

    scene_list = list(scenes.values())
    scene_list.sort(key=lambda x: x['id'])
    scene_list[0]['default'] = True

    frame = Frame(
        name="Test frame",
        scenes=scene_list
    )

    for scene_name, scene_data in scenes.items():
        scene_nim = write_scene_nim(frame, scene_data)
        scene_file_path = generated_dir / f'scene_{scene_name}.nim'
        with open(scene_file_path, 'w') as scene_file:
            scene_file.write(scene_nim)
        scene_library_path = shared_generated_dir / scene_module_filename(scene_data)
        with open(scene_library_path, 'w') as scene_library_file:
            scene_library_file.write(write_scene_library_nim(scene_data))

    scenes_nim = write_scenes_nim(frame, compilation_mode="shared")
    scenes_nim_file_path = generated_dir / 'scenes.nim'
    with open(scenes_nim_file_path, 'w') as scenes_file:
        scenes_file.write("# This file is autogenerated\n" + scenes_nim)

    print("All scenes have been saved as .nim files.")

    # update scene IDs so we could run them alongside the compiled scenes
    for scene_name, scene_data in scenes.items():
        scene_data['id'] = scene_data['id'] + '_interpreted'
        for node in scene_data.get('nodes', []):
            if node['type'] == 'scene':
                node['data']['keyword'] = node['data']['keyword'] + '_interpreted'

    # merge all scenes into one scenes.json
    merged_scenes_path = generated_dir / 'scenes.json'
    with open(merged_scenes_path, 'w') as merged_file:
        json.dump(list(scenes.values()), merged_file, indent=4)

    print("Saved scenes.json with all scenes.")
