import { MakeLogicType, actions, afterMount, connect, kea, key, listeners, path, props, reducers, selectors } from 'kea'
import copy from 'copy-to-clipboard'

import { frameHost } from '../../decorators/frame'
import {
  embeddedUsbLogsModel,
  isEmbeddedUsbLogStreamOpen,
  runEmbeddedUsbApiCommand,
  startEmbeddedUsbLogStream,
  usbBootsel,
  usbFactoryReset,
  usbProvisionWifi,
  usbRestart,
  usbWifiScan,
  type EmbeddedUsbLogStreamState,
  type EmbeddedUsbStatus,
  type EmbeddedUsbWifiNetwork,
} from '../../models/embeddedUsbLogsModel'
import type { FrameId, FrameType } from '../../types'
import {
  fetchProvisioningPlan,
  provisionOverUsb,
  skippedSettingsNotice,
  type EmbeddedProvisioningPlan,
} from './EmbeddedReleaseFlasher'
import {
  fetchReleaseFirmwareListing,
  hasReleaseFirmwarePlatform,
  saveReleaseFirmwareFile,
  type ReleaseFirmwareAsset,
  type ReleaseFirmwareListing,
} from './EmbeddedUsbFirmwareUpdate'
import {
  bootselDriveName,
  isUf2Release,
  pickUf2Asset,
  usbBoardFamilyMismatch,
  usbCardAffordances,
  type UsbCardAffordances,
} from './picoFirmware'
import {
  classifyUsbBoard,
  isUsbSilenceError,
  normalizedFirmwareVersion,
  type UsbBoardIdentity,
} from './usbBoardIdentity'
import { workspaceLogic } from './workspaceLogic'
import { isEsp32CloudFrame, workspaceMode, type WorkspaceMode } from './workspaceSurfaces'
import { confirmDialog } from '../../utils/confirmDialogLogic'

// The state behind the "Connect over USB" card (EmbeddedUsbConnect.tsx): the
// board's identity as read over the USB API, the plan and release listing
// that sharpen it, and every console action the card offers. The component
// is a template over these values; every decision lives here.
//
// Probe discipline: the board is read once per USB session, as soon as the
// log stream is streaming. Every USB API command (and every flash) stops and
// resumes that stream, so "streaming again" re-arms the probe — but only while
// nothing of ours is running, or each step of an action would re-read the
// board. Actions that change what the board IS (settings, Wi-Fi, restart,
// reset) probe again explicitly when they finish.
//
// The Pico family (picoFirmware.ts) shares all of it except flashing: `uf2`
// turns every esptool affordance off, and the firmware card above this one
// (PicoFirmwareCard.tsx) reads the release listing and the download state from
// here, so the two cards of one frame never fetch the same thing twice.

const PROBE_TIMEOUT_MS = 8000

export interface EmbeddedUsbConnectLogicProps {
  frameId: FrameId
  frame: FrameType
}

function errorDetail(error: unknown): string {
  return error instanceof Error ? error.message : String(error)
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface embeddedUsbConnectLogicValues {
  usbLogStreamStatesByFrameId: Record<FrameId, EmbeddedUsbLogStreamState> // embeddedUsbLogsModel
  actionBusy: boolean
  affordances: UsbCardAffordances
  applyBusy: boolean
  boardMismatch: string | null
  boardRunsFrameOS: boolean
  bootselBusy: boolean
  bootselDrive: string
  busy: boolean
  canProvision: boolean
  cloudManaged: boolean
  connected: boolean
  copied: boolean
  deviceVersion: string | null
  downloadBusy: boolean
  error: string | null
  expectedBackendUrl: string | null
  factoryResetBusy: boolean
  firmwareNotice: {
    isError: boolean
    text: string
  } | null
  firmwareOutdated: boolean
  flasherBusy: boolean
  flowBusy: boolean
  frameName: string
  framePlatform: string
  identity: UsbBoardIdentity | null
  identityKnown: boolean
  latestRelease: string | null
  message: string | null
  mode: WorkspaceMode
  networks: EmbeddedUsbWifiNetwork[] | null
  password: string
  plan: EmbeddedProvisioningPlan | null
  probeError: string | null
  probed: boolean
  probing: boolean
  releaseAvailable: boolean
  releaseListing: ReleaseFirmwareListing | null
  releaseListingFailed: boolean
  restartBusy: boolean
  scanBusy: boolean
  settingsBusy: boolean
  ssid: string
  status: EmbeddedUsbStatus | null
  streamBusy: boolean
  streaming: boolean
  uf2: boolean
  uf2Asset: ReleaseFirmwareAsset | null
  uf2DownloadAvailable: boolean
  uf2Platform: string
  updateBusy: boolean
  usbLogStreamOpen: boolean
  usbLogStreamState: EmbeddedUsbLogStreamState | undefined
  versionLine: string
  wifiConfigured: boolean
  wifiConnected: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface embeddedUsbConnectLogicActions {
  stopUsbLogStream: (frameId: FrameId) => {
    frameId: FrameId
  } // embeddedUsbLogsModel
  applyFrameSettings: (confirmForeign?: boolean) => {
    confirmForeign: boolean
  }
  applyWifi: () => {
    value: true
  }
  connectUsb: () => {
    value: true
  }
  copyManualCommand: (command: string) => {
    command: string
  }
  disconnectUsb: () => {
    value: true
  }
  downloadFirmware: () => {
    value: true
  }
  factoryReset: () => {
    value: true
  }
  loadLatestRelease: () => {
    value: true
  }
  loadPlan: () => {
    value: true
  }
  probe: () => {
    value: true
  }
  probeFailure: (error: string) => {
    error: string
  }
  probeStarted: () => {
    value: true
  }
  probeSuccess: (identity: UsbBoardIdentity) => {
    identity: UsbBoardIdentity
  }
  rebootIntoBootsel: () => {
    value: true
  }
  recheck: () => {
    value: true
  }
  resetSession: () => {
    value: true
  }
  restartDevice: () => {
    value: true
  }
  scanNetworks: () => {
    value: true
  }
  selectNetwork: (ssid: string) => {
    ssid: string
  }
  setApplyBusy: (busy: boolean) => {
    busy: boolean
  }
  setBootselBusy: (busy: boolean) => {
    busy: boolean
  }
  setDownloadBusy: (busy: boolean) => {
    busy: boolean
  }
  setError: (error: string | null) => {
    error: string | null
  }
  setFactoryResetBusy: (busy: boolean) => {
    busy: boolean
  }
  setFirmwareNotice: (
    notice: string | null,
    isError?: boolean
  ) => {
    isError: boolean
    notice: string | null
  }
  setFlasherBusy: (busy: boolean) => {
    busy: boolean
  }
  setLatestRelease: (release: string | null) => {
    release: string | null
  }
  setMessage: (message: string | null) => {
    message: string | null
  }
  setNetworks: (networks: EmbeddedUsbWifiNetwork[] | null) => {
    networks: EmbeddedUsbWifiNetwork[] | null
  }
  setPassword: (password: string) => {
    password: string
  }
  setPlan: (plan: EmbeddedProvisioningPlan | null) => {
    plan: EmbeddedProvisioningPlan | null
  }
  setReleaseListing: (listing: ReleaseFirmwareListing | null) => {
    listing: ReleaseFirmwareListing | null
  }
  setReleaseListingFailed: (failed: boolean) => {
    failed: boolean
  }
  setRestartBusy: (busy: boolean) => {
    busy: boolean
  }
  setScanBusy: (busy: boolean) => {
    busy: boolean
  }
  setSettingsBusy: (busy: boolean) => {
    busy: boolean
  }
  setSsid: (ssid: string) => {
    ssid: string
  }
  setUpdateBusy: (busy: boolean) => {
    busy: boolean
  }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface embeddedUsbConnectLogicMeta {
  key: FrameId
  __keaTypeGenInternalSelectorTypes: {
    cloudManaged: (frame: FrameType) => boolean
    frameName: (frame: FrameType) => string
    canProvision: (cloudManaged: boolean, mode: WorkspaceMode) => boolean
    releaseAvailable: (mode: WorkspaceMode, frame: FrameType) => boolean
    framePlatform: (frame: FrameType) => string
    uf2: (plan: EmbeddedProvisioningPlan | null, framePlatform: string) => boolean
    affordances: (uf2: boolean) => UsbCardAffordances
    uf2DownloadAvailable: (uf2: boolean, mode: WorkspaceMode) => boolean
    uf2Platform: (plan: EmbeddedProvisioningPlan | null, framePlatform: string) => string
    uf2Asset: (releaseListing: ReleaseFirmwareListing | null, uf2Platform: string) => ReleaseFirmwareAsset | null
    bootselDrive: (uf2Platform: string) => string
    usbLogStreamState: (
      usbLogStreamStatesByFrameId: Record<FrameId, EmbeddedUsbLogStreamState>,
      frameId: FrameId
    ) => EmbeddedUsbLogStreamState | undefined
    usbLogStreamOpen: (usbLogStreamState: EmbeddedUsbLogStreamState | undefined) => boolean
    streaming: (usbLogStreamState: EmbeddedUsbLogStreamState | undefined) => boolean
    streamBusy: (usbLogStreamState: EmbeddedUsbLogStreamState | undefined) => boolean
    flowBusy: (flasherBusy: boolean, updateBusy: boolean) => boolean
    actionBusy: (
      settingsBusy: boolean,
      restartBusy: boolean,
      factoryResetBusy: boolean,
      scanBusy: boolean,
      applyBusy: boolean,
      bootselBusy: boolean
    ) => boolean
    busy: (flowBusy: boolean, actionBusy: boolean, probing: boolean) => boolean
    connected: (usbLogStreamOpen: boolean, flowBusy: boolean) => boolean
    expectedBackendUrl: (plan: EmbeddedProvisioningPlan | null) => string | null
    status: (identity: UsbBoardIdentity | null) => EmbeddedUsbStatus | null
    boardMismatch: (framePlatform: string, status: EmbeddedUsbStatus | null) => string | null
    deviceVersion: (status: EmbeddedUsbStatus | null) => string | null
    firmwareOutdated: (deviceVersion: string | null, latestRelease: string | null) => boolean
    wifiConfigured: (status: EmbeddedUsbStatus | null) => boolean
    wifiConnected: (status: EmbeddedUsbStatus | null) => boolean
    identityKnown: (identity: UsbBoardIdentity | null, probing: boolean) => boolean
    boardRunsFrameOS: (identityKnown: boolean, identity: UsbBoardIdentity | null) => boolean
    versionLine: (deviceVersion: string | null, latestRelease: string | null, firmwareOutdated: boolean) => string
  }
}

export type embeddedUsbConnectLogicType = MakeLogicType<
  embeddedUsbConnectLogicValues,
  embeddedUsbConnectLogicActions,
  EmbeddedUsbConnectLogicProps
> &
  embeddedUsbConnectLogicMeta

export const embeddedUsbConnectLogic = kea<embeddedUsbConnectLogicType>([
  path(['src', 'scenes', 'workspace', 'embeddedUsbConnectLogic']),
  props({} as EmbeddedUsbConnectLogicProps),
  key((props) => props.frameId),
  connect(() => ({
    values: [embeddedUsbLogsModel, ['usbLogStreamStatesByFrameId']],
    actions: [embeddedUsbLogsModel, ['stopUsbLogStream']],
  })),
  actions({
    loadPlan: true,
    setPlan: (plan: EmbeddedProvisioningPlan | null) => ({ plan }),
    loadLatestRelease: true,
    setLatestRelease: (release: string | null) => ({ release }),
    setReleaseListing: (listing: ReleaseFirmwareListing | null) => ({ listing }),
    setReleaseListingFailed: (failed: boolean) => ({ failed }),
    downloadFirmware: true,
    setDownloadBusy: (busy: boolean) => ({ busy }),
    setFirmwareNotice: (notice: string | null, isError: boolean = false) => ({ notice, isError }),
    rebootIntoBootsel: true,
    setBootselBusy: (busy: boolean) => ({ busy }),
    connectUsb: true,
    disconnectUsb: true,
    probe: true,
    probeStarted: true,
    probeSuccess: (identity: UsbBoardIdentity) => ({ identity }),
    probeFailure: (error: string) => ({ error }),
    recheck: true,
    resetSession: true,
    applyFrameSettings: (confirmForeign: boolean = false) => ({ confirmForeign }),
    scanNetworks: true,
    setNetworks: (networks: EmbeddedUsbWifiNetwork[] | null) => ({ networks }),
    selectNetwork: (ssid: string) => ({ ssid }),
    setSsid: (ssid: string) => ({ ssid }),
    setPassword: (password: string) => ({ password }),
    applyWifi: true,
    restartDevice: true,
    factoryReset: true,
    copyManualCommand: (command: string) => ({ command }),
    setMessage: (message: string | null) => ({ message }),
    setError: (error: string | null) => ({ error }),
    setFlasherBusy: (busy: boolean) => ({ busy }),
    setUpdateBusy: (busy: boolean) => ({ busy }),
    setSettingsBusy: (busy: boolean) => ({ busy }),
    setRestartBusy: (busy: boolean) => ({ busy }),
    setFactoryResetBusy: (busy: boolean) => ({ busy }),
    setScanBusy: (busy: boolean) => ({ busy }),
    setApplyBusy: (busy: boolean) => ({ busy }),
  }),
  reducers({
    plan: [null as EmbeddedProvisioningPlan | null, { setPlan: (_, { plan }) => plan }],
    latestRelease: [
      null as string | null,
      {
        setLatestRelease: (_, { release }) => release,
        setReleaseListing: (_, { listing }) => normalizedFirmwareVersion(listing?.release),
      },
    ],
    // The whole listing, for the Pico firmware card: which .uf2 to offer, and
    // how big it is. null until it has loaded.
    releaseListing: [null as ReleaseFirmwareListing | null, { setReleaseListing: (_, { listing }) => listing }],
    releaseListingFailed: [
      false,
      {
        setReleaseListingFailed: (_, { failed }) => failed,
        setReleaseListing: () => false,
      },
    ],
    downloadBusy: [false, { setDownloadBusy: (_, { busy }) => busy }],
    firmwareNotice: [
      null as { text: string; isError: boolean } | null,
      {
        setFirmwareNotice: (_, { notice, isError }) => (notice ? { text: notice, isError } : null),
        downloadFirmware: () => null,
      },
    ],
    identity: [
      null as UsbBoardIdentity | null,
      {
        probeSuccess: (_, { identity }) => identity,
        resetSession: () => null,
      },
    ],
    // Whether this USB session has been read (or is being read). Cleared when
    // the session ends and by recheck; set as soon as a probe starts so the
    // stream flapping during the probe itself does not queue a second one.
    probed: [
      false,
      {
        probeStarted: () => true,
        recheck: () => false,
        resetSession: () => false,
      },
    ],
    probing: [
      false,
      {
        probeStarted: () => true,
        probeSuccess: () => false,
        probeFailure: () => false,
        resetSession: () => false,
      },
    ],
    probeError: [
      null as string | null,
      {
        probeStarted: () => null,
        probeFailure: (_, { error }) => error,
        resetSession: () => null,
      },
    ],
    networks: [
      null as EmbeddedUsbWifiNetwork[] | null,
      {
        setNetworks: (_, { networks }) => networks,
        resetSession: () => null,
        factoryReset: () => null,
      },
    ],
    ssid: [
      '',
      {
        setSsid: (_, { ssid }) => ssid,
        selectNetwork: (_, { ssid }) => ssid,
      },
    ],
    password: [
      '',
      {
        setPassword: (_, { password }) => password,
        selectNetwork: () => '',
      },
    ],
    message: [
      null as string | null,
      {
        setMessage: (_, { message }) => message,
        // Every action clears the previous outcome before it starts.
        applyFrameSettings: () => null,
        scanNetworks: () => null,
        applyWifi: () => null,
        restartDevice: () => null,
        rebootIntoBootsel: () => null,
        factoryReset: () => null,
        connectUsb: () => null,
        selectNetwork: () => null,
      },
    ],
    error: [
      null as string | null,
      {
        setError: (_, { error }) => error,
        applyFrameSettings: () => null,
        scanNetworks: () => null,
        applyWifi: () => null,
        restartDevice: () => null,
        rebootIntoBootsel: () => null,
        factoryReset: () => null,
        connectUsb: () => null,
        selectNetwork: () => null,
      },
    ],
    copied: [false, { copyManualCommand: () => true }],
    flasherBusy: [false, { setFlasherBusy: (_, { busy }) => busy }],
    updateBusy: [false, { setUpdateBusy: (_, { busy }) => busy }],
    settingsBusy: [false, { setSettingsBusy: (_, { busy }) => busy }],
    restartBusy: [false, { setRestartBusy: (_, { busy }) => busy }],
    bootselBusy: [false, { setBootselBusy: (_, { busy }) => busy }],
    factoryResetBusy: [false, { setFactoryResetBusy: (_, { busy }) => busy }],
    scanBusy: [false, { setScanBusy: (_, { busy }) => busy }],
    applyBusy: [false, { setApplyBusy: (_, { busy }) => busy }],
  }),
  selectors({
    mode: [() => [], (): WorkspaceMode => workspaceMode()],
    cloudManaged: [(_, p) => [p.frame], (frame: FrameType): boolean => isEsp32CloudFrame(frame)],
    frameName: [(_, p) => [p.frame], (frame: FrameType): string => frame.name || frameHost(frame)],
    // The self-hosted backend knows what a stock image must be told to become
    // this frame; the cloud pushes its settings over the hub instead, and a
    // device's own admin bundle has no plan to fetch.
    canProvision: [
      (s) => [s.cloudManaged, s.mode],
      (cloudManaged: boolean, mode: WorkspaceMode): boolean => !cloudManaged && mode === 'backend',
    ],
    // Both control planes serve the release listing; the device's own admin
    // bundle serves neither that nor the firmware bytes.
    releaseAvailable: [
      (s, p) => [s.mode, p.frame],
      (mode: WorkspaceMode, frame: FrameType): boolean => mode !== 'frameAdmin' && hasReleaseFirmwarePlatform(frame),
    ],
    // Configured on a backend frame, reported at enrollment on a cloud one.
    framePlatform: [
      (_, p) => [p.frame],
      (frame: FrameType): string => frame.embedded?.platform || frame.hardware?.platform || '',
    ],
    // A Pico: its release is a .uf2 a person copies onto the BOOTSEL drive, so
    // nothing here may offer to flash it. The plan says so once it has loaded;
    // until then (and wherever there is no plan) the platform name does.
    uf2: [
      (s) => [s.plan, s.framePlatform],
      (plan: EmbeddedProvisioningPlan | null, framePlatform: string): boolean =>
        isUf2Release(plan?.releaseFormat, framePlatform),
    ],
    affordances: [(s) => [s.uf2], (uf2: boolean): UsbCardAffordances => usbCardAffordances(uf2)],
    // The Pico firmware card is a self-hosted affair: the cloud publishes no
    // pico assets, and a device's own admin bundle serves no listing at all.
    uf2DownloadAvailable: [
      (s) => [s.uf2, s.mode],
      (uf2: boolean, mode: WorkspaceMode): boolean => uf2 && mode === 'backend',
    ],
    uf2Platform: [
      (s) => [s.plan, s.framePlatform],
      (plan: EmbeddedProvisioningPlan | null, framePlatform: string): string => plan?.releasePlatform || framePlatform,
    ],
    uf2Asset: [
      (s) => [s.releaseListing, s.uf2Platform],
      (listing: ReleaseFirmwareListing | null, uf2Platform: string): ReleaseFirmwareAsset | null =>
        pickUf2Asset(listing?.assets, uf2Platform),
    ],
    bootselDrive: [(s) => [s.uf2Platform], (uf2Platform: string): string => bootselDriveName(uf2Platform)],
    usbLogStreamState: [
      (s, p) => [s.usbLogStreamStatesByFrameId, p.frameId],
      (
        states: Record<FrameId, EmbeddedUsbLogStreamState | undefined>,
        frameId: FrameId
      ): EmbeddedUsbLogStreamState | undefined => states[frameId],
    ],
    usbLogStreamOpen: [
      (s) => [s.usbLogStreamState],
      (state: EmbeddedUsbLogStreamState | undefined): boolean => isEmbeddedUsbLogStreamOpen(state),
    ],
    streaming: [
      (s) => [s.usbLogStreamState],
      (state: EmbeddedUsbLogStreamState | undefined): boolean => state?.status === 'streaming',
    ],
    streamBusy: [
      (s) => [s.usbLogStreamState],
      (state: EmbeddedUsbLogStreamState | undefined): boolean =>
        state?.status === 'selecting' || state?.status === 'connecting' || state?.status === 'stopping',
    ],
    flowBusy: [(s) => [s.flasherBusy, s.updateBusy], (a: boolean, b: boolean): boolean => a || b],
    actionBusy: [
      (s) => [s.settingsBusy, s.restartBusy, s.factoryResetBusy, s.scanBusy, s.applyBusy, s.bootselBusy],
      (a: boolean, b: boolean, c: boolean, d: boolean, e: boolean, f: boolean): boolean => a || b || c || d || e || f,
    ],
    busy: [
      (s) => [s.flowBusy, s.actionBusy, s.probing],
      (flowBusy: boolean, actionBusy: boolean, probing: boolean): boolean => flowBusy || actionBusy || probing,
    ],
    // A flash closes the log stream for its duration; the card stays in its
    // connected layout while one of ours holds the port.
    connected: [
      (s) => [s.usbLogStreamOpen, s.flowBusy],
      (usbLogStreamOpen: boolean, flowBusy: boolean): boolean => usbLogStreamOpen || flowBusy,
    ],
    expectedBackendUrl: [
      (s) => [s.plan],
      (plan: EmbeddedProvisioningPlan | null): string | null =>
        plan?.settings.find((setting) => setting.key === 'backend')?.value ?? null,
    ],
    status: [
      (s) => [s.identity],
      (identity: UsbBoardIdentity | null): EmbeddedUsbStatus | null =>
        identity && identity.kind !== 'silent' ? identity.status : null,
    ],
    // A Pico on the cable of an ESP32 frame, or the other way round: nothing
    // we would send it is meant for it.
    boardMismatch: [
      (s) => [s.framePlatform, s.status],
      (framePlatform: string, status: EmbeddedUsbStatus | null): string | null =>
        usbBoardFamilyMismatch(framePlatform, status?.board?.target),
    ],
    deviceVersion: [
      (s) => [s.status],
      (status: EmbeddedUsbStatus | null): string | null => normalizedFirmwareVersion(status?.version),
    ],
    firmwareOutdated: [
      (s) => [s.deviceVersion, s.latestRelease],
      (deviceVersion: string | null, latestRelease: string | null): boolean =>
        Boolean(deviceVersion && latestRelease && deviceVersion !== latestRelease),
    ],
    wifiConfigured: [
      (s) => [s.status],
      (status: EmbeddedUsbStatus | null): boolean => Boolean(status?.config?.wifiSsid),
    ],
    wifiConnected: [(s) => [s.status], (status: EmbeddedUsbStatus | null): boolean => status?.wifi?.state === 2],
    identityKnown: [
      (s) => [s.identity, s.probing],
      (identity: UsbBoardIdentity | null, probing: boolean): boolean => identity !== null && !probing,
    ],
    boardRunsFrameOS: [
      (s) => [s.identityKnown, s.identity],
      (identityKnown: boolean, identity: UsbBoardIdentity | null): boolean =>
        identityKnown && identity !== null && identity.kind !== 'silent',
    ],
    versionLine: [
      (s) => [s.deviceVersion, s.latestRelease, s.firmwareOutdated],
      (deviceVersion: string | null, latestRelease: string | null, firmwareOutdated: boolean): string =>
        deviceVersion
          ? `FrameOS ${deviceVersion}${
              latestRelease ? (firmwareOutdated ? ` · latest ${latestRelease}` : ' · latest') : ''
            }`
          : 'FrameOS (version unknown)',
    ],
  }),
  listeners(({ actions, values, props }) => ({
    loadPlan: async () => {
      if (!values.canProvision) {
        return
      }
      try {
        actions.setPlan(await fetchProvisioningPlan(props.frameId))
      } catch {
        // The flasher fetches its own copy and reports; here the plan only
        // sharpens the identity check and the "set up" button.
      }
    },
    loadLatestRelease: async () => {
      if (!values.releaseAvailable && !values.uf2DownloadAvailable) {
        return
      }
      try {
        actions.setReleaseListing(await fetchReleaseFirmwareListing())
      } catch {
        // Without it the status line just omits "latest"; the Pico firmware
        // card says it could not look the release up and links to GitHub.
        actions.setReleaseListingFailed(true)
      }
    },
    downloadFirmware: async () => {
      const asset = values.uf2Asset
      if (!asset || values.downloadBusy) {
        return
      }
      actions.setDownloadBusy(true)
      try {
        const fileName = await saveReleaseFirmwareFile(asset)
        actions.setFirmwareNotice(`Saved ${fileName} to your downloads. Copy it onto the ${values.bootselDrive} drive.`)
      } catch (downloadError) {
        actions.setFirmwareNotice(errorDetail(downloadError), true)
      } finally {
        actions.setDownloadBusy(false)
      }
    },
    connectUsb: async () => {
      const started = await startEmbeddedUsbLogStream(props.frameId)
      if (started) {
        workspaceLogic.actions.openFrameToolBehindDrawer(props.frameId, 'logs')
      }
    },
    disconnectUsb: () => {
      actions.stopUsbLogStream(props.frameId)
    },
    probe: async () => {
      if (values.probing) {
        return
      }
      actions.probeStarted()
      try {
        const result = await runEmbeddedUsbApiCommand(props.frameId, 'status', {
          timeoutMs: PROBE_TIMEOUT_MS,
          mirrorOutput: false,
          probe: true,
        })
        let status: EmbeddedUsbStatus | null = null
        try {
          status = JSON.parse(result.text ?? '') as EmbeddedUsbStatus
        } catch {
          status = null
        }
        actions.probeSuccess(
          classifyUsbBoard(
            props.frame,
            status,
            values.mode,
            values.expectedBackendUrl,
            'The board answered on USB, but not with a FrameOS status.'
          )
        )
      } catch (probeFailure) {
        if (isUsbSilenceError(probeFailure)) {
          actions.probeSuccess(classifyUsbBoard(props.frame, null, values.mode, values.expectedBackendUrl))
        } else {
          actions.probeFailure(errorDetail(probeFailure))
        }
      }
    },
    recheck: () => {
      actions.probe()
    },
    // The USB model's stream state is the session: gone (and no flash of ours
    // holding the port) means the board is gone; streaming again means it is
    // back and unread.
    [embeddedUsbLogsModel.actionTypes.setUsbLogStreamState]: ({ frameId }) => {
      if (frameId !== props.frameId) {
        return
      }
      if (!values.connected && !values.flowBusy) {
        if (values.identity !== null || values.probed) {
          actions.resetSession()
        }
        return
      }
      if (values.streaming && !values.probed && !values.busy) {
        actions.probe()
      }
    },
    applyFrameSettings: async ({ confirmForeign }) => {
      const identity = values.identity
      if (confirmForeign && identity?.kind === 'other-frame') {
        if (
          !(await confirmDialog({
            title: `Re-provision this board as "${values.frameName}"?`,
            message: `The board is currently ${identity.label}. It stops being that other frame.`,
            confirmLabel: 'Re-provision',
            danger: true,
          }))
        ) {
          return
        }
      }
      actions.setSettingsBusy(true)
      try {
        const plan = values.plan ?? (await fetchProvisioningPlan(props.frameId))
        if (!plan.supported) {
          actions.setError(`This frame cannot be provisioned yet: ${plan.blockers.join(' ')}`)
          return
        }
        const { skipped } = await provisionOverUsb(props.frameId, plan, null, actions.setMessage)
        const sent = plan.settings.length - skipped.length
        // A Pico is never flashed from here, so this button is its whole
        // provisioning: the frame's Wi-Fi rides along, the way it does at the
        // end of the ESP32 browser flash (EmbeddedReleaseFlasher).
        const wifi = values.uf2 ? plan.wifi : null
        if (wifi) {
          actions.setMessage(`Sent ${sent} settings to the board; joining ${wifi.ssid} and restarting it.`)
          await usbProvisionWifi(props.frameId, wifi.ssid, wifi.password)
        } else {
          actions.setMessage(`Sent ${sent} settings to the board; restarting it to apply them.`)
          await usbRestart(props.frameId)
        }
        const notice = skippedSettingsNotice(skipped)
        actions.setMessage(
          `Sent ${sent} settings to the board. It rebooted and is ${wifi ? `joining ${wifi.ssid}` : 'applying them'}.${
            notice ? ` ${notice}` : ''
          }`
        )
        actions.recheck()
      } catch (settingsError) {
        actions.setError(`Applying the frame's settings failed: ${errorDetail(settingsError)}`)
      } finally {
        actions.setSettingsBusy(false)
      }
    },
    scanNetworks: async () => {
      actions.setScanBusy(true)
      try {
        const result = await usbWifiScan(props.frameId)
        // Hidden networks scan as an empty SSID and cannot be selected here.
        actions.setNetworks(result.networks.filter((network) => network.ssid.length > 0))
      } catch (scanError) {
        actions.setError(`Wi-Fi scan failed: ${errorDetail(scanError)}`)
      } finally {
        actions.setScanBusy(false)
      }
    },
    applyWifi: async () => {
      const targetSsid = values.ssid.trim()
      if (!targetSsid) {
        actions.setError('Enter or select a Wi-Fi network name first.')
        return
      }
      actions.setApplyBusy(true)
      try {
        await usbProvisionWifi(props.frameId, targetSsid, values.password)
        actions.setPassword('')
        actions.setMessage(`Wi-Fi settings saved. The device rebooted and is joining "${targetSsid}".`)
        actions.recheck()
      } catch (applyError) {
        actions.setError(`Applying Wi-Fi settings failed: ${errorDetail(applyError)}`)
      } finally {
        actions.setApplyBusy(false)
      }
    },
    restartDevice: async () => {
      actions.setRestartBusy(true)
      try {
        await usbRestart(props.frameId)
        actions.setMessage('Restart acknowledged. The device rebooted and the USB session reconnected.')
        actions.recheck()
      } catch (restartError) {
        actions.setError(`Restart failed: ${errorDetail(restartError)}`)
      } finally {
        actions.setRestartBusy(false)
      }
    },
    rebootIntoBootsel: async () => {
      actions.setBootselBusy(true)
      try {
        // The board does not come back as a serial port, so there is nothing
        // to re-read: the USB session ends and the card returns to "Connect".
        await usbBootsel(props.frameId)
        actions.setMessage(
          `The board rebooted into its bootloader. A drive named ${values.bootselDrive} should appear on this computer: copy the .uf2 onto it, wait for the board to restart, then connect again.`
        )
      } catch (bootselError) {
        actions.setError(`Rebooting into BOOTSEL failed: ${errorDetail(bootselError)}`)
      } finally {
        actions.setBootselBusy(false)
      }
    },
    factoryReset: async () => {
      // A reset is `nvs_erase_all` on the whole frameos namespace
      // (fos_config.c), which takes a cloud enrollment with it — cloud_url,
      // cloud_fid and the device token all live there. On a cloud-managed
      // frame that is not a reset but an unlink, so say so.
      if (
        !(await confirmDialog({
          title: `Factory reset "${values.frameName}"?`,
          message: values.cloudManaged
            ? 'This erases everything the board has stored — Wi-Fi, hardware settings AND its enrollment in this account. It will NOT come back as this frame: re-link it afterwards from "Re-link a wiped board", and this frame row is left behind empty until then.\n\nTo install new firmware, use "Update firmware, keep settings" instead. This cannot be undone.'
            : "This erases the device's Wi-Fi, backend and hardware settings and reboots it. This cannot be undone.",
          confirmLabel: 'Factory reset',
          danger: true,
        }))
      ) {
        return
      }
      actions.setFactoryResetBusy(true)
      try {
        await usbFactoryReset(props.frameId)
        actions.setMessage(
          values.cloudManaged
            ? 'Factory reset complete. The device erased its settings — including its enrollment — and rebooted.'
            : 'Factory reset complete. The device erased its settings and rebooted.'
        )
        actions.recheck()
      } catch (resetError) {
        actions.setError(`Factory reset failed: ${errorDetail(resetError)}`)
      } finally {
        actions.setFactoryResetBusy(false)
      }
    },
    copyManualCommand: ({ command }) => {
      copy(command)
    },
  })),
  afterMount(({ actions }) => {
    actions.loadPlan()
    actions.loadLatestRelease()
  }),
])
