import { MakeLogicType, actions, connect, kea, listeners, path, reducers, selectors } from 'kea'
import { framesModel } from '../../models/framesModel'
import { longRunningTasksModel } from '../../models/longRunningTasksModel'
import type { LongRunningTask } from '../../models/longRunningTasksModel'
import { publishedReleaseModel } from '../../models/publishedReleaseModel'
import { frameStatusWithSpinner, frameUpgradeIsQueued } from '../../decorators/frame'
import type { FrameId, FrameType } from '../../types'
import { isCloudMode } from '../../utils/cloudMode'
import { deviceUpgradeInFlight, frameLogic, pendingFrameosUpgrade } from '../frame/frameLogic'
import { embeddedOtaSupported, frameAdminLoginIsOnlyAccess } from '../frame/frameDeployUtils'
import { EMBEDDED_VIRTUAL } from '../../devices'
import { workspaceLogic } from './workspaceLogic'
import { frameMenuActionDisabledReason, frameMenuActionIsAllowed, workspaceMode } from './workspaceSurfaces'

/**
 * How one frame is asked to update itself — the verb behind the single-frame
 * "Update" affordance on each control plane, so "Update all" does per frame
 * exactly what its own drawer would:
 * - `cloudNotify`: every cloud-managed frame, Pi or esp32, gets the durable
 *   notify_update_available nudge (framesModel.updateFrameFirmware).
 * - `embeddedOta`: a backend esp32 board with two app slots pulls the signed
 *   release through the backend's relay (framesModel.applyEmbeddedFirmwareOta).
 * - `deviceUpgrade`: a Buildroot card the backend only reaches through its
 *   admin login runs frameos/upgrade.nim itself (frameLogic.startDeviceUpgrade).
 * - `fullDeploy`: a Pi the backend has a shell on gets the FrameOS this
 *   backend was built with over SSH (framesModel.deployFrame, the deploy
 *   drawer's "Full deploy"); there is no release upgrade over SSH.
 */
export type FleetUpdateVerb = 'cloudNotify' | 'embeddedOta' | 'deviceUpgrade' | 'fullDeploy'

/** The verb that updates this frame from here, or null when none does (a virtual or Pico frame, a cloud frame listed by a backend). */
export function fleetUpdateVerbForFrame(frame: FrameType): FleetUpdateVerb | null {
  if (isCloudMode()) {
    const mode = workspaceMode()
    return frameMenuActionIsAllowed(mode, 'updateFirmware', frame) &&
      !frameMenuActionDisabledReason(mode, 'updateFirmware', frame)
      ? 'cloudNotify'
      : null
  }
  if (frame.managed_by === 'cloud') {
    return null
  }
  if ((frame.mode ?? 'rpios') === 'embedded') {
    const platform = frame.embedded?.platform ?? ''
    return platform !== EMBEDDED_VIRTUAL && !platform.startsWith('pico') && embeddedOtaSupported(frame)
      ? 'embeddedOta'
      : null
  }
  return frameAdminLoginIsOnlyAccess(frame) ? 'deviceUpgrade' : 'fullDeploy'
}

/** An update this UI already asked for and that has not settled: never ask again on top of it. */
export function fleetUpdateInFlight(frame: FrameType, runningTasks: LongRunningTask[]): boolean {
  if (frameUpgradeIsQueued(frame) || frameStatusWithSpinner.includes(frame.status)) {
    return true
  }
  if (
    runningTasks.some((task) => task.frameId === frame.id && (task.kind === 'deploy' || task.kind === 'embeddedOta'))
  ) {
    return true
  }
  return deviceUpgradeInFlight(frameLogic.findMounted({ frameId: frame.id })?.values.deviceUpgradeStatus)
}

/** The pause between two frames' update requests: one at a time, never a burst at the backend or the hub. */
export const FLEET_UPDATE_STAGGER_MS = 1500

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface fleetUpdateLogicValues {
  runningTasks: LongRunningTask[] // longRunningTasksModel
  latestPublishedRelease: string | null // publishedReleaseModel
  homeActiveFramesList: FrameType[] // workspaceLogic
  framesNeedingUpdate: FrameType[]
  startedFrameIds: Record<FrameId, number>
  updateAllTitle: string
  updatingAll: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface fleetUpdateLogicActions {
  finishUpdateAll: () => {
    value: true
  }
  markFrameUpdateStarted: (frameId: FrameId) => {
    frameId: FrameId
  }
  updateAllFrames: () => {
    value: true
  }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface fleetUpdateLogicMeta {
  __keaTypeGenInternalSelectorTypes: {
    framesNeedingUpdate: (
      homeActiveFramesList: FrameType[],
      latestPublishedRelease: string | null,
      runningTasks: LongRunningTask[],
      startedFrameIds: Record<FrameId, number>
    ) => FrameType[]
    updateAllTitle: (framesNeedingUpdate: FrameType[], latestPublishedRelease: string | null) => string
  }
}

export type fleetUpdateLogicType = MakeLogicType<fleetUpdateLogicValues, fleetUpdateLogicActions, Record<string, any>> &
  fleetUpdateLogicMeta

/**
 * "Update all" in the frames sidebar: the active frames whose only pending
 * change is a FrameOS upgrade (pendingFrameosUpgrade) and that have no
 * update queued or running, updated one after another with a pause in
 * between. One run at a time: a second click while the loop runs is a no-op,
 * and every frame the loop has asked leaves the list until the next fleet
 * refresh shows the request landed (queued) or the frame moved on.
 */
export const fleetUpdateLogic = kea<fleetUpdateLogicType>([
  path(['src', 'scenes', 'workspace', 'fleetUpdateLogic']),
  connect({
    values: [
      publishedReleaseModel,
      ['latestPublishedRelease'],
      longRunningTasksModel,
      ['runningTasks'],
      workspaceLogic,
      ['homeActiveFramesList'],
    ],
  }),
  actions({
    updateAllFrames: true,
    markFrameUpdateStarted: (frameId: FrameId) => ({ frameId }),
    finishUpdateAll: true,
  }),
  reducers({
    updatingAll: [
      false,
      {
        updateAllFrames: () => true,
        finishUpdateAll: () => false,
      },
    ],
    startedFrameIds: [
      {} as Record<FrameId, number>,
      {
        markFrameUpdateStarted: (state, { frameId }) => ({ ...state, [frameId]: Date.now() }),
      },
    ],
  }),
  selectors({
    framesNeedingUpdate: [
      (s) => [s.homeActiveFramesList, s.latestPublishedRelease, s.runningTasks, s.startedFrameIds],
      (
        homeActiveFramesList: fleetUpdateLogicValues['homeActiveFramesList'],
        latestPublishedRelease: fleetUpdateLogicValues['latestPublishedRelease'],
        runningTasks: fleetUpdateLogicValues['runningTasks'],
        startedFrameIds: fleetUpdateLogicValues['startedFrameIds']
      ): FrameType[] =>
        homeActiveFramesList.filter(
          (frame) =>
            !startedFrameIds[frame.id] &&
            !!pendingFrameosUpgrade(frame, latestPublishedRelease) &&
            !!fleetUpdateVerbForFrame(frame) &&
            !fleetUpdateInFlight(frame, runningTasks)
        ),
    ],
    updateAllTitle: [
      (s) => [s.framesNeedingUpdate, s.latestPublishedRelease],
      (
        framesNeedingUpdate: fleetUpdateLogicValues['framesNeedingUpdate'],
        latestPublishedRelease: fleetUpdateLogicValues['latestPublishedRelease']
      ): string => {
        const count = framesNeedingUpdate.length
        const version = framesNeedingUpdate
          .map((frame) => pendingFrameosUpgrade(frame, latestPublishedRelease)?.currentVersion)
          .find((candidate): candidate is string => !!candidate)
        return `Update ${count} active ${count === 1 ? 'frame' : 'frames'}${version ? ` to FrameOS ${version}` : ''}`
      },
    ],
  }),
  listeners(({ actions, values, cache }) => ({
    updateAllFrames: async () => {
      // The reducer flipped `updatingAll` for the spinner; this flag is what
      // keeps a second click from starting a second loop next to the first.
      if (cache.updatingAll) {
        return
      }
      cache.updatingAll = true
      try {
        const frames = values.framesNeedingUpdate
        for (const [index, frame] of frames.entries()) {
          if (index > 0) {
            await sleep(FLEET_UPDATE_STAGGER_MS)
          }
          actions.markFrameUpdateStarted(frame.id)
          try {
            await startFrameUpdate(frame)
          } catch (error) {
            // The per-verb listener already reported the failure as a task
            // toast; the loop moves on to the next frame.
            console.error(`Update all: could not start the update of frame ${frame.id}`, error)
          }
        }
      } finally {
        cache.updatingAll = false
        actions.finishUpdateAll()
      }
    },
  })),
])

/** Ask one frame to update, the way its own drawer would, and wait for the request to be sent. */
async function startFrameUpdate(frame: FrameType): Promise<void> {
  switch (fleetUpdateVerbForFrame(frame)) {
    case 'cloudNotify':
      await framesModel.asyncActions.updateFrameFirmware(frame.id)
      // updateFrameFirmware does not refetch: the row's pending_command_types
      // is what keeps the frame out of the list once startedFrameIds is stale.
      framesModel.actions.loadFrame(frame.id)
      return
    case 'embeddedOta':
      await framesModel.asyncActions.applyEmbeddedFirmwareOta(frame.id)
      return
    case 'deviceUpgrade': {
      // The sidebar row keeps a frameLogic mounted for every listed frame; an
      // extra mount for the call's duration covers a row that is not.
      const logic = frameLogic({ frameId: frame.id })
      const unmount = logic.mount()
      try {
        await logic.asyncActions.startDeviceUpgrade()
      } finally {
        unmount()
      }
      return
    }
    case 'fullDeploy':
      await framesModel.asyncActions.deployFrame(frame.id, false)
      return
    case null:
      return
  }
}
