import {
  MakeLogicType,
  actions,
  afterMount,
  beforeUnmount,
  connect,
  kea,
  key,
  path,
  props,
  reducers,
  selectors,
} from 'kea'
import { loaders } from 'kea-loaders'

import type { MetricsType, FrameId } from '../../types'
import { apiFetch } from '../../utils/apiFetch'
import {
  filterMetricsByCategoryAndTimeRange,
  latestBatteryPercentFromMetrics,
  latestMetricSummariesByCategoryFromMetrics,
  metricsByCategoryFromMetrics,
  metricTimestamp,
  type MetricSeries,
  type TimeRange,
} from '../frame/panels/Metrics/metricsLogic'
import { socketLogic } from '../socketLogic'
import { withoutBatteryMisreads } from '../../utils/batteryMisreads'

const PREVIEW_METRICS_WINDOW_MS = 60 * 60 * 1000
const PREVIEW_METRICS_LIMIT = 1000
const CURRENT_TIME_UPDATE_MS = 60 * 1000

export interface FrameMetricsPreviewLogicProps {
  frameId: FrameId
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface frameMetricsPreviewLogicValues {
  currentTime: number
  headerMetricsByCategory: Record<string, MetricSeries[]>
  latestBatteryPercent: number | null
  latestMetricSummariesByCategory: Record<string, string>
  metricsByCategory: Record<string, MetricSeries[]>
  previewMetricsTimeRange: TimeRange | null
  recentMetrics: MetricsType[]
  recentMetricsLoading: boolean
  sortedRecentMetrics: MetricsType[]
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface frameMetricsPreviewLogicActions {
  loadRecentMetrics: () => any
  loadRecentMetricsFailure: (
    error: string,
    errorObject?: any
  ) => {
    error: string
    errorObject?: any
  }
  loadRecentMetricsSuccess: (
    recentMetrics: MetricsType[],
    payload?: any
  ) => {
    recentMetrics: MetricsType[]
    payload?: any
  }
  setCurrentTime: (currentTime: number) => {
    currentTime: number
  }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface frameMetricsPreviewLogicMeta {
  key: FrameId
  __keaTypeGenInternalSelectorTypes: {
    sortedRecentMetrics: (recentMetrics: MetricsType[]) => MetricsType[]
    previewMetricsTimeRange: (currentTime: number, sortedRecentMetrics: MetricsType[]) => TimeRange | null
    metricsByCategory: (sortedRecentMetrics: MetricsType[]) => Record<string, MetricSeries[]>
    headerMetricsByCategory: (
      metricsByCategory: Record<string, MetricSeries[]>,
      previewMetricsTimeRange: TimeRange | null
    ) => Record<string, MetricSeries[]>
    latestMetricSummariesByCategory: (sortedRecentMetrics: MetricsType[]) => Record<string, string>
    latestBatteryPercent: (sortedRecentMetrics: MetricsType[]) => number | null
  }
}

export type frameMetricsPreviewLogicType = MakeLogicType<
  frameMetricsPreviewLogicValues,
  frameMetricsPreviewLogicActions,
  FrameMetricsPreviewLogicProps
> &
  frameMetricsPreviewLogicMeta

export const frameMetricsPreviewLogic = kea<frameMetricsPreviewLogicType>([
  path(['src', 'scenes', 'workspace', 'frameMetricsPreviewLogic']),
  props({} as FrameMetricsPreviewLogicProps),
  connect(() => ({ logic: [socketLogic] })),
  key((props) => props.frameId),
  actions({
    setCurrentTime: (currentTime: number) => ({ currentTime }),
  }),
  loaders(({ props }) => ({
    recentMetrics: [
      [] as MetricsType[],
      {
        loadRecentMetrics: async () => {
          try {
            const since = new Date(Date.now() - PREVIEW_METRICS_WINDOW_MS).toISOString()
            const response = await apiFetch(
              `/api/frames/${props.frameId}/metrics/recent?limit=${PREVIEW_METRICS_LIMIT}&since=${encodeURIComponent(
                since
              )}`
            )
            if (!response.ok) {
              throw new Error('Failed to fetch recent metrics')
            }
            const data = await response.json()
            return data.metrics as MetricsType[]
          } catch (error) {
            console.error(error)
            return []
          }
        },
      },
    ],
  })),
  reducers(({ props }) => ({
    currentTime: [
      Date.now(),
      {
        setCurrentTime: (_, { currentTime }) => currentTime,
      },
    ],
    recentMetrics: {
      [socketLogic.actionTypes.newMetrics]: (state, { metrics }) => {
        if (metrics.frame_id !== props.frameId) {
          return state
        }
        const cutoff = Date.now() - PREVIEW_METRICS_WINDOW_MS
        return [...state, metrics as MetricsType].filter((metric) => metricTimestamp(metric) >= cutoff)
      },
    },
  })),
  selectors({
    // Battery readings the neighbouring samples contradict are ADC misreads
    // and are stripped here, at the source, so the header chips, the sidebar
    // glyph and the metric alerts never see one (utils/batteryMisreads.ts).
    sortedRecentMetrics: [
      (s) => [s.recentMetrics],
      (metrics: frameMetricsPreviewLogicValues['recentMetrics']) =>
        withoutBatteryMisreads([...metrics].sort((a, b) => metricTimestamp(a) - metricTimestamp(b))).metrics,
    ],
    previewMetricsTimeRange: [
      (s) => [s.currentTime, s.sortedRecentMetrics],
      (
        currentTime: frameMetricsPreviewLogicValues['currentTime'],
        metrics: frameMetricsPreviewLogicValues['sortedRecentMetrics']
      ): TimeRange | null =>
        metrics.length === 0 ? null : { start: currentTime - PREVIEW_METRICS_WINDOW_MS, end: currentTime },
    ],
    metricsByCategory: [
      (s) => [s.sortedRecentMetrics],
      (metrics: frameMetricsPreviewLogicValues['sortedRecentMetrics']): Record<string, MetricSeries[]> =>
        metricsByCategoryFromMetrics(metrics),
    ],
    headerMetricsByCategory: [
      (s) => [s.metricsByCategory, s.previewMetricsTimeRange],
      (
        metricsByCategory: frameMetricsPreviewLogicValues['metricsByCategory'],
        previewMetricsTimeRange: frameMetricsPreviewLogicValues['previewMetricsTimeRange']
      ) =>
        filterMetricsByCategoryAndTimeRange(
          metricsByCategory,
          ['load', 'memoryUsage', 'diskUsage', 'batteryPercent'],
          previewMetricsTimeRange
        ),
    ],
    latestMetricSummariesByCategory: [
      (s) => [s.sortedRecentMetrics],
      (metrics: frameMetricsPreviewLogicValues['sortedRecentMetrics']): Record<string, string> =>
        latestMetricSummariesByCategoryFromMetrics(metrics),
    ],
    // Frames with a battery pin (ESP32 boards) report a charge estimate;
    // shown as a battery glyph in the header chips and the workspace sidebar.
    latestBatteryPercent: [
      (s) => [s.sortedRecentMetrics],
      (metrics: frameMetricsPreviewLogicValues['sortedRecentMetrics']): number | null =>
        latestBatteryPercentFromMetrics(metrics),
    ],
  }),
  afterMount(({ actions, cache }) => {
    actions.loadRecentMetrics()
    actions.setCurrentTime(Date.now())
    cache.currentTimeInterval = window.setInterval(() => actions.setCurrentTime(Date.now()), CURRENT_TIME_UPDATE_MS)
  }),
  beforeUnmount(({ cache }) => {
    if (cache.currentTimeInterval) {
      window.clearInterval(cache.currentTimeInterval)
    }
  }),
])
