import { MakeLogicType, actions, connect, kea, key, listeners, path, props, reducers, selectors } from 'kea'
import { loaders } from 'kea-loaders'

import type { FrameId, MetricsType } from '../../types'
import { apiFetch } from '../../utils/apiFetch'
import { metricTimestamp } from '../frame/panels/Metrics/metricsLogic'
import { socketLogic } from '../socketLogic'

/**
 * The battery popup's data: the retained metrics history of one frame,
 * fetched the first time the popup opens (the sidebar glyph itself reads the
 * one-hour preview window frameMetricsPreviewLogic already holds) and kept
 * current from the fleet socket afterwards. Two weeks of samples is plenty
 * for a trend and is within the 1000 newest samples either backend serves
 * (a deep-sleeping frame waking every 15 minutes fills that in ten days).
 */
const BATTERY_HISTORY_WINDOW_MS = 14 * 24 * 60 * 60 * 1000
const BATTERY_HISTORY_LIMIT = 1000
/** A reopened popup reuses a history this fresh instead of refetching. */
const BATTERY_HISTORY_MAX_AGE_MS = 60 * 1000

export interface FrameBatteryLogicProps {
  frameId: FrameId
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface frameBatteryLogicValues {
  batteryHistory: MetricsType[]
  batteryHistoryLoadedAt: number | null
  batteryHistoryLoading: boolean
  selectedCycleSeconds: number | null
  sortedBatteryHistory: MetricsType[]
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface frameBatteryLogicActions {
  ensureBatteryHistory: () => {
    value: true
  }
  loadBatteryHistory: () => any
  loadBatteryHistoryFailure: (
    error: string,
    errorObject?: any
  ) => {
    error: string
    errorObject?: any
  }
  loadBatteryHistorySuccess: (
    batteryHistory: MetricsType[],
    payload?: any
  ) => {
    batteryHistory: MetricsType[]
    payload?: any
  }
  setSelectedCycleSeconds: (cycleSeconds: number | null) => {
    cycleSeconds: number | null
  }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface frameBatteryLogicMeta {
  key: FrameId
  __keaTypeGenInternalSelectorTypes: {
    sortedBatteryHistory: (batteryHistory: MetricsType[]) => MetricsType[]
  }
}

export type frameBatteryLogicType = MakeLogicType<
  frameBatteryLogicValues,
  frameBatteryLogicActions,
  FrameBatteryLogicProps
> &
  frameBatteryLogicMeta

export const frameBatteryLogic = kea<frameBatteryLogicType>([
  path(['src', 'scenes', 'workspace', 'frameBatteryLogic']),
  props({} as FrameBatteryLogicProps),
  key((props) => props.frameId),
  connect(() => ({ logic: [socketLogic] })),
  actions({
    ensureBatteryHistory: true,
    setSelectedCycleSeconds: (cycleSeconds: number | null) => ({ cycleSeconds }),
  }),
  loaders(({ props }) => ({
    batteryHistory: [
      [] as MetricsType[],
      {
        loadBatteryHistory: async () => {
          const since = new Date(Date.now() - BATTERY_HISTORY_WINDOW_MS).toISOString()
          const response = await apiFetch(
            `/api/frames/${props.frameId}/metrics/recent?limit=${BATTERY_HISTORY_LIMIT}&since=${encodeURIComponent(
              since
            )}`
          )
          if (!response.ok) {
            throw new Error('Failed to fetch the battery history')
          }
          const data = await response.json()
          return (Array.isArray(data?.metrics) ? data.metrics : []) as MetricsType[]
        },
      },
    ],
  })),
  reducers(({ props }) => ({
    batteryHistory: {
      [socketLogic.actionTypes.newMetrics]: (state, { metrics }) => {
        if (metrics.frame_id !== props.frameId || state.length === 0) {
          return state
        }
        return [...state, metrics as MetricsType]
      },
    },
    batteryHistoryLoadedAt: [
      null as number | null,
      {
        loadBatteryHistorySuccess: () => Date.now(),
      },
    ],
    // The forecast slider's stop, per frame; null = the observed cadence.
    selectedCycleSeconds: [
      null as number | null,
      {
        setSelectedCycleSeconds: (_, { cycleSeconds }) => cycleSeconds,
      },
    ],
  })),
  selectors({
    sortedBatteryHistory: [
      (s) => [s.batteryHistory],
      (history: frameBatteryLogicValues['batteryHistory']): MetricsType[] =>
        [...history].sort((a, b) => metricTimestamp(a) - metricTimestamp(b)),
    ],
  }),
  listeners(({ actions, values }) => ({
    ensureBatteryHistory: () => {
      const loadedAt = values.batteryHistoryLoadedAt
      if (values.batteryHistoryLoading) {
        return
      }
      if (loadedAt !== null && Date.now() - loadedAt < BATTERY_HISTORY_MAX_AGE_MS) {
        return
      }
      actions.loadBatteryHistory()
    },
  })),
])
