// Generated by kea-typegen on Thu, 21 May 2026 23:13:48 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { FrameScene, FrameType } from '../../types'
import type { SceneSelection, WorkspaceUtilityPanel } from './workspaceLogic'

export interface workspaceLogicType extends Logic {
  actionCreators: {
    setSearch: (search: string) => {
      type: 'set search (src.scenes.workspace.workspaceLogic)'
      payload: {
        search: string
      }
    }
    selectFrame: (frameId: number | null) => {
      type: 'select frame (src.scenes.workspace.workspaceLogic)'
      payload: {
        frameId: number | null
      }
    }
    focusFrame: (frameId: number) => {
      type: 'focus frame (src.scenes.workspace.workspaceLogic)'
      payload: {
        frameId: number
      }
    }
    setRouteSelection: (
      frameId: number | null,
      sceneId?: string | null
    ) => {
      type: 'set route selection (src.scenes.workspace.workspaceLogic)'
      payload: {
        frameId: number | null
        sceneId: string | null
      }
    }
    navigateToSceneFrame: (frameId: number) => {
      type: 'navigate to scene frame (src.scenes.workspace.workspaceLogic)'
      payload: {
        frameId: number
      }
    }
    navigateToScene: (
      frameId: number,
      sceneId: string
    ) => {
      type: 'navigate to scene (src.scenes.workspace.workspaceLogic)'
      payload: {
        frameId: number
        sceneId: string
      }
    }
    openSceneControl: (
      frameId: number,
      sceneId: string
    ) => {
      type: 'open scene control (src.scenes.workspace.workspaceLogic)'
      payload: {
        frameId: number
        sceneId: string
      }
    }
    closeSceneControl: () => {
      type: 'close scene control (src.scenes.workspace.workspaceLogic)'
      payload: {
        value: true
      }
    }
    openUtilityPanel: (panel: WorkspaceUtilityPanel) => {
      type: 'open utility panel (src.scenes.workspace.workspaceLogic)'
      payload: {
        panel: WorkspaceUtilityPanel
      }
    }
    closeUtilityPanel: () => {
      type: 'close utility panel (src.scenes.workspace.workspaceLogic)'
      payload: {
        value: true
      }
    }
    selectNode: (nodeId: string | null) => {
      type: 'select node (src.scenes.workspace.workspaceLogic)'
      payload: {
        nodeId: string | null
      }
    }
  }
  actionKeys: {
    'set search (src.scenes.workspace.workspaceLogic)': 'setSearch'
    'select frame (src.scenes.workspace.workspaceLogic)': 'selectFrame'
    'focus frame (src.scenes.workspace.workspaceLogic)': 'focusFrame'
    'set route selection (src.scenes.workspace.workspaceLogic)': 'setRouteSelection'
    'navigate to scene frame (src.scenes.workspace.workspaceLogic)': 'navigateToSceneFrame'
    'navigate to scene (src.scenes.workspace.workspaceLogic)': 'navigateToScene'
    'open scene control (src.scenes.workspace.workspaceLogic)': 'openSceneControl'
    'close scene control (src.scenes.workspace.workspaceLogic)': 'closeSceneControl'
    'open utility panel (src.scenes.workspace.workspaceLogic)': 'openUtilityPanel'
    'close utility panel (src.scenes.workspace.workspaceLogic)': 'closeUtilityPanel'
    'select node (src.scenes.workspace.workspaceLogic)': 'selectNode'
  }
  actionTypes: {
    setSearch: 'set search (src.scenes.workspace.workspaceLogic)'
    selectFrame: 'select frame (src.scenes.workspace.workspaceLogic)'
    focusFrame: 'focus frame (src.scenes.workspace.workspaceLogic)'
    setRouteSelection: 'set route selection (src.scenes.workspace.workspaceLogic)'
    navigateToSceneFrame: 'navigate to scene frame (src.scenes.workspace.workspaceLogic)'
    navigateToScene: 'navigate to scene (src.scenes.workspace.workspaceLogic)'
    openSceneControl: 'open scene control (src.scenes.workspace.workspaceLogic)'
    closeSceneControl: 'close scene control (src.scenes.workspace.workspaceLogic)'
    openUtilityPanel: 'open utility panel (src.scenes.workspace.workspaceLogic)'
    closeUtilityPanel: 'close utility panel (src.scenes.workspace.workspaceLogic)'
    selectNode: 'select node (src.scenes.workspace.workspaceLogic)'
  }
  actions: {
    setSearch: (search: string) => void
    selectFrame: (frameId: number | null) => void
    focusFrame: (frameId: number) => void
    setRouteSelection: (frameId: number | null, sceneId?: string | null) => void
    navigateToSceneFrame: (frameId: number) => void
    navigateToScene: (frameId: number, sceneId: string) => void
    openSceneControl: (frameId: number, sceneId: string) => void
    closeSceneControl: () => void
    openUtilityPanel: (panel: WorkspaceUtilityPanel) => void
    closeUtilityPanel: () => void
    selectNode: (nodeId: string | null) => void
  }
  asyncActions: {
    setSearch: (search: string) => Promise<any>
    selectFrame: (frameId: number | null) => Promise<any>
    focusFrame: (frameId: number) => Promise<any>
    setRouteSelection: (frameId: number | null, sceneId?: string | null) => Promise<any>
    navigateToSceneFrame: (frameId: number) => Promise<any>
    navigateToScene: (frameId: number, sceneId: string) => Promise<any>
    openSceneControl: (frameId: number, sceneId: string) => Promise<any>
    closeSceneControl: () => Promise<any>
    openUtilityPanel: (panel: WorkspaceUtilityPanel) => Promise<any>
    closeUtilityPanel: () => Promise<any>
    selectNode: (nodeId: string | null) => Promise<any>
  }
  defaults: {
    search: string
    selectedFrameId: number | null
    selectedSceneIdsByFrame: Record<number, string>
    sceneControlSelection: SceneSelection | null
    utilityPanel: WorkspaceUtilityPanel | null
    selectedNodeId: string | null
  }
  events: {}
  key: undefined
  listeners: {
    focusFrame: ((
      action: {
        type: 'focus frame (src.scenes.workspace.workspaceLogic)'
        payload: {
          frameId: number
        }
      },
      previousState: any
    ) => void | Promise<void>)[]
    navigateToSceneFrame: ((
      action: {
        type: 'navigate to scene frame (src.scenes.workspace.workspaceLogic)'
        payload: {
          frameId: number
        }
      },
      previousState: any
    ) => void | Promise<void>)[]
    navigateToScene: ((
      action: {
        type: 'navigate to scene (src.scenes.workspace.workspaceLogic)'
        payload: {
          frameId: number
          sceneId: string
        }
      },
      previousState: any
    ) => void | Promise<void>)[]
  }
  path: ['src', 'scenes', 'workspace', 'workspaceLogic']
  pathString: 'src.scenes.workspace.workspaceLogic'
  props: Record<string, unknown>
  reducer: (
    state: any,
    action: any,
    fullState: any
  ) => {
    search: string
    selectedFrameId: number | null
    selectedSceneIdsByFrame: Record<number, string>
    sceneControlSelection: SceneSelection | null
    utilityPanel: WorkspaceUtilityPanel | null
    selectedNodeId: string | null
  }
  reducers: {
    search: (state: string, action: any, fullState: any) => string
    selectedFrameId: (state: number | null, action: any, fullState: any) => number | null
    selectedSceneIdsByFrame: (state: Record<number, string>, action: any, fullState: any) => Record<number, string>
    sceneControlSelection: (state: SceneSelection | null, action: any, fullState: any) => SceneSelection | null
    utilityPanel: (state: WorkspaceUtilityPanel | null, action: any, fullState: any) => WorkspaceUtilityPanel | null
    selectedNodeId: (state: string | null, action: any, fullState: any) => string | null
  }
  selector: (state: any) => {
    search: string
    selectedFrameId: number | null
    selectedSceneIdsByFrame: Record<number, string>
    sceneControlSelection: SceneSelection | null
    utilityPanel: WorkspaceUtilityPanel | null
    selectedNodeId: string | null
  }
  selectors: {
    search: (state: any, props?: any) => string
    selectedFrameId: (state: any, props?: any) => number | null
    selectedSceneIdsByFrame: (state: any, props?: any) => Record<number, string>
    sceneControlSelection: (state: any, props?: any) => SceneSelection | null
    utilityPanel: (state: any, props?: any) => WorkspaceUtilityPanel | null
    selectedNodeId: (state: any, props?: any) => string | null
    frames: (state: any, props?: any) => Record<number, FrameType>
    framesList: (state: any, props?: any) => FrameType[]
    activeFramesList: (state: any, props?: any) => FrameType[]
    archivedFramesList: (state: any, props?: any) => FrameType[]
    selectedFrame: (state: any, props?: any) => FrameType | null
    selectedSceneId: (state: any, props?: any) => string | null
    selectedScene: (state: any, props?: any) => FrameScene | null
    filteredOverviewFrames: (state: any, props?: any) => FrameType[]
    filteredSelectedFrameScenes: (state: any, props?: any) => FrameScene[]
  }
  sharedListeners: {}
  values: {
    search: string
    selectedFrameId: number | null
    selectedSceneIdsByFrame: Record<number, string>
    sceneControlSelection: SceneSelection | null
    utilityPanel: WorkspaceUtilityPanel | null
    selectedNodeId: string | null
    frames: Record<number, FrameType>
    framesList: FrameType[]
    activeFramesList: FrameType[]
    archivedFramesList: FrameType[]
    selectedFrame: FrameType | null
    selectedSceneId: string | null
    selectedScene: FrameScene | null
    filteredOverviewFrames: FrameType[]
    filteredSelectedFrameScenes: FrameScene[]
  }
  _isKea: true
  _isKeaWithKey: false
  __keaTypeGenInternalSelectorTypes: {
    selectedFrame: (
      frames: Record<number, FrameType>,
      selectedFrameId: number | null,
      activeFramesList: FrameType[],
      framesList: FrameType[]
    ) => FrameType | null
    selectedSceneId: (selectedFrame: FrameType | null, selectedSceneIdsByFrame: Record<number, string>) => string | null
    selectedScene: (selectedFrame: FrameType | null, selectedSceneId: string | null) => FrameScene | null
    filteredOverviewFrames: (activeFramesList: FrameType[], search: string) => FrameType[]
    filteredSelectedFrameScenes: (selectedFrame: FrameType | null, search: string) => FrameScene[]
  }
}
