import {
  MakeLogicType,
  actions,
  afterMount,
  beforeUnmount,
  connect,
  kea,
  listeners,
  path,
  reducers,
  selectors,
} from 'kea'
import { inHassioAddon } from '../../utils/inHassioAddon'
import { loaders } from 'kea-loaders'
import { socketLogic } from '../socketLogic'
import { forms } from 'kea-forms'
import { FrameOSSettings, SSHKeyEntry } from '../../types'
import { apiFetch, logApiError } from '../../utils/apiFetch'
import { normalizeSshKeys } from '../../utils/sshKeys'
import { onSettingsChanged } from '../../utils/settingsInvalidation'
import { v4 as uuidv4 } from 'uuid'
import { showWorkingMessage } from '../../utils/workingMessage'
import { isFrameControlMode } from '../../utils/frameControlMode'
import { isInFrameAdminMode } from '../../utils/frameAdmin'
import { guessBrowserTimezone } from '../../utils/timezone'
import type { DeepPartial, DeepPartialMap, FieldName, ValidationErrorType } from 'kea-forms'

function setDefaultSettings(settings: Partial<FrameOSSettings> | Record<string, any>): FrameOSSettings {
  // Mirrors selected_build_environment_provider on the backend: the add-on
  // container has no Docker socket, so its default is on-device builds.
  const buildEnvironmentProvider =
    settings.buildEnvironment?.provider ||
    (settings.modalSandbox?.enabled
      ? 'modal'
      : settings.buildHost?.enabled
      ? 'buildHost'
      : inHassioAddon()
      ? 'none'
      : 'docker')
  const personalSettings = isSettingsObject(settings.personal) ? settings.personal : {}
  return {
    ...settings,
    defaults: {
      timezone: guessBrowserTimezone(),
      wifiSSID: '',
      wifiPassword: '',
      backendHost: '',
      backendPort: '',
      ...(settings.defaults ?? {}),
    },
    homeAssistant: settings.homeAssistant ?? {},
    frameOS: settings.frameOS ?? {},
    github: settings.github ?? {},
    immich: settings.immich ?? {},
    openAI: settings.openAI ?? {},
    posthog: settings.posthog ?? {},
    personal: {
      ...personalSettings,
      favouriteTemplateIds: normalizeFavouriteTemplateIds(settings.personal?.favouriteTemplateIds),
    },
    repositories: settings.repositories ?? [],
    ssh_keys: normalizeSshKeys(settings.ssh_keys),
    unsplash: settings.unsplash ?? {},
    buildEnvironment: {
      ...(settings.buildEnvironment ?? {}),
      provider: buildEnvironmentProvider,
    },
    buildHost: settings.buildHost ?? {},
    modalSandbox: settings.modalSandbox ?? {},
  }
}

function isSettingsObject(value: unknown): value is Record<string, any> {
  return Boolean(value && typeof value === 'object' && !Array.isArray(value))
}

function normalizeFavouriteTemplateIds(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return []
  }
  return Array.from(new Set(value.filter((id): id is string => typeof id === 'string' && id.trim() !== '')))
}

export interface CustomFont {
  id: string
  path: string
  size: number
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface settingsLogicValues {
  customFonts: CustomFont[]
  customFontsForm: {
    files: File[]
  }
  customFontsFormAllErrors: Record<string, any>
  customFontsFormChanged: boolean
  customFontsFormErrors: DeepPartialMap<
    {
      files: File[]
    },
    ValidationErrorType
  >
  customFontsFormHasErrors: boolean
  customFontsFormManualErrors: Record<string, any>
  customFontsFormTouched: boolean
  customFontsFormTouches: Record<string, boolean>
  customFontsFormValidationErrors: DeepPartialMap<
    {
      files: File[]
    },
    ValidationErrorType
  >
  customFontsLoading: boolean
  generatingSshKeyId: string | null
  homeAssistantMqttHostDefault: string
  isCustomFontsFormSubmitting: boolean
  isCustomFontsFormValid: boolean
  isSettingsSubmitting: boolean
  isSettingsValid: boolean
  isSyncingHomeAssistant: boolean
  isTestingBuildHost: boolean
  isTestingModalSandbox: boolean
  openAiModelOverridesExpanded: boolean
  savedSettings: FrameOSSettings
  savedSettingsLoading: boolean
  settings: FrameOSSettings
  settingsAllErrors: Record<string, any>
  settingsChanged: boolean
  settingsErrors: DeepPartialMap<FrameOSSettings, ValidationErrorType>
  settingsHasErrors: boolean
  settingsManualErrors: Record<string, any>
  settingsTouched: boolean
  settingsTouches: Record<string, boolean>
  settingsValidationErrors: DeepPartialMap<FrameOSSettings, ValidationErrorType>
  showCustomFontsFormErrors: boolean
  showSettingsErrors: boolean
  sshKeyExpandedIds: string[]
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface settingsLogicActions {
  addSshKey: () => {
    value: true
  }
  deleteCustomFont: (font: CustomFont) => CustomFont
  deleteCustomFontFailure: (
    error: string,
    errorObject?: any
  ) => {
    error: string
    errorObject?: any
  }
  deleteCustomFontSuccess: (
    customFonts: CustomFont[],
    payload?: CustomFont
  ) => {
    customFonts: CustomFont[]
    payload?: CustomFont
  }
  generateSshKey: (id: string) => {
    id: string
  }
  loadCustomFonts: () => any
  loadCustomFontsFailure: (
    error: string,
    errorObject?: any
  ) => {
    error: string
    errorObject?: any
  }
  loadCustomFontsSuccess: (
    customFonts: CustomFont[],
    payload?: any
  ) => {
    customFonts: CustomFont[]
    payload?: any
  }
  loadSettings: () => any
  loadSettingsFailure: (
    error: string,
    errorObject?: any
  ) => {
    error: string
    errorObject?: any
  }
  loadSettingsSuccess: (
    savedSettings: FrameOSSettings,
    payload?: any
  ) => {
    savedSettings: FrameOSSettings
    payload?: any
  }
  newBuildHostKey: () => {
    value: true
  }
  removeSshKey: (id: string) => {
    id: string
  }
  resetCustomFontsForm: (values?: { files: File[] }) => {
    values?: {
      files: File[]
    }
  }
  resetSettings: (values?: FrameOSSettings) => {
    values?: FrameOSSettings
  }
  setCustomFontsFormManualErrors: (errors: Record<string, any>) => {
    errors: Record<string, any>
  }
  setCustomFontsFormValue: (
    key: FieldName,
    value: any
  ) => {
    name: FieldName
    value: any
  }
  setCustomFontsFormValues: (
    values: DeepPartial<{
      files: File[]
    }>
  ) => {
    values: DeepPartial<{
      files: File[]
    }>
  }
  setGeneratingSshKeyId: (id: string | null) => {
    id: string | null
  }
  setPersonalFavouriteTemplateIds: (templateIds: string[]) => {
    templateIds: string[]
  }
  setSettingsManualErrors: (errors: Record<string, any>) => {
    errors: Record<string, any>
  }
  setSettingsValue: (
    key: FieldName,
    value: any
  ) => {
    name: FieldName
    value: any
  }
  setSettingsValues: (values: DeepPartial<FrameOSSettings>) => {
    values: DeepPartial<FrameOSSettings>
  }
  setSshKeyExpanded: (
    id: string,
    expanded: boolean
  ) => {
    expanded: boolean
    id: string
  }
  setSshKeyExpandedIds: (ids: string[]) => {
    ids: string[]
  }
  setSyncingHomeAssistant: (syncing: boolean) => {
    syncing: boolean
  }
  setTestingBuildHost: (testing: boolean) => {
    testing: boolean
  }
  setTestingModalSandbox: (testing: boolean) => {
    testing: boolean
  }
  submitCustomFontsForm: () => {
    value: boolean
  }
  submitCustomFontsFormFailure: (
    error: Error,
    errors: Record<string, any>
  ) => {
    error: Error
    errors: Record<string, any>
  }
  submitCustomFontsFormRequest: (customFontsForm: { files: File[] }) => {
    customFontsForm: {
      files: File[]
    }
  }
  submitCustomFontsFormSuccess: (customFontsForm: { files: File[] }) => {
    customFontsForm: {
      files: File[]
    }
  }
  submitSettings: () => {
    value: boolean
  }
  submitSettingsFailure: (
    error: Error,
    errors: Record<string, any>
  ) => {
    error: Error
    errors: Record<string, any>
  }
  submitSettingsRequest: (settings: FrameOSSettings) => {
    settings: FrameOSSettings
  }
  submitSettingsSuccess: (settings: FrameOSSettings) => {
    settings: FrameOSSettings
  }
  syncHomeAssistant: () => {
    value: true
  }
  testBuildHost: () => {
    value: true
  }
  testModalSandbox: () => {
    value: true
  }
  toggleOpenAiModelOverrides: () => {
    value: true
  }
  togglePersonalFavouriteTemplate: (templateId: string) => {
    templateId: string
  }
  toggleSshKeyExpanded: (id: string) => {
    id: string
  }
  touchCustomFontsFormField: (key: string) => {
    key: string
  }
  touchSettingsField: (key: string) => {
    key: string
  }
  updateSavedSettings: (settings: Record<string, any>) => {
    settings: Record<string, any>
  }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface settingsLogicMeta {
  __keaTypeGenInternalSelectorTypes: {
    homeAssistantMqttHostDefault: (settings: FrameOSSettings) => string
  }
}

export type settingsLogicType = MakeLogicType<settingsLogicValues, settingsLogicActions, Record<string, any>> &
  settingsLogicMeta

export const settingsLogic = kea<settingsLogicType>([
  path(['src', 'scenes', 'settings', 'settingsLogic']),
  connect(() => ({ logic: [socketLogic] })),
  actions({
    updateSavedSettings: (settings: Record<string, any>) => ({ settings }),
    addSshKey: true,
    generateSshKey: (id: string) => ({ id }),
    removeSshKey: (id: string) => ({ id }),
    setSshKeyExpandedIds: (ids: string[]) => ({ ids }),
    setSshKeyExpanded: (id: string, expanded: boolean) => ({ id, expanded }),
    toggleSshKeyExpanded: (id: string) => ({ id }),
    setPersonalFavouriteTemplateIds: (templateIds: string[]) => ({ templateIds }),
    togglePersonalFavouriteTemplate: (templateId: string) => ({ templateId }),
    toggleOpenAiModelOverrides: true,
    newBuildHostKey: true,
    testBuildHost: true,
    testModalSandbox: true,
    syncHomeAssistant: true,
    setTestingBuildHost: (testing: boolean) => ({ testing }),
    setTestingModalSandbox: (testing: boolean) => ({ testing }),
    setSyncingHomeAssistant: (syncing: boolean) => ({ syncing }),
    setGeneratingSshKeyId: (id: string | null) => ({ id }),
  }),
  loaders(({ values }) => ({
    savedSettings: [
      setDefaultSettings({}),
      {
        loadSettings: async () => {
          try {
            const response = await apiFetch(`/api/settings`)
            if (!response.ok) {
              throw new Error('Failed to fetch settings')
            }
            const data = await response.json()
            return setDefaultSettings({ ...values.savedSettings, ...data })
          } catch (error) {
            logApiError(error)
            return values.savedSettings
          }
        },
      },
    ],
    customFonts: [
      [] as CustomFont[],
      {
        loadCustomFonts: async () => {
          try {
            const response = await apiFetch(`/api/assets`)
            if (!response.ok) {
              throw new Error('Failed to fetch assets')
            }
            const data = await response.json()
            return data.filter((asset: CustomFont) => asset.path.startsWith('fonts/') && asset.path.endsWith('.ttf'))
          } catch (error) {
            logApiError(error)
            return values.customFonts
          }
        },
        deleteCustomFont: async (font: CustomFont) => {
          const response = await apiFetch(`/api/assets/${font.id}`, {
            method: 'DELETE',
          })
          if (!response.ok) {
            throw new Error('Failed to delete font')
          }
          return values.customFonts.filter((f) => f.id !== font.id)
        },
      },
    ],
  })),
  reducers({
    savedSettings: {
      updateSavedSettings: (state, { settings }) => setDefaultSettings({ ...state, ...settings }),
    },
    generatingSshKeyId: [
      null as string | null,
      {
        setGeneratingSshKeyId: (_, { id }) => id,
      },
    ],
    sshKeyExpandedIds: [
      [] as string[],
      {
        setSshKeyExpandedIds: (_, { ids }) => ids,
        setSshKeyExpanded: (state, { id, expanded }) =>
          expanded ? (state.includes(id) ? state : [...state, id]) : state.filter((keyId) => keyId !== id),
        toggleSshKeyExpanded: (state, { id }) =>
          state.includes(id) ? state.filter((keyId) => keyId !== id) : [...state, id],
      },
    ],
    openAiModelOverridesExpanded: [
      false,
      {
        toggleOpenAiModelOverrides: (state) => !state,
      },
    ],
    isTestingModalSandbox: [
      false,
      {
        setTestingModalSandbox: (_, { testing }) => testing,
      },
    ],
    isTestingBuildHost: [
      false,
      {
        setTestingBuildHost: (_, { testing }) => testing,
      },
    ],
    isSyncingHomeAssistant: [
      false,
      {
        setSyncingHomeAssistant: (_, { syncing }) => syncing,
      },
    ],
  }),
  forms(({ values, actions }) => ({
    settings: {
      defaults: setDefaultSettings({}),
      submit: async (formValues) => {
        const response = await apiFetch(`/api/settings`, {
          method: 'POST',
          body: JSON.stringify(formValues),
          headers: { 'Content-Type': 'application/json' },
        })
        if (!response.ok) {
          throw new Error('Failed to update frame')
        }
        actions.resetSettings(setDefaultSettings(await response.json()))
      },
    },
    customFontsForm: {
      defaults: { files: [] } as { files: File[] },
      submit: async (formValues) => {
        if (!formValues.files.length) {
          return
        }

        const workingMessage = showWorkingMessage('Uploading assets...')
        try {
          for (const file of formValues.files) {
            const formData = new FormData()
            formData.append('path', `fonts/${file.name}`)
            formData.append('file', file)

            const response = await apiFetch(`/api/assets`, {
              method: 'POST',
              body: formData,
            })
            if (!response.ok) {
              throw new Error(`Failed to upload file: ${file.name}`)
            }
          }
          workingMessage.success('Assets uploaded successfully')
          actions.loadCustomFonts()
          actions.resetCustomFontsForm()
        } catch (error) {
          workingMessage.error(error instanceof Error ? error.message : 'Failed to upload assets')
          throw error
        }
      },
    },
  })),
  // After forms(): the `settings` selector this depends on is created there
  selectors({
    // Mirrors the backend default: MQTT host falls back to the HA URL's hostname
    homeAssistantMqttHostDefault: [
      (s) => [s.settings],
      (settings: settingsLogicValues['settings']): string => {
        const url = (settings.homeAssistant?.url ?? '').trim()
        if (url) {
          try {
            return new URL(url.includes('://') ? url : `http://${url}`).hostname || 'homeassistant.local'
          } catch {
            // fall through to the generic default
          }
        }
        return 'homeassistant.local'
      },
    ],
  }),
  afterMount(({ actions, cache }) => {
    // Logics that write a settings group on their own (sshKeysLogic) say so
    // here; reload rather than let the form offer stale values back.
    cache.unsubscribeSettingsChanged = onSettingsChanged(() => actions.loadSettings())
    if (isFrameControlMode() && !isInFrameAdminMode()) {
      return
    }
    actions.loadSettings()
    if (!isFrameControlMode()) {
      actions.loadCustomFonts()
    }
  }),
  beforeUnmount(({ cache }) => {
    cache.unsubscribeSettingsChanged?.()
  }),
  listeners(({ values, actions }) => ({
    loadSettingsSuccess: ({ savedSettings }) => {
      actions.resetSettings(setDefaultSettings(savedSettings))
      const savedKeys = normalizeSshKeys(savedSettings.ssh_keys).keys
      const expandedIds = savedKeys.filter((key) => !key.private && !key.public).map((key) => key.id)
      actions.setSshKeyExpandedIds(expandedIds)
    },
    [socketLogic.actionTypes.updateSettings]: ({ settings }) => {
      actions.updateSavedSettings(setDefaultSettings(settings))
      actions.resetSettings(setDefaultSettings({ ...values.savedSettings, ...settings }))
    },
    addSshKey: async () => {
      const keyId = uuidv4()
      const keys = values.settings.ssh_keys?.keys ?? []
      actions.setSettingsValue(['ssh_keys', 'keys'] as any, [
        ...keys,
        {
          id: keyId,
          name: `Key ${keys.length + 1}`,
          private: '',
          public: '',
          use_for_new_frames: keys.length === 0,
        } satisfies SSHKeyEntry,
      ])
      actions.setSshKeyExpanded(keyId, true)
    },
    generateSshKey: async ({ id }) => {
      actions.setGeneratingSshKeyId(id)
      try {
        const response = await apiFetch(`/api/generate_ssh_keys`, {
          method: 'POST',
        })
        if (!response.ok) {
          throw new Error('Failed to generate new key')
        }
        const data = await response.json()
        const keys = values.settings.ssh_keys?.keys ?? []
        actions.setSettingsValue(
          ['ssh_keys', 'keys'] as any,
          keys.map((key) =>
            key.id === id
              ? ({
                  ...key,
                  private: data.private,
                  public: `${data.public} frameos@${window.location.hostname}`,
                } satisfies SSHKeyEntry)
              : key
          )
        )
      } finally {
        actions.setGeneratingSshKeyId(null)
      }
    },
    removeSshKey: async ({ id }) => {
      const keys = values.settings.ssh_keys?.keys ?? []
      if (keys.length <= 1) {
        return
      }
      actions.setSettingsValue(
        ['ssh_keys', 'keys'] as any,
        keys.filter((key) => key.id !== id)
      )
      actions.setSshKeyExpanded(id, false)
    },
    setPersonalFavouriteTemplateIds: async ({ templateIds }) => {
      const previousPersonal = values.savedSettings.personal ?? { favouriteTemplateIds: [] }
      const favouriteTemplateIds = normalizeFavouriteTemplateIds(templateIds)
      const personal = {
        ...previousPersonal,
        ...(values.settings.personal ?? {}),
        favouriteTemplateIds,
      }
      actions.setSettingsValue(['personal', 'favouriteTemplateIds'] as any, favouriteTemplateIds)
      actions.updateSavedSettings({ personal })

      try {
        const response = await apiFetch(`/api/settings`, {
          method: 'POST',
          body: JSON.stringify({ personal }),
          headers: { 'Content-Type': 'application/json' },
        })
        if (!response.ok) {
          throw new Error('Failed to update personal favourites')
        }
        const updatedSettings = setDefaultSettings(await response.json())
        actions.updateSavedSettings(updatedSettings)
        actions.setSettingsValue(['personal'] as any, updatedSettings.personal)
      } catch (error) {
        console.error(error)
        actions.setSettingsValue(['personal'] as any, previousPersonal)
        actions.updateSavedSettings({ personal: previousPersonal })
      }
    },
    togglePersonalFavouriteTemplate: async ({ templateId }) => {
      const favouriteTemplateIds = normalizeFavouriteTemplateIds(values.settings.personal?.favouriteTemplateIds)
      actions.setPersonalFavouriteTemplateIds(
        favouriteTemplateIds.includes(templateId)
          ? favouriteTemplateIds.filter((id) => id !== templateId)
          : [...favouriteTemplateIds, templateId]
      )
    },
    newBuildHostKey: async () => {
      if (values.savedSettings.buildHost?.sshKey) {
        if (
          !confirm('Are you sure you want to generate a new key? You might lose access to the existing build host.')
        ) {
          return
        }
      }
      const response = await apiFetch(`/api/generate_ssh_keys`, {
        method: 'POST',
      })
      if (!response.ok) {
        throw new Error('Failed to generate new key')
      }
      const data = await response.json()
      actions.setSettingsValue(['buildHost', 'sshKey'], data.private)
      actions.setSettingsValue(
        ['buildHost', 'sshPublicKey'],
        `${data.public} frameos-buildhost@${window.location.hostname}`
      )
    },
    testBuildHost: async () => {
      actions.setTestingBuildHost(true)
      const workingMessage = showWorkingMessage('Checking build host connection...')
      try {
        const response = await apiFetch(`/api/settings/test_build_host`, {
          method: 'POST',
          body: JSON.stringify({ buildHost: values.settings.buildHost ?? {} }),
          headers: { 'Content-Type': 'application/json' },
        })
        if (!response.ok) {
          const data = await response.json().catch(() => null)
          throw new Error(data?.detail || 'Build host connection check failed')
        }
        // The check pins the host key it was offered (trust on first use);
        // it lands in the form next to the credentials and is saved with them.
        const data = await response.json().catch(() => null)
        if (data?.hostKey && !values.settings.buildHost?.hostKey) {
          actions.setSettingsValues({
            buildHost: {
              ...(values.settings.buildHost ?? {}),
              hostKey: data.hostKey,
              hostKeyFingerprint: data.hostKeyFingerprint ?? '',
            },
          })
        }
        workingMessage.success('Build host connection check succeeded')
      } catch (error) {
        const message = error instanceof Error ? error.message : 'Build host connection check failed'
        workingMessage.error(message)
        throw error
      } finally {
        actions.setTestingBuildHost(false)
      }
    },
    syncHomeAssistant: async () => {
      actions.setSyncingHomeAssistant(true)
      const workingMessage = showWorkingMessage('Saving settings and syncing frames to Home Assistant...')
      try {
        // Save the whole settings form (like the Save button) so the sync uses
        // what's on screen and the form no longer counts as unsaved.
        const formValues = {
          ...values.settings,
          homeAssistant: { ...(values.settings.homeAssistant ?? {}), syncEnabled: true },
        }
        const saveResponse = await apiFetch(`/api/settings`, {
          method: 'POST',
          body: JSON.stringify(formValues),
          headers: { 'Content-Type': 'application/json' },
        })
        if (!saveResponse.ok) {
          throw new Error('Failed to save settings')
        }
        const updatedSettings = await saveResponse.json()
        actions.updateSavedSettings(updatedSettings)
        actions.resetSettings(setDefaultSettings(updatedSettings))

        const response = await apiFetch(`/api/settings/home_assistant/sync`, {
          method: 'POST',
        })
        const data = await response.json().catch(() => null)
        if (!response.ok) {
          throw new Error(data?.detail || 'Home Assistant sync failed')
        }
        const message = data?.message || 'Synced frames to Home Assistant.'
        if (data?.warning) {
          workingMessage.warning(message)
        } else {
          workingMessage.success(message)
        }
      } catch (error) {
        const message = error instanceof Error ? error.message : 'Home Assistant sync failed'
        workingMessage.error(message)
        throw error
      } finally {
        actions.setSyncingHomeAssistant(false)
      }
    },
    testModalSandbox: async () => {
      actions.setTestingModalSandbox(true)
      const workingMessage = showWorkingMessage('Testing Modal sandbox...')
      try {
        const response = await apiFetch(`/api/settings/test_modal_sandbox`, {
          method: 'POST',
          body: JSON.stringify({ modalSandbox: { ...(values.settings.modalSandbox ?? {}), enabled: true } }),
          headers: { 'Content-Type': 'application/json' },
        })
        if (!response.ok) {
          const data = await response.json().catch(() => null)
          throw new Error(data?.detail || 'Modal sandbox test failed')
        }
        workingMessage.success('Modal sandbox test succeeded')
      } catch (error) {
        const message = error instanceof Error ? error.message : 'Modal sandbox test failed'
        workingMessage.error(message)
        throw error
      } finally {
        actions.setTestingModalSandbox(false)
      }
    },
  })),
])
