import { MakeLogicType, afterMount, beforeUnmount, kea, path, reducers, selectors } from 'kea'
import { loaders } from 'kea-loaders'

import { apiFetch } from '../../utils/apiFetch'

export interface DiskInfo {
  totalBytes: number
  usedBytes: number
  freeBytes: number
}

export interface MemoryInfo {
  totalBytes: number | null
  availableBytes: number | null
}

export interface LoadInfo {
  one: number | null
  five: number | null
  fifteen: number | null
}

export interface CacheInfo {
  name: string
  path: string
  sizeBytes: number
  exists: boolean
}

export interface DatabaseInfo {
  path: string | null
  sizeBytes: number | null
  exists: boolean
}

export interface DockerInfo {
  cliAvailable: boolean
  daemonAvailable: boolean
  error?: string | null
}

export interface SystemInfoResponse {
  disk: DiskInfo
  caches: CacheInfo[]
  database: DatabaseInfo
  memory: MemoryInfo
  load: LoadInfo
  docker: DockerInfo
}

export interface SystemMetricsResponse {
  disk: DiskInfo
  memory: MemoryInfo
  load: LoadInfo
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface systemInfoLogicValues {
  currentDisk: DiskInfo | null
  currentLoad: LoadInfo | null
  currentMemory: MemoryInfo | null
  systemInfo: SystemInfoResponse | null
  systemInfoLoading: boolean
  systemMetrics: SystemMetricsResponse | null
  systemMetricsLoading: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface systemInfoLogicActions {
  loadSystemInfo: () => any
  loadSystemInfoFailure: (
    error: string,
    errorObject?: any
  ) => {
    error: string
    errorObject?: any
  }
  loadSystemInfoSuccess: (
    systemInfo: SystemInfoResponse,
    payload?: any
  ) => {
    systemInfo: SystemInfoResponse
    payload?: any
  }
  loadSystemMetrics: () => any
  loadSystemMetricsFailure: (
    error: string,
    errorObject?: any
  ) => {
    error: string
    errorObject?: any
  }
  loadSystemMetricsSuccess: (
    systemMetrics: SystemMetricsResponse,
    payload?: any
  ) => {
    systemMetrics: SystemMetricsResponse
    payload?: any
  }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface systemInfoLogicMeta {
  __keaTypeGenInternalSelectorTypes: {
    currentDisk: (systemMetrics: SystemMetricsResponse | null, systemInfo: SystemInfoResponse | null) => DiskInfo | null
    currentMemory: (
      systemMetrics: SystemMetricsResponse | null,
      systemInfo: SystemInfoResponse | null
    ) => MemoryInfo | null
    currentLoad: (systemMetrics: SystemMetricsResponse | null, systemInfo: SystemInfoResponse | null) => LoadInfo | null
  }
}

export type systemInfoLogicType = MakeLogicType<systemInfoLogicValues, systemInfoLogicActions, Record<string, any>> &
  systemInfoLogicMeta

export const systemInfoLogic = kea<systemInfoLogicType>([
  path(['src', 'scenes', 'settings', 'systemInfoLogic']),
  loaders(() => ({
    systemInfo: [
      null as SystemInfoResponse | null,
      {
        loadSystemInfo: async () => {
          const response = await apiFetch(`/api/system/info`)
          if (!response.ok) {
            throw new Error('Failed to fetch system information')
          }
          return (await response.json()) as SystemInfoResponse
        },
      },
    ],
    systemMetrics: [
      null as SystemMetricsResponse | null,
      {
        loadSystemMetrics: async () => {
          const response = await apiFetch(`/api/system/metrics`)
          if (!response.ok) {
            throw new Error('Failed to fetch system metrics')
          }
          return (await response.json()) as SystemMetricsResponse
        },
      },
    ],
  })),
  reducers({
    systemInfo: {
      loadSystemInfoFailure: () => null,
    },
    systemMetrics: {
      loadSystemMetricsFailure: () => null,
    },
  }),
  selectors({
    currentDisk: [
      (s) => [s.systemMetrics, s.systemInfo],
      (systemMetrics: systemInfoLogicValues['systemMetrics'], systemInfo: systemInfoLogicValues['systemInfo']) =>
        systemMetrics?.disk ?? systemInfo?.disk ?? null,
    ],
    currentMemory: [
      (s) => [s.systemMetrics, s.systemInfo],
      (systemMetrics: systemInfoLogicValues['systemMetrics'], systemInfo: systemInfoLogicValues['systemInfo']) =>
        systemMetrics?.memory ?? systemInfo?.memory ?? null,
    ],
    currentLoad: [
      (s) => [s.systemMetrics, s.systemInfo],
      (systemMetrics: systemInfoLogicValues['systemMetrics'], systemInfo: systemInfoLogicValues['systemInfo']) =>
        systemMetrics?.load ?? systemInfo?.load ?? null,
    ],
  }),
  afterMount(({ actions, cache }) => {
    actions.loadSystemInfo()
    const refreshMetrics = () => actions.loadSystemMetrics()
    refreshMetrics()
    cache.metricsInterval = window.setInterval(refreshMetrics, 5000)
  }),
  beforeUnmount(({ cache }) => {
    if (cache.metricsInterval) {
      window.clearInterval(cache.metricsInterval)
    }
  }),
])
