# Generated by frameos/tools/generate_cloud_contract.py from docs/cloud-frames-contract.json — do not edit.

import ./contract_types

const CloudContractSettings* = @[
  SettingSpec(key: "name", rule:
    Rule(kind: rkString, minLen: 1, maxLen: 256),
  profiles: @[
    ProfileSpec(profile: "linux"),
    ProfileSpec(profile: "esp32")]),
  SettingSpec(key: "rotate", rule:
    Rule(kind: rkInt, intEnum: @[0, 90, 180, 270]),
  profiles: @[
    ProfileSpec(profile: "linux"),
    ProfileSpec(profile: "esp32", restart: true)]),
  SettingSpec(key: "interval", rule:
    Rule(kind: rkNumber, hasMin: true, min: 1.0, hasMax: true, max: 86400.0),
  profiles: @[
    ProfileSpec(profile: "linux"),
    ProfileSpec(profile: "esp32")]),
  SettingSpec(key: "scaling_mode", rule:
    Rule(kind: rkString, strEnum: @["contain", "cover", "stretch", "center"]),
  profiles: @[
    ProfileSpec(profile: "linux"),
    ProfileSpec(profile: "esp32")]),
  SettingSpec(key: "timezone", rule:
    Rule(kind: rkString, minLen: 1, maxLen: 64, format: sfIanaZone),
  profiles: @[
    ProfileSpec(profile: "linux"),
    ProfileSpec(profile: "esp32", since: "2026.8.34")]),
  SettingSpec(key: "timezone_data", companion: "timezone", rule:
    Rule(kind: rkAnyOf, children: @[
      Rule(kind: rkObject, open: true),
      Rule(kind: rkNull)]),
  profiles: @[
    ProfileSpec(profile: "esp32", since: "2026.8.34")]),
  SettingSpec(key: "debug", rule:
    Rule(kind: rkBool),
  profiles: @[
    ProfileSpec(profile: "linux"),
    ProfileSpec(profile: "esp32", since: "2026.8.31")]),
  SettingSpec(key: "flip", rule:
    Rule(kind: rkString, strEnum: @["", "horizontal", "vertical", "both"]),
  profiles: @[
    ProfileSpec(profile: "linux", since: "2026.8.30")]),
  SettingSpec(key: "error_behavior", rule:
    Rule(kind: rkObject, keys: @[
      KeyRule(name: "mode", rule:
        Rule(kind: rkString, strEnum: @["safe_mode", "show_error_retry", "silent_retry"])),
      KeyRule(name: "retry_seconds", rule:
        Rule(kind: rkNumber, hasMin: true, min: 1.0, hasMax: true, max: 86400.0)),
      KeyRule(name: "silent_retry_seconds", rule:
        Rule(kind: rkNumber, hasMin: true, min: 1.0, hasMax: true, max: 86400.0)),
      KeyRule(name: "show_error_retry_seconds", rule:
        Rule(kind: rkNumber, hasMin: true, min: 1.0, hasMax: true, max: 86400.0)),
      KeyRule(name: "silent_retry_forever", rule:
        Rule(kind: rkBool)),
      KeyRule(name: "silent_window_minutes", rule:
        Rule(kind: rkNumber, hasMin: true, min: 1.0, hasMax: true, max: 10080.0))]),
  profiles: @[
    ProfileSpec(profile: "linux", since: "2026.8.30")]),
  SettingSpec(key: "control_code", rule:
    Rule(kind: rkObject, keys: @[
      KeyRule(name: "enabled", rule:
        Rule(kind: rkBool)),
      KeyRule(name: "position", rule:
        Rule(kind: rkString, strEnum: @["top-left", "top-right", "bottom-left", "bottom-right", "center"])),
      KeyRule(name: "size", rule:
        Rule(kind: rkNumber, hasMin: true, min: 1.0, hasMax: true, max: 50.0)),
      KeyRule(name: "padding", rule:
        Rule(kind: rkInt, hasMin: true, min: 0.0, hasMax: true, max: 50.0)),
      KeyRule(name: "offsetX", rule:
        Rule(kind: rkInt, hasMin: true, min: -4096.0, hasMax: true, max: 4096.0)),
      KeyRule(name: "offsetY", rule:
        Rule(kind: rkInt, hasMin: true, min: -4096.0, hasMax: true, max: 4096.0)),
      KeyRule(name: "qrCodeColor", rule:
        Rule(kind: rkString, format: sfHtmlHexColor)),
      KeyRule(name: "backgroundColor", rule:
        Rule(kind: rkString, format: sfHtmlHexColor))]),
  profiles: @[
    ProfileSpec(profile: "linux", since: "2026.8.30")]),
  SettingSpec(key: "metrics_interval", rule:
    Rule(kind: rkNumber, hasMin: true, min: 0.0, hasMax: true, max: 86400.0),
  profiles: @[
    ProfileSpec(profile: "linux", since: "2026.8.30")]),
  SettingSpec(key: "max_http_response_bytes", rule:
    Rule(kind: rkInt, hasMin: true, min: 65536.0, hasMax: true, max: 67108864.0),
  profiles: @[
    ProfileSpec(profile: "linux", since: "2026.8.30"),
    ProfileSpec(profile: "esp32", since: "2026.8.31", restart: true, hasRule: true, rule:
      Rule(kind: rkInt, hasMin: true, min: 1024.0, hasMax: true, max: 67108864.0))]),
  SettingSpec(key: "save_assets", rule:
    Rule(kind: rkAnyOf, children: @[
      Rule(kind: rkBool),
      Rule(kind: rkMap, keyMinLen: 1, keyMaxLen: 64, children: @[
        Rule(kind: rkBool)])]),
  profiles: @[
    ProfileSpec(profile: "linux", since: "2026.8.30")]),
  SettingSpec(key: "timezone_updater", rule:
    Rule(kind: rkObject, keys: @[
      KeyRule(name: "enabled", rule:
        Rule(kind: rkBool)),
      KeyRule(name: "hour", rule:
        Rule(kind: rkInt, hasMin: true, min: 0.0, hasMax: true, max: 23.0))]),
  profiles: @[
    ProfileSpec(profile: "linux", since: "2026.8.30")]),
  SettingSpec(key: "palette", extraChecks: @["colorNames, when present, has exactly as many entries as colors"], rule:
    Rule(kind: rkObject, required: @["colors"], keys: @[
      KeyRule(name: "name", rule:
        Rule(kind: rkString, maxLen: 64)),
      KeyRule(name: "colors", rule:
        Rule(kind: rkArray, maxItems: 16, children: @[
          Rule(kind: rkString, format: sfHtmlHexColor)])),
      KeyRule(name: "colorNames", rule:
        Rule(kind: rkArray, children: @[
          Rule(kind: rkString, maxLen: 32)]))]),
  profiles: @[
    ProfileSpec(profile: "linux", since: "2026.8.31", restart: true)]),
  SettingSpec(key: "device_config", rule:
    Rule(kind: rkObject, minKeys: 1, keys: @[
      KeyRule(name: "partial", rule:
        Rule(kind: rkBool)),
      KeyRule(name: "partialMaxAreaPercent", rule:
        Rule(kind: rkNumber, hasMin: true, min: 0.0, hasMax: true, max: 100.0)),
      KeyRule(name: "partialMaxRefreshesBeforeFull", rule:
        Rule(kind: rkInt, hasMin: true, min: 0.0, hasMax: true, max: 1000.0))]),
  profiles: @[
    ProfileSpec(profile: "linux", since: "2026.8.31", restart: true)]),
  SettingSpec(key: "gpio_buttons", extraChecks: @["no pin appears twice"], rule:
    Rule(kind: rkArray, maxItems: 16, children: @[
      Rule(kind: rkObject, required: @["pin", "label"], keys: @[
        KeyRule(name: "pin", rule:
          Rule(kind: rkInt, hasMin: true, min: 0.0, hasMax: true, max: 48.0)),
        KeyRule(name: "label", rule:
          Rule(kind: rkString, format: sfGpioLabel))])]),
  profiles: @[
    ProfileSpec(profile: "linux", since: "2026.8.31", restart: true),
    ProfileSpec(profile: "esp32", since: "2026.8.31", restart: true, hasRule: true, rule:
      Rule(kind: rkArray, maxItems: 8, children: @[
        Rule(kind: rkObject, required: @["pin", "label"], keys: @[
          KeyRule(name: "pin", rule:
            Rule(kind: rkInt, hasMin: true, min: 0.0, hasMax: true, max: 48.0)),
          KeyRule(name: "label", rule:
            Rule(kind: rkString, format: sfGpioLabel))])]))]),
  SettingSpec(key: "deep_sleep", rule:
    Rule(kind: rkBool),
  profiles: @[
    ProfileSpec(profile: "esp32")]),
  SettingSpec(key: "deep_sleep_on_battery", rule:
    Rule(kind: rkBool),
  profiles: @[
    ProfileSpec(profile: "esp32")]),
  SettingSpec(key: "wake_check_seconds", rule:
    Rule(kind: rkInt, hasMin: true, min: 0.0, hasMax: true, max: 86400.0),
  profiles: @[
    ProfileSpec(profile: "esp32")]),
  SettingSpec(key: "battery_pin", rule:
    Rule(kind: rkInt, hasMin: true, min: -1.0, hasMax: true, max: 48.0),
  profiles: @[
    ProfileSpec(profile: "esp32", restart: true)]),
  SettingSpec(key: "battery_divider", rule:
    Rule(kind: rkNumber, hasMin: true, min: 0.5, hasMax: true, max: 20.0),
  profiles: @[
    ProfileSpec(profile: "esp32", restart: true)]),
  SettingSpec(key: "battery_enable_pin", rule:
    Rule(kind: rkInt, hasMin: true, min: -1.0, hasMax: true, max: 48.0),
  profiles: @[
    ProfileSpec(profile: "esp32", since: "2026.8.39", restart: true)]),
]

const CloudContractVerbs* = @[
  VerbSpec(verb: "set_scenes", scope: "", content: true),
  VerbSpec(verb: "set_current_scene", scope: "", content: true),
  VerbSpec(verb: "set_settings", scope: "", content: true),
  VerbSpec(verb: "set_schedule", scope: "", content: true),
  VerbSpec(verb: "refresh_service_settings", scope: "settings:services", content: true),
  VerbSpec(verb: "get_state", scope: "", content: false),
  VerbSpec(verb: "get_logs", scope: "telemetry:logs", content: false),
  VerbSpec(verb: "get_metrics", scope: "telemetry:metrics", content: false),
  VerbSpec(verb: "render", scope: "", content: false),
  VerbSpec(verb: "reboot", scope: "", content: false),
  VerbSpec(verb: "restart_runtime", scope: "", content: false),
  VerbSpec(verb: "notify_update_available", scope: "", content: false),
  VerbSpec(verb: "assets_list", scope: "", content: false),
  VerbSpec(verb: "asset_get", scope: "", content: false),
  VerbSpec(verb: "asset_put", scope: "", content: false),
  VerbSpec(verb: "asset_put_chunk", scope: "", content: false),
  VerbSpec(verb: "asset_mkdir", scope: "", content: false),
  VerbSpec(verb: "asset_delete", scope: "", content: false),
  VerbSpec(verb: "asset_rename", scope: "", content: false),
  VerbSpec(verb: "image_get", scope: "", content: false),
]

const CloudContractLimits* = @[
  LimitSpec(name: "assetMaxFileBytes", profile: "linux", value: 8388608),
  LimitSpec(name: "assetMaxFileBytes", profile: "esp32", value: 8388608),
  LimitSpec(name: "assetPutMaxBytes", profile: "linux", value: 2621440),
  LimitSpec(name: "assetPutMaxBytes", profile: "esp32", value: 262144),
  LimitSpec(name: "chunkedUploadMaxBytes", profile: "linux", value: 67108864),
  LimitSpec(name: "chunkedUploadMaxBytes", profile: "esp32", value: 67108864),
  LimitSpec(name: "uploadIdMaxLen", profile: "linux", value: 64),
  LimitSpec(name: "uploadIdMaxLen", profile: "esp32", value: 47),
  LimitSpec(name: "assetListMaxEntries", profile: "linux", value: 5000),
  LimitSpec(name: "assetListMaxEntries", profile: "esp32", value: 2000),
  LimitSpec(name: "getLogsMaxLimit", profile: "linux", value: 1000),
  LimitSpec(name: "getLogsMaxLimit", profile: "esp32", value: 128),
]
