#!/usr/bin/env python3
"""Generate embedded/esp32/main/fos_tz_table.h: IANA zone name -> POSIX TZ rule.

The ESP32 has no tz database, but newlib's localtime()/tzset() understand
POSIX TZ strings ("CET-1CEST,M3.5.0,M10.5.0/3"), and every TZif v2+ file
ends with exactly that string as its footer — the rule that applies from
the last transition onward, i.e. the current one. So the firmware carries
a name -> rule table (~600 zones, rules deduplicated: a few dozen distinct
strings) instead of 400 KB of transitions. Historic dates render with the
current rule; nobody schedules a frame in 1987.

Run from the repo root after a tzdata update on this machine:

    python3 embedded/esp32/tools/gen_tz_table.py

Zone names come from zone1970.tab + backward links (the names users see in
the FrameOS time zone picker, which is built from the same tzdata via
frameos/assets/compiled/tz/timezone_aliases.json).
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "embedded" / "esp32" / "main" / "fos_tz_table.h"
ALIASES = ROOT / "frameos" / "assets" / "compiled" / "tz" / "timezone_aliases.json"
TZDATA = ROOT / "frameos" / "assets" / "compiled" / "tz" / "tzdata.json"

ZONEINFO_DIRS = [
    Path("/usr/share/zoneinfo"),
    Path("/usr/lib/zoneinfo"),
    Path("/var/db/timezone/zoneinfo"),
]


def zoneinfo_dir() -> Path:
    for candidate in ZONEINFO_DIRS:
        if (candidate / "Europe" / "Brussels").exists():
            return candidate
    sys.exit("no zoneinfo directory found; install tzdata")


def tzif_footer(path: Path) -> str | None:
    data = path.read_bytes()
    if data[:4] != b"TZif" or data[4:5] < b"2":
        return None
    # The footer is the last line: "\n<rule>\n".
    tail = data.rstrip(b"\n")
    nl = tail.rfind(b"\n")
    if nl < 0:
        return None
    rule = tail[nl + 1 :].decode("ascii", "replace").strip()
    return rule or None


def zone_names(zdir: Path) -> list[str]:
    names: set[str] = set()
    for tab in ("zone1970.tab", "zone.tab"):
        tab_path = zdir / tab
        if not tab_path.exists():
            continue
        for line in tab_path.read_text(encoding="utf-8").splitlines():
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) >= 3:
                names.add(parts[2])
    if ALIASES.exists():
        aliases = json.loads(ALIASES.read_text(encoding="utf-8"))
        for alias, target in aliases.items():
            names.add(alias)
            names.add(target)
    if TZDATA.exists():
        # The zones the FrameOS picker offers (lib/tz) — every one of them
        # must resolve on the chip too.
        for zone in json.loads(TZDATA.read_text(encoding="utf-8")).get("timezones", []):
            if isinstance(zone, dict) and zone.get("name"):
                names.add(zone["name"])
    names.add("UTC")
    names.add("Etc/UTC")
    return sorted(n for n in names if (zdir / n).is_file())


def main() -> None:
    zdir = zoneinfo_dir()
    rules: dict[str, int] = {}
    rule_list: list[str] = []
    entries: list[tuple[str, int]] = []
    for name in zone_names(zdir):
        rule = tzif_footer(zdir / name)
        if rule is None:
            continue
        if rule not in rules:
            rules[rule] = len(rule_list)
            rule_list.append(rule)
        entries.append((name, rules[rule]))
    entries.sort()

    lines = [
        "/* Generated by embedded/esp32/tools/gen_tz_table.py — do not edit.",
        " * IANA zone name -> POSIX TZ rule (the TZif footer, i.e. the rule in",
        f" * force today). {len(entries)} zones, {len(rule_list)} distinct rules. */",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "    const char *name;",
        "    uint8_t rule;",
        "} fos_tz_entry_t;",
        "",
        f"#define FOS_TZ_RULE_COUNT {len(rule_list)}",
        f"#define FOS_TZ_ENTRY_COUNT {len(entries)}",
        "",
        "static const char *const FOS_TZ_RULES[FOS_TZ_RULE_COUNT] = {",
    ]
    for rule in rule_list:
        lines.append(f'    "{rule}",')
    lines.append("};")
    lines.append("")
    lines.append("/* Sorted by name (strcmp) for binary search. */")
    lines.append("static const fos_tz_entry_t FOS_TZ_ENTRIES[FOS_TZ_ENTRY_COUNT] = {")
    for name, idx in entries:
        lines.append(f'    {{"{name}", {idx}}},')
    lines.append("};")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(entries)} zones, {len(rule_list)} rules, "
          f"{OUT.stat().st_size} bytes of source")


if __name__ == "__main__":
    main()
