import { useValues } from 'kea'
import { frameLogic } from '../../frameLogic'
import { sceneSourceLogic } from './sceneSourceLogic'
import React from 'react'
import { Code } from '../../../../components/Code'
import { Spinner } from '../../../../components/Spinner'

export function SceneSource() {
  const { frame } = useValues(frameLogic)
  const { sceneSource, sceneSourceLoading } = useValues(sceneSourceLogic({ frameId: frame.id }))
  return (
    <div className="space-y-2">
      {sceneSourceLoading ? (
        <Spinner />
      ) : (
        <div className="whitespace-pre bg-black p-2 font-mono text-sm">
          {'# The following code is autogenerated\n'}
          {sceneSource.trimStart()}
        </div>
      )}
    </div>
  )
}
