import { MakeLogicType, actions, connect, kea, key, listeners, path, props, reducers, selectors } from 'kea'
import { v4 as uuidv4 } from 'uuid'

import { ScheduledEvent, ScheduledEventName, StateField, FrameId } from '../../../../types'
import { frameLogic } from '../../frameLogic'
import { isScheduledSystemEvent, ScheduledSystemEventName } from '../../../../utils/scheduleEvents'
import type { FrameType } from '../../../../types'
import type { FrameScene, FrameSchedule } from '../../../../types'

export interface ScheduleLogicProps {
  frameId: FrameId
}

const defaultScheduleMinute = 14 * 60
const scheduleInsertStepMinutes = 30

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface scheduleLogicValues {
  frame: FrameType // frameLogic
  frameForm: Partial<FrameType> // frameLogic
  disabled: boolean
  dropIndex: number | null
  dropZoneVisible: boolean
  editingEvents: Record<string, boolean>
  eventCountsByScene: Record<string, number>
  events: ScheduledEvent[]
  fieldsForScene: Record<string, StateField[]>
  filteredScenes: FrameScene[]
  sceneSearch: string
  scenes: FrameScene[] | undefined
  schedule: FrameSchedule | undefined
  sortedEvents: ScheduledEvent[]
  sortedScenes: FrameScene[]
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface scheduleLogicActions {
  setFrameFormValues: (
    values: import('/Users/marius/Projects/FrameOS/frameos/node_modules/.pnpm/kea-forms@3.2.0_kea@3.1.7_react@19.2.8__typescript@5.9.3/node_modules/kea-forms/lib/types').DeepPartial<FrameType>
  ) => {
    values: import('/Users/marius/Projects/FrameOS/frameos/node_modules/.pnpm/kea-forms@3.2.0_kea@3.1.7_react@19.2.8__typescript@5.9.3/node_modules/kea-forms/lib/types').DeepPartial<FrameType>
  } // frameLogic
  addEventForScene: (
    sceneId: string,
    insertIndex?: number | null
  ) => {
    event: ScheduledEvent
    insertIndex: number | null | undefined
  }
  addSystemEvent: (systemEvent: ScheduledSystemEventName) => {
    event: ScheduledEvent
  }
  closeEvent: (id: string) => {
    id: string
  }
  deleteEvent: (id: string) => {
    id: string
  }
  editEvent: (id: string) => {
    id: string
  }
  hideDropZone: () => {
    value: true
  }
  setDropIndex: (dropIndex: number | null) => {
    dropIndex: number | null
  }
  setEventType: (
    id: string,
    eventType: ScheduledEventName
  ) => {
    eventType: ScheduledEventName
    id: string
  }
  setSceneSearch: (sceneSearch: string) => {
    sceneSearch: string
  }
  showDropZone: () => {
    value: true
  }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface scheduleLogicMeta {
  key: FrameId
  __keaTypeGenInternalSelectorTypes: {
    schedule: (frameForm: Partial<FrameType>, frame: FrameType) => FrameSchedule | undefined
    events: (schedule: FrameSchedule | undefined) => ScheduledEvent[]
    disabled: (schedule: FrameSchedule | undefined) => boolean
    scenes: (frame: FrameType, frameForm: Partial<FrameType>) => FrameScene[] | undefined
    sortedScenes: (scenes: FrameScene[] | undefined) => FrameScene[]
    filteredScenes: (sortedScenes: FrameScene[], sceneSearch: string) => FrameScene[]
    fieldsForScene: (frame: FrameType, frameForm: Partial<FrameType>) => Record<string, StateField[]>
    eventCountsByScene: (events: ScheduledEvent[]) => Record<string, number>
    sortedEvents: (events: ScheduledEvent[]) => ScheduledEvent[]
  }
}

export type scheduleLogicType = MakeLogicType<scheduleLogicValues, scheduleLogicActions, ScheduleLogicProps> &
  scheduleLogicMeta

export const scheduleLogic = kea<scheduleLogicType>([
  path(['src', 'scenes', 'frame', 'panels', 'Schedule', 'scheduleLogic']),
  props({} as ScheduleLogicProps),
  key((props) => props.frameId),

  connect(({ frameId }: ScheduleLogicProps) => ({
    values: [frameLogic({ frameId }), ['frame', 'frameForm']],
    actions: [frameLogic({ frameId }), ['setFrameFormValues']],
  })),

  actions({
    setSceneSearch: (sceneSearch: string) => ({ sceneSearch }),
    addEventForScene: (sceneId: string, insertIndex?: number | null) => ({
      event: newScheduledEvent(sceneId),
      insertIndex,
    }),
    /** A restart / reboot entry: no scene, no state — see utils/scheduleEvents.ts. */
    addSystemEvent: (systemEvent: ScheduledSystemEventName) => ({
      event: newSystemScheduledEvent(systemEvent),
    }),
    /** Switch an existing entry between showing a scene and a system action. */
    setEventType: (id: string, eventType: ScheduledEventName) => ({ id, eventType }),
    editEvent: (id: string) => ({ id }),
    closeEvent: (id: string) => ({ id }),
    deleteEvent: (id: string) => ({ id }),
    showDropZone: true,
    hideDropZone: true,
    setDropIndex: (dropIndex: number | null) => ({ dropIndex }),
  }),

  reducers({
    dropIndex: [
      null as number | null,
      {
        setDropIndex: (_, { dropIndex }) => dropIndex,
        hideDropZone: () => null,
        addEventForScene: () => null,
        addSystemEvent: () => null,
      },
    ],
    dropZoneVisible: [
      false,
      {
        showDropZone: () => true,
        hideDropZone: () => false,
        addEventForScene: () => false,
        addSystemEvent: () => false,
      },
    ],
    sceneSearch: [
      '',
      {
        setSceneSearch: (_, { sceneSearch }) => sceneSearch,
      },
    ],
    editingEvents: [
      {} as Record<string, boolean>,
      {
        addEventForScene: (state, { event, insertIndex }) =>
          insertIndex === undefined || insertIndex === null ? { ...state, [event.id]: true } : state,
        addSystemEvent: (state, { event }) => ({ ...state, [event.id]: true }),
        editEvent: (state, { id }) => ({ ...state, [id]: true }),
        closeEvent: (state, { id }) => {
          const { [id]: _, ...rest } = state
          return rest
        },
        deleteEvent: (state, { id }) => {
          const { [id]: _, ...rest } = state
          return rest
        },
      },
    ],
  }),

  selectors({
    schedule: [
      (s) => [s.frameForm, s.frame],
      (frameForm: scheduleLogicValues['frameForm'], frame: scheduleLogicValues['frame']) =>
        frameForm.schedule ?? frame.schedule,
    ],
    events: [(s) => [s.schedule], (schedule: scheduleLogicValues['schedule']) => schedule?.events ?? []],
    disabled: [(s) => [s.schedule], (schedule: scheduleLogicValues['schedule']) => schedule?.disabled ?? false],
    scenes: [
      (s) => [s.frame, s.frameForm],
      (frame: scheduleLogicValues['frame'], frameForm: scheduleLogicValues['frameForm']) =>
        frameForm.scenes ?? frame.scenes,
    ],
    sortedScenes: [
      (s) => [s.scenes],
      (scenes: scheduleLogicValues['scenes']) =>
        [...(scenes ?? [])].toSorted((a, b) => (a.name || a.id).localeCompare(b.name || b.id)),
    ],
    filteredScenes: [
      (s) => [s.sortedScenes, s.sceneSearch],
      (sortedScenes: scheduleLogicValues['sortedScenes'], sceneSearch: scheduleLogicValues['sceneSearch']) => {
        const normalizedSearch = sceneSearch.trim().toLowerCase()
        if (!normalizedSearch) {
          return sortedScenes
        }
        return sortedScenes.filter((scene) =>
          [scene.name, scene.id, ...(scene.nodes ?? []).map((node) => `${node.type} ${node.id}`)]
            .join(' ')
            .toLowerCase()
            .includes(normalizedSearch)
        )
      },
    ],
    fieldsForScene: [
      (s) => [s.frame, s.frameForm],
      (
        frame: scheduleLogicValues['frame'],
        frameForm: scheduleLogicValues['frameForm']
      ): Record<string, StateField[]> =>
        (frameForm?.scenes ?? frame.scenes ?? []).reduce((acc, scene) => {
          acc[scene.id] = scene.fields ?? []
          return acc
        }, {} as Record<string, StateField[]>),
    ],
    eventCountsByScene: [
      (s) => [s.events],
      (events: scheduleLogicValues['events']): Record<string, number> =>
        events.reduce((acc, event) => {
          const sceneId = isScheduledSystemEvent(event.event) ? null : event.payload?.sceneId
          if (sceneId) {
            acc[sceneId] = (acc[sceneId] ?? 0) + 1
          }
          return acc
        }, {} as Record<string, number>),
    ],
    sortedEvents: [
      (s) => [s.events],
      (events: scheduleLogicValues['events']) =>
        [...events].sort((a, b) => (a.hour === b.hour ? a.minute - b.minute : a.hour - b.hour)),
    ],
  }),

  listeners(({ actions, values }) => ({
    addEventForScene: ({ event, insertIndex }) => {
      const effectiveInsertIndex = eventInsertIndex(values.sortedEvents, insertIndex)
      const nextEvent = configureEventForInsert(event, values.sortedEvents, effectiveInsertIndex)
      actions.setFrameFormValues({
        ...values.frameForm,
        schedule: {
          ...values.schedule,
          events: insertEvent(values.events, values.sortedEvents, nextEvent, effectiveInsertIndex),
        },
      })
    },
    addSystemEvent: ({ event }) => {
      // Keeps its own 04:00 default rather than slotting in next to the last
      // scene change: a maintenance entry is about the hour, not the order,
      // and the row opens for editing so the time is the first thing seen.
      actions.setFrameFormValues({
        ...values.frameForm,
        schedule: { ...values.schedule, events: [...values.events, event] },
      })
    },
    setEventType: ({ id, eventType }) => {
      actions.setFrameFormValues({
        ...values.frameForm,
        schedule: {
          ...values.schedule,
          events: values.events.map((event) => (event.id === id ? withEventType(event, eventType) : event)),
        },
      })
    },
    deleteEvent: ({ id }) => {
      actions.setFrameFormValues({
        ...values.frameForm,
        schedule: { ...values.schedule, events: values.events.filter((event) => event.id !== id) },
      })
    },
  })),
])

function eventMinute(event: Pick<ScheduledEvent, 'hour' | 'minute'>): number {
  return Math.max(0, Math.min(1439, event.hour * 60 + event.minute))
}

function minuteConfig(totalMinutes: number): Pick<ScheduledEvent, 'hour' | 'minute'> {
  const boundedMinutes = Math.max(0, Math.min(1439, Math.round(totalMinutes)))
  return {
    hour: Math.floor(boundedMinutes / 60),
    minute: boundedMinutes % 60,
  }
}

function insertedWeekday(before: ScheduledEvent | undefined, after: ScheduledEvent | undefined): number {
  if (before && after && before.weekday === after.weekday) {
    return before.weekday
  }
  return before?.weekday ?? after?.weekday ?? 0
}

function insertedMinute(before: ScheduledEvent | undefined, after: ScheduledEvent | undefined): number {
  if (before && after) {
    const beforeMinute = eventMinute(before)
    const afterMinute = eventMinute(after)
    if (afterMinute > beforeMinute + 1) {
      return Math.floor((beforeMinute + afterMinute) / 2)
    }
    return beforeMinute
  }
  if (before) {
    return Math.min(1439, eventMinute(before) + scheduleInsertStepMinutes)
  }
  if (after) {
    return Math.max(0, eventMinute(after) - scheduleInsertStepMinutes)
  }
  return defaultScheduleMinute
}

function eventInsertIndex(sortedEvents: ScheduledEvent[], insertIndex?: number | null): number {
  if (insertIndex === undefined || insertIndex === null) {
    return sortedEvents.length
  }
  return Math.max(0, Math.min(sortedEvents.length, insertIndex))
}

function configureEventForInsert(
  event: ScheduledEvent,
  sortedEvents: ScheduledEvent[],
  insertIndex: number
): ScheduledEvent {
  const before = sortedEvents[insertIndex - 1]
  const after = sortedEvents[insertIndex]
  const time = minuteConfig(insertedMinute(before, after))

  return {
    ...event,
    ...time,
    weekday: insertedWeekday(before, after),
  }
}

function insertEvent(
  events: ScheduledEvent[],
  sortedEvents: ScheduledEvent[],
  event: ScheduledEvent,
  insertIndex?: number | null
): ScheduledEvent[] {
  if (insertIndex === undefined || insertIndex === null) {
    return [...events, event]
  }

  const before = sortedEvents[insertIndex - 1]
  const after = sortedEvents[insertIndex]
  const eventTime = eventMinute(event)
  const beforeTime = before ? eventMinute(before) : null
  const nextEvents = [...events]
  const targetId = before && beforeTime !== null && eventTime <= beforeTime ? before.id : after?.id
  const targetIndex = targetId ? nextEvents.findIndex((candidate) => candidate.id === targetId) : -1

  if (targetIndex === -1) {
    nextEvents.push(event)
  } else if (before && targetId === before.id) {
    nextEvents.splice(targetIndex + 1, 0, event)
  } else {
    nextEvents.splice(targetIndex, 0, event)
  }

  return nextEvents
}

function newScheduledEvent(sceneId = ''): ScheduledEvent {
  return {
    id: uuidv4(),
    hour: 14,
    minute: 0,
    weekday: 0,
    event: 'setCurrentScene',
    payload: { sceneId, state: {} },
  }
}

function newSystemScheduledEvent(systemEvent: ScheduledSystemEventName): ScheduledEvent {
  // 04:00 — the hour a nightly restart is least likely to be noticed; the
  // cron the self-hosted backend installs for the same job defaults there too.
  return {
    id: uuidv4(),
    hour: 4,
    minute: 0,
    weekday: 0,
    event: systemEvent,
    payload: {},
  }
}

/** Keep id/time/enabled, swap what the entry does. A system action carries no payload. */
export function withEventType(event: ScheduledEvent, eventType: ScheduledEventName): ScheduledEvent {
  if (event.event === eventType) {
    return event
  }
  if (isScheduledSystemEvent(eventType)) {
    return { ...event, event: eventType, payload: {} }
  }
  return {
    ...event,
    event: eventType,
    payload: { sceneId: event.payload?.sceneId ?? '', state: event.payload?.state ?? {} },
  }
}
