import {
  MakeLogicType,
  actions,
  beforeUnmount,
  BuiltLogic,
  connect,
  kea,
  key,
  listeners,
  path,
  props,
  reducers,
  selectors,
} from 'kea'
import { AppNodeData, FrameId } from '../../types'

import { frameLogic } from './frameLogic'
import { sceneExecutionForFrame } from '../../utils/sceneExecution'
import type { FrameType } from '../../types'

// Tracks what is being edited in a frame's workspace: which editors (scene
// diagram, scene JSON, app source) are open, which one is active, and the
// last selected scene. chatLogic derives its chat context from this and
// diagramLogic uses it to scope global keyboard shortcuts to the visible
// scene. (This replaced the old four-area "panels" layout logic.)
export interface FrameEditorsLogicProps {
  frameId: FrameId
}

export interface AnyBuiltLogic extends BuiltLogic {}

export type FrameEditorKind = 'diagram' | 'sceneJSON' | 'editApp'

export interface FrameEditor {
  kind: FrameEditorKind
  key: string
  sceneId: string
  nodeId?: string
  nodeData?: AppNodeData
  title?: string
}

export function diagramEditorKey(sceneId: string): string {
  return `diagram:${sceneId}`
}

export function sceneJSONEditorKey(sceneId: string): string {
  return `sceneJSON:${sceneId}`
}

export function editAppEditorKey(sceneId: string, nodeId: string): string {
  return `editApp:${sceneId}.${nodeId}`
}

function upsertEditor(editors: FrameEditor[], editor: FrameEditor): FrameEditor[] {
  return editors.find((e) => e.key === editor.key)
    ? editors.map((e) => (e.key === editor.key ? editor : e))
    : [...editors, editor]
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface frameEditorsLogicValues {
  frameForm: Partial<FrameType> // frameLogic
  activeEditApp: FrameEditor | null
  activeEditor: FrameEditor | null
  activeEditorKey: string | null
  activeSceneEditorId: string | null
  lastSelectedScene: string | null
  openEditors: FrameEditor[]
  scenesOpen: boolean
  selectedSceneId: string | null
  selectedSceneIsInterpreted: boolean
  selectedSceneName: string | null
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface frameEditorsLogicActions {
  closeEditor: (editorKey: string) => {
    editorKey: string
  }
  closeSceneEditors: (sceneIds: string[]) => {
    sceneIds: string[]
  }
  editApp: (
    sceneId: string,
    nodeId: string,
    nodeData: AppNodeData
  ) => {
    nodeData: AppNodeData
    nodeId: string
    sceneId: string
  }
  editScene: (sceneId: string) => {
    sceneId: string
  }
  editSceneJSON: (sceneId: string) => {
    sceneId: string
  }
  persistUntilClosed: (
    editorKey: string,
    logic: AnyBuiltLogic
  ) => {
    editorKey: string
    logic: AnyBuiltLogic
  }
  selectScene: (sceneId: string) => {
    sceneId: string
  }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface frameEditorsLogicMeta {
  key: FrameId
  __keaTypeGenInternalSelectorTypes: {
    activeEditor: (openEditors: FrameEditor[], activeEditorKey: string | null) => FrameEditor | null
    scenesOpen: (activeEditor: FrameEditor | null) => boolean
    activeSceneEditorId: (activeEditor: FrameEditor | null) => string | null
    activeEditApp: (activeEditor: FrameEditor | null) => FrameEditor | null
    selectedSceneId: (
      frameForm: Partial<FrameType>,
      lastSelectedScene: string | null,
      activeSceneEditorId: string | null
    ) => string | null
    selectedSceneName: (frameForm: Partial<FrameType>, selectedSceneId: string | null) => string | null
    selectedSceneIsInterpreted: (frameForm: Partial<FrameType>, selectedSceneId: string | null) => boolean
  }
}

export type frameEditorsLogicType = MakeLogicType<
  frameEditorsLogicValues,
  frameEditorsLogicActions,
  FrameEditorsLogicProps
> &
  frameEditorsLogicMeta

/** The editor logics each mounted workspace keeps alive, by editor key —
 * module state keyed by logic path rather than `cache`, because under
 * StrictMode / Fast Refresh kea can run afterMount on one built object and
 * beforeUnmount on another for the same path (see diagramLogic). */
const persistedEditors = new Map<string, Map<string, () => void>>()

function unmountPersistedEditors(pathString: string, matches: (editorKey: string) => boolean): void {
  const persisted = persistedEditors.get(pathString)
  if (!persisted) {
    return
  }
  for (const [editorKey, unmount] of Array.from(persisted.entries())) {
    if (matches(editorKey)) {
      persisted.delete(editorKey)
      unmount()
    }
  }
  if (persisted.size === 0) {
    persistedEditors.delete(pathString)
  }
}

export const frameEditorsLogic = kea<frameEditorsLogicType>([
  path(['src', 'scenes', 'frame', 'frameEditorsLogic']),
  props({} as FrameEditorsLogicProps),
  key((props) => props.frameId),
  connect((props: FrameEditorsLogicProps) => ({
    values: [frameLogic(props), ['frameForm']],
  })),
  actions({
    selectScene: (sceneId: string) => ({ sceneId }),
    editScene: (sceneId: string) => ({ sceneId }),
    editSceneJSON: (sceneId: string) => ({ sceneId }),
    editApp: (sceneId: string, nodeId: string, nodeData: AppNodeData) => ({ sceneId, nodeId, nodeData }),
    closeEditor: (editorKey: string) => ({ editorKey }),
    closeSceneEditors: (sceneIds: string[]) => ({ sceneIds }),
    persistUntilClosed: (editorKey: string, logic: AnyBuiltLogic) => ({ editorKey, logic }),
  }),
  reducers({
    openEditors: [
      [] as FrameEditor[],
      {
        editScene: (state, { sceneId }) =>
          upsertEditor(state, { kind: 'diagram', key: diagramEditorKey(sceneId), sceneId }),
        editSceneJSON: (state, { sceneId }) =>
          upsertEditor(state, { kind: 'sceneJSON', key: sceneJSONEditorKey(sceneId), sceneId }),
        editApp: (state, { sceneId, nodeId, nodeData }) =>
          upsertEditor(state, {
            kind: 'editApp',
            key: editAppEditorKey(sceneId, nodeId),
            sceneId,
            nodeId,
            nodeData,
            title: nodeData.name || nodeData.keyword || nodeId,
          }),
        closeEditor: (state, { editorKey }) => state.filter((editor) => editor.key !== editorKey),
        closeSceneEditors: (state, { sceneIds }) => state.filter((editor) => !sceneIds.includes(editor.sceneId)),
      },
    ],
    activeEditorKey: [
      null as string | null,
      {
        editScene: (_, { sceneId }) => diagramEditorKey(sceneId),
        editSceneJSON: (_, { sceneId }) => sceneJSONEditorKey(sceneId),
        editApp: (_, { sceneId, nodeId }) => editAppEditorKey(sceneId, nodeId),
        closeEditor: (state, { editorKey }) => (state === editorKey ? null : state),
      },
    ],
    lastSelectedScene: [
      null as string | null,
      {
        selectScene: (_, { sceneId }) => sceneId,
        editScene: (_, { sceneId }) => sceneId,
        editSceneJSON: (_, { sceneId }) => sceneId,
      },
    ],
  }),
  selectors(() => ({
    activeEditor: [
      (s) => [s.openEditors, s.activeEditorKey],
      (
        openEditors: frameEditorsLogicValues['openEditors'],
        activeEditorKey: frameEditorsLogicValues['activeEditorKey']
      ): FrameEditor | null =>
        activeEditorKey ? openEditors.find((editor) => editor.key === activeEditorKey) ?? null : null,
    ],
    scenesOpen: [
      (s) => [s.activeEditor],
      (activeEditor: frameEditorsLogicValues['activeEditor']): boolean => !activeEditor,
    ],
    activeSceneEditorId: [
      (s) => [s.activeEditor],
      (activeEditor: frameEditorsLogicValues['activeEditor']): string | null =>
        activeEditor && (activeEditor.kind === 'diagram' || activeEditor.kind === 'sceneJSON')
          ? activeEditor.sceneId
          : null,
    ],
    activeEditApp: [
      (s) => [s.activeEditor],
      (activeEditor: frameEditorsLogicValues['activeEditor']): FrameEditor | null =>
        activeEditor?.kind === 'editApp' ? activeEditor : null,
    ],
    selectedSceneId: [
      (s) => [s.frameForm, s.lastSelectedScene, s.activeSceneEditorId],
      (
        frameForm: frameEditorsLogicValues['frameForm'],
        lastSelectedScene: frameEditorsLogicValues['lastSelectedScene'],
        activeSceneEditorId: frameEditorsLogicValues['activeSceneEditorId']
      ): string | null =>
        lastSelectedScene ??
        activeSceneEditorId ??
        frameForm?.scenes?.find((s) => s.default)?.id ??
        frameForm?.scenes?.[0]?.id ??
        null,
    ],
    selectedSceneName: [
      (s) => [s.frameForm, s.selectedSceneId],
      (
        frameForm: frameEditorsLogicValues['frameForm'],
        selectedSceneId: frameEditorsLogicValues['selectedSceneId']
      ): string | null =>
        selectedSceneId ? frameForm?.scenes?.find((s) => s.id === selectedSceneId)?.name ?? null : null,
    ],
    selectedSceneIsInterpreted: [
      (s) => [s.frameForm, s.selectedSceneId],
      (
        frameForm: frameEditorsLogicValues['frameForm'],
        selectedSceneId: frameEditorsLogicValues['selectedSceneId']
      ): boolean =>
        !!selectedSceneId &&
        sceneExecutionForFrame(
          frameForm?.scenes?.find((scene) => scene.id === selectedSceneId),
          frameForm?.mode
        ) === 'interpreted',
    ],
  })),
  listeners(({ pathString }) => ({
    persistUntilClosed: ({ editorKey, logic }) => {
      const persisted = persistedEditors.get(pathString) ?? new Map<string, () => void>()
      if (!persisted.has(editorKey)) {
        persisted.set(editorKey, logic.mount())
        persistedEditors.set(pathString, persisted)
      }
    },
    closeEditor: ({ editorKey }) => {
      unmountPersistedEditors(pathString, (key) => key === editorKey)
    },
    closeSceneEditors: ({ sceneIds }) => {
      unmountPersistedEditors(pathString, (editorKey) =>
        sceneIds.some(
          (sceneId) =>
            editorKey === diagramEditorKey(sceneId) ||
            editorKey === sceneJSONEditorKey(sceneId) ||
            editorKey.startsWith(`editApp:${sceneId}.`)
        )
      )
    },
  })),
  // Leaving the workspace (another frame, the dashboard) unmounts this logic
  // but nothing closes the editors: every diagram/app/JSON logic they kept
  // mounted, and through kea's connect the whole frameLogic behind them, used
  // to live on until the page reloaded.
  beforeUnmount(({ pathString }) => {
    unmountPersistedEditors(pathString, () => true)
  }),
])
