// Generated by frameos/tools/generate_events_contract.py from docs/events-contract.json — do not edit.

/** Both pointer axes on the wire: 0..POINTER_WIRE_MAX across the picture. */
export const POINTER_WIRE_MAX = 32767

/** Lifecycle events and scene commands: the host sends these, a button would not. */
export const HOST_EVENT_NAMES: readonly string[] = ["init", "render", "open", "close", "turnOn", "turnOff", "setSceneState", "setCurrentScene"]

/** Pointer input: sent by the canvas with a position, never by a button. */
export const POINTER_EVENT_NAMES: readonly string[] = ["pointerMove", "pointerDown", "pointerUp", "pointerCancel", "mouseMove", "mouseDown", "mouseUp", "tap", "doubleTap", "longPress", "swipe", "wheel"]

/** Keyboard input: sent by the focused canvas, never by a button. */
export const KEYBOARD_EVENT_NAMES: readonly string[] = ["keyDown", "keyUp", "textInput"]
