## Generated by tools/sign_firmware.py nim-const — the runtime refuses
## release archives not signed by this key. Regenerate after a key
## rotation, together with embedded/esp32/main/fos_ota_pubkey.h: a
## device that trusts a retired key is the whole point of having one.

const
  OtaSigningPublicKeyBase64* = "0LvFbK8ePu0fSujVkabbyzo0gEppxSV3qhyBHQfaoMw="
  OtaSigningKeyIdHex* = "27c4c7f5df300370"
