// Generated by frameos/tools/generate_cloud_contract.py from docs/cloud-frames-contract.json — do not edit.
// The keys a cloud-managed frame accepts over set_settings, per profile:
// `since` is the first firmware version that knows the key (null = every
// version), `restart` means applying it restarts the runtime / reboots the
// chip, `companion` keys ride only next to another key. Rules live on the
// cloud (cloud-frames-contract.gen.ts) and the devices; the SPA only
// decides what to offer and send.

export const cloudFramesContractSettings = {
  "linux": {
    "name": {
      "since": null
    },
    "rotate": {
      "since": null
    },
    "interval": {
      "since": null
    },
    "scaling_mode": {
      "since": null
    },
    "timezone": {
      "since": null
    },
    "debug": {
      "since": null
    },
    "flip": {
      "since": "2026.8.30"
    },
    "error_behavior": {
      "since": "2026.8.30"
    },
    "control_code": {
      "since": "2026.8.30"
    },
    "metrics_interval": {
      "since": "2026.8.30"
    },
    "max_http_response_bytes": {
      "since": "2026.8.30"
    },
    "save_assets": {
      "since": "2026.8.30"
    },
    "timezone_updater": {
      "since": "2026.8.30"
    },
    "palette": {
      "since": "2026.8.31",
      "restart": true
    },
    "device_config": {
      "since": "2026.8.31",
      "restart": true
    },
    "gpio_buttons": {
      "since": "2026.8.31",
      "restart": true
    }
  },
  "esp32": {
    "name": {
      "since": null
    },
    "rotate": {
      "since": null,
      "restart": true
    },
    "interval": {
      "since": null
    },
    "scaling_mode": {
      "since": null
    },
    "timezone": {
      "since": "2026.8.34"
    },
    "timezone_data": {
      "since": "2026.8.34",
      "companion": "timezone"
    },
    "debug": {
      "since": "2026.8.31"
    },
    "max_http_response_bytes": {
      "since": "2026.8.31",
      "restart": true
    },
    "gpio_buttons": {
      "since": "2026.8.31",
      "restart": true
    },
    "deep_sleep": {
      "since": null
    },
    "deep_sleep_on_battery": {
      "since": null
    },
    "wake_check_seconds": {
      "since": null
    },
    "battery_pin": {
      "since": null,
      "restart": true
    },
    "battery_divider": {
      "since": null,
      "restart": true
    },
    "battery_enable_pin": {
      "since": "2026.8.39",
      "restart": true
    }
  }
} as const

export type CloudFramesContractProfile = keyof typeof cloudFramesContractSettings
