import { MakeLogicType, actions, kea, listeners, path, reducers } from 'kea'

// One confirmation dialog for the whole app (ConfirmDialog, mounted by both
// App roots). `confirmDialog()` parks its request here and awaits the answer;
// the dialog answers through the actions below. Without a mounted host (an
// embed that never mounted the dialog, a unit test) it falls back to
// `window.confirm`, which is what every caller did before this existed — so
// the flows that go through it (deletes, resets, disconnects) never lose
// their guard, they only lose the blocking browser prompt where a host is up.

export interface ConfirmDialogRequest {
  /** Heading; defaults to a generic "Are you sure?". */
  title?: string
  /** Body text. Blank lines split paragraphs. */
  message: string
  /** Defaults to "Confirm". */
  confirmLabel?: string
  /** Defaults to "Cancel". */
  cancelLabel?: string
  /** Renders the confirm button in the danger colour and focuses Cancel. */
  danger?: boolean
  /**
   * The work a confirmation starts. The dialog stays up while it runs — the
   * confirm button spinning, Cancel and the close button disabled — and closes
   * when it settles, so a slow action (a push to a frame) never looks like a
   * click that did nothing. `confirmDialog()` resolves true afterwards; the
   * work reports its own failures. The `window.confirm` fallback awaits it too.
   */
  onConfirm?: () => Promise<void> | void
  /** The confirm button's label while `onConfirm` runs. Defaults to `confirmLabel`. */
  busyLabel?: string
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface confirmDialogLogicValues {
  busy: boolean
  hosts: number
  pending: ConfirmDialogRequest | null
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface confirmDialogLogicActions {
  answer: (confirmed: boolean) => {
    confirmed: boolean
  }
  confirm: () => {
    value: true
  }
  hostMounted: () => {
    value: true
  }
  hostUnmounted: () => {
    value: true
  }
  open: (request: ConfirmDialogRequest) => {
    request: ConfirmDialogRequest
  }
}

export type confirmDialogLogicType = MakeLogicType<confirmDialogLogicValues, confirmDialogLogicActions>

type Resolver = (confirmed: boolean) => void
let resolver: Resolver | null = null

export const confirmDialogLogic = kea<confirmDialogLogicType>([
  path(['src', 'utils', 'confirmDialogLogic']),
  actions({
    open: (request: ConfirmDialogRequest) => ({ request }),
    answer: (confirmed: boolean) => ({ confirmed }),
    /** The confirm button: runs the request's `onConfirm`, if any, then answers yes. */
    confirm: true,
    hostMounted: true,
    hostUnmounted: true,
  }),
  reducers({
    pending: [
      null as ConfirmDialogRequest | null,
      {
        open: (_, { request }) => request,
        answer: () => null,
      },
    ],
    busy: [
      false,
      {
        confirm: () => true,
        open: () => false,
        answer: () => false,
      },
    ],
    hosts: [
      0,
      {
        hostMounted: (state) => state + 1,
        hostUnmounted: (state) => Math.max(0, state - 1),
      },
    ],
  }),
  listeners(({ actions, values }) => ({
    confirm: async () => {
      const request = values.pending
      if (!request) {
        return
      }
      try {
        await request.onConfirm?.()
      } catch (error) {
        console.error(error)
      }
      // A newer request may have displaced this one while it worked; that
      // one's answer is not ours to give.
      if (values.pending === request) {
        actions.answer(true)
      }
    },
    answer: ({ confirmed }) => {
      const resolve = resolver
      resolver = null
      resolve?.(confirmed)
    },
  })),
])

function toRequest(request: ConfirmDialogRequest | string): ConfirmDialogRequest {
  return typeof request === 'string' ? { message: request } : request
}

/**
 * Ask the user to confirm. Resolves true on confirm, false on cancel or
 * dismiss. A second request while one is open cancels the first.
 */
export function confirmDialog(request: ConfirmDialogRequest | string): Promise<boolean> {
  const normalized = toRequest(request)
  const logic = confirmDialogLogic.findMounted() ?? confirmDialogLogic
  if (!logic.isMounted() || logic.values.hosts === 0) {
    if (!window.confirm(normalized.message)) {
      return Promise.resolve(false)
    }
    return Promise.resolve(normalized.onConfirm?.())
      .catch((error) => console.error(error))
      .then(() => true)
  }
  resolver?.(false)
  return new Promise<boolean>((resolve) => {
    resolver = resolve
    logic.actions.open(normalized)
  })
}
