// Generated by frameos/tools/generate_events_contract.py from docs/events-contract.json — do not edit.
//
// The helpers that read these tables are in eventsContract.ts.

export const EVENTS_CONTRACT_VERSION = 1
export const POINTER_WIRE_MAX = 32767
export const CUSTOM_EVENT_MAX_NAME_LENGTH = 63

export type EventOrigin = 'driver' | 'preview' | 'scene' | 'schedule' | 'http:write' | 'http:admin' | 'cloud' | 'system'
export type EventClass = 'lifecycle' | 'input' | 'scene-command' | 'device-command'
export type EventDevice = 'keyboard' | 'pointer' | 'button'
export type EventRenderAfter = 'never' | 'always' | 'if-state-changed'
export type EventCoalesce = 'none' | 'latest'
export type EventLogPolicy = 'full' | 'name-only' | 'none'
export type ContractEventName =
  | 'init'
  | 'render'
  | 'open'
  | 'close'
  | 'keyDown'
  | 'keyUp'
  | 'mouseMove'
  | 'mouseDown'
  | 'mouseUp'
  | 'wheel'
  | 'turnOn'
  | 'turnOff'
  | 'button'
  | 'setSceneState'
  | 'setCurrentScene'
  | 'metrics'
  | 'reload'
  | 'restart'
  | 'reboot'
  | 'uploadScenes'

export interface ContractEventSpec {
  class: EventClass
  device?: EventDevice
  listen: boolean
  dispatch: boolean
  /** 'read': an event node offers the scene's state; 'payload': the payload IS the scene's state fields. */
  sceneState?: 'read' | 'payload'
  origins: EventOrigin[]
  renderAfter: EventRenderAfter
  coalesce: EventCoalesce
  log: EventLogPolicy
  hosts: { linux: boolean; esp32: boolean; wasm: boolean }
  since?: string
  /** Offered by the Schedule panel. `endsRuntime`: the runtime does not survive it. */
  schedule?: { label: string; description?: string; since?: string; endsRuntime?: boolean }
  cloud?: {
    verb: string
    profiles?: string[]
    eventRoute?: boolean
    since?: string
    before?: { verb: string; profiles?: string[] }
  }
}

export const contractEventSpecs: Record<ContractEventName, ContractEventSpec> = {
  "init": {
    "class": "lifecycle",
    "listen": true,
    "dispatch": false,
    "sceneState": "read",
    "origins": [
      "system",
      "http:admin"
    ],
    "renderAfter": "if-state-changed",
    "coalesce": "none",
    "log": "full",
    "hosts": {
      "linux": true,
      "esp32": true,
      "wasm": true
    },
    "since": "2026.9.21"
  },
  "render": {
    "class": "lifecycle",
    "listen": true,
    "dispatch": true,
    "sceneState": "read",
    "origins": [
      "system",
      "driver",
      "preview",
      "scene",
      "schedule",
      "http:write",
      "http:admin",
      "cloud"
    ],
    "renderAfter": "always",
    "coalesce": "none",
    "log": "full",
    "hosts": {
      "linux": true,
      "esp32": true,
      "wasm": true
    },
    "cloud": {
      "verb": "render"
    }
  },
  "open": {
    "class": "lifecycle",
    "listen": true,
    "dispatch": false,
    "origins": [
      "system",
      "http:admin"
    ],
    "renderAfter": "if-state-changed",
    "coalesce": "none",
    "log": "full",
    "hosts": {
      "linux": true,
      "esp32": true,
      "wasm": true
    },
    "since": "2026.9.21"
  },
  "close": {
    "class": "lifecycle",
    "listen": true,
    "dispatch": false,
    "origins": [
      "system",
      "http:admin"
    ],
    "renderAfter": "never",
    "coalesce": "none",
    "log": "full",
    "hosts": {
      "linux": true,
      "esp32": true,
      "wasm": true
    },
    "since": "2026.9.21"
  },
  "keyDown": {
    "class": "input",
    "device": "keyboard",
    "listen": true,
    "dispatch": false,
    "origins": [
      "driver",
      "scene",
      "schedule",
      "http:write",
      "http:admin",
      "system"
    ],
    "renderAfter": "if-state-changed",
    "coalesce": "none",
    "log": "name-only",
    "hosts": {
      "linux": true,
      "esp32": false,
      "wasm": false
    }
  },
  "keyUp": {
    "class": "input",
    "device": "keyboard",
    "listen": true,
    "dispatch": false,
    "origins": [
      "driver",
      "scene",
      "schedule",
      "http:write",
      "http:admin",
      "system"
    ],
    "renderAfter": "if-state-changed",
    "coalesce": "none",
    "log": "name-only",
    "hosts": {
      "linux": true,
      "esp32": false,
      "wasm": false
    }
  },
  "mouseMove": {
    "class": "input",
    "device": "pointer",
    "listen": true,
    "dispatch": false,
    "origins": [
      "driver",
      "preview",
      "scene",
      "schedule",
      "http:write",
      "http:admin",
      "system"
    ],
    "renderAfter": "never",
    "coalesce": "latest",
    "log": "none",
    "hosts": {
      "linux": true,
      "esp32": false,
      "wasm": true
    }
  },
  "mouseDown": {
    "class": "input",
    "device": "pointer",
    "listen": true,
    "dispatch": false,
    "origins": [
      "driver",
      "preview",
      "scene",
      "schedule",
      "http:write",
      "http:admin",
      "system"
    ],
    "renderAfter": "never",
    "coalesce": "none",
    "log": "none",
    "hosts": {
      "linux": true,
      "esp32": false,
      "wasm": true
    }
  },
  "mouseUp": {
    "class": "input",
    "device": "pointer",
    "listen": true,
    "dispatch": false,
    "origins": [
      "driver",
      "preview",
      "scene",
      "schedule",
      "http:write",
      "http:admin",
      "system"
    ],
    "renderAfter": "never",
    "coalesce": "none",
    "log": "none",
    "hosts": {
      "linux": true,
      "esp32": false,
      "wasm": true
    }
  },
  "wheel": {
    "class": "input",
    "device": "pointer",
    "listen": true,
    "dispatch": false,
    "origins": [
      "driver",
      "scene",
      "schedule",
      "http:write",
      "http:admin",
      "system"
    ],
    "renderAfter": "never",
    "coalesce": "none",
    "log": "none",
    "hosts": {
      "linux": true,
      "esp32": false,
      "wasm": false
    },
    "since": "2026.9.21"
  },
  "turnOn": {
    "class": "scene-command",
    "listen": true,
    "dispatch": true,
    "origins": [
      "scene",
      "schedule",
      "http:write",
      "http:admin",
      "cloud",
      "system"
    ],
    "renderAfter": "if-state-changed",
    "coalesce": "none",
    "log": "full",
    "hosts": {
      "linux": true,
      "esp32": true,
      "wasm": true
    },
    "cloud": {
      "verb": "set_display_power",
      "profiles": [
        "linux"
      ]
    }
  },
  "turnOff": {
    "class": "scene-command",
    "listen": true,
    "dispatch": true,
    "origins": [
      "scene",
      "schedule",
      "http:write",
      "http:admin",
      "cloud",
      "system"
    ],
    "renderAfter": "if-state-changed",
    "coalesce": "none",
    "log": "full",
    "hosts": {
      "linux": true,
      "esp32": true,
      "wasm": true
    },
    "cloud": {
      "verb": "set_display_power",
      "profiles": [
        "linux"
      ]
    }
  },
  "button": {
    "class": "input",
    "device": "button",
    "listen": true,
    "dispatch": false,
    "origins": [
      "driver",
      "preview",
      "scene",
      "schedule",
      "http:write",
      "http:admin",
      "cloud",
      "system"
    ],
    "renderAfter": "if-state-changed",
    "coalesce": "none",
    "log": "full",
    "hosts": {
      "linux": true,
      "esp32": true,
      "wasm": true
    },
    "cloud": {
      "verb": "scene_event",
      "since": "2026.9.21"
    }
  },
  "setSceneState": {
    "class": "scene-command",
    "listen": false,
    "dispatch": true,
    "sceneState": "payload",
    "origins": [
      "preview",
      "scene",
      "schedule",
      "http:write",
      "http:admin",
      "cloud",
      "system"
    ],
    "renderAfter": "if-state-changed",
    "coalesce": "none",
    "log": "full",
    "hosts": {
      "linux": true,
      "esp32": true,
      "wasm": true
    },
    "cloud": {
      "verb": "scene_event",
      "since": "2026.9.21",
      "before": {
        "verb": "set_current_scene",
        "profiles": [
          "linux"
        ]
      }
    }
  },
  "setCurrentScene": {
    "class": "scene-command",
    "listen": false,
    "dispatch": true,
    "origins": [
      "preview",
      "scene",
      "schedule",
      "http:write",
      "http:admin",
      "cloud",
      "system"
    ],
    "renderAfter": "always",
    "coalesce": "none",
    "log": "full",
    "hosts": {
      "linux": true,
      "esp32": true,
      "wasm": true
    },
    "schedule": {
      "label": "Show a scene"
    },
    "cloud": {
      "verb": "set_current_scene"
    }
  },
  "metrics": {
    "class": "device-command",
    "listen": false,
    "dispatch": false,
    "origins": [
      "scene",
      "schedule",
      "http:write",
      "http:admin",
      "cloud",
      "system"
    ],
    "renderAfter": "never",
    "coalesce": "none",
    "log": "full",
    "hosts": {
      "linux": true,
      "esp32": false,
      "wasm": false
    },
    "cloud": {
      "verb": "get_metrics"
    }
  },
  "reload": {
    "class": "device-command",
    "listen": false,
    "dispatch": false,
    "origins": [
      "schedule",
      "http:admin",
      "system"
    ],
    "renderAfter": "never",
    "coalesce": "none",
    "log": "full",
    "hosts": {
      "linux": true,
      "esp32": true,
      "wasm": false
    }
  },
  "restart": {
    "class": "device-command",
    "listen": false,
    "dispatch": false,
    "origins": [
      "schedule",
      "http:admin",
      "cloud",
      "system"
    ],
    "renderAfter": "never",
    "coalesce": "none",
    "log": "full",
    "hosts": {
      "linux": true,
      "esp32": true,
      "wasm": false
    },
    "schedule": {
      "label": "Restart FrameOS",
      "description": "Exit and relaunch the FrameOS runtime. A few seconds of downtime; the device stays up.",
      "since": "2026.8.32",
      "endsRuntime": true
    },
    "cloud": {
      "verb": "restart_runtime",
      "eventRoute": false
    }
  },
  "reboot": {
    "class": "device-command",
    "listen": false,
    "dispatch": false,
    "origins": [
      "schedule",
      "http:admin",
      "cloud",
      "system"
    ],
    "renderAfter": "never",
    "coalesce": "none",
    "log": "full",
    "hosts": {
      "linux": true,
      "esp32": true,
      "wasm": false
    },
    "schedule": {
      "label": "Reboot device",
      "description": "Reboot the whole device. Use this for the nightly reboot some panels and Wi-Fi chips like.",
      "since": "2026.8.32",
      "endsRuntime": true
    },
    "cloud": {
      "verb": "reboot",
      "eventRoute": false
    }
  },
  "uploadScenes": {
    "class": "device-command",
    "listen": false,
    "dispatch": false,
    "origins": [
      "http:admin",
      "cloud",
      "system"
    ],
    "renderAfter": "never",
    "coalesce": "none",
    "log": "full",
    "hosts": {
      "linux": true,
      "esp32": true,
      "wasm": false
    },
    "cloud": {
      "verb": "set_scenes"
    }
  }
}

export const customEventPolicy: Pick<ContractEventSpec, 'origins' | 'renderAfter' | 'coalesce' | 'log'> = {
  "origins": [
    "driver",
    "preview",
    "scene",
    "http:write",
    "http:admin",
    "system"
  ],
  "renderAfter": "if-state-changed",
  "coalesce": "none",
  "log": "full"
}

/** Origins a scene opts into per custom event: `origins` on its declaration. */
export const customEventDeclarableOrigins: readonly EventOrigin[] = ["schedule", "cloud"]

/** Log lines, not scene events (docs/events-contract.json `logEvents`). */
export const sceneChangedLogEvents: readonly string[] = ["render:scene", "render:sceneChange", "event:setCurrentScene"]
/** Log lines, not scene events (docs/events-contract.json `logEvents`). */
export const sceneStateChangedLogEvents: readonly string[] = ["event:setSceneState", "event:setCurrentScene", "event:uploadScenes"]

/** `context` keys per JavaScript sandbox. */
export const codeContextKeys: readonly string[] = ["event", "payload", "loopIndex", "loopKey", "hasImage", "imageWidth", "imageHeight"]
export const appContextKeys: readonly string[] = ["event", "payload", "loopIndex", "loopKey", "hasImage", "nextSleep", "image", "imageWidth", "imageHeight"]

/** Ambient declarations for the Monaco editors: event names and payloads. */
export const eventTypeDeclarations = `/** What each built-in scene event carries in \`context.payload\` (docs/events.md). */
interface FrameOSEventPayloads {
  /** Once per scene, when it is first loaded and its apps are ready — before its first open and render. */
  init: Record<string, any>;
  /** Render the scene. Triggered according to the frame's refresh interval, or when explicitly requested. */
  render: Record<string, any>;
  /** Every time the scene becomes the frame's current scene: at boot, and whenever the frame switches to it, including switching back. */
  open: { sceneId: string };
  /** When the frame switches away from the scene to another one. Carries no payload. */
  close: Record<string, never>;
  /** When a key is pressed on a keyboard */
  keyDown: { key: string; code: number };
  /** When a key is released on a keyboard */
  keyUp: { key: string; code: number };
  /** When a mouse moves (not logged) */
  mouseMove: { x: number; y: number };
  /** When a mouse button is pressed (not logged) */
  mouseDown: { button: number };
  /** When a mouse button is released (not logged) */
  mouseUp: { button: number };
  /** When a mouse wheel is scrolled (not logged). Deltas are wheel notches; deltaY is positive when scrolling down (towards the user), deltaX when scrolling right. Linux frames only. */
  wheel: { deltaX: number; deltaY: number };
  /** Turn the screen on */
  turnOn: Record<string, never>;
  /** Turn the screen off */
  turnOff: Record<string, never>;
  /** When a GPIO button is pressed */
  button: { pin: number; label: string; level: number };
  /** Set the scene's public state. This is not used for private state changes. */
  setSceneState: { state?: any; render?: boolean };
  /** Switch the frame to another scene. An optional \`state\` object is applied to that scene's public state. */
  setCurrentScene: { sceneId: string; state?: any };
}
`

/** The members of a code node's `context`. */
export const codeContextMembers = `  /** The name of the event this run is handling. */
  event: keyof FrameOSEventPayloads | (string & {});
  /** That event's payload. */
  payload: any;
  /** Index of the current iteration inside a loop. */
  loopIndex: number;
  /** Key of the current iteration inside a loop. */
  loopKey: string;
  /** Whether the run carries a canvas. */
  hasImage: boolean;
  /** Width of the canvas. In scene pixels, of the canvas this run draws on (a cell's inside render/split); absent when the run has none. */
  imageWidth?: number;
  /** Height of the canvas. In scene pixels, of the canvas this run draws on (a cell's inside render/split); absent when the run has none. */
  imageHeight?: number;
`

/** The members of a JavaScript app's `FrameOSContext`. */
export const appContextMembers = `  /** The name of the event this run is handling. */
  event: keyof FrameOSEventPayloads | (string & {});
  /** That event's payload. */
  payload: any;
  /** Index of the current iteration inside a loop. */
  loopIndex: number;
  /** Key of the current iteration inside a loop. */
  loopKey: string;
  /** Whether the run carries a canvas. */
  hasImage: boolean;
  /** Seconds until the next render. */
  nextSleep: number;
  /** The canvas, when there is one. */
  image?: FrameOSImageRef;
  /** Width of the canvas. In scene pixels, of the canvas this run draws on (a cell's inside render/split); absent when the run has none. */
  imageWidth?: number;
  /** Height of the canvas. In scene pixels, of the canvas this run draws on (a cell's inside render/split); absent when the run has none. */
  imageHeight?: number;
`
