"""frame mode

Revision ID: 07cada389a1c
Revises: a5465bd14643
Create Date: 2025-07-27 16:52:39.037081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07cada389a1c'
down_revision = 'a5465bd14643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frame', sa.Column('mode', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frame', 'mode')
    # ### end Alembic commands ###
