"""add tls certificate expiry to frame

Revision ID: 11a2d26ea7e7
Revises: 60acbd298511
Create Date: 2026-02-15 23:40:24.988741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a2d26ea7e7'
down_revision = '60acbd298511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frame', sa.Column('tls_server_cert_not_valid_after', sa.DateTime(), nullable=True))
    op.add_column('frame', sa.Column('tls_client_ca_cert_not_valid_after', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frame', 'tls_client_ca_cert_not_valid_after')
    op.drop_column('frame', 'tls_server_cert_not_valid_after')
    # ### end Alembic commands ###
