"""log to file

Revision ID: 1e2acb9652e8
Revises: b29d2204547c
Create Date: 2024-04-26 01:13:40.516170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2acb9652e8'
down_revision = 'b29d2204547c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lost_and_found')
    with op.batch_alter_table('frame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_to_file', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frame', schema=None) as batch_op:
        batch_op.drop_column('log_to_file')

    op.create_table('lost_and_found',
    sa.Column('rootpgno', sa.INTEGER(), nullable=True),
    sa.Column('pgno', sa.INTEGER(), nullable=True),
    sa.Column('nfield', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('c0', sa.NullType(), nullable=True),
    sa.Column('c1', sa.NullType(), nullable=True),
    sa.Column('c2', sa.NullType(), nullable=True),
    sa.Column('c3', sa.NullType(), nullable=True),
    sa.Column('c4', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
