"""frame debug and last log

Revision ID: 3145a02fc973
Revises: f4fafd71db11
Create Date: 2024-01-27 00:31:21.815386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3145a02fc973'
down_revision = 'f4fafd71db11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debug', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_log_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frame', schema=None) as batch_op:
        batch_op.drop_column('last_log_at')
        batch_op.drop_column('debug')

    # ### end Alembic commands ###
