"""agents2

Revision ID: 32bfe4f77c4b
Revises: 5ce6b0147b7b
Create Date: 2025-05-09 01:27:39.049138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32bfe4f77c4b'
down_revision = '5ce6b0147b7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('server_key_created_at', sa.DateTime(), nullable=False))
    op.add_column('agent', sa.Column('server_key_revoked_at', sa.DateTime(), nullable=True))
    op.add_column('agent', sa.Column('server_key_version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'server_key_version')
    op.drop_column('agent', 'server_key_revoked_at')
    op.drop_column('agent', 'server_key_created_at')
    # ### end Alembic commands ###
