"""tls settings

Revision ID: 6f45af81d344
Revises: f78f9e8ec198
Create Date: 2026-02-10 00:39:35.424033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f45af81d344'
down_revision = 'f78f9e8ec198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frame', sa.Column('https_proxy', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frame', 'https_proxy')
    # ### end Alembic commands ###
