"""ssh keys

Revision ID: 7132985d44a8
Revises: cacc07166daa
Create Date: 2025-12-26 00:39:56.521880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '7132985d44a8'
down_revision = 'cacc07166daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frame', sa.Column('ssh_keys', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frame', 'ssh_keys')
    # ### end Alembic commands ###
