"""ssh keys

Revision ID: 7132985d44a8
Revises: cacc07166daa
Create Date: 2025-12-26 00:39:56.521880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '7132985d44a8'
down_revision = 'cacc07166daa'
branch_labels = None
depends_on = None


def normalize_key_ids(keys):
    if not isinstance(keys, list):
        return []
    return sorted({str(key).strip() for key in keys if key})


def normalize_settings_ssh_keys(ssh_keys):
    if not isinstance(ssh_keys, dict):
        return {"keys": []}

    raw_keys = ssh_keys.get("keys")
    normalized = []
    if isinstance(raw_keys, list):
        for entry in raw_keys:
            if not isinstance(entry, dict):
                continue
            key_id = str(entry.get("id") or "").strip()
            if not key_id:
                continue
            normalized.append(
                {
                    "id": key_id,
                    "name": entry.get("name") or key_id,
                    "private": entry.get("private") or "",
                    "public": entry.get("public") or "",
                    "use_for_new_frames": bool(entry.get("use_for_new_frames")),
                }
            )

    if normalized:
        return {"keys": normalized}

    legacy_private = ssh_keys.get("default")
    legacy_public = ssh_keys.get("default_public")
    if legacy_private or legacy_public:
        return {
            "keys": [
                {
                    "id": "default",
                    "name": "Default",
                    "private": legacy_private or "",
                    "public": legacy_public or "",
                    "use_for_new_frames": True,
                }
            ]
        }

    return {"keys": []}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frame', sa.Column('ssh_keys', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###

    connection = op.get_bind()
    meta = sa.MetaData()
    frame_table = sa.Table(
        "frame",
        meta,
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("ssh_keys", sqlite.JSON()),
        sa.Column("last_successful_deploy", sqlite.JSON()),
    )
    settings_table = sa.Table(
        "settings",
        meta,
        sa.Column("key", sa.String()),
        sa.Column("value", sqlite.JSON()),
    )

    settings_row = connection.execute(
        sa.select(settings_table.c.value).where(settings_table.c.key == "ssh_keys")
    ).scalar_one_or_none()
    normalized_settings = normalize_settings_ssh_keys(settings_row or {})
    default_ids = normalize_key_ids(
        [key.get("id") for key in normalized_settings.get("keys", []) if key.get("use_for_new_frames")]
    )

    if settings_row is not None:
        connection.execute(
            settings_table.update()
            .where(settings_table.c.key == "ssh_keys")
            .values(value=normalized_settings)
        )

    frames = connection.execute(
        sa.select(frame_table.c.id, frame_table.c.last_successful_deploy)
    ).all()
    for frame_id, last_successful_deploy in frames:
        deploy_data = last_successful_deploy if isinstance(last_successful_deploy, dict) else {}
        deployed_keys = deploy_data.get("ssh_keys")
        normalized_deployed_ids = normalize_key_ids(deployed_keys) if isinstance(deployed_keys, list) else default_ids
        update_values = {"ssh_keys": normalized_deployed_ids or None}

        if deploy_data and "ssh_keys" not in deploy_data and normalized_deployed_ids:
            update_values["last_successful_deploy"] = {**deploy_data, "ssh_keys": normalized_deployed_ids}

        connection.execute(frame_table.update().where(frame_table.c.id == frame_id).values(**update_values))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frame', 'ssh_keys')
    # ### end Alembic commands ###
