"""create assets

Revision ID: 71488fd5da47
Revises: 91f9db3712b9
Create Date: 2025-01-12 23:03:11.065086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71488fd5da47'
down_revision = '91f9db3712b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assets')
    # ### end Alembic commands ###
