"""image width height

Revision ID: 84c01e9562bc
Revises: c994980b0da1
Create Date: 2023-10-17 23:06:08.552756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c01e9562bc'
down_revision = 'c994980b0da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('image_height', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.drop_column('image_height')
        batch_op.drop_column('image_width')

    # ### end Alembic commands ###
