"""reboot and control code

Revision ID: 8cad2df43b45
Revises: 1e2acb9652e8
Create Date: 2024-05-11 23:16:10.087724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '8cad2df43b45'
down_revision = '1e2acb9652e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reboot', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('control_code', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frame', schema=None) as batch_op:
        batch_op.drop_column('control_code')
        batch_op.drop_column('reboot')

    # ### end Alembic commands ###
