"""add repositories

Revision ID: 94f724b7c2a4
Revises: 84c01e9562bc
Create Date: 2023-10-20 00:06:52.359084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite


# revision identifiers, used by Alembic.
revision = '94f724b7c2a4'
down_revision = '84c01e9562bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('templates', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repository')

    # ### end Alembic commands ###
