"""nix config

Revision ID: a5465bd14643
Revises: 1a4ece62d617
Create Date: 2025-07-27 15:06:01.355230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'a5465bd14643'
down_revision = '1a4ece62d617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frame', sa.Column('nix', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frame', 'nix')
    # ### end Alembic commands ###
