"""scene images

Revision ID: ad5fc3d4001b
Revises: dba97ae75b42
Create Date: 2025-04-19 01:24:22.957725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5fc3d4001b'
down_revision = 'dba97ae75b42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene_image',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.String(length=128), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['frame.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('frame_id', 'scene_id', name='u_frame_scene')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scene_image')
    # ### end Alembic commands ###
