"""repository description

Revision ID: b29d2204547c
Revises: f8db11069084
Create Date: 2024-04-11 23:12:23.814494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29d2204547c'
down_revision = 'f8db11069084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
