"""add name

Revision ID: c23c0c58172b
Revises: 48b1417633df
Create Date: 2023-10-12 01:01:27.699798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23c0c58172b'
down_revision = '48b1417633df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=256), nullable=True))
    with op.batch_alter_table('frame', schema=None) as batch_op:
        batch_op.execute("UPDATE frame SET name = frame_host")
    with op.batch_alter_table('frame', schema=None) as batch_op:
        batch_op.alter_column('name', existing_type=sa.String(length=256), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frame', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
