"""add rpios to frame

Revision ID: cacc07166daa
Revises: 3e5b1f8a3f4d
Create Date: 2025-11-18 23:54:40.720882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'cacc07166daa'
down_revision = '3e5b1f8a3f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gallery')
    op.drop_index('ix_gallery_image_gallery_id', table_name='gallery_image')
    op.drop_table('gallery_image')
    op.add_column('frame', sa.Column('rpios', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frame', 'rpios')
    op.create_table('gallery_image',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('gallery_id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=512), nullable=False),
    sa.Column('original_path', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('thumbnail_path', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=128), nullable=True),
    sa.Column('extension', sa.VARCHAR(length=16), nullable=True),
    sa.Column('width', sa.INTEGER(), nullable=True),
    sa.Column('height', sa.INTEGER(), nullable=True),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['gallery.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gallery_image_gallery_id', 'gallery_image', ['gallery_id'], unique=False)
    op.create_table('gallery',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
