"""metrics backend

Revision ID: cff1b463a3c0
Revises: 94f724b7c2a4
Create Date: 2023-10-28 00:36:18.357218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'cff1b463a3c0'
down_revision = '94f724b7c2a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('metrics', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['frame.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('frame_metrics')
    with op.batch_alter_table('frame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metrics_interval', sa.Double(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frame', schema=None) as batch_op:
        batch_op.drop_column('metrics_interval')

    op.create_table('frame_metrics',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('frame_id', sa.INTEGER(), nullable=False),
    sa.Column('metrics', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['frame.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('metrics')
    # ### end Alembic commands ###
