"""ai context

Revision ID: f78f9e8ec198
Revises: 45c374c4d6ec
Create Date: 2026-01-25 00:30:36.274550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78f9e8ec198'
down_revision = '45c374c4d6ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('context_type', sa.String(length=32), nullable=True))
    op.add_column('chat', sa.Column('context_id', sa.String(length=256), nullable=True))
    op.drop_column('chat', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('title', sa.VARCHAR(length=160), nullable=True))
    op.drop_column('chat', 'context_id')
    op.drop_column('chat', 'context_type')
    # ### end Alembic commands ###
