import { MakeLogicType, actions, kea, key, listeners, path, props, reducers, selectors } from 'kea'
import { forms } from 'kea-forms'
import { v4 as uuidv4 } from 'uuid'
import { FrameScene, FrameType, FrameId } from '../types'
import { frameFormSceneErrors } from '../scenes/frame/frameFormSceneErrors'
import { convertSceneWithFeedback, postSceneConversion, type SceneConversionResult } from '../utils/sceneConvert'
import type { DeepPartial, DeepPartialMap, FieldName, ValidationErrorType } from 'kea-forms'

// In-memory replacement for frameLogic's editor-facing slice, used by the
// standalone embedded editor build (see frameLogicShim.ts and build.mjs).
// Scenes come in over postMessage and edits flow back out through
// embedBridge — there is no backend and nothing to deploy.
//
// frameForm is a real kea-forms form (like the one on the real frameLogic):
// the settings/state/events panels render <Form logic={frameLogic}
// formKey="frameForm"> fields, and logics like scenesLogic connect to
// form-generated actions such as submitFrameFormSuccess.
//
// Every action and value an editor logic connects to on frameLogic must
// exist here too — kea throws at build time otherwise, which takes the whole
// editor (and the scene store page hosting it) down. The cloud's
// embedded-editor-logics test builds each of those logics against this shim.

export interface EmbedFrameLogicProps {
  frameId: FrameId
}

export const embedBridge: {
  onScenesChanged?: (scenes: FrameScene[]) => void
  /** The Nim → interpreted converter. Defaults to the host page's own
   * POST /api/scenes/convert (the cloud's public converter, when the editor
   * is mounted on scenes.frameos.net). */
  convertScene?: (scene: FrameScene) => Promise<SceneConversionResult>
} = {}

export const EMBED_SCENE_CONVERT_PATH = '/api/scenes/convert'

function defaultConvertScene(scene: FrameScene): Promise<SceneConversionResult> {
  // Not apiFetch: the embed's apiFetch answers every call with a synthetic
  // 404 (no backend), while the converter lives on the host page's origin.
  return postSceneConversion(EMBED_SCENE_CONVERT_PATH, scene, (input, init) => fetch(input, init))
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface embedFrameLogicValues {
  convertingSceneId: string | null
  defaultInterval: number
  defaultScene: string
  frame: Partial<FrameType> | null
  frameForm: FrameType
  frameFormAllErrors: Record<string, any>
  frameFormChanged: boolean
  frameFormErrors: DeepPartialMap<FrameType, ValidationErrorType>
  frameFormHasErrors: boolean
  frameFormManualErrors: Record<string, any>
  frameFormTouched: boolean
  frameFormTouches: Record<string, boolean>
  frameFormValidationErrors: DeepPartialMap<FrameType, ValidationErrorType>
  frameId: FrameId
  height: number | undefined
  isFrameAdminMode: false
  isFrameFormSubmitting: boolean
  isFrameFormValid: boolean
  lastDeploy: null
  mode: 'buildroot' | 'embedded' | 'rpios'
  scenes: FrameScene[]
  showFrameFormErrors: boolean
  unsavedChanges: false
  width: number | undefined
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface embedFrameLogicActions {
  applyTemplate: (
    template: any,
    openDrawer?: boolean
  ) => {
    openDrawer: boolean | undefined
    template: any
  }
  convertSceneToInterpreted: (
    sceneId: string,
    asCopy?: boolean
  ) => {
    asCopy: boolean
    sceneId: string
  }
  initEmbedFrame: (frame: Partial<FrameType>) => {
    frame: Partial<FrameType>
  }
  resetFrameForm: (values?: FrameType) => {
    values?: FrameType
  }
  sceneConversionFinished: (
    sceneId: string,
    ok: boolean
  ) => {
    ok: boolean
    sceneId: string
  }
  sendEvent: (
    event: string,
    payload?: Record<string, any>
  ) => {
    event: string
    payload: Record<string, any> | undefined
  }
  setFrameFormManualErrors: (errors: Record<string, any>) => {
    errors: Record<string, any>
  }
  setFrameFormValue: (
    key: FieldName,
    value: any
  ) => {
    name: FieldName
    value: any
  }
  setFrameFormValues: (values: DeepPartial<FrameType>) => {
    values: DeepPartial<FrameType>
  }
  submitFrameForm: () => {
    value: boolean
  }
  submitFrameFormFailure: (
    error: Error,
    errors: Record<string, any>
  ) => {
    error: Error
    errors: Record<string, any>
  }
  submitFrameFormRequest: (frameForm: FrameType) => {
    frameForm: FrameType
  }
  submitFrameFormSuccess: (frameForm: FrameType) => {
    frameForm: FrameType
  }
  touchFrameFormField: (key: string) => {
    key: string
  }
  updateNodeData: (
    sceneId: string,
    nodeId: string,
    nodeData: Record<string, any>
  ) => {
    nodeData: Record<string, any>
    nodeId: string
    sceneId: string
  }
  updateScene: (
    sceneId: string,
    scene: Partial<FrameScene>
  ) => {
    scene: Partial<FrameScene>
    sceneId: string
  }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface embedFrameLogicMeta {
  key: FrameId
  __keaTypeGenInternalSelectorTypes: {
    frameId: (arg: FrameId) => FrameId
    scenes: (frame: any, frameForm: any) => FrameScene[]
    mode: (frame: any, frameForm: any) => 'buildroot' | 'embedded' | 'rpios'
    width: (frameForm: any) => number | undefined
    height: (frameForm: any) => number | undefined
    defaultInterval: (frameForm: any) => number
    defaultScene: (scenes: any) => string
  }
}

export type embedFrameLogicType = MakeLogicType<embedFrameLogicValues, embedFrameLogicActions, EmbedFrameLogicProps> &
  embedFrameLogicMeta

export const embedFrameLogic = kea<embedFrameLogicType>([
  path(['src', 'embed', 'embedFrameLogic']),
  props({} as EmbedFrameLogicProps),
  key((props: EmbedFrameLogicProps) => props.frameId),
  actions({
    initEmbedFrame: (frame: Partial<FrameType>) => ({ frame }),
    applyTemplate: (template: any, openDrawer?: boolean) => ({ template, openDrawer }),
    sendEvent: (event: string, payload?: Record<string, any>) => ({ event, payload }),
    updateScene: (sceneId: string, scene: Partial<FrameScene>) => ({ sceneId, scene }),
    // The Nim → interpreted converter on the editor's copy of the scene
    // (same contract as frameLogic: in place, unsaved — or, with asCopy, as
    // a new scene beside the original; there is nothing to save here, the
    // edit streams out through embedBridge either way).
    convertSceneToInterpreted: (sceneId: string, asCopy: boolean = false) => ({ sceneId, asCopy }),
    sceneConversionFinished: (sceneId: string, ok: boolean) => ({ sceneId, ok }),
    updateNodeData: (sceneId: string, nodeId: string, nodeData: Record<string, any>) => ({
      sceneId,
      nodeId,
      nodeData,
    }),
  }),
  forms(() => ({
    frameForm: {
      options: {
        showErrorsOnTouch: true,
      },
      defaults: {} as FrameType,
      errors: (state: Partial<FrameType>) => ({
        scenes: frameFormSceneErrors(state.scenes),
      }),
      // Nothing to save: edits already stream out through embedBridge.
      submit: async () => {},
    },
  })),
  reducers({
    frame: [
      null as Partial<FrameType> | null,
      {
        initEmbedFrame: (_: any, { frame }: { frame: Partial<FrameType> }) => frame,
      },
    ],
    frameForm: {
      initEmbedFrame: (_: any, { frame }: { frame: Partial<FrameType> }) => ({ ...frame } as FrameType),
    },
    convertingSceneId: [
      null as string | null,
      {
        convertSceneToInterpreted: (_: any, { sceneId }: { sceneId: string }) => sceneId,
        sceneConversionFinished: () => null,
      },
    ],
  }),
  selectors({
    frameId: [() => [(_: any, props: EmbedFrameLogicProps) => props.frameId], (frameId: FrameId) => frameId],
    scenes: [
      (s: any) => [s.frame, s.frameForm],
      (frame: Partial<FrameType> | null, frameForm: Partial<FrameType>): FrameScene[] =>
        frameForm?.scenes ?? frame?.scenes ?? [],
    ],
    mode: [
      (s: any) => [s.frame, s.frameForm],
      (frame: Partial<FrameType> | null, frameForm: Partial<FrameType>) => frameForm?.mode || frame?.mode || 'rpios',
    ],
    width: [
      (s: any) => [s.frameForm],
      (frameForm: Partial<FrameType>) =>
        frameForm.rotate === 90 || frameForm.rotate === 270 ? frameForm.height : frameForm.width,
    ],
    height: [
      (s: any) => [s.frameForm],
      (frameForm: Partial<FrameType>) =>
        frameForm.rotate === 90 || frameForm.rotate === 270 ? frameForm.width : frameForm.height,
    ],
    defaultInterval: [(s: any) => [s.frameForm], (frameForm: Partial<FrameType>) => frameForm.interval ?? 300],
    defaultScene: [
      (s: any) => [s.scenes],
      (scenes: FrameScene[]) =>
        (scenes.find((scene) => scene.id === 'default' || scene.default) || scenes[0])?.id ?? null,
    ],
    unsavedChanges: [() => [], () => false],
    // No deploys and no frame-admin mode in the embed; connected logics
    // (scenesLogic and friends) still expect these to exist.
    lastDeploy: [() => [], () => null],
    isFrameAdminMode: [() => [], () => false],
  }),
  listeners(({ actions, values }: { actions: any; values: any }) => ({
    setFrameFormValues: async (_: any, breakpoint: any) => {
      await breakpoint(150)
      embedBridge.onScenesChanged?.(values.frameForm?.scenes ?? [])
    },
    // Individual form-field edits (kea-forms Field components dispatch
    // setFrameFormValue) must stream out the same way batched edits do.
    setFrameFormValue: async (_: any, breakpoint: any) => {
      await breakpoint(150)
      embedBridge.onScenesChanged?.(values.frameForm?.scenes ?? [])
    },
    sendEvent: () => {
      // No frame to send events to in the embed.
    },
    updateScene: ({ sceneId, scene }: { sceneId: string; scene: Partial<FrameScene> }) => {
      const frameForm = values.frameForm
      const hasScene = frameForm.scenes?.some(({ id }: FrameScene) => id === sceneId)
      const scenes = hasScene
        ? frameForm.scenes?.map((s: FrameScene) => (s.id === sceneId ? { ...s, ...scene } : s))
        : [...(frameForm.scenes ?? []), { ...scene, id: sceneId } as FrameScene]
      actions.setFrameFormValues({ scenes })
    },
    updateNodeData: ({
      sceneId,
      nodeId,
      nodeData,
    }: {
      sceneId: string
      nodeId: string
      nodeData: Record<string, any>
    }) => {
      const scenes: FrameScene[] = values.frameForm.scenes ?? values.frame?.scenes ?? []
      const scene = scenes.find(({ id }) => id === sceneId)
      const currentNode = scene?.nodes?.find(({ id }) => id === nodeId)
      if (currentNode) {
        actions.setFrameFormValues({
          scenes: scenes.map((s) =>
            s.id === sceneId
              ? {
                  ...s,
                  nodes: s.nodes?.map((n) =>
                    n.id === nodeId ? { ...n, data: { ...(n.data ?? {}), ...nodeData } } : n
                  ),
                }
              : s
          ),
        })
      } else {
        console.error(`Node ${nodeId} not found in scene ${sceneId}`)
      }
    },
    convertSceneToInterpreted: async ({ sceneId, asCopy }: { sceneId: string; asCopy: boolean }) => {
      const scenes: FrameScene[] = values.frameForm.scenes ?? values.frame?.scenes ?? []
      const scene = scenes.find((s) => s.id === sceneId)
      if (!scene) {
        actions.sceneConversionFinished(sceneId, false)
        return
      }
      const converted = await convertSceneWithFeedback(scene, embedBridge.convertScene ?? defaultConvertScene, asCopy)
      if (!converted) {
        actions.sceneConversionFinished(sceneId, false)
        return
      }
      if (asCopy) {
        const copyId = uuidv4()
        const taken = new Set(scenes.map((s) => s.name))
        let name = `${scene.name || 'Scene'} (interpreted)`
        for (let counter = 2; taken.has(name); counter += 1) {
          name = `${scene.name || 'Scene'} (interpreted) ${counter}`
        }
        actions.updateScene(copyId, { ...converted, id: copyId, name, default: false })
        actions.sceneConversionFinished(sceneId, true)
        return
      }
      actions.updateScene(sceneId, converted)
      actions.sceneConversionFinished(sceneId, true)
    },
    applyTemplate: ({ template }: { template: any }) => {
      // The embedded editor has no template store; adding a template means
      // appending its scenes.
      const incoming: FrameScene[] = template?.scenes ?? []
      if (incoming.length > 0) {
        actions.setFrameFormValues({ scenes: [...(values.frameForm.scenes ?? []), ...incoming] })
      }
    },
  })),
])
