import { MakeLogicType, kea, key, path, props, selectors } from 'kea'
import { LogType, FrameId } from '../../src/types'

// Swapped in for panels/Logs/logsLogic by the embedded-editor build: there is
// no backend or websocket, so the log feed (used only for runtime error
// badges on nodes) is permanently empty.

export interface LogsLogicProps {
  frameId: FrameId
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface logsLogicValues {
  logs: LogType[]
  logsLoading: false
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface logsLogicMeta {
  key: FrameId
}

export type logsLogicType = MakeLogicType<logsLogicValues, {}, LogsLogicProps> & logsLogicMeta

export const logsLogic = kea<logsLogicType>([
  path(['src', 'embed', 'logsLogicShim']),
  props({} as LogsLogicProps),
  key((props: LogsLogicProps) => props.frameId),
  selectors({
    logs: [() => [], (): LogType[] => []],
    logsLoading: [() => [], () => false],
  }),
])
