import {
  MakeLogicType,
  actions,
  afterMount,
  beforeUnmount,
  connect,
  kea,
  key,
  listeners,
  path,
  props,
  reducers,
  selectors,
} from 'kea'
import { frameLogic } from '../../frameLogic'
import { isInFrameAdminMode } from '../../../../utils/frameAdmin'
import { apiFetch } from '../../../../utils/apiFetch'

import type { FrameId } from '../../../../types'
import type { FrameType } from '../../../../types'

export type PingMode = 'icmp' | 'http'

export type PingResult = {
  id: number
  timestamp: string
  clientElapsedMs: number | null
  serverElapsedMs: number | null
  icmpTimeMs: number | null
  ok: boolean
  message: string
  mode: PingMode
  target: string
  status?: number | null
}

export interface PingLogicProps {
  frameId: FrameId
}

const MAX_RESULTS = 200
const ICMP_TIME_REGEX = /time[=<]\s*([\d.]+)\s*ms/i

const normalizeIntervalSeconds = (value: number | null | undefined) => {
  if (!Number.isFinite(value)) {
    return 1
  }
  return Math.max(1, value ?? 1)
}

const normalizePingMode = (value: string | null | undefined): PingMode => (value === 'http' ? 'http' : 'icmp')

const normalizePath = (value: string | null | undefined) => {
  const trimmed = (value ?? '').trim() || '/ping'
  return trimmed.startsWith('/') ? trimmed : `/${trimmed}`
}

const clearScheduledPing = (cache: Record<string, any>) => {
  if (cache.timeoutId) {
    window.clearTimeout(cache.timeoutId)
    cache.timeoutId = null
  }
}

const invalidatePendingPings = (cache: Record<string, any>) => {
  cache.requestId = (cache.requestId ?? 0) + 1
}

const extractIcmpTime = (message: string) => {
  const match = message.match(ICMP_TIME_REGEX)
  if (!match) {
    return null
  }
  const parsed = Number(match[1])
  return Number.isFinite(parsed) ? parsed : null
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface pingLogicValues {
  frame: FrameType // frameLogic
  httpPath: string
  intervalMs: number
  intervalSeconds: number
  isFrameAdminMode: boolean
  isPinging: boolean
  isRunning: boolean
  normalisedPath: string
  pingMode: PingMode
  results: PingResult[]
  targetLabel: string
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface pingLogicActions {
  appendResult: (result: PingResult) => {
    result: PingResult
  }
  runPing: () => {
    value: true
  }
  scheduleNext: (elapsed: number) => {
    elapsed: number
  }
  setHttpPath: (httpPath: string) => {
    httpPath: string
  }
  setIntervalSeconds: (intervalSeconds: number | null) => {
    intervalSeconds: number | null
  }
  setIsPinging: (isPinging: boolean) => {
    isPinging: boolean
  }
  setPingMode: (pingMode: string | PingMode) => {
    pingMode: string
  }
  startRunning: () => {
    value: true
  }
  stopRunning: () => {
    value: true
  }
  toggleRunning: () => {
    value: true
  }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface pingLogicMeta {
  key: FrameId
  __keaTypeGenInternalSelectorTypes: {
    intervalMs: (intervalSeconds: number) => number
    normalisedPath: (httpPath: string) => string
    targetLabel: (frame: FrameType, normalisedPath: string, pingMode: PingMode) => string
  }
}

export type pingLogicType = MakeLogicType<pingLogicValues, pingLogicActions, PingLogicProps> & pingLogicMeta

export const pingLogic = kea<pingLogicType>([
  path(['src', 'scenes', 'frame', 'panels', 'Ping', 'pingLogic']),
  props({} as PingLogicProps),
  key((props: PingLogicProps) => props.frameId),
  connect(({ frameId }: PingLogicProps) => ({
    values: [frameLogic({ frameId }), ['frame']],
  })),
  actions({
    setIntervalSeconds: (intervalSeconds: number | null) => ({ intervalSeconds }),
    setPingMode: (pingMode: PingMode | string) => ({ pingMode }),
    setHttpPath: (httpPath: string) => ({ httpPath }),
    toggleRunning: true,
    startRunning: true,
    stopRunning: true,
    runPing: true,
    setIsPinging: (isPinging: boolean) => ({ isPinging }),
    appendResult: (result: PingResult) => ({ result }),
    scheduleNext: (elapsed: number) => ({ elapsed }),
  }),
  reducers({
    intervalSeconds: [
      1,
      {
        setIntervalSeconds: (_, { intervalSeconds }) => normalizeIntervalSeconds(intervalSeconds),
      },
    ],
    pingMode: [
      'icmp' as PingMode,
      {
        setPingMode: (_, { pingMode }) => normalizePingMode(pingMode),
      },
    ],
    httpPath: [
      '/ping',
      {
        setHttpPath: (_, { httpPath }) => httpPath,
      },
    ],
    isRunning: [
      false,
      {
        startRunning: () => true,
        stopRunning: () => false,
        setPingMode: () => false,
      },
    ],
    isPinging: [
      false,
      {
        setIsPinging: (_, { isPinging }) => isPinging,
        stopRunning: () => false,
        setPingMode: () => false,
      },
    ],
    results: [
      [] as PingResult[],
      {
        appendResult: (state, { result }) => [result, ...state].slice(0, MAX_RESULTS),
        setPingMode: (state, { pingMode }) => {
          const nextMode = normalizePingMode(pingMode)
          return state.some((result) => result.mode !== nextMode) ? [] : state
        },
      },
    ],
  }),
  selectors({
    isFrameAdminMode: [() => [], () => isInFrameAdminMode()],
    intervalMs: [
      (s) => [s.intervalSeconds],
      (intervalSeconds: pingLogicValues['intervalSeconds']) => normalizeIntervalSeconds(intervalSeconds) * 1000,
    ],
    normalisedPath: [(s) => [s.httpPath], (httpPath: pingLogicValues['httpPath']) => normalizePath(httpPath)],
    targetLabel: [
      (s) => [s.frame, s.normalisedPath, s.pingMode],
      (
        frame: pingLogicValues['frame'],
        normalisedPath: pingLogicValues['normalisedPath'],
        pingMode: pingLogicValues['pingMode']
      ) => {
        const host = frame?.frame_host || 'frame'
        const port = frame?.frame_port ? `:${frame.frame_port}` : ''
        return pingMode === 'http' ? `${host}${port}${normalisedPath}` : host
      },
    ],
  }),
  listeners(({ actions, values, cache, props }) => ({
    toggleRunning: () => {
      if (values.isRunning) {
        actions.stopRunning()
      } else {
        actions.startRunning()
      }
    },
    startRunning: () => {
      clearScheduledPing(cache)
      actions.runPing()
    },
    stopRunning: () => {
      clearScheduledPing(cache)
    },
    setIntervalSeconds: () => {
      if (values.isRunning) {
        actions.stopRunning()
        actions.startRunning()
      }
    },
    setPingMode: () => {
      clearScheduledPing(cache)
      invalidatePendingPings(cache)
    },
    setHttpPath: () => {
      if (values.isRunning) {
        actions.stopRunning()
        actions.startRunning()
      }
    },
    scheduleNext: ({ elapsed }) => {
      if (!values.isRunning) {
        return
      }
      clearScheduledPing(cache)
      const delay = Math.max(values.intervalMs - elapsed, 0)
      cache.timeoutId = window.setTimeout(() => {
        actions.runPing()
      }, delay)
    },
    runPing: async () => {
      const startedAt = Date.now()
      actions.setIsPinging(true)
      cache.requestId = (cache.requestId ?? 0) + 1
      const id = cache.requestId as number
      let ok = false
      let message = ''
      let mode: PingMode = values.isFrameAdminMode ? 'http' : values.pingMode
      let target = values.targetLabel
      let status: number | null | undefined = null
      let payload: {
        elapsed_ms?: number | null
        ok?: boolean
        mode?: PingMode
        target?: string
        status?: number | null
        message?: string
      } | null = null
      let responseText: string | null = null

      try {
        const selectedMode: PingMode = values.isFrameAdminMode ? 'http' : values.pingMode
        const params = new URLSearchParams({ mode: selectedMode })
        if (selectedMode === 'http') {
          params.set('path', values.normalisedPath)
        }
        const response = await apiFetch(`/api/frames/${props.frameId}/ping?${params.toString()}`)
        const contentType = response.headers.get('content-type') ?? ''
        if (contentType.includes('application/json')) {
          try {
            payload = await response.json()
          } catch (error) {
            message = error instanceof Error ? error.message : String(error)
          }
        } else {
          responseText = (await response.text()).trim()
        }

        ok = payload?.ok ?? response.ok
        mode = (payload?.mode as PingMode) || selectedMode
        target = payload?.target ?? values.targetLabel
        status = mode === 'http' ? (payload ? payload.status ?? null : response.status) : null
        if (payload?.message) {
          message = payload.message
        } else if (payload && Object.keys(payload).length > 0) {
          message = JSON.stringify(payload)
        } else {
          message = responseText || (ok ? 'pong' : `HTTP ${response.status}`)
        }
      } catch (error) {
        message = error instanceof Error ? error.message : String(error)
      }

      if (id !== cache.requestId) {
        return
      }

      const elapsed = Date.now() - startedAt
      const clientElapsedMs = elapsed
      const serverElapsedMs = payload?.elapsed_ms ?? null
      const icmpTimeMs = mode === 'icmp' ? extractIcmpTime(message) : null
      actions.appendResult({
        id,
        timestamp: new Date().toLocaleTimeString(),
        clientElapsedMs,
        serverElapsedMs,
        icmpTimeMs,
        ok,
        message,
        mode,
        target,
        status,
      })
      actions.setIsPinging(false)
      actions.scheduleNext(elapsed)
    },
  })),
  afterMount(({ cache }) => {
    cache.timeoutId = null
    cache.requestId = 0
  }),
  beforeUnmount(({ cache }) => {
    clearScheduledPing(cache)
    invalidatePendingPings(cache)
  }),
])

export const formatMs = (value: number, precision = 0) => {
  const fixed = value.toFixed(precision)
  return fixed.replace(/\.?0+$/, '')
}
