import { MakeLogicType, actions, afterMount, connect, kea, key, listeners, path, props, reducers, selectors } from 'kea'

import { frameLogic } from '../../frameLogic'

import { FrameScene, FrameStateRecord, FrameType, FrameId } from '../../../../types'

import { loaders } from 'kea-loaders'

import { socketLogic } from '../../../socketLogic'
import { apiFetch } from '../../../../utils/apiFetch'
import { isCloudMode } from '../../../../utils/cloudMode'
import { activeSceneFromLastState } from '../../../../utils/cloudFrameScenes'
import { longRunningTasksModel } from '../../../../models/longRunningTasksModel'
import { embeddedUsbApiCanUse, runEmbeddedUsbApiCommand } from '../../../../models/embeddedUsbLogsModel'
import { sceneIdsRefer } from '../../../../utils/systemScenes'
import { SCENE_ACTIVATION_TIMEOUT_MS } from '../../../../utils/sceneActivation'
import type { TemplateType } from '../../../../types'
import type { StateField } from '../../../../types'

export interface ControlLogicProps {
  frameId: FrameId
}

const UPLOADED_SCENE_PREFIX = 'uploaded/'
const emptyFrameStateRecord: FrameStateRecord = { sceneId: '', states: {} }

function normaliseFrameStateRecord(payload: any): FrameStateRecord {
  const sceneId = typeof payload?.sceneId === 'string' ? payload.sceneId : ''
  const states =
    payload?.states && typeof payload.states === 'object' && !Array.isArray(payload.states) ? payload.states : {}
  return {
    sceneId,
    states,
    ...(payload?.cache && typeof payload.cache === 'object' ? { cache: payload.cache } : {}),
  }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface controlLogicValues {
  frame: FrameType // frameLogic
  frameForm: Partial<FrameType> // frameLogic
  activatingSceneId: string | null
  fields: StateField[]
  loading: boolean | string
  scene: FrameScene | null
  sceneChanging: string | null
  sceneId: string
  scenes: FrameScene[] | undefined
  scenesAsOptions: {
    label: string
    value: string
  }[]
  stateRecord: FrameStateRecord
  stateRecordLoading: boolean
  states: Record<string, Record<string, any>>
  uploadedScenes: FrameScene[]
  uploadedScenesLoading: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface controlLogicActions {
  applyTemplate: (
    template: Partial<TemplateType>,
    openDrawer?: boolean | undefined,
    preserveSceneIds?: boolean | undefined
  ) => {
    openDrawer: boolean
    preserveSceneIds: boolean
    template: Partial<TemplateType>
  } // frameLogic
  updateScene: (
    sceneId: string,
    scene: Partial<FrameScene>
  ) => {
    scene: Partial<FrameScene>
    sceneId: string
  } // frameLogic
  currentSceneChanged: (sceneId: string) => {
    sceneId: string
  }
  loadUploadedScenes: () => any
  loadUploadedScenesFailure: (
    error: string,
    errorObject?: any
  ) => {
    error: string
    errorObject?: any
  }
  loadUploadedScenesSuccess: (
    uploadedScenes: FrameScene[],
    payload?: any
  ) => {
    uploadedScenes: FrameScene[]
    payload?: any
  }
  sceneActivationSettled: (sceneId: string) => {
    sceneId: string
  }
  sceneActivationStarted: (sceneId: string) => {
    sceneId: string
  }
  setCurrentScene: (sceneId: string) => {
    sceneId: string
  }
  sync: () => {
    value: true
  }
  syncFailure: (
    error: string,
    errorObject?: any
  ) => {
    error: string
    errorObject?: any
  }
  syncSuccess: (
    stateRecord: FrameStateRecord,
    payload?: {
      value: true
    }
  ) => {
    stateRecord: FrameStateRecord
    payload?: {
      value: true
    }
  }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface controlLogicMeta {
  key: FrameId
  __keaTypeGenInternalSelectorTypes: {
    scenes: (frame: FrameType, frameForm: Partial<FrameType>) => FrameScene[] | undefined
    scene: (scenes: FrameScene[] | undefined, sceneId: string) => FrameScene | null
    fields: (scene: FrameScene | null) => StateField[]
    scenesAsOptions: (scenes: FrameScene[] | undefined) => {
      label: string
      value: string
    }[]
    states: (stateRecord: FrameStateRecord) => Record<string, Record<string, any>>
    sceneId: (stateRecord: FrameStateRecord) => string
    loading: (
      stateRecord: FrameStateRecord,
      sceneChanging: string | null,
      stateRecordLoading: boolean
    ) => boolean | string
  }
}

export type controlLogicType = MakeLogicType<controlLogicValues, controlLogicActions, ControlLogicProps> &
  controlLogicMeta

/** The activate event's response body, when the server sent JSON with a `type`
 * (cloud); the backend answers with whatever it likes, so parse leniently. */
export function activationWasRedeploy(body: string): boolean {
  try {
    const parsed = JSON.parse(body) as { type?: unknown } | null
    return parsed?.type === 'set_scenes'
  } catch {
    return false
  }
}

export const controlLogic = kea<controlLogicType>([
  path(['src', 'scenes', 'frame', 'panels', 'Scenes', 'controlLogic']),
  props({} as ControlLogicProps),
  key((props) => props.frameId),
  connect(({ frameId }: ControlLogicProps) => ({
    logic: [longRunningTasksModel],
    values: [frameLogic({ frameId }), ['frame', 'frameForm']],
    actions: [frameLogic({ frameId }), ['updateScene', 'applyTemplate']],
  })),
  actions({
    sync: true,
    setCurrentScene: (sceneId: string) => ({ sceneId }),
    currentSceneChanged: (sceneId: string) => ({ sceneId }),
    // The Activate button's own state: armed when an activation request
    // leaves the browser, released when the frame logs that scene's
    // render:done (or a render error, or the timeout). The toast queue
    // tracks the same thing for the notification strip; this is for the
    // button that was clicked, which used to give no sign at all.
    sceneActivationStarted: (sceneId: string) => ({ sceneId }),
    sceneActivationSettled: (sceneId: string) => ({ sceneId }),
  }),
  loaders(({ props, values }) => ({
    stateRecord: [
      emptyFrameStateRecord,
      {
        sync: async (_, breakpoint) => {
          await breakpoint(100)

          // The standalone embedded editor has no frame to sync state from.
          if (typeof window !== 'undefined' && (window as any).FRAMEOS_EMBEDDED_NO_BACKEND) {
            return emptyFrameStateRecord
          }

          // Both planes answer /states in the same {sceneId, states, cache}
          // shape. The cloud's copy is the device's last report (hello /
          // `state`, mirrored onto the frame row by the hub) and the route
          // queues a `get_state` verb for a connected frame, answering with
          // cache.refreshing so the drawer syncs once more for the reply.
          try {
            const statesResponse = await apiFetch(`/api/frames/${props.frameId}/states`)
            if (statesResponse.ok) {
              return normaliseFrameStateRecord(await statesResponse.json())
            }
          } catch (error) {
            console.error(error)
          }

          // No /state fallback on the cloud: the frame row's last_state at
          // least names the active scene, which is what the controls need.
          if (isCloudMode()) {
            return normaliseFrameStateRecord({
              sceneId: activeSceneFromLastState(values.frame?.last_state) ?? '',
              states: {},
            })
          }

          const response = await apiFetch(`/api/frames/${props.frameId}/state`)
          if (!response.ok) {
            throw new Error('Failed to fetch frame state')
          }
          console.error('Failed to fetch frame states, but could load one state. You might need to redeploy the frame.')
          const resp = await response.json()
          return normaliseFrameStateRecord({ states: { [resp.sceneId]: resp.state }, sceneId: resp.sceneId })
        },
      },
    ],
    uploadedScenes: [
      [] as FrameScene[],
      {
        loadUploadedScenes: async () => {
          // No /uploaded_scenes route on the cloud: the pushed set already
          // lives in the frame form / frame row the drawer resolves against.
          if (isCloudMode()) {
            return []
          }
          const response = await apiFetch(`/api/frames/${props.frameId}/uploaded_scenes`)
          if (!response.ok) {
            throw new Error('Failed to fetch uploaded scenes')
          }
          const payload = await response.json()
          return (payload?.scenes ?? []) as FrameScene[]
        },
      },
    ],
  })),
  reducers({
    stateRecord: [
      emptyFrameStateRecord,
      {
        currentSceneChanged: (state, { sceneId }) => ({ ...state, sceneId }),
      },
    ],
    sceneChanging: [
      null as null | string,
      {
        setCurrentScene: (_, { sceneId }) => sceneId,
        syncSuccess: () => null,
        syncFailure: () => null,
        currentSceneChanged: () => null,
      },
    ],
    activatingSceneId: [
      null as null | string,
      {
        sceneActivationStarted: (_, { sceneId }) => sceneId,
        sceneActivationSettled: (state, { sceneId }) =>
          state !== null && sceneIdsRefer(state, sceneId) ? null : state,
      },
    ],
  }),
  selectors({
    scenes: [
      (s) => [s.frame, s.frameForm],
      (frame: controlLogicValues['frame'], frameForm: controlLogicValues['frameForm']) =>
        frameForm.scenes ?? frame.scenes,
    ],
    scene: [
      (s) => [s.scenes, s.sceneId],
      (scenes: controlLogicValues['scenes'], sceneId: controlLogicValues['sceneId']): FrameScene | null =>
        scenes?.find((scene) => scene.id === sceneId) ?? null,
    ],
    fields: [
      (s) => [s.scene],
      (scene: controlLogicValues['scene']) => (scene?.fields ?? []).filter((field) => field.access === 'public'),
    ],
    scenesAsOptions: [
      (s) => [s.scenes],
      (scenes: controlLogicValues['scenes']): { label: string; value: string }[] =>
        (scenes ?? []).map((scene) => ({
          label: scene.name || 'Unnamed Scene',
          value: scene.id || '',
        })),
    ],
    states: [(s) => [s.stateRecord], (stateRecord: controlLogicValues['stateRecord']) => stateRecord?.states ?? {}],
    sceneId: [(s) => [s.stateRecord], (stateRecord: controlLogicValues['stateRecord']) => stateRecord?.sceneId ?? null],
    loading: [
      (s) => [s.stateRecord, s.sceneChanging, s.stateRecordLoading],
      (
        stateRecord: controlLogicValues['stateRecord'],
        stateRecordLoading: controlLogicValues['sceneChanging'],
        sceneChanging: controlLogicValues['stateRecordLoading']
      ) => !stateRecord?.sceneId || stateRecordLoading || !!sceneChanging,
    ],
  }),
  listeners(({ actions, props, values }) => ({
    [socketLogic.actionTypes.socketReconnected]: () => {
      // The active scene / state record is event-sourced from newLog, so a
      // scene change during the outage would go unnoticed. Resync once -- this
      // is a single small state snapshot, not a bulk download.
      if (!values.stateRecordLoading) {
        actions.sync()
      }
    },
    sceneActivationStarted: async ({ sceneId }, breakpoint) => {
      // A later activation replaces this wait (kea cancels the older
      // listener at its breakpoint), so only the newest request times out.
      await breakpoint(SCENE_ACTIVATION_TIMEOUT_MS)
      actions.sceneActivationSettled(sceneId)
    },
    setCurrentScene: async ({ sceneId }) => {
      const scene =
        values.frameForm.scenes?.find((item) => item.id === sceneId) ??
        values.frame?.scenes?.find((item) => item.id === sceneId)
      longRunningTasksModel.actions.startTask({
        frameId: props.frameId,
        kind: 'activate',
        sceneId,
        title: 'Activating scene',
        detail: scene?.name || sceneId,
      })
      actions.sceneActivationStarted(sceneId)
      try {
        let usbSucceeded = false
        if ((values.frame?.mode ?? 'rpios') === 'embedded' && embeddedUsbApiCanUse(props.frameId)) {
          try {
            await runEmbeddedUsbApiCommand(props.frameId, 'scene-payload', { payload: sceneId, timeoutMs: 10000 })
            usbSucceeded = true
          } catch (error) {
            // A stale or busy USB port must not strand a network-reachable
            // frame — fall through to the HTTP event below.
          }
        }
        let detail = scene?.name || sceneId
        if (!usbSucceeded) {
          const response = await apiFetch(`/api/frames/${props.frameId}/event/setCurrentScene`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ sceneId }),
          })
          if (!response.ok) {
            throw new Error('Failed to send scene activation event')
          }
          // The cloud answers `type: "set_scenes"` when the frame did not hold
          // the scene and got the assigned set re-pushed instead of a plain
          // select — a deploy, so say so rather than "activated".
          if (activationWasRedeploy(await response.text())) {
            detail = `${detail} — deployed, the frame shows it as soon as it syncs`
          }
        }
        actions.currentSceneChanged(sceneId)
        socketLogic.actions.updateFrame({ id: props.frameId, active_scene_id: sceneId } as FrameType)
        longRunningTasksModel.actions.finishTask({
          frameId: props.frameId,
          kind: 'activate',
          sceneId,
          status: 'success',
          detail,
        })
        if (isCloudMode()) {
          // The cloud queues the verb; the frame's render:done may never
          // reach this page. "Accepted" is as far as the button can see.
          actions.sceneActivationSettled(sceneId)
        }
      } catch (error) {
        actions.sceneActivationSettled(sceneId)
        longRunningTasksModel.actions.taskFailed({
          frameId: props.frameId,
          kind: 'activate',
          sceneId,
          detail: error instanceof Error ? error.message : 'Failed to activate scene',
        })
        throw error
      }
    },
    syncSuccess: async ({ stateRecord }, breakpoint) => {
      if (values.activatingSceneId !== null && stateRecord?.sceneId && stateRecord.sceneId.length > 0) {
        // The frame says it is on the scene we asked for: the render:done
        // happened while the socket was down (the runtime restarted, say)
        // and the reconnect resync is the only signal left.
        if (sceneIdsRefer(values.activatingSceneId, stateRecord.sceneId)) {
          actions.sceneActivationSettled(stateRecord.sceneId)
        }
      }
      if (stateRecord?.sceneId?.startsWith(UPLOADED_SCENE_PREFIX)) {
        actions.loadUploadedScenes()
      }
      if (stateRecord?.cache?.refreshing && !stateRecord.cache.cached) {
        const retryAfterSeconds = Math.max(1, Number(stateRecord.cache.retry_after) || 5)
        await breakpoint(retryAfterSeconds * 1000)
        if (!values.stateRecordLoading) {
          actions.sync()
        }
      }
    },
    [socketLogic.actionTypes.newLog]: ({ log }) => {
      // Only react to logs for THIS frame; otherwise a scene change on another
      // frame would overwrite this frame's active scene and trigger a redundant
      // sync() per mounted controlLogic.
      if (log.frame_id !== props.frameId) {
        return
      }
      try {
        const { event, sceneId } = JSON.parse(log.line)
        if (values.activatingSceneId !== null) {
          // The device reports an interpreted scene as `uploaded/<id>`;
          // sceneActivationSettled compares the public ids.
          if (event === 'render:done' && typeof sceneId === 'string') {
            actions.sceneActivationSettled(sceneId)
          } else if (event === 'render:error' || event === 'event:error') {
            actions.sceneActivationSettled(values.activatingSceneId)
          }
        }
        if (event === 'render:sceneChange') {
          if (sceneId !== values.sceneId) {
            actions.currentSceneChanged(sceneId)
            if (!values.stateRecordLoading) {
              actions.sync()
            }
          } else {
            actions.currentSceneChanged(sceneId)
          }
        } else if (
          event === 'event:setSceneState' ||
          event === 'event:setCurrentScene' ||
          event === 'event:uploadScenes'
        ) {
          if (!values.stateRecordLoading) {
            actions.sync()
          }
        }
      } catch (error) {}
    },
  })),
  afterMount(({ actions }) => {
    actions.sync()
  }),
])
