import { MakeLogicType, connect, kea, key, path, props, selectors } from 'kea'

import { forms } from 'kea-forms'
import { apiFetch } from '../../../../utils/apiFetch'
import { FrameScene, FrameType, FrameId } from '../../../../types'
import { frameLogic } from '../../frameLogic'
import { activationWasRedeploy, controlLogic } from './controlLogic'
import { longRunningTasksModel } from '../../../../models/longRunningTasksModel'
import { socketLogic } from '../../../socketLogic'
import { visiblePublicStateFields } from '../../../../utils/showIf'
import type { DeepPartial, DeepPartialMap, FieldName, ValidationErrorType } from 'kea-forms'
import type { StateField } from '../../../../types'
import type { TemplateType } from '../../../../types'

export interface ExpandedSceneLogicProps {
  frameId: FrameId
  sceneId: string
  scene?: FrameScene | null
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface expandedSceneLogicValues {
  loading: boolean | string // controlLogic
  states: Record<string, Record<string, any>> // controlLogic
  frame: FrameType // frameLogic
  frameForm: Partial<FrameType> // frameLogic
  fields: StateField[]
  hasStateChanges: boolean
  isStateChangesSubmitting: boolean
  isStateChangesValid: boolean
  scene: FrameScene | null
  scenes: FrameScene[] | undefined
  scenesAsOptions: {
    label: string
    value: string
  }[]
  showStateChangesErrors: boolean
  stateChanges: Record<string, any>
  stateChangesAllErrors: Record<string, any>
  stateChangesChanged: boolean
  stateChangesErrors: DeepPartialMap<Record<string, any>, ValidationErrorType>
  stateChangesHasErrors: boolean
  stateChangesManualErrors: Record<string, any>
  stateChangesTouched: boolean
  stateChangesTouches: Record<string, boolean>
  stateChangesValidationErrors: DeepPartialMap<Record<string, any>, ValidationErrorType>
  visibleFields: StateField[]
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface expandedSceneLogicActions {
  applyTemplate: (
    template: Partial<TemplateType>,
    openDrawer?: boolean | undefined,
    preserveSceneIds?: boolean | undefined
  ) => {
    openDrawer: boolean
    preserveSceneIds: boolean
    template: Partial<TemplateType>
  } // frameLogic
  updateScene: (
    sceneId: string,
    scene: Partial<FrameScene>
  ) => {
    scene: Partial<FrameScene>
    sceneId: string
  } // frameLogic
  resetStateChanges: (values?: Record<string, any>) => {
    values?: Record<string, any>
  }
  setStateChangesManualErrors: (errors: Record<string, any>) => {
    errors: Record<string, any>
  }
  setStateChangesValue: (
    key: FieldName,
    value: any
  ) => {
    name: FieldName
    value: any
  }
  setStateChangesValues: (values: DeepPartial<Record<string, any>>) => {
    values: DeepPartial<Record<string, any>>
  }
  submitStateChanges: () => {
    value: boolean
  }
  submitStateChangesFailure: (
    error: Error,
    errors: Record<string, any>
  ) => {
    error: Error
    errors: Record<string, any>
  }
  submitStateChangesRequest: (stateChanges: Record<string, any>) => {
    stateChanges: Record<string, any>
  }
  submitStateChangesSuccess: (stateChanges: Record<string, any>) => {
    stateChanges: Record<string, any>
  }
  touchStateChangesField: (key: string) => {
    key: string
  }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface expandedSceneLogicMeta {
  key: string
  __keaTypeGenInternalSelectorTypes: {
    scenes: (frame: FrameType, frameForm: Partial<FrameType>) => FrameScene[] | undefined
    scene: (scenes: FrameScene[] | undefined, arg: any, arg2: any) => FrameScene | null
    fields: (scene: FrameScene | null) => StateField[]
    visibleFields: (
      fields: StateField[],
      states: Record<string, Record<string, any>>,
      stateChanges: Record<string, any>,
      arg: any
    ) => StateField[]
    scenesAsOptions: (scenes: FrameScene[] | undefined) => {
      label: string
      value: string
    }[]
    hasStateChanges: (
      stateChanges: Record<string, any>,
      loading: boolean | string,
      states: Record<string, Record<string, any>>,
      arg: any
    ) => boolean
  }
}

export type expandedSceneLogicType = MakeLogicType<
  expandedSceneLogicValues,
  expandedSceneLogicActions,
  ExpandedSceneLogicProps
> &
  expandedSceneLogicMeta

export const expandedSceneLogic = kea<expandedSceneLogicType>([
  path(['src', 'scenes', 'frame', 'panels', 'Scenes', 'expandedSceneLogic']),
  props({} as ExpandedSceneLogicProps),
  key((props) => `${props.frameId}${props.sceneId}`),
  connect(({ frameId }: ExpandedSceneLogicProps) => ({
    logic: [longRunningTasksModel],
    values: [frameLogic({ frameId }), ['frame', 'frameForm'], controlLogic({ frameId }), ['states', 'loading']],
    actions: [frameLogic({ frameId }), ['updateScene', 'applyTemplate']],
  })),
  forms(({ values, props }) => ({
    stateChanges: {
      defaults: {} as Record<string, any>,
      submit: async (formValues) => {
        longRunningTasksModel.actions.startTask({
          frameId: props.frameId,
          kind: 'activate',
          sceneId: props.sceneId,
          title: 'Activating scene',
          detail: values.scene?.name || props.sceneId,
        })
        const state: Record<string, any> = {}
        // Only submit fields the user can currently see, matching the
        // on-frame control page: hidden fields keep their current values
        const fields = visiblePublicStateFields(
          values.scene?.fields ?? [],
          values.states[props.sceneId] ?? {},
          formValues
        )
        try {
          for (const field of fields) {
            if (field.name in formValues && field.access === 'public') {
              if (field.type === 'boolean') {
                state[field.name] = formValues[field.name] === 'true' || field.value
              } else if (field.type === 'integer') {
                state[field.name] = parseInt(formValues[field.name] ?? field.value)
              } else if (field.type === 'float') {
                state[field.name] = parseFloat(formValues[field.name] ?? field.value)
              } else {
                state[field.name] = formValues[field.name] ?? field.value
              }
            }
          }
          const response = await apiFetch(`/api/frames/${props.frameId}/event/setCurrentScene`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ sceneId: props.sceneId, state }),
          })
          if (!response.ok) {
            throw new Error('Failed to send scene activation event')
          }
          const redeployed = activationWasRedeploy(await response.text())
          controlLogic({ frameId: props.frameId }).actions.currentSceneChanged(props.sceneId)
          socketLogic.actions.updateFrame({ id: props.frameId, active_scene_id: props.sceneId } as FrameType)
          longRunningTasksModel.actions.finishTask({
            frameId: props.frameId,
            kind: 'activate',
            sceneId: props.sceneId,
            status: 'success',
            detail: redeployed
              ? `${values.scene?.name || props.sceneId} — deployed, the frame shows it as soon as it syncs`
              : values.scene?.name || props.sceneId,
          })
        } catch (error) {
          longRunningTasksModel.actions.taskFailed({
            frameId: props.frameId,
            kind: 'activate',
            sceneId: props.sceneId,
            detail: error instanceof Error ? error.message : 'Failed to activate scene',
          })
          throw error
        }
      },
    },
  })),
  selectors({
    scenes: [
      (s) => [s.frame, s.frameForm],
      (frame: expandedSceneLogicValues['frame'], frameForm: expandedSceneLogicValues['frameForm']) =>
        frameForm.scenes ?? frame.scenes,
    ],
    scene: [
      (s) => [s.scenes, (_, p) => p.sceneId, (_, p) => p.scene],
      (scenes: expandedSceneLogicValues['scenes'], sceneId, sceneOverride): FrameScene | null =>
        sceneOverride ?? scenes?.find((scene) => scene.id === sceneId) ?? null,
    ],
    fields: [
      (s) => [s.scene],
      (scene: expandedSceneLogicValues['scene']) => (scene?.fields ?? []).filter((field) => field.access === 'public'),
    ],
    visibleFields: [
      (s) => [s.fields, s.states, s.stateChanges, (_, props) => props.sceneId],
      (
        fields: expandedSceneLogicValues['fields'],
        states: expandedSceneLogicValues['states'],
        stateChanges: expandedSceneLogicValues['stateChanges'],
        sceneId
      ) => visiblePublicStateFields(fields, states[sceneId] ?? {}, stateChanges),
    ],
    scenesAsOptions: [
      (s) => [s.scenes],
      (scenes: expandedSceneLogicValues['scenes']): { label: string; value: string }[] =>
        (scenes ?? []).map((scene) => ({
          label: scene.name || 'Unnamed Scene',
          value: scene.id || '',
        })),
    ],
    hasStateChanges: [
      (s) => [s.stateChanges, s.loading, s.states, (_, props) => props.sceneId],
      (
        stateChanges: expandedSceneLogicValues['stateChanges'],
        loading: expandedSceneLogicValues['loading'],
        states: expandedSceneLogicValues['states'],
        sceneId
      ) => {
        if (loading && !states) {
          return false
        }
        const currentState = states[sceneId] ?? {}
        return Object.keys(stateChanges).some((key) => stateChanges[key] !== currentState[key])
      },
    ],
  }),
])
