import { MakeLogicType, actions, kea, path, reducers, selectors } from 'kea'

import { SceneActionKey, normalizeSceneActionKey } from '../../../../utils/sceneActions'

export type { SceneActionKey }

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface sceneActionsLogicValues {
  preferredSceneAction: SceneActionKey | null
  storedSceneAction: string | null
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface sceneActionsLogicActions {
  setPreferredSceneAction: (action: SceneActionKey) => {
    action: SceneActionKey
  }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface sceneActionsLogicMeta {
  __keaTypeGenInternalSelectorTypes: {
    preferredSceneAction: (storedSceneAction: string | null) => SceneActionKey | null
  }
}

export type sceneActionsLogicType = MakeLogicType<
  sceneActionsLogicValues,
  sceneActionsLogicActions,
  Record<string, any>
> &
  sceneActionsLogicMeta

/**
 * Global, persisted preference for the scene action split-button: picking an
 * option from the dropdown runs it and makes it the default everywhere.
 * `null` means the user hasn't picked yet — each context supplies its own
 * default (matching what the old standalone buttons did).
 */
export const sceneActionsLogic = kea<sceneActionsLogicType>([
  path(['src', 'scenes', 'frame', 'panels', 'Scenes', 'sceneActionsLogic']),
  actions({
    setPreferredSceneAction: (action: SceneActionKey) => ({ action }),
  }),
  reducers({
    // Kept as a raw string: the browser may hold a key from an older build
    // ('activate', 'preview-frame'), which the selector below folds into the
    // two keys that exist now.
    storedSceneAction: [
      null as string | null,
      { persist: true, storageKey: 'scenes.preferredSceneAction' },
      {
        setPreferredSceneAction: (_, { action }) => action,
      },
    ],
  }),
  selectors({
    preferredSceneAction: [
      (s) => [s.storedSceneAction],
      (storedSceneAction: sceneActionsLogicValues['storedSceneAction']): SceneActionKey | null =>
        storedSceneAction === null ? null : normalizeSceneActionKey(storedSceneAction),
    ],
  }),
])
