import { MakeLogicType, actions, afterMount, connect, kea, key, listeners, path, props, reducers, selectors } from 'kea'
import { FrameScene, SceneNodeData, FrameId } from '../../../../types'
import { frameLogic, sanitizeScene, sceneEqualForComparison } from '../../frameLogic'
import { undeployedSceneIdsFor } from '../../../../utils/sceneDeployState'
import { workspaceMode } from '../../../workspace/workspaceSurfaces'
import { appsModel } from '../../../../models/appsModel'
import { sceneUpdatesLogic } from './sceneUpdatesLogic'
import { forms } from 'kea-forms'
import { v4 as uuidv4 } from 'uuid'
import { frameEditorsLogic } from '../../frameEditorsLogic'
import { controlLogic } from './controlLogic'
import { collectSecretSettingsFromScenes } from '../secretSettings'
import { apiFetch } from '../../../../utils/apiFetch'
import { isCloudMode } from '../../../../utils/cloudMode'
import { isInFrameAdminMode } from '../../../../utils/frameAdmin'
import { frameAssetsApiPath } from '../../../../utils/frameAssetsApi'
import { uploadFileInChunks } from '../../../../utils/uploadFileInChunks'
import { buildSdCardImageScene } from './sceneShortcuts'
import { assignSceneImages } from '../../../../utils/sceneImages'
import { socketLogic } from '../../../socketLogic'
import { longRunningTasksModel } from '../../../../models/longRunningTasksModel'
import { embeddedUsbApiCanUse, runEmbeddedUsbApiCommand } from '../../../../models/embeddedUsbLogsModel'
import { embeddedUsbUploadTimeoutMs, scheduleEmbeddedUsbFrameImageRefresh } from '../../../../models/framesModel'
import type { DeepPartial, DeepPartialMap, FieldName, ValidationErrorType } from 'kea-forms'
import type { AppConfig, FrameType } from '../../../../types'
import type { TemplateType } from '../../../../types'

export interface ScenesLogicProps {
  frameId: FrameId
}

export interface SceneRenameDialog {
  sceneId: string
  name: string
}

const UPLOADED_SCENE_PREFIX = 'uploaded/'

const applyStateToSceneFields = (scene: FrameScene, state: Record<string, any> | null): FrameScene => {
  if (!state || !scene.fields?.length) {
    return scene
  }
  const fields = scene.fields.map((field) => {
    if (!field?.name) {
      return field
    }
    if (Object.prototype.hasOwnProperty.call(state, field.name)) {
      return { ...field, value: String(state[field.name]) }
    }
    return field
  })
  return { ...scene, fields }
}

function referencedSceneIds(scene: FrameScene): string[] {
  const sceneIds = new Set<string>()

  for (const node of scene.nodes ?? []) {
    const data = node.data as any
    if (node.type === 'scene' && typeof data?.keyword === 'string' && data.keyword) {
      sceneIds.add(data.keyword)
    } else if (node.type === 'dispatch' && data?.keyword === 'setCurrentScene') {
      const targetSceneId = data?.config?.sceneId
      if (typeof targetSceneId === 'string' && targetSceneId) {
        sceneIds.add(targetSceneId)
      }
    }
  }

  return Array.from(sceneIds)
}

export function collectScenePreviewPayloadScenes(
  rootScene: FrameScene,
  scenes: FrameScene[],
  resolvedState: Record<string, any> | null
): FrameScene[] {
  const sceneById = new Map(scenes.map((scene) => [scene.id, scene]))
  const result: FrameScene[] = []
  const visited = new Set<string>()

  const visit = (scene: FrameScene, isRoot = false): void => {
    if (visited.has(scene.id)) {
      return
    }
    visited.add(scene.id)
    result.push(isRoot ? applyStateToSceneFields(scene, resolvedState) : scene)

    for (const referencedSceneId of referencedSceneIds(scene)) {
      const referencedScene = sceneById.get(referencedSceneId)
      if (referencedScene) {
        visit(referencedScene)
      }
    }
  }

  visit(rootScene, true)
  return result
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface scenesLogicValues {
  apps: Record<string, AppConfig> // appsModel
  activeSceneId: string // controlLogic
  states: Record<string, Record<string, any>> // controlLogic
  uploadedScenes: FrameScene[] // controlLogic
  uploadedScenesLoading: boolean // controlLogic
  frame: FrameType // frameLogic
  frameForm: Partial<FrameType> // frameLogic
  isFrameAdminMode: boolean // frameLogic
  lastDeploy: Partial<FrameType> | null // frameLogic
  sceneUpdateVersions: Record<string, string> // sceneUpdatesLogic
  activeScene: FrameScene | null
  activeSettingsKey: string | null
  activeUploadedScene: FrameScene | null
  aiError: string | null
  aiPrompt: string
  aiSceneFormLocation: string | null
  aiSceneLastLog: {
    message: string
    stage?: string | undefined
    status?: string | undefined
    timestamp: string
  } | null
  aiSceneLogs: {
    message: string
    stage?: string | undefined
    status?: string | undefined
    timestamp: string
  }[]
  aiSceneLogsByRequestId: Record<
    string,
    {
      message: string
      stage?: string
      status?: string
      timestamp: string
    }[]
  >
  aiSceneLogsExpanded: boolean
  aiSceneRequestId: string | null
  editingFrame: Partial<FrameType>
  expandedScenes: Record<string, boolean>
  filteredScenes: FrameScene[]
  focusedSceneId: string | null
  frameId: FrameId
  isGeneratingAiScene: boolean
  isInstallingMissingActiveScene: boolean
  isNewSceneSubmitting: boolean
  isNewSceneValid: boolean
  isUploadingImage: boolean
  linkedActiveSceneId: string | null
  linksToOtherScenes: Record<string, Set<string>>
  missingActiveExpanded: boolean
  missingActiveMatchesSearch: boolean
  missingActiveSceneId: string | null
  multiSelectEnabled: boolean
  newScene: {
    name: string
  }
  newSceneAllErrors: Record<string, any>
  newSceneChanged: boolean
  newSceneErrors: DeepPartialMap<
    {
      name: string
    },
    ValidationErrorType
  >
  newSceneFormLocation: string | null
  newSceneHasErrors: boolean
  newSceneManualErrors: Record<string, any>
  newSceneTouched: boolean
  newSceneTouches: Record<string, boolean>
  newSceneValidationErrors: DeepPartialMap<
    {
      name: string
    },
    ValidationErrorType
  >
  otherScenesLinkingToScene: Record<string, Set<string>>
  previewingSceneId: string | null
  rawScenes: FrameScene[]
  renameSceneDialog: SceneRenameDialog | null
  sceneSecretSettings: Map<string, string[]>
  sceneTitles: {
    [k: string]: string
  }
  scenes: FrameScene[]
  search: string
  selectedSceneIds: Set<string>
  showNewSceneErrors: boolean
  showingSettings: Record<string, boolean>
  undeployedSceneIds: Set<string>
  unsavedSceneIds: Set<string>
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface scenesLogicActions {
  syncActiveScene: () => {
    value: true
  } // controlLogic
  closeSceneEditors: (sceneIds: string[]) => {
    sceneIds: string[]
  } // frameEditorsLogic
  editScene: (sceneId: string) => {
    sceneId: string
  } // frameEditorsLogic
  applyTemplate: (
    template: Partial<TemplateType>,
    openDrawer?: boolean | undefined,
    preserveSceneIds?: boolean | undefined
  ) => {
    openDrawer: boolean
    preserveSceneIds: boolean
    template: Partial<TemplateType>
  } // frameLogic
  sendEvent: (
    event: string,
    payload: Record<string, any>
  ) => {
    event: string
    payload: Record<string, any>
  } // frameLogic
  updateSceneFromRepo: (sceneId: string) => {
    sceneId: string
  } // sceneUpdatesLogic
  clearFocusedScene: () => {
    value: true
  }
  clearSceneSelection: () => {
    value: true
  }
  closeAiScene: () => {
    value: true
  }
  closeNewScene: () => {
    value: true
  }
  closeRenameSceneDialog: () => {
    value: true
  }
  copySceneJSON: (sceneId: string) => {
    sceneId: string
  }
  createNewScene: () => {
    value: true
  }
  deleteScene: (sceneId: string) => {
    sceneId: string
  }
  deleteSelectedScenes: () => {
    value: true
  }
  disableMultiSelect: () => {
    value: true
  }
  duplicateScene: (sceneId: string) => {
    sceneId: string
  }
  enableMultiSelect: () => {
    value: true
  }
  expandScene: (sceneId: string) => {
    sceneId: string
  }
  focusScene: (sceneId: string) => {
    sceneId: string
  }
  generateAiScene: () => {
    value: true
  }
  generateAiSceneFailure: (error: string) => {
    error: string
  }
  generateAiSceneSuccess: () => {
    value: true
  }
  installMissingActiveScene: () => {
    value: true
  }
  installMissingActiveSceneFailure: () => {
    value: true
  }
  installMissingActiveSceneSuccess: () => {
    value: true
  }
  openAiScene: (location: string) => {
    location: string
  }
  openNewScene: (location: string) => {
    location: string
  }
  openRenameSceneDialog: (
    sceneId: string,
    name: string
  ) => {
    name: string
    sceneId: string
  }
  previewScene: (
    sceneId: string,
    state?: Record<string, any> | null,
    scenes?: FrameScene[] | null
  ) => {
    sceneId: string
    scenes: FrameScene[] | null
    state: Record<string, any> | null | undefined
  }
  previewSceneFailure: () => {
    value: true
  }
  previewSceneSuccess: () => {
    value: true
  }
  removeDefault: () => {
    value: true
  }
  renameScene: (sceneId: string) => {
    sceneId: string
  }
  resetNewScene: (values?: { name: string }) => {
    values?: {
      name: string
    }
  }
  setActiveSettingsKey: (activeSettingsKey: string | null) => {
    activeSettingsKey: string | null
  }
  setAiPrompt: (prompt: string) => {
    prompt: string
  }
  setAiSceneLogMessage: (log: {
    message: string
    requestId: string
    stage?: string
    status?: string
    timestamp: string
  }) => {
    log: {
      message: string
      requestId: string
      stage?: string | undefined
      status?: string | undefined
      timestamp: string
    }
  }
  setAiSceneLogsExpanded: (expanded: boolean) => {
    expanded: boolean
  }
  setAiSceneRequestId: (requestId: string | null) => {
    requestId: string | null
  }
  setAsDefault: (sceneId: string) => {
    sceneId: string
  }
  setNewSceneManualErrors: (errors: Record<string, any>) => {
    errors: Record<string, any>
  }
  setNewSceneValue: (
    key: FieldName,
    value: any
  ) => {
    name: FieldName
    value: any
  }
  setNewSceneValues: (
    values: DeepPartial<{
      name: string
    }>
  ) => {
    values: DeepPartial<{
      name: string
    }>
  }
  setRenameSceneName: (name: string) => {
    name: string
  }
  setSearch: (search: string) => {
    search: string
  }
  setSelectedSceneIds: (sceneIds: string[]) => {
    sceneIds: string[]
  }
  submitNewScene: () => {
    value: boolean
  }
  submitNewSceneFailure: (
    error: Error,
    errors: Record<string, any>
  ) => {
    error: Error
    errors: Record<string, any>
  }
  submitNewSceneRequest: (newScene: { name: string }) => {
    newScene: {
      name: string
    }
  }
  submitNewSceneSuccess: (newScene: { name: string }) => {
    newScene: {
      name: string
    }
  }
  submitRenameScene: () => {
    value: true
  }
  sync: () => {
    value: true
  }
  toggleAiSceneLogsExpanded: () => {
    value: true
  }
  toggleMissingActiveExpanded: () => {
    value: true
  }
  toggleSceneSelection: (sceneId: string) => {
    sceneId: string
  }
  toggleSettings: (sceneId: string) => {
    sceneId: string
  }
  touchNewSceneField: (key: string) => {
    key: string
  }
  uploadImage: (file: File) => {
    file: File
  }
  uploadImageFailure: () => {
    value: true
  }
  uploadImageSuccess: () => {
    value: true
  }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface scenesLogicMeta {
  key: FrameId
  __keaTypeGenInternalSelectorTypes: {
    frameId: (arg: FrameId) => FrameId
    editingFrame: (frameForm: Partial<FrameType>, frame: FrameType) => Partial<FrameType>
    rawScenes: (editingFrame: Partial<FrameType>) => FrameScene[]
    undeployedSceneIds: (rawScenes: FrameScene[], frame: FrameType, isFrameAdminMode: boolean) => Set<string>
    unsavedSceneIds: (frame: FrameType, frameForm: Partial<FrameType>) => Set<string>
    scenes: (rawScenes: FrameScene[], unsavedSceneIds: Set<string>, undeployedSceneIds: Set<string>) => FrameScene[]
    filteredScenes: (scenes: FrameScene[], search: string) => FrameScene[]
    sceneTitles: (scenes: FrameScene[]) => {
      [k: string]: string
    }
    linksToOtherScenes: (scenes: FrameScene[]) => Record<string, Set<string>>
    otherScenesLinkingToScene: (linksToOtherScenes: Record<string, Set<string>>) => Record<string, Set<string>>
    sceneSecretSettings: (scenes: FrameScene[], apps: Record<string, AppConfig>) => Map<string, string[]>
    linkedActiveSceneId: (activeSceneId: string, scenes: FrameScene[]) => string | null
    activeScene: (scenes: FrameScene[], linkedActiveSceneId: string | null) => FrameScene | null
    missingActiveSceneId: (activeScene: FrameScene | null, activeSceneId: string) => string | null
    activeUploadedScene: (missingActiveSceneId: string | null, uploadedScenes: FrameScene[]) => FrameScene | null
    missingActiveMatchesSearch: (
      search: string,
      missingActiveSceneId: string | null,
      activeUploadedScene: FrameScene | null
    ) => boolean
    aiSceneLastLog: (
      aiSceneRequestId: string | null,
      aiSceneLogsByRequestId: Record<
        string,
        {
          message: string
          stage?: string
          status?: string
          timestamp: string
        }[]
      >
    ) => {
      message: string
      stage?: string | undefined
      status?: string | undefined
      timestamp: string
    } | null
    aiSceneLogs: (
      aiSceneRequestId: string | null,
      aiSceneLogsByRequestId: Record<
        string,
        {
          message: string
          stage?: string
          status?: string
          timestamp: string
        }[]
      >
    ) => {
      message: string
      stage?: string | undefined
      status?: string | undefined
      timestamp: string
    }[]
  }
}

export type scenesLogicType = MakeLogicType<scenesLogicValues, scenesLogicActions, ScenesLogicProps> & scenesLogicMeta

export const scenesLogic = kea<scenesLogicType>([
  path(['src', 'scenes', 'frame', 'panels', 'Scenes', 'scenesLogic']),
  props({} as ScenesLogicProps),
  key((props) => props.frameId),
  connect(({ frameId }: ScenesLogicProps) => ({
    logic: [socketLogic],
    values: [
      frameLogic({ frameId }),
      ['frame', 'frameForm', 'lastDeploy', 'isFrameAdminMode'],
      appsModel,
      ['apps'],
      controlLogic({ frameId }),
      ['sceneId as activeSceneId', 'uploadedScenes', 'uploadedScenesLoading', 'states'],
      sceneUpdatesLogic({ frameId }),
      ['sceneUpdateVersions'],
    ],
    actions: [
      frameLogic({ frameId }),
      ['applyTemplate', 'sendEvent'],
      frameEditorsLogic({ frameId }),
      ['editScene', 'closeSceneEditors'],
      controlLogic({ frameId }),
      ['sync as syncActiveScene'],
      sceneUpdatesLogic({ frameId }),
      ['updateSceneFromRepo'],
    ],
  })),
  actions({
    toggleSettings: (sceneId: string) => ({ sceneId }),
    setAsDefault: (sceneId: string) => ({ sceneId }),
    removeDefault: true,
    deleteScene: (sceneId: string) => ({ sceneId }),
    deleteSelectedScenes: true,
    renameScene: (sceneId: string) => ({ sceneId }),
    openRenameSceneDialog: (sceneId: string, name: string) => ({ sceneId, name }),
    setRenameSceneName: (name: string) => ({ name }),
    closeRenameSceneDialog: true,
    submitRenameScene: true,
    duplicateScene: (sceneId: string) => ({ sceneId }),
    openNewScene: (location: string) => ({ location }),
    closeNewScene: true,
    createNewScene: true,
    openAiScene: (location: string) => ({ location }),
    closeAiScene: true,
    sync: true,
    expandScene: (sceneId: string) => ({ sceneId }),
    copySceneJSON: (sceneId: string) => ({ sceneId }),
    setSearch: (search: string) => ({ search }),
    setActiveSettingsKey: (activeSettingsKey: string | null) => ({ activeSettingsKey }),
    enableMultiSelect: true,
    disableMultiSelect: true,
    clearSceneSelection: true,
    toggleSceneSelection: (sceneId: string) => ({ sceneId }),
    setSelectedSceneIds: (sceneIds: string[]) => ({ sceneIds }),
    toggleMissingActiveExpanded: true,
    uploadImage: (file: File) => ({ file }),
    uploadImageSuccess: true,
    uploadImageFailure: true,
    previewScene: (sceneId: string, state?: Record<string, any> | null, scenes?: FrameScene[] | null) => ({
      sceneId,
      state,
      scenes: scenes ?? null,
    }),
    previewSceneSuccess: true,
    previewSceneFailure: true,
    setAiPrompt: (prompt: string) => ({ prompt }),
    generateAiScene: true,
    generateAiSceneSuccess: true,
    generateAiSceneFailure: (error: string) => ({ error }),
    setAiSceneRequestId: (requestId: string | null) => ({ requestId }),
    setAiSceneLogMessage: (log: {
      requestId: string
      message: string
      status?: string
      stage?: string
      timestamp: string
    }) => ({
      log,
    }),
    toggleAiSceneLogsExpanded: true,
    setAiSceneLogsExpanded: (expanded: boolean) => ({ expanded }),
    installMissingActiveScene: true,
    installMissingActiveSceneSuccess: true,
    installMissingActiveSceneFailure: true,
    focusScene: (sceneId: string) => ({ sceneId }),
    clearFocusedScene: true,
  }),
  forms(({ actions, values, props }) => ({
    newScene: {
      defaults: {
        name: '',
      },
      errors: (values) => ({
        name: !values.name ? 'Name is required' : undefined,
      }),
      submit: ({ name }, breakpoint) => {
        const scenes: FrameScene[] = values.frameForm.scenes || []
        const id = uuidv4()
        frameLogic({ frameId: props.frameId }).actions.setFrameFormValues({
          scenes: [
            ...scenes,
            sanitizeScene(
              {
                id,
                name,
                nodes: [
                  {
                    id: '463556ab-e4fe-40c7-93f3-40bc723f454e',
                    type: 'event',
                    position: {
                      x: 121,
                      y: 113,
                    },
                    data: {
                      keyword: 'render',
                    },
                    width: 99,
                    height: 40,
                  },
                ],
                edges: [],
                fields: [],
                settings: { execution: 'interpreted' },
              },
              values.frameForm
            ),
          ],
        })
        actions.editScene(id)
        actions.resetNewScene()
      },
    },
  })),
  reducers(() => ({
    search: [
      '',
      {
        setSearch: (_, { search }) => search,
      },
    ],
    newSceneFormLocation: [
      null as string | null,
      {
        openNewScene: (_, { location }) => location,
        closeNewScene: () => null,
        submitNewSceneSuccess: () => null,
      },
    ],
    aiSceneFormLocation: [
      null as string | null,
      {
        openAiScene: (_, { location }) => location,
        closeAiScene: () => null,
      },
    ],
    renameSceneDialog: [
      null as SceneRenameDialog | null,
      {
        openRenameSceneDialog: (_, { sceneId, name }) => ({ sceneId, name }),
        setRenameSceneName: (state, { name }) => (state ? { ...state, name } : state),
        closeRenameSceneDialog: () => null,
        deleteScene: (state, { sceneId }) => (state?.sceneId === sceneId ? null : state),
      },
    ],
    showingSettings: [
      {} as Record<string, boolean>,
      {
        toggleSettings: (state, { sceneId }) => ({ ...state, [sceneId]: !state[sceneId] }),
      },
    ],
    expandedScenes: [
      {} as Record<string, boolean>,
      {
        expandScene: (state, { sceneId }) => ({ ...state, [sceneId]: !state[sceneId] }),
      },
    ],
    activeSettingsKey: [
      null as string | null,
      {
        setActiveSettingsKey: (_, { activeSettingsKey }) => activeSettingsKey,
      },
    ],
    multiSelectEnabled: [
      false,
      {
        enableMultiSelect: () => true,
        disableMultiSelect: () => false,
      },
    ],
    isUploadingImage: [
      false,
      {
        uploadImage: () => true,
        uploadImageSuccess: () => false,
        uploadImageFailure: () => false,
      },
    ],
    previewingSceneId: [
      null as string | null,
      {
        previewScene: (_, { sceneId }) => sceneId,
        previewSceneSuccess: () => null,
        previewSceneFailure: () => null,
      },
    ],
    focusedSceneId: [
      null as string | null,
      {
        focusScene: (_, { sceneId }) => sceneId,
        clearFocusedScene: () => null,
      },
    ],
    aiPrompt: [
      '',
      {
        setAiPrompt: (_, { prompt }) => prompt,
        closeAiScene: () => '',
      },
    ],
    aiError: [
      null as string | null,
      {
        generateAiScene: () => null,
        generateAiSceneFailure: (_, { error }) => error,
        closeAiScene: () => null,
      },
    ],
    aiSceneRequestId: [
      null as string | null,
      {
        setAiSceneRequestId: (_, { requestId }) => requestId,
        closeAiScene: () => null,
      },
    ],
    aiSceneLogsByRequestId: [
      {} as Record<string, { message: string; status?: string; stage?: string; timestamp: string }[]>,
      {
        setAiSceneLogMessage: (state, { log }) => ({
          ...state,
          [log.requestId]: [...(state[log.requestId] ?? []), log],
        }),
        [socketLogic.actionTypes.aiSceneLog]: (state, { log }) => {
          if (!log.requestId) {
            return state
          }
          return {
            ...state,
            [log.requestId]: [...(state[log.requestId] ?? []), log],
          }
        },
      },
    ],
    aiSceneLogsExpanded: [
      false,
      {
        toggleAiSceneLogsExpanded: (state) => !state,
        setAiSceneLogsExpanded: (_, { expanded }) => expanded,
        closeAiScene: () => false,
      },
    ],
    isGeneratingAiScene: [
      false,
      {
        generateAiScene: () => true,
        generateAiSceneSuccess: () => false,
        generateAiSceneFailure: () => false,
      },
    ],
    isInstallingMissingActiveScene: [
      false,
      {
        installMissingActiveScene: () => true,
        installMissingActiveSceneSuccess: () => false,
        installMissingActiveSceneFailure: () => false,
      },
    ],
    missingActiveExpanded: [
      false,
      {
        toggleMissingActiveExpanded: (state) => !state,
      },
    ],
    selectedSceneIds: [
      new Set<string>(),
      {
        toggleSceneSelection: (state, { sceneId }) => {
          const next = new Set(state)
          if (next.has(sceneId)) {
            next.delete(sceneId)
          } else {
            next.add(sceneId)
          }
          return next
        },
        clearSceneSelection: () => new Set<string>(),
        setSelectedSceneIds: (_, { sceneIds }) => new Set(sceneIds),
        disableMultiSelect: () => new Set<string>(),
        deleteScene: (state, { sceneId }) => {
          const next = new Set(state)
          next.delete(sceneId)
          return next
        },
      },
    ],
  })),
  selectors({
    frameId: [() => [(_, props: ScenesLogicProps) => props.frameId], (frameId: FrameId) => frameId],
    editingFrame: [
      (s) => [s.frameForm, s.frame],
      (frameForm: scenesLogicValues['frameForm'], frame: scenesLogicValues['frame']) => frameForm || frame || null,
    ],
    rawScenes: [
      (s) => [s.editingFrame],
      (frame: scenesLogicValues['editingFrame']): FrameScene[] => frame?.scenes ?? [],
    ],
    undeployedSceneIds: [
      (s) => [s.rawScenes, s.frame, s.isFrameAdminMode],
      (
        scenes: scenesLogicValues['rawScenes'],
        frame: scenesLogicValues['frame'],
        isFrameAdminMode: scenesLogicValues['isFrameAdminMode']
      ): Set<string> =>
        undeployedSceneIdsFor({
          mode: isFrameAdminMode ? 'frameAdmin' : workspaceMode(),
          scenes,
          frame,
          scenesEqual: sceneEqualForComparison,
        }),
    ],
    unsavedSceneIds: [
      (s) => [s.frame, s.frameForm],
      (frame: scenesLogicValues['frame'], frameForm: scenesLogicValues['frameForm']): Set<string> => {
        // frame is null until framesModel has loaded, e.g. when the workspace
        // scene control panel mounts this logic on a fresh page load.
        const frameScenes = frame?.scenes || []
        const unsavedScenes = frameForm?.scenes || frame?.scenes || []
        const unsaved = new Set<string>()
        unsavedScenes.forEach((scene) => {
          const original = frameScenes.find((s) => s.id === scene.id)
          if (!original || !sceneEqualForComparison(original, scene)) {
            unsaved.add(scene.id)
          }
        })
        return unsaved
      },
    ],
    scenes: [
      (s) => [s.rawScenes, s.unsavedSceneIds, s.undeployedSceneIds],
      (
        rawScenes: scenesLogicValues['rawScenes'],
        unsavedSceneIds: scenesLogicValues['unsavedSceneIds'],
        undeployedSceneIds: scenesLogicValues['undeployedSceneIds']
      ) => {
        return rawScenes.toSorted((a, b) => {
          const aPriority = unsavedSceneIds.has(a.id) || undeployedSceneIds.has(a.id)
          const bPriority = unsavedSceneIds.has(b.id) || undeployedSceneIds.has(b.id)
          if (aPriority !== bPriority) {
            return aPriority ? -1 : 1
          }
          return a.name.localeCompare(b.name)
        })
      },
    ],
    filteredScenes: [
      (s) => [s.scenes, s.search],
      (scenes: scenesLogicValues['scenes'], search: scenesLogicValues['search']) => {
        const searchPieces = search
          .toLowerCase()
          .split(' ')
          .filter((s) => s)
        if (searchPieces.length === 0) {
          return scenes
        }
        return scenes.filter((scene) => searchPieces.every((piece) => scene.name.toLowerCase().includes(piece)))
      },
    ],
    sceneTitles: [
      (s) => [s.scenes],
      (scenes: scenesLogicValues['scenes']) => Object.fromEntries(scenes.map((scene) => [scene.id, scene.name])),
    ],
    linksToOtherScenes: [
      (s) => [s.scenes],
      (scenes: scenesLogicValues['scenes']): Record<string, Set<string>> => {
        return Object.fromEntries(
          scenes.map((scene) => [
            scene.id,
            new Set<string>(
              scene.nodes
                .filter((node) => node.type === 'scene')
                .map((node) => (node.data as SceneNodeData)?.keyword)
                .filter(Boolean)
            ),
          ])
        )
      },
    ],
    otherScenesLinkingToScene: [
      (s) => [s.linksToOtherScenes],
      (links: scenesLogicValues['linksToOtherScenes']): Record<string, Set<string>> => {
        const result: Record<string, Set<string>> = {}
        Object.entries(links).forEach(([sceneId, linkedScenes]) => {
          linkedScenes.forEach((linkedScene) => {
            result[linkedScene] ||= new Set()
            result[linkedScene].add(sceneId)
          })
        })
        return result
      },
    ],
    sceneSecretSettings: [
      (s) => [s.scenes, s.apps],
      (scenes: scenesLogicValues['scenes'], apps: scenesLogicValues['apps']): Map<string, string[]> => {
        const settingsByScene = new Map<string, string[]>()
        for (const scene of scenes) {
          const secretSettings = collectSecretSettingsFromScenes([scene], apps)
          if (secretSettings.length) {
            settingsByScene.set(scene.id, secretSettings)
          }
        }
        return settingsByScene
      },
    ],
    linkedActiveSceneId: [
      (s) => [s.activeSceneId, s.scenes],
      (activeSceneId: scenesLogicValues['activeSceneId'], scenes: scenesLogicValues['scenes']) => {
        if (!activeSceneId) {
          return null
        }
        if (!activeSceneId.startsWith(UPLOADED_SCENE_PREFIX)) {
          return activeSceneId
        }
        const candidateId = activeSceneId.slice(UPLOADED_SCENE_PREFIX.length)
        return scenes.some((scene) => scene.id === candidateId) ? candidateId : activeSceneId
      },
    ],
    activeScene: [
      (s) => [s.scenes, s.linkedActiveSceneId],
      (scenes: scenesLogicValues['scenes'], linkedActiveSceneId: scenesLogicValues['linkedActiveSceneId']) =>
        scenes.find((scene) => scene.id === linkedActiveSceneId) ?? null,
    ],
    missingActiveSceneId: [
      (s) => [s.activeScene, s.activeSceneId],
      (activeScene: scenesLogicValues['activeScene'], activeSceneId: scenesLogicValues['activeSceneId']) =>
        !activeScene && activeSceneId ? activeSceneId : null,
    ],
    activeUploadedScene: [
      (s) => [s.missingActiveSceneId, s.uploadedScenes],
      (
        missingActiveSceneId: scenesLogicValues['missingActiveSceneId'],
        uploadedScenes: scenesLogicValues['uploadedScenes']
      ) =>
        missingActiveSceneId
          ? uploadedScenes.find((scene) => `uploaded/${scene.id}` === missingActiveSceneId) ?? null
          : null,
    ],
    missingActiveMatchesSearch: [
      (s) => [s.search, s.missingActiveSceneId, s.activeUploadedScene],
      (
        search: scenesLogicValues['search'],
        missingActiveSceneId: scenesLogicValues['missingActiveSceneId'],
        activeUploadedScene: scenesLogicValues['activeUploadedScene']
      ) => {
        if (!missingActiveSceneId) {
          return false
        }
        const searchPieces = search
          .toLowerCase()
          .split(' ')
          .filter((s) => s)
        if (searchPieces.length === 0) {
          return true
        }
        const sceneName = activeUploadedScene?.name?.toLowerCase() ?? ''
        if (!sceneName) {
          return false
        }
        return searchPieces.every((piece) => sceneName.includes(piece))
      },
    ],
    aiSceneLastLog: [
      (s) => [s.aiSceneRequestId, s.aiSceneLogsByRequestId],
      (
        requestId: scenesLogicValues['aiSceneRequestId'],
        logsByRequestId: scenesLogicValues['aiSceneLogsByRequestId']
      ) => {
        if (!requestId) {
          return null
        }
        const logs = logsByRequestId[requestId] ?? []
        return logs.length ? logs[logs.length - 1] : null
      },
    ],
    aiSceneLogs: [
      (s) => [s.aiSceneRequestId, s.aiSceneLogsByRequestId],
      (
        requestId: scenesLogicValues['aiSceneRequestId'],
        logsByRequestId: scenesLogicValues['aiSceneLogsByRequestId']
      ) =>
        requestId
          ? [...(logsByRequestId[requestId] ?? [])].toSorted(
              (left, right) => new Date(left.timestamp).getTime() - new Date(right.timestamp).getTime()
            )
          : [],
    ],
  }),
  listeners(({ actions, values, cache, props }) => ({
    focusScene: ({ sceneId }) => {
      if (!sceneId) {
        return
      }
      if (cache.focusedSceneTimeout) {
        clearTimeout(cache.focusedSceneTimeout)
      }
      cache.focusedSceneTimeout = window.setTimeout(() => {
        actions.clearFocusedScene()
        cache.focusedSceneTimeout = null
      }, 2500)
    },
    generateAiScene: async () => {
      const prompt = values.aiPrompt.trim()
      if (!prompt) {
        actions.generateAiSceneFailure('Add a prompt to generate a scene.')
        return
      }
      const requestId = uuidv4()
      actions.setAiSceneRequestId(requestId)
      actions.setAiSceneLogsExpanded(true)
      try {
        const response = await apiFetch('/api/ai/scenes/generate', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ prompt, requestId, frameId: props.frameId }),
        })
        if (!response.ok) {
          const payload = await response.json().catch(() => ({}))
          throw new Error(payload?.detail || 'Failed to generate scene')
        }
        const payload = await response.json()
        const scenes = Array.isArray(payload?.scenes) ? payload.scenes : []
        const title = typeof payload?.title === 'string' ? payload.title : undefined
        if (!scenes.length) {
          throw new Error('No scenes returned from AI')
        }
        const existingSceneIds = new Set(values.scenes.map((scene) => scene.id))
        const sanitizedScenes = scenes.map((scene: Partial<FrameScene>) => {
          const sanitizedScene = sanitizeScene(scene, values.frameForm)
          return {
            ...sanitizedScene,
            settings: {
              ...sanitizedScene.settings,
              autoArrangeOnLoad: true,
            },
          }
        })
        actions.applyTemplate({ scenes: sanitizedScenes, name: title || 'AI Generated Scene' })
        actions.generateAiSceneSuccess()
        await new Promise((resolve) => setTimeout(resolve, 0))
        const updatedScenes = values.frameForm?.scenes ?? values.scenes
        const newlyAddedScene = updatedScenes.find((scene) => !existingSceneIds.has(scene.id))
        if (newlyAddedScene) {
          actions.focusScene(newlyAddedScene.id)
        }
        actions.setAiSceneLogMessage({
          requestId,
          message: 'Scene generated: ' + (title || 'AI Generated Scene'),
          status: 'success',
          timestamp: new Date().toISOString(),
        })
      } catch (error) {
        console.error(error)
        actions.generateAiSceneFailure(error instanceof Error ? error.message : 'Failed to generate scene')
        actions.setAiSceneLogMessage({
          requestId,
          message: error instanceof Error ? error.message : 'Failed to generate scene',
          status: 'error',
          timestamp: new Date().toISOString(),
        })
      }
    },
    uploadImage: async ({ file }) => {
      try {
        const uploadPath = frameAssetsApiPath(props.frameId, 'assets/upload_image')
        const payload = isInFrameAdminMode()
          ? await uploadFileInChunks({
              frameId: props.frameId,
              suffix: 'assets/upload_image',
              file,
              filename: file.name,
            })
          : await (async () => {
              const formData = new FormData()
              formData.append('file', file)
              const response = await apiFetch(uploadPath, {
                method: 'POST',
                body: formData,
              })
              if (!response.ok) {
                throw new Error('Image upload failed')
              }
              return await response.json()
            })()
        const assetsPath = values.frameForm.assets_path || '/srv/assets'
        const relativePath = payload?.path || ''
        const filename = payload?.filename || relativePath.split('/').pop() || file.name
        const sceneId = uuidv4()
        const scene = buildSdCardImageScene(filename, assetsPath, sceneId)
        await actions.sendEvent('uploadScenes', { scenes: [scene], sceneId })
        actions.uploadImageSuccess()
      } catch (error) {
        console.error(error)
        alert('Failed to upload image')
        actions.uploadImageFailure()
      }
    },
    previewScene: async ({ sceneId, state, scenes }) => {
      // An explicit `scenes` list lets callers preview scenes that aren't
      // installed on the frame, e.g. template previews.
      const sceneList = scenes?.length ? scenes : values.scenes
      const scene = sceneList.find((item) => item.id === sceneId)
      if (!scene) {
        actions.previewSceneFailure()
        return
      }
      const taskKind = values.isFrameAdminMode ? 'activate' : 'preview'
      longRunningTasksModel.actions.startTask({
        frameId: props.frameId,
        kind: taskKind,
        sceneId,
        title: values.isFrameAdminMode ? 'Activating scene' : 'Previewing scene',
        detail: scene.name || scene.id,
      })
      try {
        const resolvedState = state ?? values.states?.[scene.id] ?? values.states?.[`uploaded/${scene.id}`] ?? null
        const payloadScenes = collectScenePreviewPayloadScenes(scene, sceneList, resolvedState)
        const payload = {
          scenes: payloadScenes,
          sceneId: scene.id,
          ...(resolvedState && Object.keys(resolvedState).length > 0 ? { state: resolvedState } : {}),
        }
        let usbSucceeded = false
        if ((values.frame?.mode ?? 'rpios') === 'embedded' && embeddedUsbApiCanUse(props.frameId)) {
          try {
            const payloadBytes = new TextEncoder().encode(JSON.stringify(payload))
            await runEmbeddedUsbApiCommand(props.frameId, 'upload-scenes', {
              payload: payloadBytes,
              timeoutMs: embeddedUsbUploadTimeoutMs(payloadBytes.byteLength),
            })
            scheduleEmbeddedUsbFrameImageRefresh(props.frameId)
            usbSucceeded = true
          } catch (error) {
            // Stale/busy USB port — fall through to the HTTP event.
          }
        }
        if (!usbSucceeded) {
          const response = await apiFetch(`/api/frames/${props.frameId}/event/uploadScenes`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload),
          })
          if (!response.ok) {
            throw new Error('Failed to send preview scene event')
          }
          // On the cloud "accepted" only means "queued on the hub". With the
          // frame offline nothing happens on the panel, and the silent
          // success used to read as "preview does nothing" — say so.
          if (isCloudMode() && values.frame?.connected === false) {
            longRunningTasksModel.actions.finishTask({
              frameId: props.frameId,
              kind: taskKind,
              sceneId,
              detail: 'Queued — the frame is offline; it shows this when it reconnects.',
            })
          }
        }
        actions.previewSceneSuccess()
      } catch (error) {
        console.error(error)
        longRunningTasksModel.actions.taskFailed({
          frameId: props.frameId,
          kind: taskKind,
          sceneId,
          detail:
            error instanceof Error
              ? error.message
              : values.isFrameAdminMode
              ? 'Failed to activate the scene'
              : 'Failed to preview the scene',
        })
        actions.previewSceneFailure()
      }
    },
    installMissingActiveScene: async () => {
      if (!values.uploadedScenes.length) {
        actions.installMissingActiveSceneFailure()
        return
      }
      try {
        const currentState =
          values.missingActiveSceneId && values.states ? values.states[values.missingActiveSceneId] : null
        const uploadedScenes = values.uploadedScenes.map((scene) => {
          if (!values.activeUploadedScene || scene.id !== values.activeUploadedScene.id) {
            return scene
          }
          if (!currentState || !scene.fields?.length) {
            return scene
          }
          const fields = scene.fields.map((field) => {
            if (!field?.name) {
              return field
            }
            if (Object.prototype.hasOwnProperty.call(currentState, field.name)) {
              return { ...field, value: String(currentState[field.name]) }
            }
            return field
          })
          return { ...scene, fields }
        })

        let imageBlob: Blob | null = null
        try {
          const imageResponse = await apiFetch(`/api/frames/${props.frameId}/image`)
          if (imageResponse.ok) {
            imageBlob = await imageResponse.blob()
          }
        } catch (error) {
          console.error('Failed to fetch current frame image', error)
        }

        actions.applyTemplate({
          scenes: uploadedScenes,
          name: values.activeUploadedScene?.name || 'Active scene',
          image: imageBlob ?? undefined,
        })
        actions.installMissingActiveSceneSuccess()
      } catch (error) {
        console.error('Failed to install uploaded scenes', error)
        alert('Failed to install the active scene')
        actions.installMissingActiveSceneFailure()
      }
    },
    setAsDefault: ({ sceneId }) => {
      frameLogic({ frameId: props.frameId }).actions.setFrameFormValues({
        scenes: values.scenes.map((s) =>
          s.id === sceneId ? { ...s, default: true } : s['default'] ? { ...s, default: false } : s
        ),
      })
    },
    removeDefault: () => {
      frameLogic({ frameId: props.frameId }).actions.setFrameFormValues({
        scenes: values.scenes.map((scene) => {
          if ('default' in scene) {
            const { default: _, ...rest } = scene
            return rest
          }
          return scene
        }),
      })
    },
    duplicateScene: async ({ sceneId }) => {
      const scene = values.scenes.find((s) => s.id === sceneId)
      if (!scene) {
        return
      }
      const newSceneId = uuidv4()
      frameLogic({ frameId: props.frameId }).actions.setFrameFormValues({
        scenes: [...values.scenes, { ...scene, default: false, id: newSceneId }],
      })
      // The copy looks exactly like the original until it is edited, so it
      // should not sit at "no snapshot" while its twin shows a picture. The
      // backend copies the stored bytes; nothing goes over the network.
      await assignSceneImages(
        props.frameId,
        [newSceneId],
        { sourceSceneId: sceneId },
        {
          label: 'snapshot',
          ignoreMissingSource: true,
        }
      )
    },
    renameScene: ({ sceneId }) => {
      const scene = values.scenes.find((s) => s.id === sceneId)
      if (!scene) {
        return
      }
      actions.openRenameSceneDialog(sceneId, scene.name ?? '')
    },
    submitRenameScene: () => {
      const dialog = values.renameSceneDialog
      if (!dialog) {
        return
      }
      const sceneName = dialog.name.trim()
      if (!sceneName) {
        return
      }
      const scene = values.scenes.find((s) => s.id === dialog.sceneId)
      if (!scene || scene.name === sceneName) {
        return
      }
      frameLogic({ frameId: props.frameId }).actions.setFrameFormValues({
        scenes: values.scenes.map((s) => (s.id === dialog.sceneId ? { ...s, name: sceneName } : s)),
      })
      actions.closeRenameSceneDialog()
    },
    deleteScene: ({ sceneId }) => {
      frameLogic({ frameId: props.frameId }).actions.setFrameFormValues({
        scenes: values.scenes.filter((s) => s.id !== sceneId),
      })
      actions.closeSceneEditors([sceneId])
    },
    deleteSelectedScenes: () => {
      const selectedIds = Array.from(values.selectedSceneIds)
      if (selectedIds.length === 0) {
        return
      }
      frameLogic({ frameId: props.frameId }).actions.setFrameFormValues({
        scenes: values.scenes.filter((scene) => !values.selectedSceneIds.has(scene.id)),
      })
      selectedIds.forEach((sceneId) => {
        actions.closeSceneEditors([sceneId])
      })
      actions.clearSceneSelection()
    },
    closeNewScene: () => {
      actions.resetNewScene({ name: '' })
    },
    openNewScene: () => {
      actions.resetNewScene({ name: '' })
      actions.closeAiScene()
    },
    openAiScene: () => {
      actions.closeNewScene()
    },
    createNewScene: () => {
      const scenes: FrameScene[] = values.frameForm.scenes || []
      const id = uuidv4()
      frameLogic({ frameId: props.frameId }).actions.setFrameFormValues({
        scenes: [
          ...scenes,
          {
            id,
            name: 'My Scene',
            nodes: [
              {
                id: '463556ab-e4fe-40c7-93f3-40bc723f454e',
                type: 'event',
                position: {
                  x: 121,
                  y: 113,
                },
                data: {
                  keyword: 'render',
                },
                width: 99,
                height: 40,
              },
            ],
            edges: [],
            fields: [],
          },
        ],
      })
      actions.editScene(id)
      actions.resetNewScene()
    },
    copySceneJSON: ({ sceneId }) => {
      const scene = values.scenes.find((s) => s.id === sceneId)
      if (!scene) {
        return
      }
      navigator.clipboard.writeText(JSON.stringify(scene))
    },
  })),
  afterMount(({ actions }) => {
    actions.syncActiveScene()
  }),
])
