import {
  MakeLogicType,
  actions,
  beforeUnmount,
  connect,
  kea,
  key,
  listeners,
  path,
  props,
  reducers,
  selectors,
} from 'kea'

import { entityImagesModel } from '../../../../models/entityImagesModel'
import { socketLogic } from '../../../socketLogic'
import { SCENE_ACTIVATION_TIMEOUT_MS } from '../../../../utils/sceneActivation'
import { sceneIdsRefer } from '../../../../utils/systemScenes'
import type { ScenePreviewSurface } from '../../../../utils/scenePreviewDeploy'
import { controlLogic } from './controlLogic'
import { expandedSceneLogic } from './expandedSceneLogic'
import { livePreviewLogic } from './livePreviewLogic'
import { scenesLogic } from './scenesLogic'
import type { FrameId, FrameScene } from '../../../../types'
import type { LivePreviewSourceTemplate } from './livePreviewLogic'
import type { DeepPartial, FieldName } from 'kea-forms/lib/types'

export interface ScenePreviewPanelLogicProps {
  frameId: FrameId
  sceneId: string
  scene?: FrameScene | null
}

/** No render signal at all within this long, and the spinner gives up. */
export const SCENE_DEPLOY_TIMEOUT_MS = SCENE_ACTIVATION_TIMEOUT_MS
/** Give the frame's image bump a moment after the activation settles. */
const SETTLE_GRACE_MS = 1200
/** Editing a field while the browser preview runs re-renders it, once you stop typing. */
const AUTO_APPLY_DEBOUNCE_MS = 300

export const DEPLOY_TIMED_OUT_NOTICE = 'No render signal received from the frame'
export const DEPLOY_FAILED_NOTICE = 'The frame did not accept the scene'

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface scenePreviewPanelLogicValues {
  nextState: Record<string, any> // expandedSceneLogic
  livePreviewSceneId: string | null // livePreviewLogic
  deployNotice: string | null
  deployPending: boolean
  deployStartedAt: number | null
  showFrameImage: boolean
  snapshotMissing: boolean
  surface: ScenePreviewSurface
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface scenePreviewPanelLogicActions {
  sceneActivationSettled: (sceneId: string) => {
    sceneId: string
  } // controlLogic
  updateEntityImage: (
    entity: string | null,
    subentity: string,
    force?: any
  ) => {
    entity: string | null
    force: any
    subentity: string
  } // entityImagesModel
  updateEntityImageTimestamp: (
    entity: string,
    subentity: string
  ) => {
    entity: string
    subentity: string
  } // entityImagesModel
  deployToFrame: () => {
    value: true
  } // expandedSceneLogic
  deployToFrameFailure: () => {
    value: true
  } // expandedSceneLogic
  resetStateChanges: (values?: Record<string, any> | undefined) => {
    values?: Record<string, any>
  } // expandedSceneLogic
  setStateChangesValue: (
    key: FieldName,
    value: any
  ) => {
    name: FieldName
    value: any
  } // expandedSceneLogic
  setStateChangesValues: (values: DeepPartial<Record<string, any>>) => {
    values: DeepPartial<Record<string, any>>
  } // expandedSceneLogic
  closeLivePreview: () => {
    value: true
  } // livePreviewLogic
  dispatchPreviewEvent: (
    name: string,
    payload: Record<string, any>
  ) => {
    name: string
    payload: Record<string, any>
  } // livePreviewLogic
  openLivePreview: (
    sceneId: string,
    state?: Record<string, any> | null | undefined,
    scenes?: FrameScene[] | null | undefined,
    sourceTemplate?: LivePreviewSourceTemplate | null | undefined
  ) => {
    sceneId: string
    scenes: FrameScene[] | null
    sourceTemplate: LivePreviewSourceTemplate | null
    state: Record<string, any> | null
  } // livePreviewLogic
  previewSceneFailure: () => {
    value: true
  } // scenesLogic
  frameRendered: (frameId: FrameId) => {
    frameId: FrameId
  } // socketLogic
  newSceneImage: (
    frameId: FrameId,
    sceneId: string,
    width: number,
    height: number
  ) => {
    frameId: FrameId
    height: number
    sceneId: string
    width: number
  } // socketLogic
  deploySettled: (notice?: string | null) => {
    notice: string | null
  }
  setSnapshotMissing: (missing: boolean) => {
    missing: boolean
  }
  startBrowserPreview: () => {
    value: true
  }
  stopBrowserPreview: () => {
    value: true
  }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface scenePreviewPanelLogicMeta {
  key: string
  __keaTypeGenInternalSelectorTypes: {
    surface: (
      livePreviewSceneId: string | null,
      deployPending: boolean,
      showFrameImage: boolean,
      arg: any
    ) => ScenePreviewSurface
  }
}

export type scenePreviewPanelLogicType = MakeLogicType<
  scenePreviewPanelLogicValues,
  scenePreviewPanelLogicActions,
  ScenePreviewPanelLogicProps
> &
  scenePreviewPanelLogicMeta

/**
 * The scene editor's Preview drawer: which picture the surface shows, and the
 * deploy that swaps it for the frame's own render.
 *
 * "Deploy to frame" spins until the frame says it rendered. The frame can say
 * so in four different ways depending on the control plane (a WS `render`
 * event, a new scene image, the frame image timestamp bumping, or the
 * activation settling), so every one of them releases the spinner; a frame
 * that says nothing at all releases it after SCENE_DEPLOY_TIMEOUT_MS with a
 * notice rather than spinning forever.
 */
export const scenePreviewPanelLogic = kea<scenePreviewPanelLogicType>([
  path(['src', 'scenes', 'frame', 'panels', 'Scenes', 'scenePreviewPanelLogic']),
  props({} as ScenePreviewPanelLogicProps),
  key((props) => `${props.frameId}/${props.sceneId}`),
  connect(({ frameId, sceneId, scene }: ScenePreviewPanelLogicProps) => ({
    values: [
      livePreviewLogic({ frameId }),
      ['livePreviewSceneId'],
      expandedSceneLogic({ frameId, sceneId, scene }),
      ['nextState'],
    ],
    actions: [
      livePreviewLogic({ frameId }),
      ['openLivePreview', 'closeLivePreview', 'dispatchPreviewEvent'],
      expandedSceneLogic({ frameId, sceneId, scene }),
      ['setStateChangesValue', 'setStateChangesValues', 'resetStateChanges', 'deployToFrame', 'deployToFrameFailure'],
      controlLogic({ frameId }),
      ['sceneActivationSettled'],
      scenesLogic({ frameId }),
      ['previewSceneFailure'],
      entityImagesModel,
      ['updateEntityImage', 'updateEntityImageTimestamp'],
      socketLogic,
      ['frameRendered', 'newSceneImage'],
    ],
  })),
  actions({
    startBrowserPreview: true,
    stopBrowserPreview: true,
    deploySettled: (notice?: string | null) => ({ notice: notice ?? null }),
    /** The frame has no stored snapshot of this scene (the image 404s). */
    setSnapshotMissing: (missing: boolean) => ({ missing }),
  }),
  reducers({
    deployPending: [
      false,
      {
        deployToFrame: () => true,
        deploySettled: () => false,
      },
    ],
    deployStartedAt: [
      null as number | null,
      {
        deployToFrame: () => Date.now(),
        deploySettled: () => null,
      },
    ],
    deployNotice: [
      null as string | null,
      {
        deployToFrame: () => null,
        startBrowserPreview: () => null,
        deploySettled: (_, { notice }) => notice,
      },
    ],
    // Once the frame has rendered what we sent, the surface shows the frame's
    // own panel image instead of the (now older) scene snapshot.
    showFrameImage: [
      false,
      {
        deploySettled: () => true,
      },
    ],
    snapshotMissing: [
      false,
      {
        setSnapshotMissing: (_, { missing }) => missing,
      },
    ],
  }),
  selectors({
    surface: [
      (s) => [s.livePreviewSceneId, s.deployPending, s.showFrameImage, (_, props) => props.sceneId],
      (
        livePreviewSceneId: scenePreviewPanelLogicValues['livePreviewSceneId'],
        deployPending: scenePreviewPanelLogicValues['deployPending'],
        showFrameImage: scenePreviewPanelLogicValues['showFrameImage'],
        sceneId
      ): ScenePreviewSurface =>
        livePreviewSceneId === sceneId ? 'live' : deployPending ? 'pending' : showFrameImage ? 'frame' : 'snapshot',
    ],
  }),
  listeners(({ actions, cache, props, values }) => {
    const isThisScenesPreview = (): boolean => values.livePreviewSceneId === props.sceneId
    const settleIfPending = (notice?: string | null): void => {
      if (values.deployPending) {
        actions.deploySettled(notice ?? null)
      }
    }
    // While the browser preview runs, a field edit re-renders it — but only
    // once the user stops typing. The timer lives in the cache because three
    // different form actions feed it (kea breakpoints debounce per action).
    const scheduleAutoApply = (): void => {
      if (!isThisScenesPreview()) {
        return
      }
      if (cache.autoApplyTimer) {
        clearTimeout(cache.autoApplyTimer)
      }
      cache.autoApplyTimer = setTimeout(() => {
        cache.autoApplyTimer = null
        if (!isThisScenesPreview()) {
          return
        }
        actions.dispatchPreviewEvent('setSceneState', { state: values.nextState, render: true })
      }, AUTO_APPLY_DEBOUNCE_MS)
    }

    return {
      startBrowserPreview: () => {
        actions.openLivePreview(props.sceneId, values.nextState)
      },
      stopBrowserPreview: () => {
        if (isThisScenesPreview()) {
          actions.closeLivePreview()
        }
      },
      // expandedSceneLogic owns the deploy itself (which of the four calls
      // to make); this logic only watches it, so the diagram toolbar's
      // "Deploy to frame" spins the drawer's surface too.
      deployToFrame: async (_, breakpoint) => {
        // The canvas is about to be replaced by the frame's picture; a
        // browser preview left running would keep painting over it.
        if (isThisScenesPreview()) {
          actions.closeLivePreview()
        }
        // A second deploy cancels this wait at the breakpoint, so only the
        // newest one can time out (same pattern as controlLogic).
        await breakpoint(SCENE_DEPLOY_TIMEOUT_MS)
        settleIfPending(DEPLOY_TIMED_OUT_NOTICE)
      },
      deploySettled: () => {
        // Ask for a fresh panel image: what the frame just rendered is the
        // picture the drawer promises to show.
        actions.updateEntityImage(`frames/${props.frameId}`, 'image')
      },
      // --- settle signals, one per control plane -------------------------
      frameRendered: ({ frameId }) => {
        if (frameId === props.frameId) {
          settleIfPending()
        }
      },
      newSceneImage: ({ frameId, sceneId }) => {
        if (frameId === props.frameId && sceneId === props.sceneId) {
          settleIfPending()
        }
      },
      updateEntityImageTimestamp: ({ entity, subentity }) => {
        if (entity === `frames/${props.frameId}` && subentity === 'image') {
          settleIfPending()
        }
      },
      sceneActivationSettled: async ({ sceneId }, breakpoint) => {
        if (!values.deployPending || !sceneIdsRefer(sceneId, props.sceneId)) {
          return
        }
        // The activation is done, but the frame's image bump arrives a beat
        // later — wait for it rather than flashing the old picture.
        await breakpoint(SETTLE_GRACE_MS)
        settleIfPending()
      },
      previewSceneFailure: () => {
        settleIfPending(DEPLOY_FAILED_NOTICE)
      },
      deployToFrameFailure: () => {
        settleIfPending(DEPLOY_FAILED_NOTICE)
      },
      // --- the live preview follows the form -----------------------------
      setStateChangesValue: () => scheduleAutoApply(),
      setStateChangesValues: () => scheduleAutoApply(),
      resetStateChanges: () => scheduleAutoApply(),
    }
  }),
  beforeUnmount(({ actions, cache, props, values }) => {
    if (cache.autoApplyTimer) {
      clearTimeout(cache.autoApplyTimer)
      cache.autoApplyTimer = null
    }
    // The preview belongs to this drawer: closing it (or leaving the scene)
    // stops the worker instead of leaving it rendering into nothing.
    if (values.livePreviewSceneId === props.sceneId) {
      actions.closeLivePreview()
    }
  }),
])
