import { MakeLogicType, actions, afterMount, connect, kea, key, listeners, path, props, selectors } from 'kea'
import type { DeepPartial } from 'kea-forms'

import { FrameScene, FrameId } from '../../../../types'
import { frameLogic, sanitizeScene } from '../../frameLogic'
import { clearCloudSceneJsonCache, framesModel } from '../../../../models/framesModel'
import { longRunningTasksModel } from '../../../../models/longRunningTasksModel'
import { repositoriesModel } from '../../../../models/repositoriesModel'
import { cloudDriveLogic } from '../Templates/cloudDriveLogic'
import { loadRepositoryTemplateScenes } from '../Templates/templatesLogic'
import {
  findTemplateForOrigin,
  sameTemplateOrigin,
  sceneOriginForTemplate,
  sceneUpdateVersion,
  shortSceneVersion,
} from '../../../../utils/sceneOrigin'
import { remapSceneIds } from '../../../../utils/duplicateScenes'
import { mergeInstalledFieldValues } from '../../../../utils/sceneUpdateFields'
import { isCloudMode } from '../../../../utils/cloudMode'
import { fetchStoreSceneScenesJson, updateCloudFrameStoreScene } from '../../../../utils/cloudFrameApi'
import { activeSceneFromLastState } from '../../../../utils/cloudFrameScenes'
import { confirmDialog } from '../../../../utils/confirmDialogLogic'
import type { FrameType, RepositoryType, TemplateType } from '../../../../types'

// How old the catalogs may be before a surface showing scenes asks again. The
// models load once at mount, and a workspace tab stays open for days; without
// this a new version only showed after a reload. (The backend itself re-reads
// a repository at most once a day; the cloud lists its assignments every
// minute and needs no catalog at all.)
const CATALOG_MAX_AGE_MS = 15 * 60 * 1000

export interface SceneUpdatesLogicProps {
  frameId: FrameId
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface sceneUpdatesLogicValues {
  driveRepository: RepositoryType // cloudDriveLogic
  driveTemplates: TemplateType[] // cloudDriveLogic
  frame: FrameType // frameLogic
  frameForm: Partial<FrameType> // frameLogic
  unsavedChanges: boolean // frameLogic
  repositories: RepositoryType[] // repositoriesModel
  installedScenes: FrameScene[]
  sceneUpdateVersions: Record<string, string>
  updateRepositories: RepositoryType[]
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface sceneUpdatesLogicActions {
  setFrameFormValues: (values: DeepPartial<FrameType>) => {
    values: DeepPartial<FrameType>
  } // frameLogic
  updateScene: (
    sceneId: string,
    scene: Partial<FrameScene>
  ) => {
    scene: Partial<FrameScene>
    sceneId: string
  } // frameLogic
  confirmSceneUpdate: (sceneId: string) => {
    sceneId: string
  }
  updateSceneFromRepo: (sceneId: string) => {
    sceneId: string
  }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface sceneUpdatesLogicMeta {
  key: FrameId
  __keaTypeGenInternalSelectorTypes: {
    installedScenes: (frameForm: Partial<FrameType>, frame: FrameType) => FrameScene[]
    updateRepositories: (
      repositories: RepositoryType[],
      driveRepository: RepositoryType,
      driveTemplates: TemplateType[]
    ) => RepositoryType[]
    sceneUpdateVersions: (
      installedScenes: FrameScene[],
      updateRepositories: RepositoryType[],
      frame: FrameType
    ) => Record<string, string>
  }
}

export type sceneUpdatesLogicType = MakeLogicType<
  sceneUpdatesLogicValues,
  sceneUpdatesLogicActions,
  SceneUpdatesLogicProps
> &
  sceneUpdatesLogicMeta

/**
 * Cloud: move the store scene behind `scene` to its newest version on this
 * frame, then bring the workspace along — the hydration cache is keyed by
 * version and the frame form keeps its own copy of every scene, so both are
 * refreshed here rather than left for the next poll.
 */
async function updateCloudScene(
  frameId: FrameId,
  scene: FrameScene,
  frame: FrameType | undefined,
  /** The frame form's scenes when it has unsaved edits, else null. */
  editedFormScenes: FrameScene[] | null,
  setFormScenes: (scenes: FrameScene[]) => void
): Promise<void> {
  const storeSceneId = frame?.cloud_scene_sources?.[scene.id]?.scene_id ?? scene.origin?.storeSceneId
  if (!storeSceneId) {
    return
  }
  const name = scene.name || 'scene'
  longRunningTasksModel.actions.startTask({
    frameId,
    kind: 'deploy',
    title: `Updating "${name}"`,
    detail: 'Sending the latest version to this frame',
  })
  try {
    const result = await updateCloudFrameStoreScene(frameId, storeSceneId, activeSceneFromLastState(frame?.last_state))
    if (result.updated && result.sceneVersion && editedFormScenes) {
      // A form with unsaved edits does not reset itself when the frame's
      // scenes move (frameLogic's `frame` subscription), so it would keep
      // showing — and later save — the old version. Replace this pack's
      // scenes in it and leave the edits to every other scene alone.
      const updatedScenes = await fetchStoreSceneScenesJson(storeSceneId, result.sceneVersion)
      const updatedById = new Map((updatedScenes ?? []).map((updated) => [updated.id, updated]))
      if (updatedById.size > 0) {
        setFormScenes(
          editedFormScenes.map((formScene) => {
            const updated = updatedById.get(formScene.id)
            return updated ? sanitizeScene(updated, frame ?? {}) : formScene
          })
        )
      }
    }
    clearCloudSceneJsonCache(storeSceneId)
    framesModel.actions.hydrateCloudFrameScenes(frameId, true)
    framesModel.actions.loadFrame(frameId)
    longRunningTasksModel.actions.finishTask({
      frameId,
      kind: 'deploy',
      status: 'success',
      detail: !result.updated
        ? 'This frame already has the latest version'
        : result.connected
        ? `Version ${result.sceneVersion ?? 'latest'} is on its way to the frame`
        : `Version ${result.sceneVersion ?? 'latest'} is queued — the frame takes it when it next connects`,
    })
  } catch (error) {
    longRunningTasksModel.actions.taskFailed({
      frameId,
      kind: 'deploy',
      detail: error instanceof Error ? error.message : String(error),
    })
  }
}

/**
 * "Update available" / "Update to latest" for installed scenes. Kept separate
 * from scenesLogic on purpose: scenesLogic pulls in controlLogic, which syncs
 * the frame's state on mount — dropdowns on the frames home must not trigger
 * one such request per frame.
 *
 * The two control planes keep an installed scene differently, so they answer
 * "is there a newer version?" and "take it" differently:
 *
 *   * backend / on-device admin — the scene is a COPY in the frame's own
 *     scene list, stamped with its `origin` (repository, template, version).
 *     A newer version is the source template's version having moved, in any
 *     repository that lists it: the tracked repositories (the FrameOS Cloud
 *     store among them) and the linked account's private cloud scenes. The
 *     update re-applies the template into the frame form, unsaved — the owner
 *     reviews, then saves and deploys as usual.
 *   * cloud — the scene is an ASSIGNMENT of a store scene; the frame holds
 *     the version it was last sent (`cloud_scene_sources[…].held_version`),
 *     and the server says when the store is ahead of it. The update is a
 *     server-side move of that assignment plus the push
 *     (POST /api/frames/{id}/scenes/update) — there is no copy to re-apply.
 */
export const sceneUpdatesLogic = kea<sceneUpdatesLogicType>([
  path(['src', 'scenes', 'frame', 'panels', 'Scenes', 'sceneUpdatesLogic']),
  props({} as SceneUpdatesLogicProps),
  key((props) => props.frameId),
  connect(({ frameId }: SceneUpdatesLogicProps) => ({
    values: [
      frameLogic({ frameId }),
      ['frame', 'frameForm', 'unsavedChanges'],
      repositoriesModel,
      ['repositories'],
      cloudDriveLogic,
      ['driveRepository', 'driveTemplates'],
    ],
    actions: [frameLogic({ frameId }), ['updateScene', 'setFrameFormValues']],
  })),
  actions({
    /** Ask first, then update — what the banner and the scene menus call. */
    confirmSceneUpdate: (sceneId: string) => ({ sceneId }),
    updateSceneFromRepo: (sceneId: string) => ({ sceneId }),
  }),
  selectors({
    installedScenes: [
      (s) => [s.frameForm, s.frame],
      (frameForm: sceneUpdatesLogicValues['frameForm'], frame: sceneUpdatesLogicValues['frame']): FrameScene[] =>
        frameForm?.scenes ?? frame?.scenes ?? [],
    ],
    // Everywhere an installed scene's source may be listed: the tracked
    // repositories plus the account's private cloud scenes, which live in
    // their own logic (one authenticated index, not a repository row).
    updateRepositories: [
      (s) => [s.repositories, s.driveRepository, s.driveTemplates],
      (
        repositories: sceneUpdatesLogicValues['repositories'],
        driveRepository: sceneUpdatesLogicValues['driveRepository'],
        driveTemplates: sceneUpdatesLogicValues['driveTemplates']
      ): RepositoryType[] =>
        driveTemplates.length > 0 ? [...repositories, { ...driveRepository, templates: driveTemplates }] : repositories,
    ],
    sceneUpdateVersions: [
      (s) => [s.installedScenes, s.updateRepositories, s.frame],
      (
        installedScenes: sceneUpdatesLogicValues['installedScenes'],
        updateRepositories: sceneUpdatesLogicValues['updateRepositories'],
        frame: sceneUpdatesLogicValues['frame']
      ): Record<string, string> => {
        const versions: Record<string, string> = {}
        if (isCloudMode()) {
          // The server compared the store's newest version with the one the
          // frame was last sent; hydration recorded the answer per runtime
          // scene (framesModel.hydrateCloudFrameScenes).
          const sources = frame?.cloud_scene_sources ?? {}
          for (const scene of installedScenes) {
            const version = sources[scene.id]?.update_version
            if (version) {
              versions[scene.id] = String(version)
            }
          }
          return versions
        }
        for (const scene of installedScenes) {
          const version = sceneUpdateVersion(scene, updateRepositories)
          if (version) {
            versions[scene.id] = version
          }
        }
        return versions
      },
    ],
  }),
  listeners(({ actions, values, props }) => ({
    confirmSceneUpdate: async ({ sceneId }) => {
      const version = values.sceneUpdateVersions[sceneId]
      if (!version) {
        return
      }
      const scene = values.installedScenes.find((s) => s.id === sceneId)
      const name = scene?.name ? `"${scene.name}"` : 'this scene'
      const confirmed = await confirmDialog(
        isCloudMode()
          ? {
              title: 'Update to the latest version?',
              message:
                `Version ${shortSceneVersion(version)} of ${name} replaces the one on this frame and is deployed ` +
                'right away. Unsaved changes to the scene are lost.',
              confirmLabel: 'Update to latest',
            }
          : {
              title: 'Update to the latest version?',
              message:
                `The latest published version of ${name} replaces this copy; the values you set on its fields ` +
                'are kept, any other local changes to the scene are lost. Save and deploy afterwards to send it ' +
                'to the frame.',
              confirmLabel: 'Update to latest',
              danger: true,
            }
      )
      if (confirmed) {
        actions.updateSceneFromRepo(sceneId)
      }
    },
    updateSceneFromRepo: async ({ sceneId }) => {
      const installedScenes = values.installedScenes
      const scene = installedScenes.find((s) => s.id === sceneId)
      if (scene && isCloudMode()) {
        await updateCloudScene(
          props.frameId,
          scene,
          values.frame,
          values.unsavedChanges ? values.frameForm.scenes ?? null : null,
          (scenes) => actions.setFrameFormValues({ scenes })
        )
        return
      }
      const origin = scene?.origin
      if (!scene || !origin) {
        return
      }
      const match = findTemplateForOrigin(values.updateRepositories, origin)
      if (!match) {
        console.error('Cannot update scene: source template not found in any repository', origin)
        return
      }
      const { repository, template } = match
      const templateScenes = await loadRepositoryTemplateScenes(repository, template)

      // Multi-scene templates are updated as a group: every installed scene from
      // this template keeps its id, so links between scenes keep working.
      const installedIdByTemplateSceneId: Record<string, string> = {}
      for (const installed of installedScenes) {
        if (installed.origin?.sceneId && sameTemplateOrigin(installed.origin, origin)) {
          installedIdByTemplateSceneId[installed.origin.sceneId] = installed.id
        }
      }
      // Duplicated scenes share an origin; make sure the clicked scene claims its slot.
      if (origin.sceneId) {
        installedIdByTemplateSceneId[origin.sceneId] = scene.id
      }
      const remapped = remapSceneIds(templateScenes, (id) => installedIdByTemplateSceneId[id] ?? id)
      remapped.forEach((nextScene, index) => {
        const templateSceneId = templateScenes[index].id
        const installedId = installedIdByTemplateSceneId[templateSceneId]
        if (!installedId) {
          return
        }
        // Replace the scene's content but keep its id, name, default flag and
        // the field values the user set on this copy.
        const installed = installedScenes.find((s) => s.id === installedId)
        actions.updateScene(installedId, {
          nodes: nextScene.nodes,
          edges: nextScene.edges,
          apps: nextScene.apps,
          fields: mergeInstalledFieldValues(installed?.fields, nextScene.fields),
          customEvents: nextScene.customEvents,
          settings: nextScene.settings,
          origin: sceneOriginForTemplate(repository, template, templateSceneId),
        })
      })
    },
  })),
  afterMount(() => {
    if (isCloudMode()) {
      return
    }
    repositoriesModel.actions.loadRepositoriesIfStale(CATALOG_MAX_AGE_MS)
    cloudDriveLogic.actions.loadDriveIfStale(CATALOG_MAX_AGE_MS)
  }),
])
