name: Run Tests on Pull Requests

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install redis
        run: sudo apt-get install -y redis-server

      - name: Install python dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install node dependencies
        run: |
          cd frontend
          npm install
          npm run build

      - name: Run Pytest
        run: |
          cd backend
          TEST=1 pytest
