name: Run Tests on Pull Requests

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install redis
        run: sudo apt-get install -y redis-server

      - name: Cache pip packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install python dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: |
          cd backend
          TEST=1 pytest

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '2.0.2'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run script
        run: |
          cd e2e
          make

      - name: Check for modifications
        id: check_mod
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "Changes detected in the repository after running the script."
            echo "::set-output name=changes_detected::true"
          else
            echo "No changes detected in the repository."
            echo "::set-output name=changes_detected::false"
          fi

      - name: Fail if changes detected
        if: steps.check_mod.outputs.changes_detected == 'true'
        run: exit 1